------------------------------------------------------------------------
-- Presentations of groups
--
-- Soundness of the phase-affine rulesets (Lemmas 1 and 9)
--
-- The monoid congruence generated by the rules of a fragment, the laws
-- of the symmetry and the structural rules preserves the operator, in
-- every admissible fragment: the quadratic rules need p odd and the
-- cubic ones p > 3 (Definition 13), for which, writing p = 2 + p-2, the
-- level lv requires 1 ≤ p-2 from lv = 2 on and 2 ≤ p-2 from lv = 3 on.
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

open import Data.Nat.Base using (ℕ ; _≤_)
open import Data.Nat.Primality using (Prime)
open import Notations using (₂₊)

module Examples.Groups.Qupit-Phase-Affine.Soundness
  (p-2 : ℕ) (p-prime : Prime (₂₊ p-2)) (lv : ℕ) where

open import Data.Nat.Properties using (_≤?_)
open import Data.Product.Base using (_×_ ; _,_ ; proj₁ ; proj₂)
open import Data.Vec.Base using (_∷_ ; head ; tail)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_ ; refl)
open import Relation.Nullary.Decidable using (recompute)
open import Word.Base using ([_]ʷ ; _•_)

open import Notations using (₁₊)

open import Examples.Groups.Qupit-Phase-Affine.Semantics p-2 p-prime
open import Examples.Groups.Qupit-Phase-Affine.Syntactics p-2 p-prime lv
open import Examples.Groups.Qupit-Phase-Affine.Interpretation p-2 p-prime lv
open import Examples.Groups.Qupit-Phase-Affine.Soundness.Rules p-2 p-prime lv

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- Admissible fragments (Definition 13)

Admissible : Set
Admissible = (2 ≤ lv → 1 ≤ p-2) × (3 ≤ lv → 2 ≤ p-2)

-- Level evidence is carried irrelevantly; it is recomputed to read off
-- the condition on p.
private
  odd : Admissible → .(2 ≤ lv) → 1 ≤ p-2
  odd adm h = proj₁ adm (recompute (2 ≤? lv) h)

  big : Admissible → .(3 ≤ lv) → 2 ≤ p-2
  big adm h = proj₂ adm (recompute (3 ≤? lv) h)

------------------------------------------------------------------------
-- The structural rules

private
  -- The operator of two letters (⟦_⟧ is abstract).
  gen² : (a b : Gen n) → ⟦ [ a ]ʷ • [ b ]ʷ ⟧ ≐ (⟦ a ⟧ᵍ ⊙ ⟦ b ⟧ᵍ)
  gen² a b = ≐-trans (⟦⟧-• [ a ]ʷ [ b ]ʷ) (⊙-cong (⟦⟧-gen a) (⟦⟧-gen b))

  -- The scalar commutes with every operator.
  comm-scalar : (G : Op n) → (G ⊙ ωₒ) ≐ (ωₒ ⊙ G)
  comm-scalar G x = Eq.cong (proj₁ (G x) ,_) (FR.+-comm 1F (proj₂ (G x)))

  -- A gate on wire 0 commutes with an operator one wire up.
  comm-up : (G : Op (₁₊ n)) → (∀ a x y → G (a ∷ x) ≡ (head (proj₁ (G (a ∷ y))) ∷ x , proj₂ (G (a ∷ y)))) →
            (H : Op n) → (up H ⊙ G) ≐ (G ⊙ up H)
  comm-up G g H (a ∷ x) =
    Eq.trans (Eq.cong (λ q → proj₁ (up H (proj₁ q)) , proj₂ q + proj₂ (up H (proj₁ q))) (g a x x))
      (Eq.trans (Eq.cong₂ _,_ refl (FR.+-comm (proj₂ (G (a ∷ x))) (proj₂ (H x))))
        (Eq.sym (Eq.cong (λ q → proj₁ q , proj₂ (H x) + proj₂ q) (g a (proj₁ (H x)) x))))

  -- A gate on wires 0 and 1 commutes with an operator two wires up.
  comm-up² : (G : Op (₂₊ n)) →
             (∀ a b x y → G (a ∷ b ∷ x) ≡ (head (proj₁ (G (a ∷ b ∷ y))) ∷ head (tail (proj₁ (G (a ∷ b ∷ y)))) ∷ x
                                           , proj₂ (G (a ∷ b ∷ y)))) →
             (H : Op n) → (up (up H) ⊙ G) ≐ (G ⊙ up (up H))
  comm-up² G g H (a ∷ b ∷ x) =
    Eq.trans (Eq.cong (λ q → proj₁ (up (up H) (proj₁ q)) , proj₂ q + proj₂ (up (up H) (proj₁ q))) (g a b x x))
      (Eq.trans (Eq.cong₂ _,_ refl (FR.+-comm (proj₂ (G (a ∷ b ∷ x))) (proj₂ (H x))))
        (Eq.sym (Eq.cong (λ q → proj₁ q , proj₂ (H x) + proj₂ q) (g a b (proj₁ (H x)) x))))

  up-ω : up (ωₒ {n}) ≐ ωₒ
  up-ω (a ∷ x) = refl

cong↑-sound : {w v : Circuit n} → ⟦ w ⟧ ≐ ⟦ v ⟧ → ⟦ w ↑ ⟧ ≐ ⟦ v ↑ ⟧
cong↑-sound {w = w} {v} e =
  ≐-trans (up-word w) (≐-trans (up-cong e) (≐-sym (up-word v)))

comm₀-sound : (h : Gate 0) (g : Gen n) →
              ⟦ [ g ]ʷ • [ gate₀ h ]ʷ ⟧ ≐ ⟦ [ gate₀ h ]ʷ • [ g ]ʷ ⟧
comm₀-sound (ω-gate e) g =
  ≐-trans (gen² g (gate₀ (ω-gate e)))
    (≐-trans (comm-scalar ⟦ g ⟧ᵍ) (≐-sym (gen² (gate₀ (ω-gate e)) g)))

comm₁-sound : (h : Gate 1) (g : Gen n) →
              ⟦ [ g ↥ ]ʷ • [ gate₁ h ]ʷ ⟧ ≐ ⟦ [ gate₁ h ]ʷ • [ g ↥ ]ʷ ⟧
comm₁-sound h g =
  ≐-trans (gen² (g ↥) (gate₁ h))
    (≐-trans (comm-up ⟦ gate₁ h ⟧ᵍ (local h) ⟦ g ⟧ᵍ) (≐-sym (gen² (gate₁ h) (g ↥))))
  where
  local : (h : Gate 1) → ∀ a x y →
          ⟦ gate₁ {n} h ⟧ᵍ (a ∷ x) ≡ (head (proj₁ (⟦ gate₁ {n} h ⟧ᵍ (a ∷ y))) ∷ x , proj₂ (⟦ gate₁ {n} h ⟧ᵍ (a ∷ y)))
  local X-gate       a x y = refl
  local (M-gate c _) a x y = refl
  local (Z-gate _)   a x y = refl
  local (S-gate _)   a x y = refl
  local (T-gate _)   a x y = refl

comm₂-sound : (h : Gate 2) (g : Gen n) →
              ⟦ [ g ↥ ↥ ]ʷ • [ gate₂ h ]ʷ ⟧ ≐ ⟦ [ gate₂ h ]ʷ • [ g ↥ ↥ ]ʷ ⟧
comm₂-sound h g =
  ≐-trans (gen² (g ↥ ↥) (gate₂ h))
    (≐-trans (comm-up² ⟦ gate₂ h ⟧ᵍ (local h) ⟦ g ⟧ᵍ) (≐-sym (gen² (gate₂ h) (g ↥ ↥))))
  where
  local : (h : Gate 2) → ∀ a b x y →
          ⟦ gate₂ {n} h ⟧ᵍ (a ∷ b ∷ x) ≡
          (head (proj₁ (⟦ gate₂ {n} h ⟧ᵍ (a ∷ b ∷ y))) ∷ head (tail (proj₁ (⟦ gate₂ {n} h ⟧ᵍ (a ∷ b ∷ y)))) ∷ x
          , proj₂ (⟦ gate₂ {n} h ⟧ᵍ (a ∷ b ∷ y)))
  local CX-gate   a b x y = refl
  local SWAP-gate a b x y = refl

ω↑=ω-sound : (h : Gate 0) → ⟦ [ gate₀ {n} h ]ʷ ↑ ⟧ ≐ ⟦ [ gate₀ h ]ʷ ⟧
ω↑=ω-sound (ω-gate e) =
  ≐-trans (⟦⟧-gen (gate₀ (ω-gate e) ↥)) (≐-trans up-ω (≐-sym (⟦⟧-gen (gate₀ (ω-gate e)))))

------------------------------------------------------------------------
-- Soundness of the rules

axiom-sound : Admissible → {w v : Circuit n} → n VRel, w === v → ⟦ w ⟧ ≐ ⟦ v ⟧
-- Aff_d.
axiom-sound adm (srel ax1)       = r1
axiom-sound adm (srel (ax2 x y)) = r2 x y
axiom-sound adm (srel (ax3 x))   = r3 x
axiom-sound adm (srel (ax4 x))   = r4 x
axiom-sound adm (srel (ax5 x))   = r5 x
axiom-sound adm (srel ax6)       = r6
axiom-sound adm (srel ax7)       = r7
axiom-sound adm (srel ax8)       = r8
-- The symmetry.
axiom-sound adm (srel swap-order)    = s-order
axiom-sound adm (srel swap-braid)    = s-braid
axiom-sound adm (srel swap-X)        = s-X
axiom-sound adm (srel (swap-M a nz)) = s-M a nz
axiom-sound adm (srel (swap-Z h))    = s-Z h
axiom-sound adm (srel (swap-S h))    = s-S h
axiom-sound adm (srel (swap-T h))    = s-T h
axiom-sound adm (srel swap-CX)       = s-CX
-- LinPhase_d.
axiom-sound adm (srel (ax19 h))   = r19 h
axiom-sound adm (srel (ax20 h))   = r20 h
axiom-sound adm (srel (ax21 h))   = r21 h
axiom-sound adm (srel (ax22 h x)) = r22 h x
axiom-sound adm (srel (ax23 h))   = r23 h
-- QuadPhase_d.
axiom-sound adm (srel (ax24 h))   = Quad.r24 (odd adm h) h
axiom-sound adm (srel (ax25 h))   = Quad.r25 (odd adm h) h
axiom-sound adm (srel (ax26 h))   = Quad.r26 (odd adm h) h
axiom-sound adm (srel (ax27 h x)) = Quad.r27 (odd adm h) h x
axiom-sound adm (srel (ax28 h))   = Quad.r28 (odd adm h) h
axiom-sound adm (srel (ax29 h))   = Quad.r29 (odd adm h) h
axiom-sound adm (srel (ax30 h))   = Quad.r30 (odd adm h) h
-- CubicPhase_d.
axiom-sound adm (srel (ax31 h))   = Cube.r31 (big adm h) h
axiom-sound adm (srel (ax32 h x)) = Cube.r32 (big adm h) h x
axiom-sound adm (srel (ax33 h))   = Cube.r33 (big adm h) h
axiom-sound adm (srel (ax34 h))   = Cube.r34 (big adm h) h
axiom-sound adm (srel (ax35 h x)) = Cube.r35 (big adm h) h x
axiom-sound adm (srel (ax36 h))   = Cube.r36 (big adm h) h
axiom-sound adm (srel (ax37 h x)) = Cube.r37 (big adm h) h x
axiom-sound adm (srel (ax38 h))   = Cube.r38 (big adm h) h
axiom-sound adm (srel (ax39 h))   = Cube.r39 (big adm h) h
axiom-sound adm (srel (ax40 h x)) = Cube.r40 (big adm h) h x
axiom-sound adm (srel (ax41 h))   = Cube.r41 (big adm h) h
axiom-sound adm (srel (ax42 h))   = Cube.r42 (big adm h) h
-- The structural rules.
axiom-sound adm (cong↑ r)   = cong↑-sound (axiom-sound adm r)
axiom-sound adm (comm₀ h g) = comm₀-sound h g
axiom-sound adm (comm₁ h g) = comm₁-sound h g
axiom-sound adm (comm₂ h g) = comm₂-sound h g
axiom-sound adm (ω↑=ω h)    = ω↑=ω-sound h

------------------------------------------------------------------------
-- Soundness of the congruence
--
-- Closing under the monoid congruence is the library's job
-- (StarInterp.Extend.Cong), for the reading built from the monoid,
-- which is ⟦_⟧ (Interpretation.⟦⟧ᴱ-def).

module _ (adm : Admissible) where

  axiom-soundᴱ : {w v : Circuit n} → n VRel, w === v → Ext.⟦_⟧ᴱ n w ≐ Ext.⟦_⟧ᴱ n v
  axiom-soundᴱ {w = w} {v} r = ⟦⟧ᴱ-≐ {w = w} {v} (axiom-sound adm r)

  soundᴱ : {w v : Circuit n} → n ⊢ w ≈ v → Ext.⟦_⟧ᴱ n w ≐ Ext.⟦_⟧ᴱ n v
  soundᴱ {n} = Ext.Cong.fʷ-cong n axiom-soundᴱ

  sound : {w v : Circuit n} → n ⊢ w ≈ v → ⟦ w ⟧ ≐ ⟦ v ⟧
  sound {w = w} {v} e = ≐-⟦⟧ᴱ {w = w} {v} (soundᴱ e)
