------------------------------------------------------------------------
-- Presentations of groups
--
-- The Clifford extension as a twisted product of *presented* groups
-- (p = 2):
--
--     1 ─→ K ─→ K ×_f Q ─→ Q ─→ 1
--
-- where both sides are groups of words modulo a congruence:
--
--   * K = the Pauli group presented by
--     Examples.Groups.ProjectivePauli.Presentation-Alt — words over the
--     circuit generators X, Z on each wire, modulo order-X, order-Z,
--     comm-Z-X and the structural circuit rules.  It is abelian
--     (Presentation-Alt.word-comm), which is what the factor-set
--     construction needs of a kernel;
--   * Q = the symplectic group presented by the SIMPLIFIED rule set,
--     Examples.Groups.Symplectic.Simplified.Syntactics — words over the
--     Clifford generators H, S, CZ modulo order-S, order-H, M-power,
--     semi-MS, the two semi-M·CZ rules, order-CZ, the two comm-CZ-S
--     rules and selinger-c10 … c15.
--
-- Both are `•-ε-group` of Presentation.GroupLike.Group-Lemmas: the
-- carrier is Word Gen, the equality is the congruence generated by the
-- rules, and the inverse comes from the Grouplike witness each
-- development supplies.
--
-- φ, the action of Q on K, is conjugation.  A symplectic generator g
-- sends a Pauli generator y to the normal form of the vector
-- actg g ⟦ y ⟧₀, and this extends to Pauli words by (_ ⁿ') and to
-- symplectic words by (_ ʰ').  Its two structural laws hold on the nose,
-- as propositional equalities of words — act u is a monoid endomorphism
-- of the free monoid, before any quotient.  That it descends to the two
-- quotients is proved through the semantics, exactly as
-- ProjectiveClifford.Qupit.SemiDirect.ConjAction does for odd p:
-- conjugating a Pauli word computes the symplectic action on its vector
-- (actw-sem), so
--
--   * act u respects the Pauli rules because they have equal readings
--     and the Pauli presentation is complete (act-congʳ);
--   * act respects the symplectic rules because their two sides denote
--     the same symplectic transformation, hence act alike (act-congˡ).
--
-- Both presentation theorems used here are proved for every prime, so
-- they hold at p = 2: Presentation-Alt.Build.sound / .complete, and
-- Simplified.Presentation.presentation (which rests in turn on
-- Symplectic.PresentationFull).
--
-- γ, the factor set, is left open — the four holes below.  It is the
-- Pauli correction carried by a lifting of Q, so writing it down means
-- choosing a lifting, i.e. a normal form for symplectic words, and
-- reading off the defect.  Its generator-level shadow is `corr` of
-- Qubit.Cocycle, whose single nontrivial entry is corr (order-S) = Z₀ —
-- the syntactic counterpart of S² = Z.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.ProjectiveClifford.Qubit.Sem3 where

open import Algebra.Bundles using (AbelianGroup ; Group)
open import Algebra.Morphism.Structures using (module GroupMorphisms)
open import Data.Nat using (ℕ)
open import Data.Product using (Σ-syntax ; proj₂)
open import Level using (0ℓ)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_ ; _≗_)

open import Word.Base using (Word ; WRel ; [_]ʷ ; ε ; _•_ ; _ⁿ' ; _ʰ')

import Presentation.Base as PB
open import Presentation.Definitions using (_IsPresentationOf_)
open import Presentation.GroupLike using (module Group-Lemmas)

open import ForStdlib.Algebra.Construct.Extension using (Extension)
open import ForStdlib.Algebra.Construct.SemiDirectProduct using (Action)
import ForStdlib.Algebra.Construct.FactorSetExtension as FSE
open FSE using (FactorSet)

-- Qubit case: fix the prime to 2 (and with it the primitive root, ℤ*₂
-- being trivial).
open import ForStdlib.Data.Fin.Mod.Prime.Two using (p-2 ; p-prime ; g* ; g-gen)

open import Examples.Groups.ProjectivePauli.Semantics p-2 p-prime using (_+ₚ_)
open import Examples.Groups.Symplectic.Semantics p-2 p-prime
  using (Symplectic ; _∘ˢ_ ; module Interpretation)
open import Examples.Construct.SemiDirectProduct.Clifford p-2 p-prime
  using (ap-ε)
import Examples.Groups.ProjectivePauli.Presentation-Alt p-2 p-prime as PA
import Examples.Groups.Symplectic.Simplified.Syntactics p-2 p-prime g* g-gen
  as SS
import Examples.Groups.Symplectic.Simplified.Lemmas p-2 p-prime g* g-gen as SL
import Examples.Groups.Symplectic.Simplified.Presentation p-2 p-prime g* g-gen
  as SimPres

open Symplectic using (ap ; linear-+)
open Interpretation using (actg ; ⟦_⟧ᵍ ; ⟦_⟧)

------------------------------------------------------------------------
-- The two alphabets and the two rule sets

-- Pauli side: the X/Z circuit generators of Presentation-Alt.
PGen : ℕ → Set
PGen = PA.Gen

-- Symplectic side: the H/S/CZ circuit generators, shared between the
-- plain and the simplified symplectic presentations.
SGen : ℕ → Set
SGen = SS.Symplectic.Gen

ΓK : (n : ℕ) → WRel (PGen n)
ΓK n = PA._QRel,_===_ n

ΓQ : (n : ℕ) → WRel (SGen n)
ΓQ n = SS.Simplified-Relations._QRel,_===_ n

------------------------------------------------------------------------
-- Conjugation, on words
--
-- A Pauli generator reads as a basis vector of the phase space, a
-- symplectic generator moves that vector by actg, and inv-nf reads the
-- result back as a Pauli word.  So conjGen g y is the Pauli word equal,
-- inside Clifford, to g · y · g⁻¹.

conjGen : ∀ {n} → SGen n → PGen n → Word (PGen n)
conjGen g y = PA.inv-nf (actg g PA.⟦ y ⟧₀)

-- The action of a symplectic word on a Pauli word: a generator acts on a
-- word letter by letter, and a product acts by its factors in turn (the
-- right one first, matching ⟦ u • v ⟧ = ⟦ u ⟧ ∘ˢ ⟦ v ⟧).
act : ∀ {n} → Word (SGen n) → Word (PGen n) → Word (PGen n)
act = (conjGen ʰ')

------------------------------------------------------------------------
-- The structural action laws
--
-- act u is a monoid endomorphism of the free monoid of Pauli words, and
-- act is a monoid homomorphism from symplectic words into those
-- endomorphisms.  All of this holds before any quotient is taken, so
-- these are propositional equalities of words.

act-ε : ∀ {n} (u : Word (SGen n)) → act u ε ≡ ε
act-ε [ g ]ʷ  = Eq.refl
act-ε ε       = Eq.refl
act-ε (u • v) = Eq.trans (Eq.cong (act u) (act-ε v)) (act-ε u)

act-• : ∀ {n} (u : Word (SGen n)) (w w′ : Word (PGen n)) →
        act u (w • w′) ≡ act u w • act u w′
act-• [ g ]ʷ  w w′ = Eq.refl
act-• ε       w w′ = Eq.refl
act-• (u • v) w w′ =
  Eq.trans (Eq.cong (act u) (act-• v w w′)) (act-• u (act v w) (act v w′))

------------------------------------------------------------------------
-- The bridge to the semantics
--
-- Conjugating a Pauli word computes the symplectic action on the vector
-- it reads as.  The generator case is exactly sem-inv, that inv-nf is a
-- section of sem; the rest is that both sides are additive.

conj-sem : ∀ {n} (g : SGen n) (w : Word (PGen n)) →
           PA.sem ((conjGen ⁿ') g w) ≡ actg g (PA.sem w)
conj-sem g [ y ]ʷ  = PA.sem-inv (actg g PA.⟦ y ⟧₀)
conj-sem g ε       = Eq.sym (ap-ε ⟦ g ⟧ᵍ)
conj-sem g (w • w′) =
  Eq.trans (Eq.cong₂ _+ₚ_ (conj-sem g w) (conj-sem g w′))
           (Eq.sym (linear-+ ⟦ g ⟧ᵍ (PA.sem w) (PA.sem w′)))

actw-sem : ∀ {n} (u : Word (SGen n)) (w : Word (PGen n)) →
           PA.sem (act u w) ≡ ap ⟦ u ⟧ (PA.sem w)
actw-sem [ g ]ʷ  w = conj-sem g w
actw-sem ε       w = Eq.refl
actw-sem (u • v) w =
  Eq.trans (actw-sem u (act v w)) (Eq.cong (ap ⟦ u ⟧) (actw-sem v w))

------------------------------------------------------------------------
-- Soundness of the simplified symplectic presentation
--
-- Equal symplectic words denote the same transformation, so they act
-- alike.  The presentation's own interpretation is the extension of
-- ⟦_⟧ᵍ, which is ⟦_⟧ written out, so the two agree.

private
  module SimP {n : ℕ} = _IsPresentationOf_ (SimPres.presentation {n})
  module SIso {n : ℕ} = GroupMorphisms.IsGroupIsomorphism
                          (_IsPresentationOf_.iso (SimPres.presentation {n}))

  denote-agrees : ∀ {n} (u : Word (SGen n)) → SimP.⟦ u ⟧ ≡ ⟦ u ⟧
  denote-agrees [ g ]ʷ  = Eq.refl
  denote-agrees ε       = Eq.refl
  denote-agrees (u • v) = Eq.cong₂ _∘ˢ_ (denote-agrees u) (denote-agrees v)

  denote-eq : ∀ {n} {u v : Word (SGen n)} →
              PB._≈_ (ΓQ n) u v → ap ⟦ u ⟧ ≗ ap ⟦ v ⟧
  denote-eq {n} {u} {v} e x = begin
    ap ⟦ u ⟧ x       ≡⟨ Eq.cong (λ S → ap S x) (Eq.sym (denote-agrees u)) ⟩
    ap SimP.⟦ u ⟧ x  ≡⟨ SIso.⟦⟧-cong e x ⟩
    ap SimP.⟦ v ⟧ x  ≡⟨ Eq.cong (λ S → ap S x) (denote-agrees v) ⟩
    ap ⟦ v ⟧ x       ∎
    where open Eq.≡-Reasoning

------------------------------------------------------------------------
-- K, Q and φ

module _ (n : ℕ) where

  private
    module KL = Group-Lemmas (ΓK n) (PA.XZ-GroupLike.grouplike {n})
    module QL = Group-Lemmas (ΓQ n) (SL.Symplectic-Sim-GroupLike.grouplike {n})
    module KB = PB (ΓK n)
    module QB = PB (ΓQ n)
    module BK = PA.Build n

  -- K: the Pauli presentation, an abelian group of words.
  K : AbelianGroup 0ℓ 0ℓ
  K = record
    { isAbelianGroup = record
      { isGroup = Group.isGroup KL.•-ε-group
      ; comm    = PA.word-comm
      }
    }

  -- Q: the simplified symplectic presentation, a group of words.
  Q : Group 0ℓ 0ℓ
  Q = QL.•-ε-group

  -- act u respects the Pauli rules: equal Pauli words go in, words with
  -- equal readings come out, and the Pauli presentation is complete.
  act-congʳ : ∀ (u : Word (SGen n)) {w w′ : Word (PGen n)} →
              KB._≈_ w w′ → KB._≈_ (act u w) (act u w′)
  act-congʳ u {w} {w′} e = BK.complete
    (Eq.trans (actw-sem u w)
      (Eq.trans (Eq.cong (ap ⟦ u ⟧) (BK.sound e))
                (Eq.sym (actw-sem u w′))))

  -- act respects the symplectic rules: equal symplectic words act alike,
  -- so the action factors through Q.
  act-congˡ : ∀ {u v : Word (SGen n)} (w : Word (PGen n)) →
              QB._≈_ u v → KB._≈_ (act u w) (act v w)
  act-congˡ {u} {v} w e = BK.complete
    (Eq.trans (actw-sem u w)
      (Eq.trans (denote-eq e (PA.sem w)) (Eq.sym (actw-sem v w))))

  φ : Action (AbelianGroup.rawMonoid K) (Group.rawMonoid Q)
  φ = record
    { act          = act
    ; act-cong     = λ {u} {u′} {w} {w′} eu ew →
                       KB.trans (act-congˡ w eu) (act-congʳ u′ ew)
    ; act-ε-homo   = λ u → KB.refl' (act-ε u)
    ; act-∙-homo   = λ u w w′ → KB.refl' (act-• u w w′)
    ; act-identity = λ _ → KB.refl
    ; act-compose  = λ _ _ _ → KB.refl
    }

  ------------------------------------------------------------------------
  -- γ: the factor set
  --
  -- The four cocycle laws are not separate obligations: by Theorem 9.8's
  -- necessity direction, an extension of Q by K realising φ, together
  -- with a unit-preserving lifting, determines its factor set and proves
  -- them all.  So the whole of γ reduces to one record.

  γ-of-lifting : {f : Word (SGen n) → Word (SGen n) → Word (PGen n)} →
                 FSE.IsFactorSet K Q φ f → FactorSet K Q φ
  γ-of-lifting {f} ifs = record
    { f                   = f
    ; isNormalisedCocycle = FSE.isFactorSet⇒isNormalisedCocycle K Q φ ifs
    }

  -- OPEN — the one remaining obligation.  What has to go in the hole is
  -- the Clifford group as an extension of Q by K, with a lifting.  The
  -- pieces exist and the shape is forced:
  --
  --   total    = CMS n, the Clifford group mod scalars
  --              (Qubit.CliffordGroup);
  --   incl     = CliffordGroup.incl ∘ sem — a Pauli WORD conjugates by
  --              the vector it reads as; injective by incl-injective and
  --              Build.complete;
  --   proj     = secn ∘ CliffordGroup.proj, where secn : Symplectic n →
  --              Word (SGen n) is Surjectivity.surj-nf.  It respects the
  --              congruence because the simplified presentation is
  --              complete: two symplectic words with ≈ˢ-equal denotations
  --              are ≈-equal;
  --   lifting  = inv-nf ∘ nf, the SYNTACTIC symplectic normal form.  It
  --              must factor through the normal-form datatype, not
  --              through Symplectic n: lifting-cong needs nf u ≡ nf v
  --              propositionally, which UniqueNormalForm gives and ≈ˢ
  --              (a pointwise equality of maps) does not;
  --   f        = proj₁ of ker⊆im-incl applied to ℓu • ℓv • (ℓ(u•v))⁻¹,
  --              which lies in the kernel because the three projections
  --              agree — this is what makes `factors` hold by
  --              construction.
  --
  -- Two lemmas are missing for it: that conjugating incl P by a Clifford
  -- word is incl of the symplectic action (`realizes`; CliffordGroup
  -- proves incl-∙, incl-ε, incl-injective and ker-witness, but not this),
  -- and a UniqueNormalForm for the SIMPLIFIED rule set, which
  -- Simplified.Iso should carry over from the plain one.

  clifford-isFactorSet :
    Σ[ f ∈ (Word (SGen n) → Word (SGen n) → Word (PGen n)) ]
      FSE.IsFactorSet K Q φ f
  clifford-isFactorSet = {!!}

  γ : FactorSet K Q φ
  γ = γ-of-lifting (proj₂ clifford-isFactorSet)

  ------------------------------------------------------------------------
  -- The twisted product K ×_f Q
  --
  -- Pauli words paired with Clifford words, multiplied by
  --
  --     (a , u) ∙ (b , v) = ((a • act u b) • f u v , u • v),
  --
  -- and the short exact sequence 1 → K → K ×_f Q → Q → 1 it carries.

  Twisted : Group 0ℓ 0ℓ
  Twisted = FSE.group K Q φ γ

  Twisted-extension : Extension (AbelianGroup.group K) Q
  Twisted-extension = FSE.factorSetExtension K Q φ γ

  ------------------------------------------------------------------------
  -- The split instance
  --
  -- Independently of γ, the trivial factor set is available, and with it
  -- the semidirect product K ⋊ Q — the extension whose lifting
  -- u ↦ (ε , u) is a homomorphism.  This one is complete: it rests only
  -- on φ.

  γ-split : FactorSet K Q φ
  γ-split = FSE.trivialFactorSet K Q φ

  Affine : Group 0ℓ 0ℓ
  Affine = FSE.group K Q φ γ-split

  Affine-extension : Extension (AbelianGroup.group K) Q
  Affine-extension = FSE.factorSetExtension K Q φ γ-split
