------------------------------------------------------------------------
-- Presentations of groups
--
-- The group the rule set with -1 presents.
--
-- Clifford.Qupit presents the exact Clifford group: the central
-- extension
--
--     1 ─→ ⟨ω⟩ ─→ Exact-group n ─→ Pauli n ⋊ Sp(2n, ℤ/pℤ) ─→ 1
--
-- built from the Weyl cocycle (Clifford.Qupit.Presentation's
-- presentation-exact).  Its scalars are ⟨ω⟩ ≅ ℤ/pℤ, of odd order p,
-- so it cannot contain -1, which has order 2.
--
-- The Clifford group of the paper (arXiv:2609.40106) is generated by
-- -ω, H, S, CZ.  Since 2 and p are coprime, -ω generates the same
-- scalars as -1 and ω together (-1 = (-ω)ᵖ, ω = (-ω)ᵖ⁺¹), so that group
-- is generated by -1 and by the exact group; and -1 is central and
-- meets the exact group trivially, the latter's scalars being of odd
-- order.  Hence it is the internal direct product
--
--     Clifford± n  =  Exact-group n  ×  ⟨ -1 ⟩,      ⟨ -1 ⟩ ≅ ℤ/2ℤ,
--
-- with scalars ±ωᵗ ≅ ℤ/2pℤ.  (On matrices the same split shows up in
-- the determinant: det(-I) = (-1)^(pⁿ) = -1 on the odd number pⁿ of
-- dimensions, while det(ωI) = ω^(pⁿ) = 1.)  This module defines the
-- three groups; Presentation.agda shows the rule set with -1 presents
-- the last.
--
-- It also re-derives how the exact interpretation reads the two
-- embeddings — a scalar word on the left is that scalar with no gate,
-- a circuit on the right is the circuit with the scalar the cocycle
-- accumulates along it.  Clifford.Qupit.Presentation proves exactly
-- these facts but keeps them private; both clients here (the direct
-- product's scalar part, and lifting a mod-scalar derivation in
-- ExactLift) need them.  They are stated generically in the generator
-- data and Realises, the discipline of that module, and instantiated
-- once at the exact data.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Fin using (toℕ)
open import Data.Nat using (ℕ ; suc)
open import Data.Nat.Primality using (Prime)
open import Data.Product using (_,_ ; ∃)
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Notations
open import ForStdlib.Data.Fin.Mod
open import ForStdlib.Data.Fin.Mod.Prime.Fermat

module Examples.Groups.Clifford+MinusOne.Qupit.Semantics
  (p-3 : ℕ)
  (let p-2 = ₁₊ p-3)
  (p-prime : Prime (suc (₁₊ p-2)))
  (let open PrimeModulus' p-2 p-prime)
  (g*@(g , g≠0) : ℤ* ₚ)
  (g-gen : ∀ ((x , _) : ℤ* ₚ) → ∃ \ (k : ℤ ₚ-₁) → x ≡ g ^′ toℕ k)
  where

open import Algebra.Bundles using (Group)
import Algebra.Construct.DirectProduct as ADP
open import Data.Product using (proj₂)
open import Level using (0ℓ)
import Relation.Binary.PropositionalEquality as Eq

open import Word.Base using (Word ; [_]ʷ ; ε ; _•_)
import Presentation.Base as PB
open import Presentation.Construct.Base using ([_]ₗ ; [_]ᵣ)

open import ForStdlib.Algebra.Construct.CentralExtension using (Cocycle)

import Examples.Groups.Cyclic.Semantics as CyS

import Examples.Groups.Clifford+MinusOne.Qupit.Syntactics
  p-3 p-prime g* g-gen as N

-- The exact layer: its total group, its presentation, and the proof
-- that the cocycle realises the corrections.
import Examples.Groups.Clifford.Qupit.Semantics p-3 p-prime as Sem
module PE = Sem.Presented-Extension g* g-gen
import Examples.Groups.Clifford.Qupit.Presentation
  p-3 p-prime g* g-gen as QP
import Examples.Groups.Clifford.Qupit.SemSRel p-3 p-prime g* g-gen as SR

------------------------------------------------------------------------
-- The three groups

-- The exact Clifford group: scalars ⟨ω⟩, presented by n Exact,_===_.
Exact-group : ℕ → Group 0ℓ 0ℓ
Exact-group n = PE.Presented-group n (QP.exact-generator-data n)

-- ⟨ -1 ⟩, presented by the cyclic relation of order 2.
Z₂ : Group 0ℓ 0ℓ
Z₂ = CyS.Cn-group 2

-- The Clifford group of the paper, scalars ±ωᵗ.
Clifford± : ℕ → Group 0ℓ 0ℓ
Clifford± n = ADP.group (Exact-group n) Z₂

------------------------------------------------------------------------
-- Reading embedded words in the exact group
--
-- Clifford.Qupit.Presentation's private emb-l, emb-r, gate, ev-pair and
-- val, restated.  Equality in the total group is pointwise — the
-- scalar words on the left, Paper-V0 on the right — so the combinators
-- are written out on pairs, as there: the implicits of a Pointwise
-- equivalence are not recovered by unification.

module Reading
  (n : ℕ)
  (gd : PE.GeneratorData n)
  (real : PE.Realises n gd)
  where

  private
    module KB = PB N.Scalar-relation
    module QB = PB (N.CR._QRel,_===_ n)
    module XP = QP.Exact-Presentation n gd real
    module G  = Group (PE.Presented-group n gd)

  -- The interpretation, and the two halves of the presentation theorem
  -- the clients spend.
  open XP public using (⟦_⟧ ; sound ; injective)

  -- Reading a circuit with every gate lifted trivially.
  module Ev = PE.Evaluation n (PE.γᶜ n gd)

  ----------------------------------------------------------------------
  -- Equality in the total group, componentwise

  infixr 4 _⟨G⟩_
  _⟨G⟩_ : ∀ {x y z} → G._≈_ x y → G._≈_ y z → G._≈_ x z
  (e₁ , e₂) ⟨G⟩ (f₁ , f₂) = KB.trans e₁ f₁ , QB.trans e₂ f₂

  G-refl : ∀ {x} → G._≈_ x x
  G-refl = KB.refl , QB.refl

  G-sym : ∀ {x y} → G._≈_ x y → G._≈_ y x
  G-sym (e₁ , e₂) = KB.sym e₁ , QB.sym e₂

  G-∙ : ∀ {x x' y y'} → G._≈_ x x' → G._≈_ y y' →
        G._≈_ (x G.∙ y) (x' G.∙ y')
  G-∙ (e₁ , e₂) (f₁ , f₂) =
      KB.cong (KB.cong e₁ f₁) (Cocycle.c-cong (PE.γᶜ n gd) e₂ f₂)
    , QB.cong e₂ f₂

  ----------------------------------------------------------------------
  -- The two embeddings

  -- A scalar word is that scalar with no gate: the cocycle vanishes on
  -- the trivial gate.
  emb-l : (a : Word N.ScalarGen) → G._≈_ ⟦ [ a ]ₗ ⟧ (a , ε)
  emb-l [ x ]ʷ  = G-refl
  emb-l ε       = G-refl
  emb-l (a • b) =
    G-∙ (emb-l a) (emb-l b) ⟨G⟩ (KB.right-unit , QB.left-unit)

  -- A circuit is read exactly as Evaluation reads it, on the nose.
  emb-r : (w : N.Circuit n) → ⟦ [ w ]ᵣ ⟧ ≡ Ev.⟦ w ⟧
  emb-r [ a ]ʷ  = Eq.refl
  emb-r ε       = Eq.refl
  emb-r (u • v) = Eq.cong₂ G._∙_ (emb-r u) (emb-r v)

  -- ... and its gate part is the circuit itself.
  gate : (w : N.Circuit n) → proj₂ Ev.⟦ w ⟧ ≡ w
  gate [ a ]ʷ  = Eq.refl
  gate ε       = Eq.refl
  gate (u • v) = Eq.cong₂ _•_ (gate u) (gate v)

  emb-r-pair : (w : N.Circuit n) → G._≈_ ⟦ [ w ]ᵣ ⟧ (Ev.scal w , w)
  emb-r-pair w =
    Eq.subst (λ z → G._≈_ z (Ev.scal w , w)) (Eq.sym (emb-r w))
             (KB.refl , QB.refl' (gate w))

  -- A split word: the scalars, then the circuit's own scalar.  The
  -- cocycle term is ε on the nose, its first argument being trivial.
  val : (a : Word N.ScalarGen) (b : N.Circuit n) →
        G._≈_ ⟦ [ a ]ₗ • [ b ]ᵣ ⟧ ((a • Ev.scal b) • ε , ε • b)
  val a b = G-∙ (emb-l a) (emb-r-pair b)

-- At the exact generator data, with Realises discharged by SemSRel:
-- the instance Exact-group is built from.
module Exact-Reading (n : ℕ) =
  Reading n (QP.exact-generator-data n) (SR.realises n)
