------------------------------------------------------------------------
-- Presentations of groups
--
-- Soundness of the real-Clifford+CH equational theory (Clément,
-- Proposition 3.1): the monoid congruence generated by Figure 4 (with
-- the swap rules of Remark 1) preserves the matrix denotation
-- ⟦_⟧ : Circuit n → Scaled n.
--
-- Two steps.  axiom-sound handles the RAW relation, one clause per
-- rule.  Each equation of Figure 4 but (19) is a computation on
-- integer matrices at the width it is drawn on (Soundness.Relators),
-- carried to every width by Interpretation.by-relator; (19) is the
-- induction of Soundness.Box; and the structural rules are the tensor
-- calculus of Semantics.Local — comm₁ and comm₂ are both the mixed
-- product law, cong↑ is functoriality of I₂ ⊗ −.  sound then closes it
-- under the monoid congruence, which is routine: every constructor of
-- _≈_ maps to the corresponding law of the scaled-matrix monoid.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Real-Clifford+CH.Soundness where

open import Data.Nat using (ℕ)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)
open import Word.Base using (Word ; [_]ʷ ; ε ; _•_)

import Presentation.Base as PB

open import Examples.Groups.Real-Clifford+CH.Semantics hiding (_^_)
open import Examples.Groups.Real-Clifford+CH.Syntactics
open import Examples.Groups.Real-Clifford+CH.Interpretation
open import Examples.Groups.Real-Clifford+CH.Soundness.Relators
open import Examples.Groups.Real-Clifford+CH.Soundness.Operators using (up-·)
open import Examples.Groups.Real-Clifford+CH.Soundness.Box using (box-Z-sound)

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- The structural rules

-- The scaled relation _~_ unfolds to an equation of operators in which
-- the powers of √2 are not unification patterns, so every lemma about
-- it is given its words explicitly.

private
  -- Two words with as many letters and the same operator denote the
  -- same matrix.
  same : (w v : Circuit n) → len w ≡ len v → ⟦ w ⟧ₒ ≐ ⟦ v ⟧ₒ → ⟦ w ⟧ ~ ⟦ v ⟧
  same w v = ~-reflexive {l = len w} {len v} {M = ⟦ w ⟧ₒ} {⟦ v ⟧ₒ}

  -- The operator of two letters (⟦_⟧ₒ is abstract).
  gen² : (a b : Gen n) → ⟦ [ a ]ʷ • [ b ]ʷ ⟧ₒ ≐ (⟦ a ⟧ᵍ ⊙ ⟦ b ⟧ᵍ)
  gen² a b = ≐-trans (⟦⟧ₒ-• [ a ]ʷ [ b ]ʷ) (⊙-cong (⟦⟧ₒ-gen a) (⟦⟧ₒ-gen b))

-- The derivation moves up a wire, and so does its operator.
cong↑-sound : {w v : Circuit n} → ⟦ w ⟧ ~ ⟦ v ⟧ → ⟦ w ↑ ⟧ ~ ⟦ v ↑ ⟧
cong↑-sound {w = w} {v} e =
  ≐-trans (·-cong (Eq.cong √2^_ (len-↑ v)) (up-word w))
    (≐-trans (≐-sym (up-· (√2^ len v) ⟦ w ⟧ₒ))
      (≐-trans (up-cong e)
        (≐-trans (up-· (√2^ len w) ⟦ v ⟧ₒ)
                 (·-cong (Eq.cong √2^_ (Eq.sym (len-↑ w))) (≐-sym (up-word v))))))

-- A one-wire gate and an operator shifted past it are M ⊗ N either way
-- round; a two-wire gate likewise, once two shifts are seen as one.
comm₁-sound : (h : Gate 1) (g : Gen n) →
              ⟦ [ g ↥ ]ʷ • [ gate₁ h ]ʷ ⟧ ~ ⟦ [ gate₁ h ]ʷ • [ g ↥ ]ʷ ⟧
comm₁-sound H-gate g = same ([ g ↥ ]ʷ • H) (H • [ g ↥ ]ʷ) Eq.refl
  (≐-trans (gen² (g ↥) H-gen)
    (≐-trans (≐-sym (emb-up-comm hM ⟦ g ⟧ᵍ)) (≐-sym (gen² H-gen (g ↥)))))
comm₁-sound Z-gate g = same ([ g ↥ ]ʷ • Z) (Z • [ g ↥ ]ʷ) Eq.refl
  (≐-trans (gen² (g ↥) Z-gen)
    (≐-trans (≐-sym (emb-up-comm zM ⟦ g ⟧ᵍ)) (≐-sym (gen² Z-gen (g ↥)))))

comm₂-sound : (h : Gate 2) (g : Gen n) →
              ⟦ [ g ↥ ↥ ]ʷ • [ gate₂ h ]ʷ ⟧ ~ ⟦ [ gate₂ h ]ʷ • [ g ↥ ↥ ]ʷ ⟧
comm₂-sound CZ-gate g = same ([ g ↥ ↥ ]ʷ • CZ) (CZ • [ g ↥ ↥ ]ʷ) Eq.refl
  (≐-trans (gen² (g ↥ ↥) CZ-gen)
    (≐-trans (⊙-cong (up-up ⟦ g ⟧ᵍ) (≐-refl (emb czM)))
      (≐-trans (≐-sym (emb-up-comm czM ⟦ g ⟧ᵍ))
        (≐-trans (⊙-cong (≐-refl (emb czM)) (≐-sym (up-up ⟦ g ⟧ᵍ)))
                 (≐-sym (gen² CZ-gen (g ↥ ↥)))))))
comm₂-sound CH-gate g = same ([ g ↥ ↥ ]ʷ • CH) (CH • [ g ↥ ↥ ]ʷ) Eq.refl
  (≐-trans (gen² (g ↥ ↥) CH-gen)
    (≐-trans (⊙-cong (up-up ⟦ g ⟧ᵍ) (≐-refl (emb chM)))
      (≐-trans (≐-sym (emb-up-comm chM ⟦ g ⟧ᵍ))
        (≐-trans (⊙-cong (≐-refl (emb chM)) (≐-sym (up-up ⟦ g ⟧ᵍ)))
                 (≐-sym (gen² CH-gen (g ↥ ↥)))))))

------------------------------------------------------------------------
-- Soundness of the axioms

axiom-sound : {w v : Circuit n} → n VRel, w === v → ⟦ w ⟧ ~ ⟦ v ⟧
-- Figure 4, by matrix computation at the width each equation is drawn on.
axiom-sound (srel order-H)       = by-relator r1ˡ  r1ʳ  p1ˡ  p1ʳ  m1
axiom-sound (srel order-Z)       = by-relator r2ˡ  r2ʳ  p2ˡ  p1ʳ  m2
axiom-sound (srel order-HZ)      = by-relator r3ˡ  r3ʳ  p3ˡ  p1ʳ  m3
axiom-sound (srel order-CZ)      = by-relator r4ˡ  r4ʳ  p4ˡ  p4ʳ  m4
axiom-sound (srel order-CH)      = by-relator r5ˡ  r5ʳ  p5ˡ  p4ʳ  m5
axiom-sound (srel merge-CZ)      = by-relator r6ˡ  r6ʳ  p6ˡ  p6ʳ  m6
axiom-sound (srel merge-CH)      = by-relator r7ˡ  r7ʳ  p7ˡ  p7ʳ  m7
axiom-sound (srel comm-CZ-Ex)    = by-relator r9ˡ  r9ʳ  p9ˡ  p9ʳ  m9
axiom-sound (srel comm-CH-°CZ)   = by-relator r10ˡ r10ʳ p10ˡ p10ʳ m10
axiom-sound (srel slide-CH)      = by-relator r11ˡ r11ʳ p11ˡ p11ʳ m11
axiom-sound (srel comm-CZ↑-CZ↓)  = by-relator r12ˡ r12ʳ p12ˡ p12ʳ m12
axiom-sound (srel comm-CZ↑-CH↓)  = by-relator r13ˡ r13ʳ p13ˡ p13ʳ m13
axiom-sound (srel symm-controls) = by-relator r14ˡ r14ʳ p14ˡ p14ʳ m14
axiom-sound (srel square-CCZX)   = by-relator r15ˡ r15ʳ p15ˡ p15ʳ m15
axiom-sound (srel comm-°CZ₂₀-CH) = by-relator r16ˡ r16ʳ p16ˡ p16ʳ m16
axiom-sound (srel comm-°CZ₂₀-HH) = by-relator r17ˡ r17ʳ p17ˡ p17ʳ m17
axiom-sound (srel conj-PP)       = by-relator r18ˡ r18ʳ p18ˡ p18ʳ m18
-- (19): the box is diagonal.
axiom-sound (srel (box-Z k))     = box-Z-sound k
-- The swap rules of Remark 1.
axiom-sound (srel swap-order)    = by-relator sgˡ  sgʳ  psgˡ  p4ʳ   msg
axiom-sound (srel swap-Z)        = by-relator sZˡ  sZʳ  psZˡ  psZʳ  msZ
axiom-sound (srel swap-H)        = by-relator sHˡ  sHʳ  psHˡ  psHʳ  msH
axiom-sound (srel swap-CZ)       = by-relator sCZˡ sCZʳ psCZˡ psCZʳ msCZ
axiom-sound (srel swap-CH)       = by-relator sCHˡ sCHʳ psCHˡ psCHʳ msCH
-- The structural rules.
axiom-sound (cong↑ r)            = cong↑-sound (axiom-sound r)
axiom-sound (comm₁ h g)          = comm₁-sound h g
axiom-sound (comm₂ h g)          = comm₂-sound h g
axiom-sound (ω↑=ω ())

------------------------------------------------------------------------
-- Soundness of the congruence (Proposition 3.1)
--
-- Closing under the monoid congruence is the library's job
-- (StarInterp.Extend.Cong): every constructor of _≈_ maps to the
-- corresponding law of the scaled-matrix monoid.  It works with the
-- reading built from the monoid, ⟦_⟧ᴱ, which is a homomorphism on the
-- nose; ⟦_⟧ is that reading (Interpretation.⟦⟧ᴱ-def).

axiom-soundᴱ : {w v : Circuit n} → n VRel, w === v →
               Ext.⟦_⟧ᴱ n w ~ Ext.⟦_⟧ᴱ n v
axiom-soundᴱ {w = w} {v} r = ⟦⟧ᴱ-~ {w = w} {v} (axiom-sound r)

soundᴱ : {w v : Circuit n} → n ⊢ w ≈ v → Ext.⟦_⟧ᴱ n w ~ Ext.⟦_⟧ᴱ n v
soundᴱ {n} = Ext.Cong.fʷ-cong n axiom-soundᴱ

sound : {w v : Circuit n} → n ⊢ w ≈ v → ⟦ w ⟧ ~ ⟦ v ⟧
sound {w = w} {v} e = ~-⟦⟧ᴱ {w = w} {v} (soundᴱ e)
