------------------------------------------------------------------------
-- Presentations of groups
--
-- Real-Clifford+CH circuits: the gate set, the shortcuts, and the
-- complete equational theory of Clément's Figure 4
--
-- This is the syntactic side of the formalisation of
--
--   A. Clément, "A Complete Equational Theory for Real-Clifford+CH
--   Quantum Circuits", arXiv:2602.06644.
--
-- The circuits are generated by the Hadamard gate H, the Pauli Z gate,
-- the controlled-Z gate CZ and the controlled-Hadamard gate CH (the
-- paper's gate set (A)), read as wire-indexed words in the Circuit
-- framework rather than as arrows of a PROP:
--
--   * a circuit is a word over generators placed on wires, so the
--     PROP's sequential composition is concatenation and the
--     interchange law is the structural comm rules of Lift-Relation;
--   * wires are numbered from 0, and wire 0 is the BOTTOM wire of the
--     paper's pictures (the paper's topmost wire of a w-wire picture is
--     wire w − 1).  A two-wire gate sits on wires 0 and 1; for CH the
--     control is wire 1 (the upper wire in the picture) and the target
--     is wire 0;
--   * the swap is not a generator.  Equation (8) of Figure 4 expresses
--     it over H and CZ, so here that word, Ex, IS the swap, and (8)
--     holds by definition.  What the PROP structure supplies for free —
--     the swap being natural and an involution (Figure 1 (f), (g)) — has
--     to be said, and it is said the way the paper's Remark 1 says it
--     for the PRO setting: by the four generator instances of Figure 2
--     and by (g), stated here as the axioms swap-*.
--
-- The multi-controlled gates of Definition 2.4 and the change-of-basis
-- pair P ⊗ P of Section 2.2 are defined as the words the paper defines
-- them as, since Equations (18) and (19) mention them.  A multi-
-- controlled gate written "on non-adjacent qubits" is, as in the paper,
-- conjugated by swaps; the paper leaves the swap network to the
-- topological rules, and one network is fixed here.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Real-Clifford+CH.Syntactics where

open import Data.Nat using (ℕ)
open import Data.Product using (_,_)
open import Notations using (₁₊ ; ₂₊ ; ₃₊ ; ₄₊)
open import Presentation.GroupLike using (Grouplike)
open import Word.Base using (Word ; WRel ; [_]ʷ ; ε ; _•_ ; _^_)

import Circuit.Base
import Presentation.Base as PB

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- Gate type: the paper's gate set (A)

data Gate : ℕ → Set where
  H-gate  : Gate 1
  Z-gate  : Gate 1
  CZ-gate : Gate 2
  CH-gate : Gate 2

------------------------------------------------------------------------
-- Syntactic framework

private module SC = Circuit.Base Gate

-- gate₀ is exported so clients can discharge it: this gate set has no
-- 0-ary gate, so every gate₀ case is the absurd `gate₀ ()`.
open SC public
  using ( Gen ; gate₀ ; gate₁ ; gate₂ ; Circuit
        ; _↥ ; _↑ ; _↓ ; _↥ᵏ_ ; _↑ᵏ_ ; _↓ᵏ_ ; _↧ᵏ_ )

pattern H-gen  = gate₁ H-gate
pattern Z-gen  = gate₁ Z-gate
pattern CZ-gen = gate₂ CZ-gate
pattern CH-gen = gate₂ CH-gate

-- The four generators as one-letter circuits.  A one-wire gate sits on
-- wire 0; a two-wire gate on wires 0 and 1, with CH controlled by wire 1.
H Z : Circuit (₁₊ n)
H = [ H-gen ]ʷ
Z = [ Z-gen ]ʷ

CZ CH : Circuit (₂₊ n)
CZ = [ CZ-gen ]ʷ
CH = [ CH-gen ]ʷ

------------------------------------------------------------------------
-- Shortcuts (Section 2.2, Figure 3)
--
-- In the names below, a ° marks a negated (white) control, on the side
-- of the wire it negates: °CZ has its upper control negated, CZ° its
-- lower one.  HC is the controlled-H with the target on the UPPER wire.

-- The Pauli X gate: X := H • Z • H.
X : Circuit (₁₊ n)
X = H • Z • H

-- The negated Z ("○"): X • Z • X.
Z° : Circuit (₁₊ n)
Z° = X • Z • X

-- CNOT with control on wire 1 and target on wire 0.
CX : Circuit (₂₊ n)
CX = H ↓ • CZ • H ↓

-- The swap, which Equation (8) of Figure 4 writes over CZ and H.  This
-- word is the paper's swap gate: (8) holds by definition.
Ex : Circuit (₂₊ n)
Ex = CZ • H ↓ • H ↑ • CZ • H ↓ • H ↑ • CZ • H ↓ • H ↑

-- Controlled-H with target on wire 1, control on wire 0; CNOT with
-- target on wire 1.
HC XC : Circuit (₂₊ n)
HC = Ex • CH • Ex
XC = Ex • CX • Ex

-- Negated controls: conjugating the control wire by X.
°CZ CZ° °CZ° °CH HC° °CX XC° : Circuit (₂₊ n)
°CZ  = X ↑ • CZ • X ↑
CZ°  = X ↓ • CZ • X ↓
°CZ° = X ↓ • X ↑ • CZ • X ↓ • X ↑
°CH  = X ↑ • CH • X ↑
HC°  = X ↓ • HC • X ↓
°CX  = X ↑ • CX • X ↑
XC°  = X ↓ • XC • X ↓

-- Gates on wires 2 and 0 of a three-wire block (the paper's "non-
-- adjacent qubits"), by conjugation with the swap of wires 0 and 1:
-- CZ₂₀ is a CZ between wires 2 and 0, CH₂₀ is controlled by wire 2 with
-- target wire 0, and °CZ₂₀ negates the control on wire 2.
CZ₂₀ CH₂₀ °CZ₂₀ : Circuit (₃₊ n)
CZ₂₀  = Ex ↓ • CZ ↑ • Ex ↓
CH₂₀  = Ex ↓ • CH ↑ • Ex ↓
°CZ₂₀ = X ↑ ↑ • CZ₂₀ • X ↑ ↑

-- The change-of-basis pair P ⊗ P of Section 2.2, with P = R_Y(π/4) Z:
-- three rounds of a controlled-H followed by H on the control wire and
-- Z on the target wire, then the swap.
PP : Circuit (₂₊ n)
PP = CH • H ↑ • Z ↓ • CH • H ↑ • Z ↓ • CH • H ↑ • Z ↓ • Ex

------------------------------------------------------------------------
-- Multi-controlled gates (Definition 2.4)
--
-- Λ□ k is the paper's k-controlled "dashed box", a k-controlled −I: its
-- controls are wires 1 … k and the dashed box sits on wire 0, the extra
-- qubit the shortcut uses.  Semantically it is the k-controlled Z on
-- the controls, tensored with the identity on wire 0.
--
-- The paper defines it by mutual induction with the multi-controlled
-- ZX and XZ gates.  The induction is well founded because the step for
-- k + 3 controls only ever needs the DOUBLY-controlled ZX and XZ, which
-- in turn need only the 2-controlled box, a base case; so those two are
-- defined first, and Λ□ by ordinary recursion.
--
-- Where the paper puts the box in the middle of the controls it means a
-- swap-conjugate of the box-at-the-bottom gate; the step for k + 3
-- controls needs the box on wire 1 with a control below it on wire 0,
-- and wire 2 idle, which is the (k + 2)-controlled gate shifted up a
-- wire and conjugated by the transposition of wires 0 and 2.

-- The transposition of wires 0 and 2, and conjugation by it and by the
-- swap of wires 0 and 1.
τ₀₂ : Circuit (₃₊ n)
τ₀₂ = Ex ↓ • Ex ↑ • Ex ↓

τ₀₂-conj : Circuit (₃₊ n) → Circuit (₃₊ n)
τ₀₂-conj w = τ₀₂ • w • τ₀₂

Ex-conj : Circuit (₂₊ n) → Circuit (₂₊ n)
Ex-conj w = Ex ↓ • w • Ex ↓

-- The single-wire ZX and XZ gates: X then Z, and Z then X.
ZX XZ : Circuit (₁₊ n)
ZX = X • Z
XZ = Z • X

-- The doubly-controlled ZX and XZ, controls on wires 1 and 2, target
-- on wire 0 (Definition 2.4's recursive step for ZX and XZ, at one
-- control above the last, with the 2-controlled box CZ ↑ swapped to
-- have its box on wire 1 and its controls on wires 0 and 2, which is
-- CZ₂₀).
CCZX CCXZ : Circuit (₃₊ n)
CCZX = CH • CZ₂₀ • CH • CZ₂₀
CCXZ = CZ₂₀ • CH • CZ₂₀ • CH

-- The k-controlled dashed box, on exactly k + 1 wires.
Λ□ : (k : ℕ) → Circuit (₁₊ k)
Λ□ 0        = Z • Z°
Λ□ 1        = Z ↑
Λ□ 2        = CZ ↑
Λ□ (₃₊ k)   = CCZX • τ₀₂-conj (Λ□ (₂₊ k) ↑) • CCXZ • τ₀₂-conj (Λ□ (₂₊ k) ↑)

-- The k-controlled ZX and XZ gates, controls on wires 1 … k, target on
-- wire 0: the paper's recursive steps, with the (k)-controlled box
-- swapped to have its box on wire 1 and a control on wire 0.
ΛZX ΛXZ : (k : ℕ) → Circuit (₁₊ k)
ΛZX 0      = ZX
ΛZX (₁₊ k) = CH • Ex-conj (Λ□ (₁₊ k)) • CH • Ex-conj (Λ□ (₁₊ k))
ΛXZ 0      = XZ
ΛXZ (₁₊ k) = Ex-conj (Λ□ (₁₊ k)) • CH • Ex-conj (Λ□ (₁₊ k)) • CH

------------------------------------------------------------------------
-- Group-specific relations: Figure 4, and the swap rules of Remark 1
--
-- The paper's equation numbers are given with each rule.  Widths are
-- exact: a rule on w wires is stated at width w, and Lift-Relation's
-- cong↑ carries it to every width above.  Equation (8) is absent
-- because Ex is defined by it, and (19) is a schema: one equation on
-- each width n ≥ 5, so it takes the number of controls as an argument.

infix 4 _SRel,_===_
data _SRel,_===_ : (n : ℕ) → WRel (Gen n) where

  -- (1)–(3): one wire.
  order-H  : (₁₊ n) SRel, H • H === ε
  order-Z  : (₁₊ n) SRel, Z • Z === ε
  order-HZ : (₁₊ n) SRel, (H • Z) ^ 8 === ε

  -- (4)–(7), (9)–(11): two wires.
  order-CZ    : (₂₊ n) SRel, CZ • CZ === ε
  order-CH    : (₂₊ n) SRel, CH • CH === ε
  merge-CZ    : (₂₊ n) SRel, CZ • °CZ === Z ↓
  merge-CH    : (₂₊ n) SRel, CH • °CH === H ↓
  comm-CZ-Ex  : (₂₊ n) SRel, CZ • Ex === Ex • CZ
  comm-CH-°CZ : (₂₊ n) SRel, CH • °CZ === °CZ • CH
  slide-CH    : (₂₊ n) SRel, CH • H ↑ • Z ↑ • CH • H ↑
                             === H ↑ • Z ↑ • CH • H ↑ • CH

  -- (12)–(18): three wires.
  comm-CZ↑-CZ↓ : (₃₊ n) SRel, CZ ↑ • CZ ↓ === CZ ↓ • CZ ↑
  comm-CZ↑-CH↓ : (₃₊ n) SRel, CZ ↑ • CH ↓ === CH ↓ • CZ ↑
  symm-controls : (₃₊ n) SRel, CH ↓ • CZ₂₀ • CH ↓ • CZ₂₀
                               === CH₂₀ • CZ ↓ • CH₂₀ • CZ ↓
  square-CCZX   : (₃₊ n) SRel, (CH ↓ • CZ₂₀) ^ 4 === CZ ↑
  comm-°CZ₂₀-CH : (₃₊ n) SRel, °CZ₂₀ • CH ↓ • CZ₂₀ • CH ↓
                               === CH ↓ • CZ₂₀ • CH ↓ • °CZ₂₀
  comm-°CZ₂₀-HH : (₃₊ n) SRel, °CZ₂₀ • CH ↓ • CH ↑ • CH ↓
                               === CH ↓ • CH ↑ • CH ↓ • °CZ₂₀
  conj-PP       : (₃₊ n) SRel, CZ ↑ • PP ↓ === PP ↓ • CH ↑

  -- (19): on n ≥ 5 wires, the (n − 1)-controlled box commutes with Z
  -- on its extra qubit.
  box-Z : ∀ k → (₁₊ (₄₊ k)) SRel, Z ↓ • Λ□ (₄₊ k) === Λ□ (₄₊ k) • Z ↓

  -- The swap rules of Remark 1: Figure 1 (g), and Figure 2 (f1)–(f4).
  swap-order : (₂₊ n) SRel, Ex • Ex === ε
  swap-Z     : (₂₊ n) SRel, Z ↑ • Ex === Ex • Z ↓
  swap-H     : (₂₊ n) SRel, H ↑ • Ex === Ex • H ↓
  swap-CZ    : (₃₊ n) SRel, CZ ↑ • Ex ↓ • Ex ↑ === Ex ↓ • Ex ↑ • CZ ↓
  swap-CH    : (₃₊ n) SRel, CH ↑ • Ex ↓ • Ex ↑ === Ex ↓ • Ex ↑ • CH ↓

------------------------------------------------------------------------
-- Full relation via Lift-Relation (adds the structural rules cong↑,
-- comm₁, comm₂)

private module LR = SC.Lift-Relation _SRel,_===_
-- ω↑=ω is the 0-ary gate's structural rule.  This gate set has no
-- 0-ary gate, so it is never inhabited here — but it still has to be
-- re-exported, or a client cannot name it to discharge it when it
-- cases on the relation.
open LR public
  using ( srel ; cong↑ ; comm₁ ; comm₂ ; ω↑=ω ; lemma-cong↑
        ; comm-gate₁-w↑ ; comm-gate₂-w↑↑ ; _VRel,_===_ )

-- The congruence generated, at each width: QC ⊢ w = v.
infix 4 _⊢_≈_
_⊢_≈_ : (n : ℕ) → Circuit n → Circuit n → Set
n ⊢ w ≈ v = PB._≈_ (_VRel,_===_ n) w v

------------------------------------------------------------------------
-- Grouplike: every generator is its own inverse, by (1), (2), (4), (5)

grouplike : Grouplike (_VRel,_===_ n)
grouplike H-gen  = H  , PB.axiom (srel order-H)
grouplike Z-gen  = Z  , PB.axiom (srel order-Z)
grouplike CZ-gen = CZ , PB.axiom (srel order-CZ)
grouplike CH-gen = CH , PB.axiom (srel order-CH)
grouplike (gate₀ ())
grouplike {₁₊ n} (g ↥) with grouplike {n} g
... | ig , prf = ig ↑ , lemma-cong↑ (ig • [ g ]ʷ) ε prf
