------------------------------------------------------------------------
-- Presentations of groups
--
-- The syntax of n-qubit Clifford circuits (Selinger, "Generators and
-- relations for n-qubit Clifford operators", LMCS 11(2:10) 2015,
-- arXiv:1310.6813): the generators ω, H, S and CZ, the derived gate X,
-- and the relations C1 … C15 of Figure 8
--
-- The paper numbers qubits from the top; here wire 0 is the bottom
-- wire, and CZ sits on wires 0 and 1.  Words are in operator order, the
-- rightmost letter acting first, so a circuit read left to right as
-- "A then B" is the word B • A.  The structural rules of Circuit.Base
-- supply what the paper's strict spatial monoidal groupoid builds in:
-- gates on disjoint wires commute, and the scalar ω, a gate on no
-- wires, commutes with everything and is the same on every wire.  The
-- factor ω⁻¹ of C10 and C11 is written ω⁷.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Qubit-Clifford.Syntactics where

open import Data.Nat using (ℕ)
open import Data.Product using (_,_)
open import Word.Base using (Word ; WRel ; [_]ʷ ; ε ; _•_ ; _^_)

open import Notations using (₁₊ ; ₂₊ ; ₃₊)
open import Presentation.GroupLike using (Grouplike)

import Circuit.Base
import Presentation.Base as PB
import Presentation.Properties as PP
import Relation.Binary.PropositionalEquality as Eq

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- Gates

-- The scalar ω = e^{iπ/4} is a gate on no wires.
data Gate : ℕ → Set where
  ω-gate           : Gate 0
  H-gate S-gate    : Gate 1
  CZ-gate          : Gate 2

private module SC = Circuit.Base Gate

open SC public
  using ( Gen ; gate₀ ; gate₁ ; gate₂ ; Circuit
        ; _↥ ; _↑ ; _↓ ; _↥ᵏ_ ; _↑ᵏ_ ; _↓ᵏ_ ; _↧ᵏ_ )

pattern ω-gen  = gate₀ ω-gate
pattern H-gen  = gate₁ H-gate
pattern S-gen  = gate₁ S-gate
pattern CZ-gen = gate₂ CZ-gate

-- The generators as one-letter circuits.
ω : Circuit n
ω = [ ω-gen ]ʷ

H S : Circuit (₁₊ n)
H = [ H-gen ]ʷ
S = [ S-gen ]ʷ

CZ : Circuit (₂₊ n)
CZ = [ CZ-gen ]ʷ

------------------------------------------------------------------------
-- Derived gates (Section 4)

-- The Pauli X gate, X = HSSH.
X : Circuit (₁₊ n)
X = H • S • S • H

------------------------------------------------------------------------
-- The relations (Figure 8)
--
-- Each is stated at the width it is drawn on; the structural rules lift
-- it to every width.  Gates drawn in one column are written lower wire
-- first.

infix 4 _SRel,_===_
data _SRel,_===_ : (n : ℕ) → WRel (Gen n) where

  -- (a) n ≥ 0.
  C₁  : n SRel, ω ^ 8 === ε

  -- (b) n ≥ 1.
  C₂  : (₁₊ n) SRel, H • H === ε
  C₃  : (₁₊ n) SRel, S • S • S • S === ε
  C₄  : (₁₊ n) SRel, H • S • H • S • H • S === ω

  -- (c) n ≥ 2.
  C₅  : (₂₊ n) SRel, CZ • CZ === ε
  C₆  : (₂₊ n) SRel, CZ • S ↑ === S ↑ • CZ
  C₇  : (₂₊ n) SRel, CZ • S === S • CZ
  C₈  : (₂₊ n) SRel,
        CZ • H ↑ • S ↑ • S ↑ • H ↑ === H ↑ • S ↑ • S ↑ • H ↑ • S • S • CZ
  C₉  : (₂₊ n) SRel,
        CZ • H • S • S • H === H • S • S • H • S ↑ • S ↑ • CZ
  C₁₀ : (₂₊ n) SRel,
        CZ • H ↑ • CZ === ω ^ 7 • S ↑ • H ↑ • S ↑ • S • CZ • H ↑ • S ↑
  C₁₁ : (₂₊ n) SRel,
        CZ • H • CZ === ω ^ 7 • S • H • S • S ↑ • CZ • H • S

  -- (d) n ≥ 3.
  C₁₂ : (₃₊ n) SRel, CZ • CZ ↑ === CZ ↑ • CZ
  C₁₃ : (₃₊ n) SRel,
        CZ ↑ • H ↑ • H ↑ ↑ • CZ ↑ • H • H ↑ • CZ • H • H ↑ • CZ ↑ • H ↑ • H ↑ ↑ • CZ ↑ ===
        CZ • H ↑ • H • CZ • H ↑ ↑ • H ↑ • CZ ↑ • H ↑ ↑ • H ↑ • CZ • H ↑ • H • CZ
  C₁₄ : (₃₊ n) SRel,
        CZ • H ↑ ↑ • H ↑ • CZ ↑ • H ↑ • H ↑ ↑ • CZ ↑ • CZ • H ↑ • H ↑ ↑ • CZ ↑ •
        H ↑ • H ↑ ↑ • CZ ↑ • CZ • H ↑ • H ↑ ↑ • CZ ↑ • H ↑ • H ↑ ↑ • CZ ↑ === ε
  C₁₅ : (₃₊ n) SRel,
        CZ ↑ • H • H ↑ • CZ • H ↑ • H • CZ • CZ ↑ • H ↑ • H • CZ •
        H ↑ • H • CZ • CZ ↑ • H ↑ • H • CZ • H ↑ • H • CZ === ε

------------------------------------------------------------------------
-- The full relation: the structural rules of Circuit.Base on top

private module LR = SC.Lift-Relation _SRel,_===_

open LR public
  using ( srel ; cong↑ ; comm₀ ; comm₁ ; comm₂ ; ω↑=ω ; lemma-cong↑
        ; comm-gate₀-w ; comm-gate₁-w↑ ; comm-gate₂-w↑↑ ; _VRel,_===_ )

-- The monoid congruence generated by the relations at width n: the
-- paper's equality of circuits.
infix 4 _⊢_≈_
_⊢_≈_ : (n : ℕ) → Circuit n → Circuit n → Set
n ⊢ w ≈ v = PB._≈_ (n VRel,_===_) w v

------------------------------------------------------------------------
-- Every generator is invertible, so the presented monoid is a group

grouplike : Grouplike (_VRel,_===_ n)
grouplike {n} ω-gen  = ω ^ 7 , PB.trans (PP.by-assoc (n VRel,_===_) Eq.refl) (PB.axiom (srel C₁))
grouplike {n} S-gen  = S • S • S , PB.trans (PP.by-assoc ((₁₊ _) VRel,_===_) Eq.refl) (PB.axiom (srel C₃))
grouplike H-gen   = H   , PB.axiom (srel C₂)
grouplike CZ-gen  = CZ  , PB.axiom (srel C₅)
grouplike (g ↥) with grouplike g
... | ig , prf = ig ↑ , lemma-cong↑ (ig • [ g ]ʷ) ε prf
