------------------------------------------------------------------------
-- Presentations of groups
--
-- Binary addition on bit vectors (Amy, QPL 2018, section 5.2)
--
-- Section 5.2 verifies a Clifford+T implementation of the out-of-place
-- adder
--
--    Adder_n : |x⟩|y⟩|0⟩ ↦ |x⟩|y⟩|x + y⟩,
--
-- "a standard out-of-place ripple-carry adder which uses n − 1 ancilla
-- bits to store intermediate carry values and an additional n bit
-- register to store the output, before copying out and uncomputing",
-- with 4(n − 1) Toffoli gates "expanded to the Clifford+T gate set".
-- The paper describes the circuit in words only, so one is designed
-- here (the one its tool generates is formalised as well: see the last
-- item); this module is the first of the development, whose plan is as
-- follows.
--
-- * Here: bit vectors a : Fin n → Bool, least significant bit first,
--   their values val a = a₀ + 2 a₁ + 4 a₂ + ⋯, the majority maj, and
--   ripple-carry addition add a b c : Fin (1 + n) → Bool, the n + 1
--   bits of a + b + c, computed position by position -- the sum bit
--   a₀ ⊕ b₀ ⊕ c, then the addition of the remaining bits with carry-in
--   maj(a₀, b₀, c).  The theorem is that these bits encode the sum:
--   val (add a b c) ≡ val a + val b + c (add-correct), by induction
--   and the full-adder identity a + b + c = (a ⊕ b ⊕ c) + 2 maj(a,b,c).
--   The intermediate carries (carry) and the sum bits (sumbit) are the
--   values the circuit's carry ancillas and temporary register hold;
--   the low n bits of add are the sum bits and the last one the carry
--   out, so the sum bits encode (a + b + c) mod 2^n (sumbit-mod).
--
-- * PathSum.Reversible: circuits of Toffoli and CNOT gates read
--   classically -- each gate xors a product of its controls into its
--   target -- with the facts the adder's proof needs, all generic:
--   every gate is an involution, so a netlist followed by its reverse
--   is the identity; a netlist that neither reads nor writes a set of
--   wires commutes with anything that writes only there; hence
--   Bennett's compute-copy-uncompute: F ++ M ++ reverse F leaves every
--   wire F works on as it was, and on the others does what M does
--   after F.  Also the gate counts.
--
-- * PathSum.Adder.Layout: the wires.  For n = m + 1 bits, 5n of them:
--   x₀ … x_m, y₀ … y_m, the output z₀ … z_n (n + 1 bits, so that it
--   can hold x + y itself, carry included), the n − 1 carry ancillas
--   c₁ … c_m and the n-bit temporary register s₀ … s_m.  They are
--   named by a small data type, mapped injectively into the circuit's
--   wires; the standard layout is x, y, z, c, s in that order, on
--   exactly 5n wires.
--
-- * PathSum.Adder.Ripple: the netlist and its correctness.  It is
--   Bennett's F ++ M ++ reverse F, with F the ripple: at each position
--   i, first the carry into i + 1, c_(i+1) ⊕= maj(x_i, y_i, c_i), by
--   the Toffoli, CNOT, Toffoli, CNOT block of Vedral, Barenco and
--   Ekert's CARRY with y_i restored (at position 0, where there is no
--   carry in, one Toffoli, c₁ ⊕= x₀ y₀), then the sum bit into the
--   temporary register, s_i ⊕= x_i ⊕ y_i ⊕ c_i; and M xors s_i into
--   z_i, and the carry out into z_n by the same block.  The theorem:
--   on every input whose carries and temporary register read 0 (blank),
--   the output z gains the bits of x + y, becoming z ⊕ (x + y), so
--   from z = 0 -- the paper's |x⟩|y⟩|0⟩ -- it reads the bits of x + y,
--   of value val x + val y; and on every input every other wire -- x,
--   y, the carries and the temporary register -- ends as it began.
--   Both are proved for every n ≥ 1 at once, by induction on the
--   positions and Bennett's lemma; no closed instance is computed
--   except small cross-checks.
--
-- * PathSum.Reversible.Expand and PathSum.Adder.Circuit: the netlist
--   expanded into Clifford+T, each Toffoli gate into the seven-T
--   circuit of PathSum.Toffoli.  By PathSum.Classical's composition
--   lemmas the circuit computes the netlist's Boolean function, so it
--   agrees, on the columns where its ancillas are |0⟩, with any
--   path-sum computing the addition on those inputs.
--
-- * PathSum.Adder.Spec and PathSum.Adder: the specification path-sum
--   (the paper's, "generated by implementing binary addition on
--   symbolic vectors") and the theorem against it.
--
-- * Resources: 5n wires, 4(n − 1) Toffoli gates for n ≥ 2 (one at
--   n = 1, where the carry out x₀ y₀ needs it -- 4(n − 1) = 0 fits only
--   an adder modulo 2^n) and 11n − 8 CNOTs; expanded, 8(n − 1) path
--   variables and 28(n − 1) T gates.  Table 2's rows, Adder8 (40
--   qubits, 56 path variables, 334 Clifford, 196 T) and Adder16 (80,
--   120, 710, 420), are exactly these at n = 8 and n = 16 but for the
--   Clifford column: the table's counts are nine per Toffoli gate plus
--   11n − 6, where the expansion here has eight per Toffoli gate and
--   11n − 8 CNOTs.  The paper's text says 5n − 1 bits, and its table
--   5n, as here.
--
-- * PathSum.Adder.CarryRipple, PathSum.Toffoli.Depth3 and
--   PathSum.Adder.Tool: the circuit the paper's tool generates, gate for
--   gate, with the same theorem.  It explains both differences: its
--   Toffoli circuit has seven CNOTs, its netlist 11n − 6, and a
--   carry-in wire the text does not count; its counts, computed from
--   the circuit, are table 2's exactly.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module PathSum.Adder.Binary where

open import Data.Bool.Base using (Bool; true; false; _∧_; _∨_; _xor_)
open import Data.Fin.Base using (Fin; zero; suc; inject₁; fromℕ)
open import Data.Nat.Base using
  (ℕ; zero; suc; _+_; _*_; _^_; _<_; _≤_; _%_; s≤s; z≤n)
open import Data.Nat.DivMod using ([m+kn]%n≡m%n; m<n⇒m%n≡m)
open import Data.Nat.Properties using
  (+-identityʳ; *-comm; ≤-trans; ≤-reflexive; +-monoˡ-≤; *-monoʳ-≤;
   m^n≢0)
open import Data.Nat.Solver using (module +-*-Solver)
open import Relation.Binary.PropositionalEquality using
  (_≡_; refl; sym; trans; cong; cong₂)

open +-*-Solver using (solve; con; _:+_; _:*_; _:=_)

private
  variable
    n m : ℕ


------------------------------------------------------------------------
-- Bits and their values

-- A bit as a natural number.

⌜_⌝ : Bool → ℕ
⌜ false ⌝ = 0
⌜ true  ⌝ = 1

-- The value of a bit vector, least significant bit first:
-- a₀ + 2 a₁ + 4 a₂ + ⋯.

val : (Fin n → Bool) → ℕ
val {zero}  a = 0
val {suc n} a = ⌜ a zero ⌝ + 2 * val (λ i → a (suc i))

-- Only the bits matter.

val-cong : {a b : Fin n → Bool} → (∀ i → a i ≡ b i) → val a ≡ val b
val-cong {zero}  h = refl
val-cong {suc n} h =
  cong₂ (λ p q → ⌜ p ⌝ + 2 * q) (h zero) (val-cong (λ i → h (suc i)))

-- The last bit is worth 2^n.

val-last : (a : Fin (suc n) → Bool) →
           val a ≡ val (λ i → a (inject₁ i)) + 2 ^ n * ⌜ a (fromℕ n) ⌝
val-last {zero}  a = refl
val-last {suc n} a =
  trans (cong (λ v → ⌜ a zero ⌝ + 2 * v) (val-last (λ i → a (suc i))))
        (shift ⌜ a zero ⌝ (val (λ i → a (suc (inject₁ i)))) (2 ^ n)
               ⌜ a (suc (fromℕ n)) ⌝)
  where
  shift : ∀ p A P q → p + 2 * (A + P * q) ≡ (p + 2 * A) + 2 * P * q
  shift = solve 4 (λ p A P q → p :+ con 2 :* (A :+ P :* q)
                              := (p :+ con 2 :* A) :+ con 2 :* P :* q)
                  refl

-- An n-bit vector is less than 2^n.

private
  ⌜⌝≤1 : ∀ b → ⌜ b ⌝ ≤ 1
  ⌜⌝≤1 false = z≤n
  ⌜⌝≤1 true  = s≤s z≤n

val< : (a : Fin n → Bool) → val a < 2 ^ n
val< {zero}  a = s≤s z≤n
val< {suc n} a = ≤-trans step (*-monoʳ-≤ 2 (val< (λ i → a (suc i))))
  where
  A : ℕ
  A = val (λ i → a (suc i))

  -- 1 + (a₀ + 2A) ≤ 2 + 2A = 2 (1 + A).
  step : suc (⌜ a zero ⌝ + 2 * A) ≤ 2 * suc A
  step = ≤-trans (s≤s (+-monoˡ-≤ (2 * A) (⌜⌝≤1 (a zero))))
                 (≤-reflexive (solve 1 (λ A → con 1 :+ (con 1 :+ con 2 :* A)
                                            := con 2 :* (con 1 :+ A))
                                       refl A))


------------------------------------------------------------------------
-- The full adder

-- The majority of three bits: the carry out of a one-bit addition.

maj : Bool → Bool → Bool → Bool
maj a b c = (a ∧ b) ∨ (a ∧ c) ∨ (b ∧ c)

-- a + b + c = (a ⊕ b ⊕ c) + 2 maj(a, b, c).

full-adder : ∀ a b c → ⌜ a ⌝ + ⌜ b ⌝ + ⌜ c ⌝ ≡
                       ⌜ a xor b xor c ⌝ + 2 * ⌜ maj a b c ⌝
full-adder false false false = refl
full-adder false false true  = refl
full-adder false true  false = refl
full-adder false true  true  = refl
full-adder true  false false = refl
full-adder true  false true  = refl
full-adder true  true  false = refl
full-adder true  true  true  = refl

-- The majority as the circuit computes it: a b, then c (b ⊕ a), the two
-- never both 1; with no carry in, a b.

maj-xor : ∀ a b c → maj a b c ≡ (a ∧ b) xor (c ∧ (b xor a))
maj-xor false false false = refl
maj-xor false false true  = refl
maj-xor false true  false = refl
maj-xor false true  true  = refl
maj-xor true  false false = refl
maj-xor true  false true  = refl
maj-xor true  true  false = refl
maj-xor true  true  true  = refl

maj-false : ∀ a b → maj a b false ≡ a ∧ b
maj-false false false = refl
maj-false false true  = refl
maj-false true  false = refl
maj-false true  true  = refl


------------------------------------------------------------------------
-- Ripple-carry addition

-- The n + 1 bits of a + b + c, least significant first: the sum bit
-- a₀ ⊕ b₀ ⊕ c, then the bits of the addition of the remaining bits
-- with carry in maj(a₀, b₀, c).  The last bit is the carry out.

add : (Fin n → Bool) → (Fin n → Bool) → Bool → Fin (suc n) → Bool
add {zero}  a b c zero    = c
add {suc n} a b c zero    = a zero xor b zero xor c
add {suc n} a b c (suc i) =
  add (λ j → a (suc j)) (λ j → b (suc j)) (maj (a zero) (b zero) c) i

-- They encode the sum.

add-correct : (a b : Fin n → Bool) (c : Bool) →
              val (add a b c) ≡ val a + val b + ⌜ c ⌝
add-correct {zero}  a b c = +-identityʳ ⌜ c ⌝
add-correct {suc n} a b c =
  trans (cong (λ v → ⌜ a zero xor b zero xor c ⌝ + 2 * v)
              (add-correct a′ b′ c′))
        (step ⌜ a zero ⌝ ⌜ b zero ⌝ ⌜ c ⌝ ⌜ a zero xor b zero xor c ⌝
              ⌜ c′ ⌝ (val a′) (val b′) (full-adder (a zero) (b zero) c))
  where
  a′ b′ : Fin n → Bool
  a′ j = a (suc j)
  b′ j = b (suc j)

  c′ : Bool
  c′ = maj (a zero) (b zero) c

  step : ∀ p q r s t A B → p + q + r ≡ s + 2 * t →
         s + 2 * (A + B + t) ≡ (p + 2 * A) + (q + 2 * B) + r
  step p q r s t A B h =
    trans (solve 4 (λ s t A B → s :+ con 2 :* (A :+ B :+ t)
                               := (s :+ con 2 :* t) :+ con 2 :* A
                                  :+ con 2 :* B)
                   refl s t A B)
    (trans (cong (λ v → v + 2 * A + 2 * B) (sym h))
           (solve 5 (λ p q r A B → (p :+ q :+ r) :+ con 2 :* A :+ con 2 :* B
                                   := (p :+ con 2 :* A) :+ (q :+ con 2 :* B)
                                      :+ r)
                    refl p q r A B))

-- In particular, without a carry in, x + y.

add-correct₀ : (a b : Fin n → Bool) → val (add a b false) ≡ val a + val b
add-correct₀ a b = trans (add-correct a b false) (+-identityʳ (val a + val b))


------------------------------------------------------------------------
-- The sum bits and the carries

-- The sum bits, a_i ⊕ b_i ⊕ (the carry into i), by the same recursion.

sumbit : (Fin n → Bool) → (Fin n → Bool) → Bool → Fin n → Bool
sumbit a b c zero    = a zero xor b zero xor c
sumbit a b c (suc i) =
  sumbit (λ j → a (suc j)) (λ j → b (suc j)) (maj (a zero) (b zero) c) i

-- The intermediate carries, into positions 1 … n − 1 (n = m + 1): the
-- values the circuit's n − 1 carry ancillas hold.

carry : (Fin (suc m) → Bool) → (Fin (suc m) → Bool) → Bool → Fin m → Bool
carry a b c zero    = maj (a zero) (b zero) c
carry a b c (suc j) =
  carry (λ i → a (suc i)) (λ i → b (suc i)) (maj (a zero) (b zero) c) j

-- The carry out of the last position.

carry-out : (Fin n → Bool) → (Fin n → Bool) → Bool → Bool
carry-out {zero}  a b c = c
carry-out {suc n} a b c =
  carry-out (λ j → a (suc j)) (λ j → b (suc j)) (maj (a zero) (b zero) c)

-- The first n bits of the addition are the sum bits, the last is the
-- carry out.

add-sumbit : (a b : Fin n → Bool) (c : Bool) (i : Fin n) →
             add a b c (inject₁ i) ≡ sumbit a b c i
add-sumbit {suc n} a b c zero    = refl
add-sumbit {suc n} a b c (suc i) =
  add-sumbit (λ j → a (suc j)) (λ j → b (suc j)) (maj (a zero) (b zero) c) i

add-carry-out : (a b : Fin n → Bool) (c : Bool) →
                add a b c (fromℕ n) ≡ carry-out a b c
add-carry-out {zero}  a b c = refl
add-carry-out {suc n} a b c =
  add-carry-out (λ j → a (suc j)) (λ j → b (suc j)) (maj (a zero) (b zero) c)

-- So a + b + c = the sum bits + 2^n × the carry out ...

sumbit-carry-out : (a b : Fin n → Bool) (c : Bool) →
                   val (sumbit a b c) + 2 ^ n * ⌜ carry-out a b c ⌝ ≡
                   val a + val b + ⌜ c ⌝
sumbit-carry-out {n} a b c =
  trans (cong₂ (λ v w → v + 2 ^ n * ⌜ w ⌝)
               (val-cong (λ i → sym (add-sumbit a b c i)))
               (sym (add-carry-out a b c)))
        (trans (sym (val-last (add a b c))) (add-correct a b c))

-- ... and the sum bits encode (a + b + c) mod 2^n.

sumbit-mod : (a b : Fin n → Bool) (c : Bool) →
             val (sumbit a b c) ≡
             _%_ (val a + val b + ⌜ c ⌝) (2 ^ n) {{m^n≢0 2 n}}
sumbit-mod {n} a b c =
  sym (trans (cong mod (sym (sumbit-carry-out a b c)))
      (trans (cong mod (cong (val (sumbit a b c) +_)
                             (*-comm (2 ^ n) ⌜ carry-out a b c ⌝)))
      (trans ([m+kn]%n≡m%n (val (sumbit a b c)) ⌜ carry-out a b c ⌝ (2 ^ n)
                           {{m^n≢0 2 n}})
             (m<n⇒m%n≡m {{m^n≢0 2 n}} (val< (sumbit a b c))))))
  where
  mod : ℕ → ℕ
  mod k = _%_ k (2 ^ n) {{m^n≢0 2 n}}
