------------------------------------------------------------------------
-- Presentations of groups
--
-- The ripple-carry adder over Clifford+T (Amy, QPL 2018, section 5.2)
--
-- PathSum.Adder.Ripple's netlist on the standard layout, each Toffoli
-- gate expanded into the seven-T circuit of PathSum.Toffoli
-- (PathSum.Reversible.Expand), is the Clifford+T circuit Adderᶜ m on
-- the 5n wires of n = m + 1 bit positions.  What it does, and what it
-- costs:
--
-- * It computes its netlist's Boolean function (Adderᶜ-computes): its
--   operator is the permutation matrix of run (adder (standard m)), up
--   to its normalisation, by PathSum.Classical's composition lemmas --
--   and that function is, on the blank inputs (carries and temporary
--   register 0), |x⟩|y⟩|z⟩ ↦ |x⟩|y⟩|z ⊕ (x + y)⟩ (PathSum.Adder.Ripple.
--   adder-computes).  So the circuit agrees, on the columns where its
--   ancillas are |0⟩, with every path-sum that computes that function
--   on blank inputs (Adderᶜ-spec, by PathSum.Ancillas.computes⇒≋[]₀*,
--   the ancillas being the carries and the temporary register listed
--   by scratch, whose clean inputs are the blank ones: clean⇔blank).
--   The specification path-sum itself -- the paper's, "generated by
--   implementing binary addition on symbolic vectors" -- is
--   PathSum.Adder.Spec's, and PathSum.Adder states the theorem against
--   it.
--
-- * Resources: 5n qubits; for n ≥ 2, 8(n − 1) path variables, 28(n − 1)
--   T gates, and 60(n − 1) + 11n − 8 gates in all, so 32(n − 1) +
--   11n − 8 Clifford gates (Adderᶜ-paths, Adderᶜ-tcount,
--   Adderᶜ-length).  At n = 8 and n = 16: 40 and 80 qubits, 56 and 120
--   path variables, 196 and 420 T gates -- table 2's Adder8 and
--   Adder16 exactly -- and 304 and 648 Clifford gates where the table
--   has 334 and 710: nine per Toffoli gate in the expansion of the
--   paper's tool (PathSum.Toffoli.Depth3) against eight here, and
--   11n − 6 CNOTs in its netlist (PathSum.Adder.CarryRipple) against
--   the 11n − 8 here (table-2-Adder8ᶜ,
--   table-2-Adder16ᶜ).  The circuits are never computed: the rows are
--   the general counts at n = 8 and n = 16.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat.Base using (ℕ; suc)

module PathSum.Adder.Circuit (M₀ : ℕ) where

open import Data.Bool.Base using (false)
open import Data.Fin.Base using (Fin; _↑ˡ_; _↑ʳ_; splitAt)
open import Data.List.Base using (length)
open import Data.Nat.Base using (_+_; _*_)
open import Data.Product.Base using (_×_; _,_)
open import Data.Sum.Base using (_⊎_; inj₁; inj₂; [_,_]′)
open import Function.Bundles using (Equivalence; _⇔_; mk⇔)
open import Relation.Binary.PropositionalEquality using
  (_≡_; refl; trans; cong; subst)

import Data.Fin.Properties as Fin

open import PathSum.Adder.Layout using
  (Wire; cin; xw; yw; sw; cw; zw; Layout; wire; width; standard)
open import PathSum.Adder.Ripple using
  (adder; Scratch; Blank; addition; adder-computes; adder-toffolis;
   adder-cnots)
open import PathSum.Ancillas M₀ using (Clean; _≋[_]₀*_; computes⇒≋[]₀*)
open import PathSum.Base using (PathSum)
open import PathSum.Classical M₀ using (_computes_)
open import PathSum.CRK.Path M₀ using (Circuit; ⟦_⟧; paths)
open import PathSum.Denotation M₀ using (Assign)
open import PathSum.Reversible using (run; toffolis; cnots)
open import PathSum.Reversible.Expand M₀ using
  (expand; expand-computes; paths-expand; tcount-expand; length-expand)
open import PathSum.Toffoli.Netlist M₀ using (tcount)

private
  variable
    m N k m′ : ℕ


------------------------------------------------------------------------
-- The circuit

-- The netlist on the standard layout, expanded into Clifford+T.

Adderᶜ : (m : ℕ) → Circuit (width m)
Adderᶜ m = expand (adder (standard m))

-- It computes the netlist's Boolean function.

Adderᶜ-computes : (m : ℕ) → ⟦ Adderᶜ m ⟧ computes run (adder (standard m))
Adderᶜ-computes m = expand-computes (adder (standard m))


------------------------------------------------------------------------
-- Its ancillas

-- The carries, then the temporary register.

scratch : Layout (Wire false m) N → Fin (m + suc m) → Fin N
scratch {m} L j =
  [ (λ j → wire L (cw j)) , (λ i → wire L (sw i)) ]′ (splitAt m j)

-- An input is clean on them exactly when it is blank.

clean⇔blank : (L : Layout (Wire false m) N) (x : Assign N) →
              Clean (scratch L) x ⇔ Blank L x
clean⇔blank {m} L x = mk⇔ blank clean
  where
  at : Fin m ⊎ Fin (suc m) → Fin _
  at = [ (λ j → wire L (cw j)) , (λ i → wire L (sw i)) ]′

  blank : Clean (scratch L) x → Blank L x
  blank cl (cw j) _ =
    subst (λ s → x (at s) ≡ false) (Fin.splitAt-↑ˡ m j (suc m))
          (cl (j ↑ˡ suc m))
  blank cl (sw i) _ =
    subst (λ s → x (at s) ≡ false) (Fin.splitAt-↑ʳ m (suc m) i)
          (cl (m ↑ʳ i))
  blank cl (cin ()) _
  blank cl (xw _)   ()
  blank cl (yw _)   ()
  blank cl (zw _)   ()

  clean : Blank L x → Clean (scratch L) x
  clean bl j = go (splitAt m j)
    where
    go : (s : Fin m ⊎ Fin (suc m)) → x (at s) ≡ false
    go (inj₁ j) = bl (cw j) _
    go (inj₂ i) = bl (sw i) _

-- So the circuit agrees, from every input whose ancillas are |0⟩, with
-- any path-sum computing a function that agrees with the addition on
-- blank inputs.

Adderᶜ-spec : (m : ℕ) (ζ : PathSum (width m) k m′)
              {G : Assign (width m) → Assign (width m)} → ζ computes G →
              (∀ x → Blank (standard m) x →
               ∀ w → addition (standard m) x w ≡ G x w) →
              ⟦ Adderᶜ m ⟧ ≋[ scratch (standard m) ]₀* ζ
Adderᶜ-spec m ζ cG h =
  computes⇒≋[]₀* ⟦ Adderᶜ m ⟧ ζ (scratch (standard m))
    (Adderᶜ-computes m) cG
    (λ x cl w →
       let bl = Equivalence.to (clean⇔blank (standard m) x) cl in
       trans (adder-computes (standard m) x bl w) (h x bl w))


------------------------------------------------------------------------
-- Resources

-- Two path variables and seven T gates per Toffoli gate; fifteen gates
-- per Toffoli gate and one per CNOT.

Adderᶜ-paths : (m : ℕ) → paths (Adderᶜ m) ≡ toffolis (adder (standard m)) * 2
Adderᶜ-paths m = paths-expand (adder (standard m))

Adderᶜ-tcount : (m : ℕ) →
                tcount (Adderᶜ m) ≡ toffolis (adder (standard m)) * 7
Adderᶜ-tcount m = tcount-expand (adder (standard m))

Adderᶜ-length : (m : ℕ) →
                length (Adderᶜ m) ≡
                toffolis (adder (standard m)) * 15 + cnots (adder (standard m))
Adderᶜ-length m = length-expand (adder (standard m))

-- Table 2's Adder8 and Adder16: qubits, path variables, T gates, and
-- all gates (so 500 − 196 = 304 and 1068 − 420 = 648 Clifford gates,
-- where the table has 334 and 710).

table-2-Adder8ᶜ :
  (width 7 ≡ 40) × (paths (Adderᶜ 7) ≡ 56) × (tcount (Adderᶜ 7) ≡ 196) ×
  (length (Adderᶜ 7) ≡ 500)
table-2-Adder8ᶜ =
  refl ,
  trans (Adderᶜ-paths 7) (cong (_* 2) (adder-toffolis (standard 7))) ,
  trans (Adderᶜ-tcount 7) (cong (_* 7) (adder-toffolis (standard 7))) ,
  trans (Adderᶜ-length 7)
        (cong₂′ (adder-toffolis (standard 7)) (adder-cnots (standard 7)))
  where
  cong₂′ : ∀ {t c t′ c′} → t ≡ t′ → c ≡ c′ → t * 15 + c ≡ t′ * 15 + c′
  cong₂′ refl refl = refl

table-2-Adder16ᶜ :
  (width 15 ≡ 80) × (paths (Adderᶜ 15) ≡ 120) ×
  (tcount (Adderᶜ 15) ≡ 420) × (length (Adderᶜ 15) ≡ 1068)
table-2-Adder16ᶜ =
  refl ,
  trans (Adderᶜ-paths 15) (cong (_* 2) (adder-toffolis (standard 15))) ,
  trans (Adderᶜ-tcount 15) (cong (_* 7) (adder-toffolis (standard 15))) ,
  trans (Adderᶜ-length 15)
        (cong₂′ (adder-toffolis (standard 15)) (adder-cnots (standard 15)))
  where
  cong₂′ : ∀ {t c t′ c′} → t ≡ t′ → c ≡ c′ → t * 15 + c ≡ t′ * 15 + c′
  cong₂′ refl refl = refl
