------------------------------------------------------------------------
-- Presentations of groups
--
-- The adder's specification, a path-sum built by symbolic addition
-- (Amy, QPL 2018, section 5.2)
--
-- Section 5.2 verifies its adder against a specification that "was
-- generated by implementing binary addition on symbolic vectors, and
-- could ostensibly be classically tested to verify its own
-- correctness".  Here that specification is built the same way, and
-- the testing is replaced by a proof, for every n at once.
--
-- Symbolic addition.  A symbolic vector is a vector of Boolean
-- expressions (PathSum.Polynomial.Boolean.BExp); addᵉ runs
-- PathSum.Adder.Binary's ripple-carry recursion on such vectors -- the
-- sum bit a_i ⊕ b_i ⊕ c, the carry maj(a_i, b_i, c) -- and builds an
-- expression for each of the n + 1 bits of a + b + c; sumbitᵉ builds
-- the first n alone, the bits of (a + b + c) mod 2^n.  The majority is
-- written as the paper's tool writes it (Feynman's adderOOPSpec, in
-- src/Feynman/Verification/SOP.hs), a c ⊕ b c ⊕ a b (majᵉ); the tool
-- writes the sum bit c ⊕ a ⊕ b, here a ⊕ (b ⊕ c) as in add.  The
-- values are the bits of the addition (⟦addᵉ⟧, ⟦sumbitᵉ⟧): evaluating
-- the symbolic sum at x is adding the values at x.  As a tree the
-- expression for the carry into position i repeats the carry into
-- position i − 1 twice, and its multilinear expansion has
-- exponentially many terms -- "the size of the bitwise expansion of
-- x + y" that the paper found limited its tool to 16 bits: every
-- Boolean polynomial computing the carry out of n bits has 2^n − 1
-- monomials, however it is written (PathSum.Adder.Expansion).  Nothing
-- here expands it: every fact is proved by induction on the positions,
-- through values.
--
-- The specification.  On the wires of an adder layout
-- (PathSum.Adder.Layout), with x and y the symbolic vectors of the
-- input registers' variables, adderˢ L is the classical path-sum
-- (PathSum.Classical: no path variables, phase 0) whose output on the
-- output wire z_k is the lift of z_k ⊕ (x + y)_k, (x + y)_k being
-- addᵉ's bit k with no carry in, and on every other wire that wire's
-- input.  By lemma 2.5 for Boolean expressions (fun-liftᵉ) it computes
-- the Boolean function |x⟩|y⟩|z⟩ ↦ |x⟩|y⟩|z ⊕ (x + y)⟩, every other
-- wire unchanged -- PathSum.Adder.Ripple's addition, on every input
-- (adderˢ-computes); from an input whose output register reads 0 its
-- output register ends holding x + y, of value val x + val y
-- (adderˢ-value).  That is the form of the paper's tool's
-- specification: its output register is symbolic, c_i ↦ c_i ⊕ carry_i
-- ⊕ a_i ⊕ b_i, rather than the |0⟩ of the paper's
-- |x⟩|y⟩|0⟩ ↦ |x⟩|y⟩|x + y⟩.  Its output register has n bits, the sum
-- modulo 2^n; this one has n + 1, the carry out included, like the
-- circuit of PathSum.Adder.Ripple.  The tool's ancillas are constant 0
-- inputs with constant 0 outputs; here they are wires like any other,
-- output unchanged, and PathSum.Adder states the theorems on the
-- inputs where they read 0, and with them read as the constant 0.
--
-- The paper's own form is here too: adder₀ˢ L outputs the lift of
-- (x + y)_k itself on z_k, and computes addition₀ L, the function
-- |x⟩|y⟩|z⟩ ↦ |x⟩|y⟩|x + y⟩ that overwrites the output register with
-- the bits of x + y (adder₀ˢ-computes, addition₀-out), whose value is
-- val x + val y (addition₀-value, adder₀ˢ-value).  On the inputs whose
-- output register reads 0 the two functions agree
-- (addition₀-addition).
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat.Base using (ℕ)

module PathSum.Adder.Spec (M₀ : ℕ) where

open import Data.Bool.Base using (Bool; true; false; _∧_; _xor_)
open import Data.Bool.Properties using (xor-identityʳ)
open import Data.Empty using (⊥-elim)
open import Data.Fin.Base using (Fin; zero; suc)
open import Data.Nat.Base using (zero; suc; _+_)
open import Data.Product.Base using (∃; _,_)
open import Relation.Binary.PropositionalEquality using
  (_≡_; refl; sym; trans; cong)
open import Relation.Nullary.Decidable using (Dec; yes; no)

open import PathSum.Adder.Binary using
  (val; val-cong; maj; add; add-correct₀; sumbit)
open import PathSum.Adder.Layout using
  (Wire; xw; yw; zw; Layout; wire; wire-inj)
open import PathSum.Adder.Ripple using
  (xbits; ybits; Work; out?; gain; addition; addition-out)
open import PathSum.Base using (PathSum)
open import PathSum.Classical M₀ using
  (_computes_; classical; classical-computes; computes-≗; fun; fun-liftᵉ;
   none)
open import PathSum.Denotation M₀ using (Assign)
open import PathSum.Polynomial using (Poly; x[_])
open import PathSum.Polynomial.Boolean using
  (BExp; ⟦_⟧ᵉ; var; lit; _⊕ᵉ_; _∧ᵉ_; liftᵉ)

private
  variable
    b : Bool
    n m N k : ℕ


------------------------------------------------------------------------
-- Symbolic addition

-- The majority as the paper's tool writes it (a c + b c + a b, c the
-- carry): a c ⊕ b c ⊕ a b.

majᵉ : BExp N k → BExp N k → BExp N k → BExp N k
majᵉ a b c = (a ∧ᵉ c) ⊕ᵉ (b ∧ᵉ c) ⊕ᵉ (a ∧ᵉ b)

private
  maj-xor₃ : ∀ a b c → maj a b c ≡ ((a ∧ c) xor (b ∧ c)) xor (a ∧ b)
  maj-xor₃ false false false = refl
  maj-xor₃ false false true  = refl
  maj-xor₃ false true  false = refl
  maj-xor₃ false true  true  = refl
  maj-xor₃ true  false false = refl
  maj-xor₃ true  false true  = refl
  maj-xor₃ true  true  false = refl
  maj-xor₃ true  true  true  = refl

⟦majᵉ⟧ : (a b c : BExp N k) (x : Fin N → Bool) (y : Fin k → Bool) →
         ⟦ majᵉ a b c ⟧ᵉ x y ≡ maj (⟦ a ⟧ᵉ x y) (⟦ b ⟧ᵉ x y) (⟦ c ⟧ᵉ x y)
⟦majᵉ⟧ a b c x y = sym (maj-xor₃ (⟦ a ⟧ᵉ x y) (⟦ b ⟧ᵉ x y) (⟦ c ⟧ᵉ x y))

-- PathSum.Adder.Binary's add on symbolic vectors: the n + 1 bits of
-- a + b + c as expressions, the sum bit a₀ ⊕ b₀ ⊕ c and then the
-- addition of the remaining bits with carry in maj(a₀, b₀, c).

addᵉ : (Fin n → BExp N k) → (Fin n → BExp N k) → BExp N k →
       Fin (suc n) → BExp N k
addᵉ {zero}  a b c zero    = c
addᵉ {suc n} a b c zero    = a zero ⊕ᵉ (b zero ⊕ᵉ c)
addᵉ {suc n} a b c (suc i) =
  addᵉ (λ j → a (suc j)) (λ j → b (suc j)) (majᵉ (a zero) (b zero) c) i

-- Evaluating the symbolic sum is adding the values.

⟦addᵉ⟧ : (a b : Fin n → BExp N k) (c : BExp N k)
         (x : Fin N → Bool) (y : Fin k → Bool) →
         ∀ i → ⟦ addᵉ a b c i ⟧ᵉ x y ≡
               add (λ j → ⟦ a j ⟧ᵉ x y) (λ j → ⟦ b j ⟧ᵉ x y) (⟦ c ⟧ᵉ x y) i
⟦addᵉ⟧ {zero}  a b c x y zero    = refl
⟦addᵉ⟧ {suc n} a b c x y zero    = refl
⟦addᵉ⟧ {suc n} a b c x y (suc i) =
  trans (⟦addᵉ⟧ (λ j → a (suc j)) (λ j → b (suc j))
                (majᵉ (a zero) (b zero) c) x y i)
        (cong (λ d → add (λ j → ⟦ a (suc j) ⟧ᵉ x y)
                         (λ j → ⟦ b (suc j) ⟧ᵉ x y) d i)
              (⟦majᵉ⟧ (a zero) (b zero) c x y))

-- The n sum bits alone, PathSum.Adder.Binary's sumbit on symbolic
-- vectors: the bits of (a + b + c) mod 2^n, which is what the tool's
-- own specification outputs.

sumbitᵉ : (Fin n → BExp N k) → (Fin n → BExp N k) → BExp N k →
          Fin n → BExp N k
sumbitᵉ a b c zero    = a zero ⊕ᵉ (b zero ⊕ᵉ c)
sumbitᵉ a b c (suc i) =
  sumbitᵉ (λ j → a (suc j)) (λ j → b (suc j)) (majᵉ (a zero) (b zero) c) i

⟦sumbitᵉ⟧ : (a b : Fin n → BExp N k) (c : BExp N k)
            (x : Fin N → Bool) (y : Fin k → Bool) →
            ∀ i → ⟦ sumbitᵉ a b c i ⟧ᵉ x y ≡
                  sumbit (λ j → ⟦ a j ⟧ᵉ x y) (λ j → ⟦ b j ⟧ᵉ x y)
                         (⟦ c ⟧ᵉ x y) i
⟦sumbitᵉ⟧ a b c x y zero    = refl
⟦sumbitᵉ⟧ a b c x y (suc i) =
  trans (⟦sumbitᵉ⟧ (λ j → a (suc j)) (λ j → b (suc j))
                   (majᵉ (a zero) (b zero) c) x y i)
        (cong (λ d → sumbit (λ j → ⟦ a (suc j) ⟧ᵉ x y)
                            (λ j → ⟦ b (suc j) ⟧ᵉ x y) d i)
              (⟦majᵉ⟧ (a zero) (b zero) c x y))


------------------------------------------------------------------------
-- The registers as symbolic vectors

-- The variables of the input registers.

xᵉ yᵉ : Layout (Wire b m) N → Fin (suc m) → BExp N 0
xᵉ L i = var x[ wire L (xw i) ]
yᵉ L i = var x[ wire L (yw i) ]

-- The n + 1 bits of x + y, symbolically: addᵉ with no carry in.

sumᵉ : Layout (Wire b m) N → Fin (suc (suc m)) → BExp N 0
sumᵉ L = addᵉ (xᵉ L) (yᵉ L) (lit false)

-- At the input x they read the bits of x + y.

⟦sumᵉ⟧ : (L : Layout (Wire b m) N) (x : Assign N) →
         ∀ k → ⟦ sumᵉ L k ⟧ᵉ x none ≡ add (xbits L x) (ybits L x) false k
⟦sumᵉ⟧ L x = ⟦addᵉ⟧ (xᵉ L) (yᵉ L) (lit false) x none


------------------------------------------------------------------------
-- The specification: the output register gains x + y

-- On z_k, z_k ⊕ (x + y)_k; elsewhere the wire's input.  Whether a wire
-- is an output wire is decided by PathSum.Adder.Ripple's out?.

adderᵉ : (L : Layout (Wire false m) N) (w : Fin N) →
         Dec (∃ λ k → wire L (zw k) ≡ w) → BExp N 0
adderᵉ L w (yes (k , _)) = var x[ w ] ⊕ᵉ sumᵉ L k
adderᵉ L w (no _)        = var x[ w ]

adderᵒ : Layout (Wire false m) N → Fin N → Poly N 0
adderᵒ L w = liftᵉ (adderᵉ L w (out? L w))

adderˢ : Layout (Wire false m) N → PathSum N 0 0
adderˢ L = classical (adderᵒ L)

-- It computes |x⟩|y⟩|z⟩ ↦ |x⟩|y⟩|z ⊕ (x + y)⟩, every other wire
-- unchanged, on every input.

fun-adderˢ : (L : Layout (Wire false m) N) (x : Assign N) →
             ∀ w → fun (adderᵒ L) x w ≡ addition L x w
fun-adderˢ L x w =
  trans (fun-liftᵉ (λ v → adderᵉ L v (out? L v)) x w) (go (out? L w))
  where
  go : (d : Dec (∃ λ k → wire L (zw k) ≡ w)) →
       ⟦ adderᵉ L w d ⟧ᵉ x none ≡ x w xor gain L x w d
  go (yes (k , _)) = cong (x w xor_) (⟦sumᵉ⟧ L x k)
  go (no _)        = sym (xor-identityʳ (x w))

adderˢ-computes : (L : Layout (Wire false m) N) →
                  adderˢ L computes addition L
adderˢ-computes L =
  computes-≗ (adderˢ L) (fun-adderˢ L) (classical-computes (adderᵒ L))

-- So it adds: from an input whose output register reads 0, the output
-- register ends holding x + y.

adderˢ-value : (L : Layout (Wire false m) N) (x : Assign N) →
               (∀ k → x (wire L (zw k)) ≡ false) →
               val (λ k → fun (adderᵒ L) x (wire L (zw k))) ≡
               val (xbits L x) + val (ybits L x)
adderˢ-value L x z0 =
  trans (val-cong (λ k →
           trans (fun-adderˢ L x (wire L (zw k)))
           (trans (addition-out L x k)
                  (cong (_xor add (xbits L x) (ybits L x) false k) (z0 k)))))
        (add-correct₀ (xbits L x) (ybits L x))


------------------------------------------------------------------------
-- The paper's form: the output register overwritten by x + y

-- |x⟩|y⟩|z⟩ ↦ |x⟩|y⟩|x + y⟩: on z_k the bit (x + y)_k, elsewhere the
-- wire's input.

module _ (L : Layout (Wire false m) N) where

  private
    zw-injective : ∀ {i j} → zw {false} {m} i ≡ zw j → i ≡ j
    zw-injective refl = refl

  over : (x : Assign N) (w : Fin N) → Dec (∃ λ k → wire L (zw k) ≡ w) →
         Bool
  over x w (yes (k , _)) = add (xbits L x) (ybits L x) false k
  over x w (no _)        = x w

  addition₀ : Assign N → Assign N
  addition₀ x w = over x w (out? L w)

  -- The output register reads the bits of x + y ...

  addition₀-out : (x : Assign N) →
                  ∀ k → addition₀ x (wire L (zw k)) ≡
                        add (xbits L x) (ybits L x) false k
  addition₀-out x k = go (out? L (wire L (zw k)))
    where
    go : (d : Dec (∃ λ k′ → wire L (zw k′) ≡ wire L (zw k))) →
         over x (wire L (zw k)) d ≡ add (xbits L x) (ybits L x) false k
    go (yes (k′ , e)) = cong (add (xbits L x) (ybits L x) false)
                             (zw-injective (wire-inj L (zw k′) (zw k) e))
    go (no ¬o)        = ⊥-elim (¬o (k , refl))

  -- ... whose value is val x + val y ...

  addition₀-value : (x : Assign N) →
                    val (λ k → addition₀ x (wire L (zw k))) ≡
                    val (xbits L x) + val (ybits L x)
  addition₀-value x =
    trans (val-cong (addition₀-out x)) (add-correct₀ (xbits L x) (ybits L x))

  -- ... and every other wire is unchanged.

  addition₀-work : (x : Assign N) (w : Fin N) → Work L w → addition₀ x w ≡ x w
  addition₀-work x w q = go (out? L w)
    where
    go : (d : Dec (∃ λ k → wire L (zw k) ≡ w)) → over x w d ≡ x w
    go (yes (k , e)) = ⊥-elim (q k e)
    go (no _)        = refl

  -- Where the output register reads 0, it is the addition.

  addition₀-addition : (x : Assign N) → (∀ k → x (wire L (zw k)) ≡ false) →
                       ∀ w → addition L x w ≡ addition₀ x w
  addition₀-addition x z0 w = go (out? L w)
    where
    go : (d : Dec (∃ λ k → wire L (zw k) ≡ w)) →
         x w xor gain L x w d ≡ over x w d
    go (yes (k , e)) = cong (_xor add (xbits L x) (ybits L x) false k)
                            (trans (cong x (sym e)) (z0 k))
    go (no _)        = xor-identityʳ (x w)

  -- The path-sum: the lift of (x + y)_k on z_k, the identity elsewhere.

  adder₀ᵉ : (w : Fin N) → Dec (∃ λ k → wire L (zw k) ≡ w) → BExp N 0
  adder₀ᵉ w (yes (k , _)) = sumᵉ L k
  adder₀ᵉ w (no _)        = var x[ w ]

  adder₀ᵒ : Fin N → Poly N 0
  adder₀ᵒ w = liftᵉ (adder₀ᵉ w (out? L w))

  adder₀ˢ : PathSum N 0 0
  adder₀ˢ = classical adder₀ᵒ

  fun-adder₀ˢ : (x : Assign N) → ∀ w → fun adder₀ᵒ x w ≡ addition₀ x w
  fun-adder₀ˢ x w =
    trans (fun-liftᵉ (λ v → adder₀ᵉ v (out? L v)) x w) (go (out? L w))
    where
    go : (d : Dec (∃ λ k → wire L (zw k) ≡ w)) →
         ⟦ adder₀ᵉ w d ⟧ᵉ x none ≡ over x w d
    go (yes (k , _)) = ⟦sumᵉ⟧ L x k
    go (no _)        = refl

  adder₀ˢ-computes : adder₀ˢ computes addition₀
  adder₀ˢ-computes =
    computes-≗ adder₀ˢ fun-adder₀ˢ (classical-computes adder₀ᵒ)

  -- It adds: on every input its output register holds x + y.

  adder₀ˢ-value : (x : Assign N) →
                  val (λ k → fun adder₀ᵒ x (wire L (zw k))) ≡
                  val (xbits L x) + val (ybits L x)
  adder₀ˢ-value x =
    trans (val-cong (λ k → fun-adder₀ˢ x (wire L (zw k)))) (addition₀-value x)
