------------------------------------------------------------------------
-- Presentations of groups
--
-- The notion "Γ presents G", in several strengths:
--
-- 1) Standard presentation (_IsPresentationOf_): _===_ presents the
--    group G iff G is isomorphic, as a group, to the free group on
--    the generators X quotiented by the monoid congruence generated by _===_.
--
-- 2) Monoid presentation (_IsMonoidPresentationOf_): the analogous
--    notion for monoids.
--
-- Soundness and adequacy of a semantics ⟦_⟧ : Syn → Sem (a setoid
-- embedding) are just the stdlib primitives Function.Congruent and
-- Function.Injective on the two setoids' equalities.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Presentation.Definitions where

open import Algebra.Bundles using (Group ; Monoid)
open import Algebra.Morphism.Structures
  using (module GroupMorphisms ; module MonoidMorphisms)
open import ForStdlib.Algebra.Morphism.Consequences
  using (isMonoidHomomorphism⇒isGroupHomomorphism)
open import Function.Definitions using (Surjective)
open import Level using (Level ; _⊔_)

open import Word.Base using (WRel ; Word)

open import Presentation.GroupLike
import Presentation.Properties as PP

private variable
  a ℓ : Level
  X : Set


------------------------------------------------------------------------
-- Group presentations

-- _===_ : WRel X is a presentation of G iff there is a group
-- isomorphism ⟦_⟧ : Word X / _≈_ ≅ G, where _≈_ is the congruence
-- closure of _===_.  The source group GL.•-ε-group is (Word X, _•_,
-- ε, _⁻¹) modulo _≈_, constructed in Presentation.GroupLike from a
-- grouplike structure gl on _===_ (which gives every generator a left
-- inverse in ≈_Γ).

infix 4 _IsPresentationOf_
record _IsPresentationOf_ (_===_ : WRel X) (G : Group a ℓ) : Set (a ⊔ ℓ) where
  field
    gl : Grouplike _===_
  module GL = Group-Lemmas _===_ gl
  open GroupMorphisms (Group.rawGroup GL.•-ε-group) (Group.rawGroup G)
  field
    ⟦_⟧ : Word X → Group.Carrier G
    iso : IsGroupIsomorphism ⟦_⟧

infix 4 _IsSubPresentationOf_
record _IsSubPresentationOf_ (_===_ : WRel X) (G : Group a ℓ) : Set (a ⊔ ℓ) where
  field
    gl : Grouplike _===_
  module GL = Group-Lemmas _===_ gl
  open GroupMorphisms (Group.rawGroup GL.•-ε-group) (Group.rawGroup G)
  field
    ⟦_⟧ : Word X → Group.Carrier G
    mono : IsGroupMonomorphism ⟦_⟧

infix 4 _IsMonoidPresentationOf_
record _IsMonoidPresentationOf_ (_===_ : WRel X) (M : Monoid a ℓ) : Set (a ⊔ ℓ) where
  open MonoidMorphisms (Monoid.rawMonoid (PP.•-ε-monoid _===_)) (Monoid.rawMonoid M)
  field
    ⟦_⟧ : Word X → Monoid.Carrier M
    iso : IsMonoidIsomorphism ⟦_⟧


infix 4 _IsSubMonoidPresentationOf_
record _IsSubMonoidPresentationOf_ (_===_ : WRel X) (M : Monoid a ℓ) : Set (a ⊔ ℓ) where
  open MonoidMorphisms (Monoid.rawMonoid (PP.•-ε-monoid _===_)) (Monoid.rawMonoid M)
  field
    ⟦_⟧ : Word X → Monoid.Carrier M
    mono : IsMonoidMonomorphism ⟦_⟧

------------------------------------------------------------------------
-- A surjective sub-presentation is a presentation
--
-- A monomorphism that is additionally surjective is an isomorphism, so
-- a sub-presentation whose interpretation ⟦_⟧ is onto is a full
-- presentation.  (These lemmas live here, not in Presentation.Properties,
-- because they mention the records above and Definitions already imports
-- Properties — the reverse import would be a cycle.)

module _ {_===_ : WRel X} {G : Group a ℓ}
         (sub : _===_ IsSubPresentationOf G) where
  open _IsSubPresentationOf_ sub

  isPresentationOf : Surjective (Group._≈_ GL.•-ε-group) (Group._≈_ G) ⟦_⟧ →
                     _===_ IsPresentationOf G
  isPresentationOf surjective = record
    { gl  = gl
    ; ⟦_⟧ = ⟦_⟧
    ; iso = record { isGroupMonomorphism = mono ; surjective = surjective }
    }

module _ {_===_ : WRel X} {M : Monoid a ℓ}
         (sub : _===_ IsSubMonoidPresentationOf M) where
  open _IsSubMonoidPresentationOf_ sub

  isMonoidPresentationOf : Surjective (Monoid._≈_ (PP.•-ε-monoid _===_)) (Monoid._≈_ M) ⟦_⟧ →
                           _===_ IsMonoidPresentationOf M
  isMonoidPresentationOf surjective = record
    { ⟦_⟧ = ⟦_⟧
    ; iso = record { isMonoidMonomorphism = mono ; surjective = surjective }
    }

------------------------------------------------------------------------
-- A grouplike monoid presentation is a group presentation
--
-- If _===_ presents (as a monoid) the underlying monoid of a group G
-- and is grouplike, then it presents G as a group.  Since •-ε-monoid is
-- the monoid of the word group •-ε-group, the monoid isomorphism is a
-- homomorphism between groups, hence a group isomorphism — a monoid
-- homomorphism between groups automatically preserves inverses.

module _ {_===_ : WRel X} {G : Group a ℓ}
         (mp : _===_ IsMonoidPresentationOf (Group.monoid G))
         (grouplike : Grouplike _===_) where
  open _IsMonoidPresentationOf_ mp
  open Group-Lemmas _===_ grouplike using (•-ε-group)
  open MonoidMorphisms (Monoid.rawMonoid (PP.•-ε-monoid _===_))
                       (Monoid.rawMonoid (Group.monoid G)) using (IsMonoidIsomorphism)
  open IsMonoidIsomorphism iso using (isMonoidHomomorphism ; injective ; surjective)

  monoidPresentation⇒presentation : _===_ IsPresentationOf G
  monoidPresentation⇒presentation = record
    { gl  = grouplike
    ; ⟦_⟧ = ⟦_⟧
    ; iso = record
        { isGroupMonomorphism = record
            { isGroupHomomorphism =
                isMonoidHomomorphism⇒isGroupHomomorphism •-ε-group G isMonoidHomomorphism
            ; injective = injective
            }
        ; surjective = surjective
        }
    }

------------------------------------------------------------------------
-- A grouplike sub-monoid presentation is a sub-presentation
--
-- The same upgrade for monomorphisms: a grouplike monoid monomorphism
-- into a group's monoid is a group monomorphism.

module _ {_===_ : WRel X} {G : Group a ℓ}
         (smp : _===_ IsSubMonoidPresentationOf (Group.monoid G))
         (grouplike : Grouplike _===_) where
  open _IsSubMonoidPresentationOf_ smp
  open Group-Lemmas _===_ grouplike using (•-ε-group)
  open MonoidMorphisms (Monoid.rawMonoid (PP.•-ε-monoid _===_))
                       (Monoid.rawMonoid (Group.monoid G)) using (IsMonoidMonomorphism)
  open IsMonoidMonomorphism mono using (isMonoidHomomorphism ; injective)

  subMonoidPresentation⇒subPresentation : _===_ IsSubPresentationOf G
  subMonoidPresentation⇒subPresentation = record
    { gl  = grouplike
    ; ⟦_⟧ = ⟦_⟧
    ; mono = record
        { isGroupHomomorphism =
            isMonoidHomomorphism⇒isGroupHomomorphism •-ε-group G isMonoidHomomorphism
        ; injective = injective
        }
    }

