------------------------------------------------------------------------
-- Presentations of groups
--
-- Independence of axioms
--
-- An axiom of a presentation is independent of the others when it is
-- not derivable from them: the congruence generated by the remaining
-- axioms does not identify its two sides.  The classical way to show
-- this is by a model, a monoid in which every remaining axiom holds
-- but the axiom in question fails.  Since the congruence generated by
-- a relation is the least one containing it, an interpretation that
-- respects each remaining axiom respects everything derivable from
-- them (soundness), and so cannot respect an axiom it separates.
--
-- Axioms are not a set here but a relation Γ : WRel X, so "the
-- remaining axioms" is a selection of its instances: a predicate P
-- on proofs of Γ w v, and Γ ∣ P the sub-relation of the selected
-- instances.  Derivability and independence are then stated for one
-- instance at a time, relative to a selection; a rule (a constructor
-- of Γ) is independent as soon as one of its instances is.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Presentation.Independence where

open import Algebra.Bundles using (Monoid)
open import Data.Product using (Σ ; _,_)
open import Data.Unit using (⊤ ; tt)
open import Level using (0ℓ)
open import Relation.Nullary.Negation using (¬_)

open import Word.Base using (WRel ; Word)
import Presentation.Base as PB
import Normalization.StarInterp as SI

private
  variable
    X : Set
    w v : Word X

------------------------------------------------------------------------
-- Selecting axiom instances

-- A selection of instances of Γ: a predicate on its proofs.
Select : WRel X → Set₁
Select Γ = ∀ {w v} → Γ w v → Set

-- The sub-relation of Γ consisting of the selected instances.
infixl 8 _∣_
_∣_ : (Γ : WRel X) → Select Γ → WRel X
(Γ ∣ P) w v = Σ (Γ w v) P

------------------------------------------------------------------------
-- Derivability and independence

module _ (Γ : WRel X) (P : Select Γ) where
  open PB (Γ ∣ P) using (_≈_ ; axiom)

  -- An instance is derivable from the selected axioms when the
  -- congruence they generate identifies its two sides.
  Derivable : Γ w v → Set
  Derivable {w = w} {v} _ = w ≈ v

  -- An instance is independent of the selected axioms when it is not.
  Independent : Γ w v → Set
  Independent a = ¬ Derivable a

  -- A selected instance is trivially derivable.
  derivable : (a : Γ w v) → P a → Derivable a
  derivable a p = axiom (a , p)

------------------------------------------------------------------------
-- Enlarging the selection preserves derivability
--
-- So in particular, what is derivable from a selection is derivable
-- from Γ: the selected axioms generate a sub-congruence of Γ's.

module _ (Γ : WRel X) {P Q : Select Γ}
         (P⊆Q : ∀ {w v} {a : Γ w v} → P a → Q a) where
  open PB (Γ ∣ P) using () renaming (_≈_ to _≈ₚ_)
  open PB (Γ ∣ Q) using () renaming (_≈_ to _≈ǫ_)

  ≈-mono : w ≈ₚ v → w ≈ǫ v
  ≈-mono PB.refl           = PB.refl
  ≈-mono (PB.sym e)        = PB.sym (≈-mono e)
  ≈-mono (PB.trans e e₁)   = PB.trans (≈-mono e) (≈-mono e₁)
  ≈-mono (PB.cong e e₁)    = PB.cong (≈-mono e) (≈-mono e₁)
  ≈-mono PB.assoc          = PB.assoc
  ≈-mono PB.left-unit      = PB.left-unit
  ≈-mono PB.right-unit     = PB.right-unit
  ≈-mono (PB.axiom (a , p)) = PB.axiom (a , P⊆Q p)

module _ (Γ : WRel X) (P : Select Γ) where
  open PB (Γ ∣ P) using () renaming (_≈_ to _≈ₚ_)
  open PB Γ using (_≈_)

  ≈-∣ : w ≈ₚ v → w ≈ v
  ≈-∣ PB.refl             = PB.refl
  ≈-∣ (PB.sym e)          = PB.sym (≈-∣ e)
  ≈-∣ (PB.trans e e₁)     = PB.trans (≈-∣ e) (≈-∣ e₁)
  ≈-∣ (PB.cong e e₁)      = PB.cong (≈-∣ e) (≈-∣ e₁)
  ≈-∣ PB.assoc            = PB.assoc
  ≈-∣ PB.left-unit        = PB.left-unit
  ≈-∣ PB.right-unit       = PB.right-unit
  ≈-∣ (PB.axiom (a , _))  = PB.axiom a

------------------------------------------------------------------------
-- The trivial selection
--
-- Selecting every instance changes nothing: Γ ∣ all generates Γ's
-- congruence, and ≈-all is the converse of ≈-∣ there.  It lets a
-- model of Γ itself (a Model at the selection all) be applied to a
-- derivation in Γ — the way to show an equation underivable in a
-- whole theory rather than one axiom independent of the others.

all : (Γ : WRel X) → Select Γ
all _ _ = ⊤

module _ (Γ : WRel X) where
  open PB Γ using (_≈_)
  open PB (Γ ∣ all Γ) using () renaming (_≈_ to _≈ₐ_)

  ≈-all : w ≈ v → w ≈ₐ v
  ≈-all PB.refl           = PB.refl
  ≈-all (PB.sym e)        = PB.sym (≈-all e)
  ≈-all (PB.trans e e₁)   = PB.trans (≈-all e) (≈-all e₁)
  ≈-all (PB.cong e e₁)    = PB.cong (≈-all e) (≈-all e₁)
  ≈-all PB.assoc          = PB.assoc
  ≈-all PB.left-unit      = PB.left-unit
  ≈-all PB.right-unit     = PB.right-unit
  ≈-all (PB.axiom a)      = PB.axiom (a , tt)

------------------------------------------------------------------------
-- Independence by a model
--
-- A model of the selected axioms is a monoid together with an
-- interpretation of the generators under which every selected
-- instance holds.  Soundness — the extension of the interpretation
-- to words respects the congruence the selected axioms generate — is
-- Normalization.StarInterp's fʷ-cong, and an instance the model
-- separates is therefore not derivable.

module Model (Γ : WRel X) (P : Select Γ) (mon : Monoid 0ℓ 0ℓ)
             (⟦_⟧₀ : X → Monoid.Carrier mon) where
  open Monoid mon using (_≈_)
  open SI.Extend (Γ ∣ P) mon ⟦_⟧₀ public using (⟦_⟧ ; homo ; ε-homo)

  module Sound (sound-ax : ∀ {w v} (a : Γ w v) → P a → ⟦ w ⟧ ≈ ⟦ v ⟧)
    where
    open SI.Extend.Cong (Γ ∣ P) mon ⟦_⟧₀ (λ (a , p) → sound-ax a p)
      public
      using () renaming (fʷ-cong to sound)

    independent : (a : Γ w v) → ¬ (⟦ w ⟧ ≈ ⟦ v ⟧) → Independent Γ P a
    independent a ⟦w⟧≉⟦v⟧ w≈v = ⟦w⟧≉⟦v⟧ (sound w≈v)
