------------------------------------------------------------------------
-- Presentations of groups
--
-- The main theorem of Bian and Selinger, "Generators and relations for
-- 2-qubit Clifford+T operators" (arXiv:2204.02217): the 2-qubit
-- Clifford+T group is presented by the generators ω, H₀, H₁, S₀, S₁,
-- T₀, T₁, CZ and the relations of Figure 1.
--
-- A Clifford+T word denotes a unitary 4 × 4 matrix over ℤ[1/√2,i]
-- through the translation f into Greylyn's generators (Generator), with
-- indices in Fin 4 (Greylyn-TwoLevel), and their matrices
-- (Clifford+T-2qubit-TwoLevel).  Then
--
-- * sound: related words have the same matrix, by Soundness and the
--   soundness of Greylyn's relations;
-- * complete: words with the same matrix are related, by the
--   completeness of Greylyn's relations (Clifford+T-2qubit-TwoLevel,
--   proved here from the exact synthesis algorithm) and Completeness
--   (the Reidemeister–Schreier theorem and the 46 equations);
--
-- so the relations present the subgroup of U₄(ℤ[1/√2,i]) the
-- generators generate: the 2-qubit Clifford+T group.
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

module Examples.Groups.Clifford+T-2qubit.Presentation where

open import Algebra.Bundles using (Group)
open import Algebra.Morphism.Structures using (module GroupMorphisms ; module MonoidMorphisms)
import Data.Nat.Properties as ℕP
open import Data.Product.Base using (_,_ ; proj₁)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)

open import ForStdlib.Algebra.Morphism.Consequences using (isMonoidHomomorphism⇒isGroupHomomorphism)
open import Word.Base
import Presentation.Base as PB
import Presentation.Properties as PP
open import Presentation.GroupLike using (Grouplike ; module Group-Lemmas)
open import Presentation.Definitions using (_IsSubPresentationOf_)
open import Presentation.Tactics.Judgement using (_⊢_ ; _===_)
open import Examples.Groups.Clifford+T-2qubit.Generator
  using (module Clifford+T ; module Greylyn ; f)
open import Examples.Groups.Clifford+T-2qubit.Soundness using (soundness)
open import Examples.Groups.Clifford+T-2qubit.Completeness using (completeness)
open import Examples.Groups.Clifford+T-2qubit.CliffordT-Lemmas using (module Clifford+T-Data)
open import Examples.Groups.Clifford+T-2qubit.Greylyn-TwoLevel using (to ; from ; to-cong ; from-cong ; from-to)
import Examples.Groups.Clifford+T-2qubit-TwoLevel.Syntactics as TL
open import Examples.Groups.Clifford+T-2qubit-TwoLevel.Semantics using (UMat ; U ; ⟦_⟧ᵐ ; ⟦•⟧ᵐ)
import Examples.Groups.Clifford+T-2qubit-TwoLevel.Presentation {4} as TLP
open import Examples.Groups.Clifford+T-2qubit-TwoLevel.Reduction {4} using (sound-act)
open import Examples.Groups.Clifford+T-2qubit-TwoLevel.MainLemma {4} using (relations-complete)

open Clifford+T using (Generator ; Rel)

private
  module P₄ = PB (TL._===_ {4})

  -- g* ∘ f* = (g* ∘ f)*.
  ʷ-ʷ : ∀ {X Y Z : Set} (f : X → Word Y) (g : Y → Word Z) (w : Word X) →
        (g ʷ) ((f ʷ) w) ≡ ((λ y → (g ʷ) (f y)) ʷ) w
  ʷ-ʷ f g [ x ]ʷ = Eq.refl
  ʷ-ʷ f g ε = Eq.refl
  ʷ-ʷ f g (w • w′) = Eq.cong₂ _•_ (ʷ-ʷ f g w) (ʷ-ʷ f g w′)

------------------------------------------------------------------------
-- The semantics

-- A Clifford+T generator as a word in the two-level generators.
tl : Generator → Word (TL.Gen 4)
tl x = (to ʷ) (f x)

⟦_⟧ : Word Generator → UMat 4
⟦ w ⟧ = TLP.⟦ (tl ʷ) w ⟧ᵘ

------------------------------------------------------------------------
-- Soundness and completeness

sound : ∀ {w v} → Rel ⊢ w === v → proj₁ ⟦ w ⟧ ≡ proj₁ ⟦ v ⟧
sound {w} {v} hyp =
  Eq.subst₂ (λ a b → ⟦ a ⟧ᵐ ≡ ⟦ b ⟧ᵐ) (ʷ-ʷ f to w) (ʷ-ʷ f to v)
    (sound-act (to-cong (soundness hyp)) _)

complete : ∀ {w v} → proj₁ ⟦ w ⟧ ≡ proj₁ ⟦ v ⟧ → Rel ⊢ w === v
complete {w} {v} eq = completeness (Eq.subst₂ (λ a b → Greylyn.Rel ⊢ a === b) (back w) (back v) (from-cong tl≈))
  where
  tl≈ : (tl ʷ) w P₄.≈ (tl ʷ) v
  tl≈ = relations-complete ℕP.≤-refl eq
  back : ∀ u → (from ʷ) ((tl ʷ) u) ≡ (f ʷ) u
  back u = Eq.trans (Eq.cong (from ʷ) (Eq.sym (ʷ-ʷ f to u))) (from-to ((f ʷ) u))

------------------------------------------------------------------------
-- The presentation

-- The relations present the subgroup of U₄(ℤ[1/√2,i]) generated by
-- the Clifford+T gates: ⟦_⟧ is a group monomorphism.
presentation : Rel IsSubPresentationOf U 4
presentation = record
  { gl = Clifford+T-Data.group-like
  ; ⟦_⟧ = ⟦_⟧
  ; mono = record
    { isGroupHomomorphism = isMonoidHomomorphism⇒isGroupHomomorphism GL.•-ε-group (U 4) isMonoidHomomorphism
    ; injective = complete
    }
  }
  where
  module GL = Group-Lemmas Rel Clifford+T-Data.group-like
  open MonoidMorphisms (Group.rawMonoid GL.•-ε-group) (Group.rawMonoid (U 4))
  isMonoidHomomorphism : IsMonoidHomomorphism ⟦_⟧
  isMonoidHomomorphism = record
    { isMagmaHomomorphism = record
      { isRelHomomorphism = record { cong = sound }
      ; homo = λ w v → ⟦•⟧ᵐ ((tl ʷ) w) ((tl ʷ) v)
      }
    ; ε-homo = Eq.refl
    }
