"""Generate Thesis/Rel1142.agda: the relations of Clement's Subcase 1.14.2.

On four indices a < b < c < d (here 0 < 1 < 2 < 3), with the pairings
PA = H[a,b] H[c,d], PB = H[a,c] H[b,d], PC = H[a,d] H[b,c], the squares
of 1.14.2 close by

  (27')  H[c,d] PB X[b,c] PB H[c,d] . H[a,b] . X[b,c] = H[a,b]
  (28')  H[c,d] PC X[b,d] PC H[c,d] . H[a,b] . X[b,c] = H[a,b]

(Clement's (27) and (28), in the form the squares use).  They follow
from (f1) PA PB = PB PA and from (G) PB PC = H[a,b] H[c,d] X[b,d] Z[d]
H[c,d] H[a,b] (Real-Clifford+CH-TwoLevel.Pairings), by chains of steps
found by search (deriv.search) or written out (manual.Chain), each
checked here and emitted as `derive` proofs for the generic Engine.

Usage: python gen1142.py [OUTDIR]   (default: the development's Thesis folder)
"""
import os, sys
from deriv import Deriver, search, verify, same
from manual import Chain
from emit import section, collect, letters_block, alist
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from tidy import tidy

OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'Thesis')

H = lambda a, b: ('H', a, b)
X = lambda a, b: ('X', a, b)
Z = lambda a: ('Z', a)

def pair_name(g):
    if g[0] == 'Z':
        return 'a1-%d' % g[1]
    if g[0] == 'X':
        return 'a2-%d%d' % (g[1], g[2])
    return 'a3-%d%d' % (g[1], g[2])

class D4(Deriver):
    def pair_name(self, g):
        return pair_name(g)

PA = [H(0, 1), H(2, 3)]
PB = [H(0, 2), H(1, 3)]
PC = [H(0, 3), H(1, 2)]
Lf1, Rf1 = PA + PB, PB + PA
LG, RG = PB + PC, [H(0, 1), H(2, 3), X(1, 3), Z(3), H(2, 3), H(0, 1)]
L27 = [H(2, 3)] + PB + [X(1, 2)] + PB + [H(2, 3), H(0, 1), X(1, 2)]
L28 = [H(2, 3)] + PC + [X(1, 3)] + PC + [H(2, 3), H(0, 1), X(1, 2)]
R2728 = [H(0, 1)]

D = D4(4)
D.add_eq('f1e', Lf1, Rf1)
D.add_eq('Ge', LG, RG)

def found(name, l, r, **kw):
    st = search(l, r, D.lib, **kw)
    assert st is not None, name
    verify(l, r, st, D.lib)
    D.derived.append((name, list(l), list(r), st))
    D.lib.add(name, l, r)

# X[b,d] PB PA = PB PA X[c,d], by (f1).
found('xpp', [X(1, 3)] + PB + PA, PB + PA + [X(2, 3)], maxdepth=8, maxlen=10, limit=8000000)
# PC = PB PA X[b,d] Z[d] PA, by (G).
found('pcG', PC, PB + RG, maxdepth=6, maxlen=12, limit=8000000)
# X[c,d] X[b,d] = X[b,d] X[b,c].
found('xx', [X(2, 3), X(1, 3)], [X(1, 3), X(1, 2)], maxdepth=4, maxlen=4, limit=100000)

# The core of (28'): X[b,d] PC PA = PC PA X[b,c].
c = Chain(D, [X(1, 3)] + PC + PA)
c.rw_at('pcG')
c.cancel()
c.rw_at('xpp')
c.rw_at('xx')
c.perm(PB + PA + [X(1, 3), Z(3), X(1, 2)])
c.insert([H(2, 3), H(0, 1)], 6)
c.rw('(sym⁼ pcG)', 0)
c.finish('core', PC + PA + [X(1, 2)])

# (27'), by search.
found('r27', L27, R2728, maxdepth=8, maxlen=12, limit=8000000)

# (28'): the core, then cancellations.
c = Chain(D, L28)
c.perm([H(2, 3)] + PC + [X(1, 3)] + PC + PA + [X(1, 2)])
c.rw('(sym⁼ core)', 4)
c.cancel()
c.finish('r28', R2728)

derivs = D.derived
used = collect(derivs)
for w in (Lf1, Rf1, LG, RG, L27, L28, R2728):
    used |= set(w)

out = []
w = out.append
w('------------------------------------------------------------------------')
w('-- Presentations of groups')
w('--')
for line in [
    "The relations of Clément's Subcase 1.14.2, on four indices",
    "0 < 1 < 2 < 3 in any set of relations Γ that derives the local ones.",
    "",
    "With PA = H[0,1] H[2,3], PB = H[0,2] H[1,3] and PC = H[0,3] H[1,2],",
    "the squares of 1.14.2 close by",
    "",
    "  r27 : H[2,3] PB X[1,2] PB H[2,3] • H[0,1] • X[1,2] = H[0,1]",
    "  r28 : H[2,3] PC X[1,3] PC H[2,3] • H[0,1] • X[1,2] = H[0,1]",
    "",
    "(his (27) and (28) in the form the squares use), from (f1)",
    "PA PB = PB PA and (G) PB PC = H[0,1] H[2,3] X[1,3] Z[3] H[2,3] H[0,1]",
    "(Real-Clifford+CH-TwoLevel.Pairings).  Generated by",
    "scripts/diagrams/gen1142.py.",
    ]:
    w('-- ' + line if line else '--')
w('------------------------------------------------------------------------')
w('')
w('{-# OPTIONS --without-K --safe #-}')
w('')
w('open import Word.Base using (WRel)')
w('import Presentation.Base as PB')
w('open import Examples.Groups.Real-Clifford+CH-TwoLevel.Syntactics using (Gen)')
w('open import Examples.Groups.Real-Clifford+CH-TwoLevel.LocalRelations using (_===ˡ_)')
w('')
w('module Examples.Groups.Real-Clifford+CH-TwoLevel-Clement.Thesis.Rel1142 where')
w('')
w('open import Data.Fin.Base using (Fin ; zero ; suc ; _<_)')
w('open import Data.List.Base using (List ; [] ; _∷_)')
w('open import Data.Nat.Base using (z≤n ; s≤s)')
w('open import Relation.Binary.PropositionalEquality using (refl)')
w('')
w('open import Examples.Groups.Real-Clifford+CH-TwoLevel.Syntactics using (H-gen ; X-gen ; Z-gen)')
w('import Presentation.Tactics.Words as TW')
w('')
w('------------------------------------------------------------------------')
w('-- Letters')
w('')
for line in letters_block(4, used):
    w(line)
w('')
w('------------------------------------------------------------------------')
w('-- The relations as letter lists (operator order)')
w('')
for nm, lst in [('Lf1', Lf1), ('Rf1', Rf1), ('LG', LG), ('RG', RG), ('L27', L27), ('L28', L28), ('R2728', R2728)]:
    w('%s : List (Gen 4)' % nm)
    w('%s = %s' % (nm, alist(lst)))
w('')
w('------------------------------------------------------------------------')
w('-- The derivations')
w('')
sec = section('From', [('f1e', 'Lf1', 'Rf1'), ('Ge', 'LG', 'RG')], derivs,
              [('r27', 'r27', 'L27', 'R2728'), ('r28', 'r28', 'L28', 'R2728')])
sec[0] = ('module From (Γ : WRel (Gen 4)) (loc : ∀ {u v} → u ===ˡ v → PB._≈_ Γ u v)\n'
          '  (f1eh : PB._≈_ Γ (TW.Associative.word-of-list Lf1) (TW.Associative.word-of-list Rf1))\n'
          '  (Geh : PB._≈_ Γ (TW.Associative.word-of-list LG) (TW.Associative.word-of-list RG)) where')
sec.insert(1, '')
sec.insert(2, '  open import Examples.Groups.Real-Clifford+CH-TwoLevel.Engine Γ loc')
sec.insert(3, '  open PB Γ using (_≈_)')
out += sec
helpers = ['f%d' % i for i in range(4)] + ['lt%d%d' % (i, j) for i in range(4) for j in range(i + 1, 4)]
path = os.path.join(OUT, 'Rel1142.agda')
open(path, 'w', encoding='utf-8').write(tidy('\n'.join(out) + '\n', helpers))
print('written Rel1142', [d[0] for d in derivs])
