------------------------------------------------------------------------
-- Presentations of groups
--
-- One-qubit completeness
--
-- On one wire the generators are ω, X and T and the relations are R₁,
-- R₇, R₁₀ and R₁₁: the presented group is ℤ₈ × D₁₆, the scalars times
-- the dihedral group of order 16 generated by T and X (the paper's
-- footnote 1).  Every one-wire circuit is equal to ω^k T^a X^e with
-- k, a ∈ ℤ₈ and e ∈ ℤ₂ — the paper's normal form at width one, a
-- scalar, a T-block and an X-block — and distinct such circuits
-- denote distinct operators.
--
-- The normal form is computed by an automaton reading the circuit
-- letter by letter (`run`); that it is a normal form for the
-- congruence is that the automaton respects the relations (run-cong,
-- decided) and that its states read back as the circuits reaching
-- them (run-sound).  Uniqueness is decided on the 128 stored
-- operators.  Completeness is then the library's by-normalization,
-- packaged by StarPresentation.MonoidSem as a sub-monoid presentation
-- of the operators.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.CNOT-Dihedral.OneQubit where

open import Algebra.Bundles using (Monoid)
open import Algebra.Morphism.Structures using (module MonoidMorphisms)
open import Data.Bool using (Bool ; true ; false ; not)
open import Data.Fin using (Fin ; toℕ)
open import Data.Product using (_×_ ; _,_ ; proj₁ ; proj₂)
open import Data.Vec using ([] ; _∷_)
open import Relation.Binary.Definitions using (DecidableEquality)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)
open import Relation.Nullary.Decidable
  using (Dec ; yes ; no ; toWitness ; map′ ; _→?_ ; _×?_)
open import Word.Base using (Word ; [_]ʷ ; ε ; _•_ ; _^_)

import Data.Bool.Properties as BoolP
import Data.Fin.Properties as FinP
import Data.Product.Properties as ProdP
import Relation.Binary.Reasoning.Setoid as SR

open import Notations
import Normalization.NormalForm.Propositional as NFBase
import Normalization.NormalForm.Setoid as SNF
import Normalization.NormalForm.Uniqueness.Propositional as NFU
open import Normalization.StarPresentation
open import Presentation.Definitions using (_IsSubMonoidPresentationOf_)
import Presentation.Base as PB
import Presentation.Properties as PP

open import Examples.Groups.CNOT-Dihedral.Semantics
open import Examples.Groups.CNOT-Dihedral.Syntactics
open import Examples.Groups.CNOT-Dihedral.Interpretation
open import Examples.Groups.CNOT-Dihedral.Soundness using (axiom-soundᴱ)

-- The one-wire theory.
Γ₁ : _
Γ₁ = 1 VRel,_===_

open PB Γ₁ using (_≈_ ; refl ; sym ; trans ; cong ; assoc ; left-unit ; right-unit ; axiom)
open PP Γ₁ using (word-setoid ; by-assoc)
open PP.Pattern-Assoc Γ₁ using (by-passoc ; □)

------------------------------------------------------------------------
-- Normal forms: ω^k T^a X^e

NF : Set
NF = ℤ₈ × ℤ₈ × Bool

Xᵉ : Bool → Circuit 1
Xᵉ true  = X
Xᵉ false = ε

[_] : NF → Circuit 1
[ k , a , e ] = ω ^ toℕ k • T ^ toℕ a • Xᵉ e

------------------------------------------------------------------------
-- The automaton
--
-- ω adds to the scalar; X toggles the X-block; T after (HZ)... after
-- ω^k T^a adds to the T-block, and after ω^k T^a X passes through X by
-- R₁₁, X T = ω T⁷ X, adding 1 to the scalar and 7 to the T-block.

step : Gen 1 → NF → NF
step ω-gen             (k , a , e)     = k + 1₈ , a , e
step (gate₀ ω-gate ↥)  (k , a , e)     = k + 1₈ , a , e
step X-gen             (k , a , e)     = k , a , not e
step T-gen             (k , a , false) = k , a + 1₈ , false
step T-gen             (k , a , true)  = k + 1₈ , a + ₇ , true

run : NF → Circuit 1 → NF
run s [ g ]ʷ  = step g s
run s ε       = s
run s (w • v) = run (run s w) v

nf : Circuit 1 → NF
nf = run (₀ , ₀ , false)

------------------------------------------------------------------------
-- The states read back as the circuits reaching them

private
  -- One more ω, and one more T, modulo their orders.
  ω-suc : ∀ k → ω ^ toℕ (k + 1₈) ≈ ω ^ toℕ k • ω
  ω-suc ₀ = sym left-unit
  ω-suc ₁ = refl
  ω-suc ₂ = by-assoc Eq.refl
  ω-suc ₃ = by-assoc Eq.refl
  ω-suc ₄ = by-assoc Eq.refl
  ω-suc ₅ = by-assoc Eq.refl
  ω-suc ₆ = by-assoc Eq.refl
  ω-suc ₇ = trans (sym (axiom (srel R₁₀))) (by-assoc Eq.refl)

  T-suc : ∀ a → T ^ toℕ (a + 1₈) ≈ T ^ toℕ a • T
  T-suc ₀ = sym left-unit
  T-suc ₁ = refl
  T-suc ₂ = by-assoc Eq.refl
  T-suc ₃ = by-assoc Eq.refl
  T-suc ₄ = by-assoc Eq.refl
  T-suc ₅ = by-assoc Eq.refl
  T-suc ₆ = by-assoc Eq.refl
  T-suc ₇ = trans (sym (axiom (srel R₇))) (by-assoc Eq.refl)

  -- Seven more T's: one fewer, by R₇ (T^a · T^7 = T^(a-1) · T^8).
  T-add7 : ∀ a → T ^ toℕ (a + ₇) ≈ T ^ toℕ a • T ^ 7
  T-add7 ₀ = sym left-unit
  T-add7 ₁ = sym (trans (by-assoc Eq.refl) (axiom (srel R₇)))
  T-add7 ₂ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))
  T-add7 ₃ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))
  T-add7 ₄ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))
  T-add7 ₅ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))
  T-add7 ₆ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))
  T-add7 ₇ = trans (sym right-unit) (trans (cong refl (sym (axiom (srel R₇)))) (by-assoc Eq.refl))

  -- X T = ω T⁷ X, from R₁₁ and R₁.
  XT : X • T ≈ ω • T ^ 7 • X
  XT = begin
    X • T                ≈⟨ sym right-unit ⟩
    (X • T) • ε          ≈⟨ cong refl (sym (axiom (srel R₁))) ⟩
    (X • T) • (X • X)    ≈⟨ by-passoc ((□ • □) • (□ • □)) ((□ • □ • □) • □) Eq.refl ⟩
    (X • T • X) • X      ≈⟨ cong (axiom (srel R₁₁)) refl ⟩
    (ω • T ^ 7) • X      ≈⟨ by-passoc ((□ • □) • □) (□ • □ • □) Eq.refl ⟩
    ω • T ^ 7 • X        ∎
    where open SR word-setoid

  step-ω : ∀ s → [ step ω-gen s ] ≈ [ s ] • ω
  step-ω (k , a , e) = begin
    ω ^ toℕ (k + 1₈) • T ^ toℕ a • Xᵉ e
      ≈⟨ cong (ω-suc k) refl ⟩
    (ω ^ toℕ k • ω) • T ^ toℕ a • Xᵉ e
      ≈⟨ by-passoc ((□ • □) • □ • □) (□ • □ • □ • □) Eq.refl ⟩
    ω ^ toℕ k • ω • T ^ toℕ a • Xᵉ e
      ≈⟨ cong refl (sym (comm-gate₀-w ω-gate (T ^ toℕ a • Xᵉ e))) ⟩
    ω ^ toℕ k • (T ^ toℕ a • Xᵉ e) • ω
      ≈⟨ by-passoc (□ • (□ • □) • □) ((□ • □ • □) • □) Eq.refl ⟩
    (ω ^ toℕ k • T ^ toℕ a • Xᵉ e) • ω ∎
    where open SR word-setoid

  step-X : ∀ s → [ step X-gen s ] ≈ [ s ] • X
  step-X (k , a , false) = sym (begin
    (ω ^ toℕ k • T ^ toℕ a • ε) • X
      ≈⟨ cong (cong refl right-unit) refl ⟩
    (ω ^ toℕ k • T ^ toℕ a) • X
      ≈⟨ by-passoc ((□ • □) • □) (□ • □ • □) Eq.refl ⟩
    ω ^ toℕ k • T ^ toℕ a • X ∎)
    where open SR word-setoid
  step-X (k , a , true)  = begin
    ω ^ toℕ k • T ^ toℕ a • ε
      ≈⟨ cong refl (cong refl (sym (axiom (srel R₁)))) ⟩
    ω ^ toℕ k • T ^ toℕ a • (X • X)
      ≈⟨ by-passoc (□ • □ • (□ • □)) ((□ • □ • □) • □) Eq.refl ⟩
    (ω ^ toℕ k • T ^ toℕ a • X) • X ∎
    where open SR word-setoid

  step-T : ∀ s → [ step T-gen s ] ≈ [ s ] • T
  step-T (k , a , false) = sym (begin
    (ω ^ toℕ k • T ^ toℕ a • ε) • T
      ≈⟨ cong (cong refl right-unit) refl ⟩
    (ω ^ toℕ k • T ^ toℕ a) • T
      ≈⟨ by-passoc ((□ • □) • □) (□ • □ • □) Eq.refl ⟩
    ω ^ toℕ k • T ^ toℕ a • T
      ≈⟨ cong refl (sym (T-suc a)) ⟩
    ω ^ toℕ k • T ^ toℕ (a + 1₈)
      ≈⟨ cong refl (sym right-unit) ⟩
    ω ^ toℕ k • T ^ toℕ (a + 1₈) • ε ∎)
    where open SR word-setoid
  step-T (k , a , true) = sym (begin
    (ω ^ toℕ k • T ^ toℕ a • X) • T
      ≈⟨ by-passoc ((□ • □ • □) • □) (□ • □ • (□ • □)) Eq.refl ⟩
    ω ^ toℕ k • T ^ toℕ a • (X • T)
      ≈⟨ cong refl (cong refl XT) ⟩
    ω ^ toℕ k • T ^ toℕ a • (ω • T ^ 7 • X)
      ≈⟨ by-passoc (□ • □ • (□ • □ • □)) (□ • (□ • □) • (□ • □)) Eq.refl ⟩
    ω ^ toℕ k • (T ^ toℕ a • ω) • (T ^ 7 • X)
      ≈⟨ cong refl (cong (comm-gate₀-w ω-gate (T ^ toℕ a)) refl) ⟩
    ω ^ toℕ k • (ω • T ^ toℕ a) • (T ^ 7 • X)
      ≈⟨ by-passoc (□ • (□ • □) • (□ • □)) ((□ • □) • (□ • □) • □) Eq.refl ⟩
    (ω ^ toℕ k • ω) • (T ^ toℕ a • T ^ 7) • X
      ≈⟨ cong (sym (ω-suc k)) (cong (sym (T-add7 a)) refl) ⟩
    ω ^ toℕ (k + 1₈) • T ^ toℕ (a + ₇) • X ∎)
    where open SR word-setoid

  step-sound : ∀ (g : Gen 1) s → [ step g s ] ≈ [ s ] • [ g ]ʷ
  step-sound ω-gen            s = step-ω s
  step-sound (gate₀ ω-gate ↥) s = trans (step-ω s) (cong refl (sym (axiom (ω↑=ω ω-gate))))
  step-sound X-gen            s = step-X s
  step-sound T-gen            s = step-T s

run-sound : ∀ s w → [ run s w ] ≈ [ s ] • w
run-sound s [ g ]ʷ  = step-sound g s
run-sound s ε       = sym right-unit
run-sound s (w • v) = begin
  [ run (run s w) v ]     ≈⟨ run-sound (run s w) v ⟩
  [ run s w ] • v         ≈⟨ cong (run-sound s w) refl ⟩
  ([ s ] • w) • v         ≈⟨ assoc ⟩
  [ s ] • (w • v)         ∎
  where open SR word-setoid

-- Every circuit equals its normal form.
nf-sound : ∀ w → [ nf w ] ≈ w
nf-sound w = trans (run-sound (₀ , ₀ , false) w)
  (trans (cong (by-assoc Eq.refl) refl) left-unit)

------------------------------------------------------------------------
-- The automaton respects the relations, decidably
--
-- Every relation at width one is between closed circuits, and the
-- automaton has 128 states: each is decided by running both sides
-- from every state.

private
  _≟NF_ : DecidableEquality NF
  _≟NF_ = ProdP.≡-dec FinP._≟_ (ProdP.≡-dec FinP._≟_ BoolP._≟_)

  ∀Bool : {P : Bool → Set} → (∀ b → Dec (P b)) → Dec (∀ b → P b)
  ∀Bool d = map′ (λ { (pt , pf) → λ { true → pt ; false → pf } })
                 (λ f → f true , f false) (d true ×? d false)

  ∀NF : {P : NF → Set} → (∀ s → Dec (P s)) → Dec (∀ s → P s)
  ∀NF d = map′ (λ f → λ { (k , a , e) → f k a e }) (λ f k a e → f (k , a , e))
               (FinP.all? (λ k → FinP.all? (λ a → ∀Bool (λ e → d (k , a , e)))))

  same-run : (w v : Circuit 1) → Dec (∀ s → run s w ≡ run s v)
  same-run w v = ∀NF (λ s → run s w ≟NF run s v)

  by-running : (w v : Circuit 1) {p : _} → ∀ s → run s w ≡ run s v
  by-running w v {p} = toWitness {a? = same-run w v} p

  axiom-run : ∀ {w v : Circuit 1} → 1 VRel, w === v → ∀ s → run s w ≡ run s v
  axiom-run (srel R₁)  = by-running (X • X) ε
  axiom-run (srel R₇)  = by-running (T ^ 8) ε
  axiom-run (srel R₁₀) = by-running (ω ^ 8) ε
  axiom-run (srel R₁₁) = by-running (X • T • X) (ω • T ^ 7)
  axiom-run (cong↑ (srel R₁₀))          = by-running ((ω ^ 8) ↑) (ε ↑)
  axiom-run (comm₁ X-gate ω-gen)            = λ s → Eq.refl
  axiom-run (comm₁ T-gate ω-gen)            = by-running (ω ↑ • T) (T • ω ↑)
  axiom-run (ω↑=ω ω-gate)                   = λ s → Eq.refl

run-cong : ∀ {w v} → w ≈ v → ∀ s → run s w ≡ run s v
run-cong refl          s = Eq.refl
run-cong (sym e)       s = Eq.sym (run-cong e s)
run-cong (trans e f)   s = Eq.trans (run-cong e s) (run-cong f s)
run-cong (cong {w} {w'} {v} {v'} e f) s =
  Eq.trans (run-cong f (run s w)) (Eq.cong (λ t → run t v') (run-cong e s))
run-cong assoc         s = Eq.refl
run-cong left-unit     s = Eq.refl
run-cong right-unit    s = Eq.refl
run-cong (axiom r)     s = axiom-run r s

------------------------------------------------------------------------
-- The normal form

open NFBase Γ₁ NF using (NormalForm)

nfp' : NormalForm
nfp' = record
  { rightInverse = record
      { to        = nf
      ; from      = [_]
      ; to-cong   = λ e → run-cong e (₀ , ₀ , false)
      ; from-cong = λ { Eq.refl → refl }
      ; inverseʳ  = λ { Eq.refl → nf-sound _ }
      }
  }

------------------------------------------------------------------------
-- Uniqueness: distinct normal forms denote distinct operators
--
-- Decided on the 128 stored operators, pairwise.

private
  Sameᴹ : NF → NF → Set
  Sameᴹ u v = ⟦ [ u ] ⟧M ≡ ⟦ [ v ] ⟧M

  distinct? : Dec (∀ u v → Sameᴹ u v → u ≡ v)
  distinct? = ∀NF (λ u → ∀NF (λ v → mat-dec {1} ⟦ [ u ] ⟧M ⟦ [ v ] ⟧M →? u ≟NF v))

  distinct : ∀ u v → Sameᴹ u v → u ≡ v
  distinct = toWitness {a? = distinct?} _

  -- A table is determined by its entries.
  tab-ext : ∀ k {A : Set} (t t' : Tab k A) → ((x : Bits k) → get t x ≡ get t' x) → t ≡ t'
  tab-ext ₀      t t' e = e []
  tab-ext (₁₊ k) t t' e =
    Eq.cong₂ _,_ (tab-ext k (proj₁ t) (proj₁ t') (λ x → e (false ∷ x)))
                 (tab-ext k (proj₂ t) (proj₂ t') (λ x → e (true ∷ x)))

  -- From operators to stored tables.
  to-table : ∀ u v → ⟦ [ u ] ⟧ ≐ ⟦ [ v ] ⟧ → Sameᴹ u v
  to-table u v e = tab-ext 1 ⟦ [ u ] ⟧M ⟦ [ v ] ⟧M (λ x →
    Eq.trans (Eq.sym (⟦⟧-ix [ u ] x)) (Eq.trans (e x) (⟦⟧-ix [ v ] x)))

unique : ∀ {u v} → ⟦ [ u ] ⟧ ≐ ⟦ [ v ] ⟧ → u ≡ v
unique {u} {v} e = distinct u v (to-table u v e)

------------------------------------------------------------------------
-- Completeness

private
  module MS = MonoidSem Γ₁ (Eq.setoid NF) (Op-monoid 1) ⟦_⟧ᵍ

  -- The library reads a circuit through the monoid (MS.⟦_⟧); that
  -- reading is ⟦_⟧ (Interpretation.⟦⟧ᴱ-def), so the witnesses transfer.
  unfp : NFU.UniqueNormalForm Γ₁ NF (Monoid.setoid (Op-monoid 1)) MS.⟦_⟧
           (SNF.NormalForm.inv-nf nfp')
  unfp = record { unique = λ {u} {v} e → unique (≐-⟦⟧ᴱ {w = [ u ]} {[ v ]} e) }

  module Sub = MS.GetSubPresentation axiom-soundᴱ nfp' unfp

-- On one wire, the relations present their image: a sub-monoid of the
-- operators.
subpresentation : Γ₁ IsSubMonoidPresentationOf Op-monoid 1
subpresentation = Sub.monoidSubPres

-- Two one-qubit circuits with the same operator are equal.
complete : ∀ {w v : Circuit 1} → ⟦ w ⟧ ≐ ⟦ v ⟧ → 1 ⊢ w ≈ v
complete {w} {v} e = MonoidMorphisms.IsMonoidMonomorphism.injective
  (_IsSubMonoidPresentationOf_.mono subpresentation) {w} {v} (⟦⟧ᴱ-≐ {w = w} {v} e)
