------------------------------------------------------------------------
-- Presentations of groups
--
-- Soundness of the CNOT-dihedral relations (Amy, Chen and Ross,
-- Proposition 3.7): the monoid congruence generated by Figure 1, the
-- laws of the symmetry and the structural rules preserves the operator
-- ⟦_⟧ : Circuit n → Op n.
--
-- Each relation is a computation on tables at the width it is drawn on
-- (Soundness.Relators), carried to every width by by-relator.  The
-- structural rules are pointwise: a gate on the bottom wires and an
-- operator shifted above them act on disjoint bits, and their phases
-- add in either order.  The congruence closure is the library's.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.CNOT-Dihedral.Soundness where

open import Data.Nat using (ℕ)
open import Data.Product using (_,_ ; proj₁ ; proj₂)
open import Data.Vec using (_∷_)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)
open import Word.Base using ([_]ʷ ; _•_)

import Presentation.Base as PB

open import Examples.Groups.CNOT-Dihedral.Semantics
open import Examples.Groups.CNOT-Dihedral.Syntactics
open import Examples.Groups.CNOT-Dihedral.Interpretation
open import Examples.Groups.CNOT-Dihedral.Soundness.Relators

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- The structural rules

private
  -- The operator of two letters (⟦_⟧ is abstract).
  gen² : (a b : Gen n) → ⟦ [ a ]ʷ • [ b ]ʷ ⟧ ≐ (⟦ a ⟧ᵍ ⊙ ⟦ b ⟧ᵍ)
  gen² a b = ≐-trans (⟦⟧-• [ a ]ʷ [ b ]ʷ) (⊙-cong (⟦⟧-gen a) (⟦⟧-gen b))

  -- Phases add in either order.
  swapᵖ : ∀ {A : Set} (y : A) (a b : ℤ₈) → (y , a + b) ≡ (y , b + a)
  swapᵖ y a b = Eq.cong (y ,_) (+-comm a b)

  -- The scalar and any operator commute.
  ω-comm : (G : Op n) → (G ⊙ ωₒ) ≐ (ωₒ ⊙ G)
  ω-comm G x = swapᵖ _ (proj₂ (G x)) 1₈

  -- A one-wire gate and an operator shifted past it.
  X-comm : (G : Op n) → (up G ⊙ Xₒ) ≐ (Xₒ ⊙ up G)
  X-comm G (a ∷ x) = swapᵖ _ (proj₂ (G x)) 0₈

  T-comm : (G : Op n) → (up G ⊙ Tₒ) ≐ (Tₒ ⊙ up G)
  T-comm G (a ∷ x) = swapᵖ _ (proj₂ (G x)) _

  -- A two-wire gate and an operator shifted twice.
  CNOT-comm : (G : Op n) → (up (up G) ⊙ CNOTₒ) ≐ (CNOTₒ ⊙ up (up G))
  CNOT-comm G (t ∷ c ∷ x) = swapᵖ _ (proj₂ (G x)) 0₈

  SWAP-comm : (G : Op n) → (up (up G) ⊙ SWAPₒ) ≐ (SWAPₒ ⊙ up (up G))
  SWAP-comm G (a ∷ b ∷ x) = swapᵖ _ (proj₂ (G x)) 0₈

  -- The scalar is the same on every wire.
  up-ω : up (ωₒ {n}) ≐ ωₒ
  up-ω (a ∷ x) = Eq.refl

-- The derivation moves up a wire, and so does its operator.
cong↑-sound : {w v : Circuit n} → ⟦ w ⟧ ≐ ⟦ v ⟧ → ⟦ w ↑ ⟧ ≐ ⟦ v ↑ ⟧
cong↑-sound {w = w} {v} e =
  ≐-trans (up-word w) (≐-trans (up-cong e) (≐-sym (up-word v)))

comm₁-sound : (h : Gate 1) (g : Gen n) →
              ⟦ [ g ↥ ]ʷ • [ gate₁ h ]ʷ ⟧ ≐ ⟦ [ gate₁ h ]ʷ • [ g ↥ ]ʷ ⟧
comm₁-sound X-gate g =
  ≐-trans (gen² (g ↥) X-gen) (≐-trans (X-comm ⟦ g ⟧ᵍ) (≐-sym (gen² X-gen (g ↥))))
comm₁-sound T-gate g =
  ≐-trans (gen² (g ↥) T-gen) (≐-trans (T-comm ⟦ g ⟧ᵍ) (≐-sym (gen² T-gen (g ↥))))

comm₂-sound : (h : Gate 2) (g : Gen n) →
              ⟦ [ g ↥ ↥ ]ʷ • [ gate₂ h ]ʷ ⟧ ≐ ⟦ [ gate₂ h ]ʷ • [ g ↥ ↥ ]ʷ ⟧
comm₂-sound CNOT-gate g =
  ≐-trans (gen² (g ↥ ↥) CNOT-gen)
    (≐-trans (CNOT-comm ⟦ g ⟧ᵍ) (≐-sym (gen² CNOT-gen (g ↥ ↥))))
comm₂-sound SWAP-gate g =
  ≐-trans (gen² (g ↥ ↥) SWAP-gen)
    (≐-trans (SWAP-comm ⟦ g ⟧ᵍ) (≐-sym (gen² SWAP-gen (g ↥ ↥))))

ω↑=ω-sound : ⟦ ω {n} ↑ ⟧ ≐ ⟦ ω ⟧
ω↑=ω-sound = ≐-trans (⟦⟧-gen (ω-gen ↥)) (≐-trans up-ω (≐-sym (⟦⟧-gen ω-gen)))

------------------------------------------------------------------------
-- Soundness of the axioms

axiom-sound : {w v : Circuit n} → n VRel, w === v → ⟦ w ⟧ ≐ ⟦ v ⟧
-- Figure 1, by computation at the width each relation is drawn on.
axiom-sound (srel R₁)  = by-relator r1ˡ  r1ʳ  p1ˡ  p1ʳ  m1
axiom-sound (srel R₂)  = by-relator r2ˡ  r2ʳ  p2ˡ  p2ʳ  m2
axiom-sound (srel R₃)  = by-relator r3ˡ  r3ʳ  p3ˡ  p3ʳ  m3
axiom-sound (srel R₄)  = by-relator r4ˡ  r4ʳ  p4ˡ  p4ʳ  m4
axiom-sound (srel R₅)  = by-relator r5ˡ  r5ʳ  p5ˡ  p5ʳ  m5
axiom-sound (srel R₆)  = by-relator r6ˡ  r6ʳ  p6ˡ  p6ʳ  m6
axiom-sound (srel R₇)  = by-relator r7ˡ  r7ʳ  p7ˡ  p1ʳ  m7
axiom-sound (srel R₈)  = by-relator r8ˡ  r8ʳ  p8ˡ  p8ʳ  m8
axiom-sound (srel R₉)  = by-relator r9ˡ  r9ʳ  p9ˡ  p9ʳ  m9
axiom-sound (srel R₁₀) = by-relator r10ˡ r10ʳ p10ˡ p10ʳ m10
axiom-sound (srel R₁₁) = by-relator r11ˡ r11ʳ p11ˡ p11ʳ m11
axiom-sound (srel R₁₂) = by-relator r12ˡ r12ʳ p12ˡ p12ʳ m12
axiom-sound (srel R₁₃) = by-relator r13ˡ r13ʳ p13ˡ p13ʳ m13
-- The laws of the symmetry.
axiom-sound (srel swap-order) = by-relator soˡ soʳ psoˡ p4ʳ  mso
axiom-sound (srel swap-braid) = by-relator sbˡ sbʳ psbˡ psbʳ msb
axiom-sound (srel swap-X)     = by-relator sXˡ sXʳ psXˡ psXʳ msX
axiom-sound (srel swap-T)     = by-relator sTˡ sTʳ psTˡ psTʳ msT
axiom-sound (srel swap-CNOT)  = by-relator sCˡ sCʳ psCˡ psCʳ msC
-- The structural rules.
axiom-sound (cong↑ r)          = cong↑-sound (axiom-sound r)
axiom-sound (comm₁ h g)        = comm₁-sound h g
axiom-sound (comm₂ h g)        = comm₂-sound h g
axiom-sound (ω↑=ω ω-gate)      = ω↑=ω-sound

------------------------------------------------------------------------
-- Soundness of the congruence (Proposition 3.7)
--
-- Closing under the monoid congruence is the library's job
-- (StarInterp.Extend.Cong), for the reading built from the monoid,
-- which is ⟦_⟧ (Interpretation.⟦⟧ᴱ-def).

axiom-soundᴱ : {w v : Circuit n} → n VRel, w === v →
               Ext.⟦_⟧ᴱ n w ≐ Ext.⟦_⟧ᴱ n v
axiom-soundᴱ {w = w} {v} r = ⟦⟧ᴱ-≐ {w = w} {v} (axiom-sound r)

soundᴱ : {w v : Circuit n} → n ⊢ w ≈ v → Ext.⟦_⟧ᴱ n w ≐ Ext.⟦_⟧ᴱ n v
soundᴱ {n} = Ext.Cong.fʷ-cong n axiom-soundᴱ

sound : {w v : Circuit n} → n ⊢ w ≈ v → ⟦ w ⟧ ≐ ⟦ v ⟧
sound {w = w} {v} e = ≐-⟦⟧ᴱ {w = w} {v} (soundᴱ e)
