------------------------------------------------------------------------
-- Presentations of groups
--
-- Uniqueness of the coset normal form of a circuit
--
-- Circuit.CosetNF builds a normal form for n-wire circuits as a tower
-- of cosets: a normal form at width 1+n is a normal form at width n,
-- lifted by one wire, followed by a coset representative for the new
-- bottom wire.  This module proves such a normal form is determined by
-- its denotation, which is the UniqueNormalForm half of a completeness
-- proof (see Normalization.NormalForm.Uniqueness).
--
-- The semantics acts on the LEFT on vectors of per-wire states, so
-- that in the denotation of inv-nf (u , c) the coset factor is the one
-- applied to the input and the lifted prefix acts afterwards, on the
-- tail of the result.  Unfolding that all the way down gives the
-- blockwise act-nf below, and the argument then runs as:
--
--   * the coset is read off the HEAD of the result, on every input
--     (c-inj), the lifted prefix being unable to disturb a head;
--   * the prefix is then compared on every tail, which c-surj supplies
--     by pulling an arbitrary tail back through the coset action, and
--     the induction hypothesis applies one wire down.
--
-- Recovering the coset from every input, rather than from states of
-- some restricted shape, is what makes this usable when a coset
-- carries per-wire data: those need probes at every wire to pin down.
--
-- The semantics enters only through its interface, never through any
-- particular gate set: a monoid homomorphism from circuits into a
-- family of monoids, a left action of those monoids on vectors of
-- per-wire states, and the fact that lifted circuits fix the head.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Algebra.Bundles using (Monoid)
open import Algebra.Morphism.Structures using (module MonoidMorphisms)
open import Data.Nat using (ℕ)
open import Data.Product using (Σ-syntax ; _,_ ; proj₁ ; proj₂)
open import Data.Vec.Base as Vec using (Vec ; _∷_ ; head ; tail)
import Data.Vec.Relation.Binary.Equality.Setoid as VecEq
open import ForStdlib.Algebra.IndexedAction using (IndexedLeftAction)
open import Level using (0ℓ)
open import Relation.Binary using (Rel ; Setoid)
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Notations
import Circuit.Base as CB
import Presentation.Properties as PP

module Circuit.Uniqueness
  (C : ℕ → Set)
  (I : ∀ {n} → C n)
  (Gate : ℕ → Set)
  (let open CB Gate)
  ([_]ᶜ : ∀ {n} → C n → Circuit (₁₊ n))
  -- The semantics of an n-wire circuit is an element of the monoid
  -- Sem n.  Writing the width implicitly, _≈ₛ_ is equality there.
  {c d} (Sem : ℕ → Monoid c d)
  (let _≈ₛ_ : ∀ {n} → Rel (Monoid.Carrier (Sem n)) d
       _≈ₛ_ {n} = Monoid._≈_ (Sem n))
  -- The relation presenting the circuits, extended with the
  -- structural rules by Lift-Relation.
  (_SRel,_===_ : (n : ℕ) → CRel n)
  (let open Lift-Relation _SRel,_===_)
  -- The circuits of width n, modulo the congruence generated by the
  -- lifted relation, form the word monoid at width n ...
  (let word-monoid : ℕ → Monoid 0ℓ 0ℓ
       word-monoid n = PP.•-ε-monoid (n VRel,_===_))
  (⟦_⟧ : ∀ {n} → Circuit n → Monoid.Carrier (Sem n))
  -- ... and the semantics is a monoid homomorphism out of it.  Its
  -- ε-homo and homo fields say ⟦_⟧ takes ε and _•_ to the unit and
  -- product of Sem n; its isRelHomomorphism field is exactly
  -- soundness, recovered as sem-sound below.
  (mhomo : ∀ n → MonoidMorphisms.IsMonoidHomomorphism
                   (Monoid.rawMonoid (word-monoid n))
                   (Monoid.rawMonoid (Sem n))
                   (⟦_⟧ {n}))
  -- Sem acts on the LEFT on vectors of single-wire states over the
  -- object setoid Ob, one object per wire.  ▷-compose says acting by
  -- a product is acting by its right factor first, which combined
  -- with mhomo's homo puts the coset factor of a normal form next to
  -- the input.
  {s e} (Ob : Setoid s e)
  (act : IndexedLeftAction (λ n → Monoid.rawMonoid (Sem n)) Ob)
  (let open IndexedLeftAction act using (_▷_ ; ▷-cong ; ▷-identity
                                        ; ▷-compose))
  (let open VecEq Ob using (_≋_))
  -- A lifted circuit leaves the head alone and acts on the tail
  -- exactly as the unlifted circuit does.  Nothing is assumed about
  -- which states it fixes: the head is all this argument needs.
  (head-fix : ∀ {n} (h : Setoid.Carrier Ob)
              (t : Vec (Setoid.Carrier Ob) n) (w : Circuit n) →
              (⟦ w ↑ ⟧ ▷ (h ∷ t)) ≋ (h ∷ (⟦ w ⟧ ▷ t)))
  -- A coset representative is determined by the head of its action,
  -- on every state ...
  (c-inj : ∀ {n} {c1 c2 : C n} →
           (∀ (ps : Vec (Setoid.Carrier Ob) (₁₊ n)) →
              Setoid._≈_ Ob (head (⟦ [ c1 ]ᶜ ⟧ ▷ ps))
                            (head (⟦ [ c2 ]ᶜ ⟧ ▷ ps))) →
           c1 ≡ c2)
  -- ... and every tail arises from its action, which is what lets the
  -- inner normal forms be compared on all of Vec Ob n.
  (c-surj : ∀ {n} (c : C n) (qs : Vec (Setoid.Carrier Ob) n) →
            Σ[ ps ∈ Vec (Setoid.Carrier Ob) (₁₊ n) ]
              (tail (⟦ [ c ]ᶜ ⟧ ▷ ps)) ≋ qs)
  where

open import Data.Product.Relation.Binary.Pointwise.NonDependent
  using (≡×≡⇒≡)
open import Relation.Binary.PropositionalEquality as Eq using (refl)

import Presentation.Base as PB
open import Circuit.CosetNF C I Gate [_]ᶜ
import Normalization.NormalForm.Uniqueness.Propositional as Uniqueness

open VecEq Ob using (≋-refl ; ≋-sym ; ≋-trans)
  renaming (_∷_ to _∷≋_)   -- the pointwise cons, not Vec's

private
  |Ob| : Set s
  |Ob| = Setoid.Carrier Ob

  -- Equality of circuits: the congruence generated by the presented
  -- relation, with the width implicit.
  infix 4 _≈ʷ_
  _≈ʷ_ : ∀ {n} → Rel (Circuit n) 0ℓ
  _≈ʷ_ {n} = PB._≈_ (n VRel,_===_)

  -- The homomorphism laws at width n: homo, ε-homo, ⟦⟧-cong.
  module Homo (n : ℕ) = MonoidMorphisms.IsMonoidHomomorphism (mhomo n)

  -- Vectors of positive length split, which act-nf's recursion needs.
  -- The vectors are matched as conses before the pointwise proof, or
  -- the split gets stuck on the stuck action term.
  vec-eta : ∀ {n} (xs : Vec |Ob| (₁₊ n)) → xs ≋ (head xs ∷ tail xs)
  vec-eta (x ∷ xs) = ≋-refl

  head-of : ∀ {n} {xs ys : Vec |Ob| (₁₊ n)} →
            xs ≋ ys → Setoid._≈_ Ob (head xs) (head ys)
  head-of {xs = _ ∷ _} {_ ∷ _} (e ∷≋ _) = e

  tail-of : ∀ {n} {xs ys : Vec |Ob| (₁₊ n)} →
            xs ≋ ys → tail xs ≋ tail ys
  tail-of {xs = _ ∷ _} {_ ∷ _} (_ ∷≋ es) = es


------------------------------------------------------------------------
-- Soundness

-- Soundness is the relational half of mhomo: the semantics maps
-- ≈-equal circuits to ≈-equal denotations.

sem-sound : ∀ {n} {w v : Circuit n} → w ≈ʷ v → ⟦ w ⟧ ≈ₛ ⟦ v ⟧
sem-sound {n} = Homo.⟦⟧-cong n


------------------------------------------------------------------------
-- The blockwise action of a normal form

-- Peeling one coset at a time: the coset acts on the input, its head
-- is the wire this level decides, and the rest of the normal form
-- carries on down the tail.

act-nf : ∀ {n} → NF n → Vec |Ob| n → Vec |Ob| n
act-nf {₀}    _       xs = xs
act-nf {₁₊ n} (u , c) ps = head rs ∷ act-nf u (tail rs)
  where rs = ⟦ [ c ]ᶜ ⟧ ▷ ps

act-nf-cong : ∀ {n} (u : NF n) {xs ys : Vec |Ob| n} →
              xs ≋ ys → act-nf u xs ≋ act-nf u ys
act-nf-cong {₀}    _       xs≋ys = xs≋ys
act-nf-cong {₁₊ n} (u , c) xs≋ys =
  head-of rs≋ ∷≋ act-nf-cong u (tail-of rs≋)
  where rs≋ = ▷-cong (Monoid.refl (Sem (₁₊ n))) xs≋ys

-- act-nf is the action of the normal form's denotation.  The lifted
-- prefix is peeled off by ▷-compose and then passes through the head
-- by head-fix.
lemma-act-nf : ∀ {n} (u : NF n) (ps : Vec |Ob| n) →
               act-nf u ps ≋ (⟦ inv-nf u ⟧ ▷ ps)
lemma-act-nf {₀}    _       ps = ≋-sym (≋-trans
  (▷-cong (Homo.ε-homo ₀) ≋-refl) (▷-identity ps))
lemma-act-nf {₁₊ n} (u , c) ps = ≋-trans
  (Setoid.refl Ob ∷≋ lemma-act-nf u (tail rs))
  (≋-trans (≋-sym (head-fix (head rs) (tail rs) (inv-nf u)))
    (≋-trans (▷-cong (Monoid.refl (Sem (₁₊ n))) (≋-sym (vec-eta rs)))
      (≋-trans (≋-sym (▷-compose ⟦ inv-nf u ↑ ⟧ ⟦ [ c ]ᶜ ⟧ ps))
               (▷-cong (Monoid.sym (Sem (₁₊ n))
                          (Homo.homo (₁₊ n) (inv-nf u ↑) [ c ]ᶜ))
                       ≋-refl))))
  where rs = ⟦ [ c ]ᶜ ⟧ ▷ ps


------------------------------------------------------------------------
-- Uniqueness of normal forms

-- Normal forms with the same blockwise action are equal.  At width
-- 1+n the coset is read off the heads by c-inj; the inner normal
-- forms are then compared at an arbitrary tail, which c-surj produces
-- as the tail of the coset's action on some state.

nf-injective : ∀ {n} (u v : NF n) →
               (∀ ps → act-nf u ps ≋ act-nf v ps) → u ≡ v
nf-injective {₀}    _        _        _   = refl
nf-injective {₁₊ n} (u₁ , c₁) (u₂ , c₂) hyp =
  ≡×≡⇒≡ (nf-injective u₁ u₂ tails , c≡c')
  where
  c≡c' : c₁ ≡ c₂
  c≡c' = c-inj (λ ps → head-of (hyp ps))

  -- With the cosets equal, the two sides run the inner normal forms
  -- on the very same tail, and every tail is such a tail.
  tails : ∀ qs → act-nf u₁ qs ≋ act-nf u₂ qs
  tails qs = ≋-trans (act-nf-cong u₁ (≋-sym tail-eq))
               (≋-trans (tail-of (hyp ps))
                        (act-nf-cong u₂ (≋-trans same tail-eq)))
    where
    cs    = c-surj c₁ qs
    ps    = proj₁ cs
    tail-eq = proj₂ cs

    same : tail (⟦ [ c₂ ]ᶜ ⟧ ▷ ps) ≋ tail (⟦ [ c₁ ]ᶜ ⟧ ▷ ps)
    same rewrite c≡c' = ≋-refl

-- Hence normal forms with equal denotations are equal.
⟦inv-nf⟧-injective : ∀ n {u v : NF n} →
                     ⟦ inv-nf {n} u ⟧ ≈ₛ ⟦ inv-nf {n} v ⟧ → u ≡ v
⟦inv-nf⟧-injective n {u} {v} eq = nf-injective u v claim
  where
  claim : ∀ ps → act-nf u ps ≋ act-nf v ps
  claim ps = ≋-trans (lemma-act-nf u ps)
               (≋-trans (▷-cong eq ≋-refl) (≋-sym (lemma-act-nf v ps)))

-- Packaged as the normal-form uniqueness witness.

unique-nf : ∀ n →
            let open Uniqueness (n VRel,_===_) (NF n)
                                (Monoid.setoid (Sem n)) (⟦_⟧ {n})
            in UniqueNormalForm (inv-nf {n})
unique-nf n = record
  { unique = ⟦inv-nf⟧-injective n
  }
