{-# OPTIONS --cubical-compatible --safe #-}

open import Word.Base using (WRel ; Word ; ε ; _•_)
open import Level using (0ℓ ; _⊔_)
open import Relation.Binary using (Setoid)
open import Data.Nat using (ℕ)
open import Data.Vec.Base using (Vec ; _∷_)
import Data.Vec.Relation.Binary.Equality.Setoid as VecEq
open import Algebra.Bundles using (Monoid)
open import Algebra.Bundles.Raw using (RawMonoid)
open import Algebra.Morphism.Structures using (module MonoidMorphisms)
import Circuit.Base as CB
import Presentation.Base as PB
import Presentation.Properties as PP
open import Notations
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)
import Relation.Binary.Reasoning.Setoid as SR

open import ForStdlib.Algebra.IndexedAction using (IndexedRightAction)

module Circuit.Uniqueness
  (C : ℕ -> Set)
  (I : ∀ {n} -> C n)
  (Gate : ℕ -> Set)
  (let open CB Gate)
  ([_]ᶜ : ∀ {n} -> C n -> Circuit (₁₊ n))
  {c d} (Sem : ℕ -> Monoid c d)
  (_SRel,_===_ : (n : ℕ) → CRel n)
  (let open Lift-Relation _SRel,_===_)
  -- The circuits of width n, modulo the congruence generated by the
  -- lifted relation, form the word monoid at width n ...
  (let word-monoid : ℕ -> Monoid 0ℓ 0ℓ
       word-monoid n = PP.•-ε-monoid (n VRel,_===_))
  (⟦_⟧ : ∀ {n} -> Circuit n → Monoid.Carrier (Sem n))
  -- ... and the semantics is an indexed monoid homomorphism from it
  -- into Sem n.  Its ε-homo and homo fields say ⟦_⟧ takes ε and _•_
  -- to the unit and product of Sem n; its isRelHomomorphism field is
  -- exactly soundness, recovered as sem-sound below.
  (mhomo : ∀ n -> MonoidMorphisms.IsMonoidHomomorphism
                    (Monoid.rawMonoid (word-monoid n))
                    (Monoid.rawMonoid (Sem n))
                    (⟦_⟧ {n}))
  -- Sem acts on the right on vectors of single-wire states over the
  -- object setoid Ob, one object per wire
  -- (ForStdlib.Algebra.IndexedAction): ◁-compose says acting by a
  -- product is acting by its factors in turn, which combined with
  -- mhomo's homo turns composition of circuits into composition of
  -- actions.
  {s e} (Ob : Setoid s e)
  (act : IndexedRightAction (\ n -> Monoid.rawMonoid (Sem n)) Ob)
  (let open IndexedRightAction act using (_◁_ ; ◁-cong ; ◁-compose))
  (let open VecEq Ob using (_≋_))
  -- A lifted circuit leaves the head alone and acts on the tail
  -- exactly as the unlifted circuit does ...
  (head-fix : ∀ {n} (h : Setoid.Carrier Ob) (t : Vec (Setoid.Carrier Ob) n)
              (w : Circuit n) -> ((h ∷ t) ◁ ⟦ w ↑ ⟧) ≋ (h ∷ (t ◁ ⟦ w ⟧)))
  -- ... so a coset representative must be determined by how it acts
  -- on the head, uniformly in the tail.  The two states compared
  -- below share a head but not a tail: the lifted prefixes of two
  -- normal forms transport a common tail by different semantic
  -- elements g1 and g2 (that is all head-fix leaves of them), so the
  -- hypothesis is quantified over that pair of transports.
  (c-inj : ∀ {n} {c1 c2 : C n} (g1 g2 : Monoid.Carrier (Sem n)) ->
    (∀ (h : Setoid.Carrier Ob) (t : Vec (Setoid.Carrier Ob) n) ->
       ((h ∷ (t ◁ g1)) ◁ ⟦ [ c1 ]ᶜ ⟧) ≋ ((h ∷ (t ◁ g2)) ◁ ⟦ [ c2 ]ᶜ ⟧)) ->
    c1 ≡ c2)
  where

open import Circuit.CosetNF C I Gate [_]ᶜ

open import Data.Product using (_,_ ; proj₁ ; proj₂)
open import Function using (_∘_)
open import Function.Bundles using (Injection ; Bijection ; RightInverse ; _⟶ₛ_)
open import Relation.Binary.Definitions using (Decidable)
open import Relation.Nullary.Decidable using (via-injection)
open import Word.Base

open VecEq Ob using (≋-setoid ; ≋-refl ; ≋-sym)

-- The homomorphism laws at width n, unpacked: homo, ε-homo, ⟦⟧-cong.
module ⟦⟧-homo (n : ℕ) = MonoidMorphisms.IsMonoidHomomorphism (mhomo n)

-- Soundness is the relational half of mhomo: the semantics maps
-- ≈-equal circuits to ≈-equal denotations.
sem-sound : ∀ {n} ->
  let open PB (n VRel,_===_) renaming (_≈_ to _≈ₐ_) in
  let open Monoid (Sem n) renaming (_≈_ to _≈ₛ_) in
  ∀ {w v} -> w ≈ₐ v -> ⟦ w ⟧ ≈ₛ ⟦ v ⟧
sem-sound {n} = ⟦⟧-homo.⟦⟧-cong n

-- The top coset of a normal form is determined by the semantics: act
-- with both sides of eq on an arbitrary state h ∷ t.  The lifted
-- prefixes pass through the head (head-fix), leaving states that
-- still share the head h and differ only in how the prefixes
-- transported the tail; c-inj separates the two coset
-- representatives from that.  No case split on the width, and no
-- state needs to be produced: h and t stay universally quantified.
coset-unique : ∀ n (l l' : NF n) (r r' : C n)
  → let open Monoid (Sem (₁₊ n)) in
  (eq : ⟦ (inv-nf {n} l ↑) • [ r ]ᶜ ⟧ ≈ ⟦ (inv-nf l') ↑ • [ r' ]ᶜ ⟧)
  → r ≡ r'
coset-unique n l l' r r' eq = c-inj ⟦ inv-nf l ⟧ ⟦ inv-nf l' ⟧ claim
  where
  module Semn = Monoid (Sem (₁₊ n))
  open Semn using (_∙_)
  open SR (≋-setoid (₁₊ n))

  homoₙ = ⟦⟧-homo.homo (₁₊ n)

  gl = ⟦ (inv-nf l ↑) ⟧
  gl' = ⟦ (inv-nf l' ↑) ⟧

  -- The two denotations split as products, so eq -- an equation
  -- between the denotations of the composite circuits -- becomes an
  -- equation between products in Sem.
  eq-∙ : (gl ∙ ⟦ [ r ]ᶜ ⟧) Semn.≈ (gl' ∙ ⟦ [ r' ]ᶜ ⟧)
  eq-∙ = Semn.trans (Semn.sym (homoₙ (inv-nf l ↑) [ r ]ᶜ))
           (Semn.trans eq (homoₙ (inv-nf l' ↑) [ r' ]ᶜ))

  claim : ∀ (h : Setoid.Carrier Ob) (t : Vec (Setoid.Carrier Ob) n) ->
          ((h ∷ (t ◁ ⟦ inv-nf l ⟧)) ◁ ⟦ [ r ]ᶜ ⟧) ≋
          ((h ∷ (t ◁ ⟦ inv-nf l' ⟧)) ◁ ⟦ [ r' ]ᶜ ⟧)
  claim h t = begin
    (h ∷ (t ◁ ⟦ inv-nf l ⟧)) ◁ ⟦ [ r ]ᶜ ⟧
      ≈⟨ ◁-cong (≋-sym (head-fix h t (inv-nf l))) Semn.refl ⟩
    ((h ∷ t) ◁ gl) ◁ ⟦ [ r ]ᶜ ⟧
      ≈⟨ ≋-sym (◁-compose (h ∷ t) gl ⟦ [ r ]ᶜ ⟧) ⟩
    (h ∷ t) ◁ (gl ∙ ⟦ [ r ]ᶜ ⟧)
      ≈⟨ ◁-cong ≋-refl eq-∙ ⟩
    (h ∷ t) ◁ (gl' ∙ ⟦ [ r' ]ᶜ ⟧)
      ≈⟨ ◁-compose (h ∷ t) gl' ⟦ [ r' ]ᶜ ⟧ ⟩
    ((h ∷ t) ◁ gl') ◁ ⟦ [ r' ]ᶜ ⟧
      ≈⟨ ◁-cong (head-fix h t (inv-nf l')) Semn.refl ⟩
    (h ∷ (t ◁ ⟦ inv-nf l' ⟧)) ◁ ⟦ [ r' ]ᶜ ⟧
      ∎



{-
open import Presentation.Base Γ
open import Presentation.Core Γ using (word-setoid)
open import Function.Definitions using (Congruent ; Injective ; Surjective ; StrictlySurjective)
open import Function.Consequences using (surjective⇒strictlySurjective ; strictlySurjective⇒surjective)


NFs : Setoid 0ℓ 0ℓ
NFs = {!!}

open import Normalization.NormalForm.Propositional Γ (NF 0) using (NormalForm)
open import Normalization.NormalForm.Uniqueness.Setoid Γ (NF 0) Sem ⟦_⟧

private
  variable
    w v : Word X

open Setoid NFs public using ()
  renaming (Carrier to |NF| ; _≈_ to _≈ₙ_ ; refl to reflₙ ; sym to symₙ ; trans to transₙ)
open Setoid Sem using ()
  renaming (Carrier to Cₛ ; _≈_ to _≈₂_ ; sym to sym₂)

--module _
-}
