------------------------------------------------------------------------
-- Presentations of groups
--
-- The out-of-place adder over Clifford+T, for every n (Amy, QPL 2018,
-- section 5.2)
--
-- Section 5.2 verifies Clifford+T implementations of
--
--    Adder_n : |x⟩|y⟩|0⟩ ↦ |x⟩|y⟩|x + y⟩
--
-- by "a standard out-of-place ripple-carry adder which uses n − 1
-- ancilla bits to store intermediate carry values and an additional n
-- bit register to store the output, before copying out and
-- uncomputing", with 4(n − 1) Toffoli gates "expanded to the
-- Clifford+T gate set", against a specification "generated by
-- implementing binary addition on symbolic vectors", for n = 8 and
-- n = 16.  Here the theorem is proved for every n ≥ 1 at once.
--
-- The circuit.  PathSum.Adder.Ripple's netlist of Toffoli and CNOT
-- gates -- Bennett's compute-copy-uncompute around a ripple of
-- carries, on 5n wires: x and y (n bits each), the output z (n + 1
-- bits, so that it holds x + y itself), the carries c₁ … c_(n−1) and
-- the temporary register s (n bits) -- each Toffoli gate expanded into
-- the seven-T circuit of PathSum.Toffoli (PathSum.Reversible.Expand):
-- adderᶜ L on any layout L of those wires, Adderᶜ m on the standard
-- one (PathSum.Adder.Circuit; n = m + 1).
--
-- The specification.  PathSum.Adder.Spec's adderˢ L, the classical
-- path-sum whose output on z_k is the lift of the Boolean expression
-- z_k ⊕ (x + y)_k, (x + y)_k being built by ripple-carry addition on
-- the symbolic vectors x and y, and whose other outputs are the
-- inputs.  The carries and the temporary register are ancillas: they
-- enter in |0⟩, so the claim concerns the columns of the operator at
-- the inputs where they read 0 (clean inputs), and says that there the
-- circuit is the specification, and leaves them clean:
--
--    ⟦ adderᶜ L ⟧ ≋[ scratch L ]₀* adderˢ L                (adderᶜ-spec)
--
-- (PathSum.Ancillas: from a clean input the normalised amplitudes of
-- the two agree), so from a clean input no amplitude reaches an output
-- with an ancilla at 1 (adderᶜ-clean); equivalently, with the ancillas
-- read as the constant 0 in the polynomials of both sides -- how the
-- paper's tool treats an ancilla -- the two path-sums are ≋ outright
-- (adderᶜ-set0).  The output register need not be 0: the circuit and
-- the specification both xor x + y into it, as the tool's
-- specification does; from an output register reading 0 the
-- specification leaves x + y there (PathSum.Adder.Spec.adderˢ-value).
-- The paper's own form, |x⟩|y⟩|0⟩ ↦ |x⟩|y⟩|x + y⟩, is the same
-- statement on the inputs whose output register reads 0 too, against
-- the specification adder₀ˢ L that outputs (x + y)_k itself on z_k
-- (adderᶜ-spec₀, adderᶜ-set0₀); there the output reads the bits of
-- x + y, of value val x + val y (PathSum.Adder.Spec.adder₀ˢ-value).
-- Adder-spec, Adder-clean, Adder-set0, Adder-spec₀ and Adder-set0₀ are
-- these on the standard layout, for every n ≥ 1.
--
-- The proof composes; nothing is reduced.  The circuit computes its
-- netlist's Boolean function (PathSum.Reversible.Expand.
-- expand-computes: each Toffoli gate's path-sum is the classical
-- Toffoli path-sum, and by proposition 2.7 a composite of path-sums
-- computing Boolean functions computes the composite function); the
-- netlist computes the addition on blank inputs
-- (PathSum.Adder.Ripple.adder-computes, by induction on the positions
-- and Bennett's lemma); the specification computes it on every input
-- (PathSum.Adder.Spec.adderˢ-computes, by lemma 2.5); and two
-- path-sums computing functions that agree on the clean inputs agree
-- there (PathSum.Ancillas.computes⇒≋[]₀*).  No path-sum of the whole
-- circuit is ever computed, and no closed instance is evaluated, so
-- the statement costs the same for every n -- where the paper's tool,
-- which expands the specification's polynomials, stopped at 16 bits.
--
-- Resources, and table 2.  The circuit has 5n qubits
-- (PathSum.Adder.Layout.width-5n), and, for n ≥ 2, 4(n − 1) Toffoli
-- gates and 11n − 8 CNOTs (PathSum.Adder.Ripple.adder-toffolis,
-- adder-cnots); each Toffoli gate contributes two Hadamards, hence two
-- path variables, seven T or T† gates, and eight Clifford gates (two
-- Hadamards and six CNOTs; cliffords-expand, counting H, CNOT and
-- R_k, R_k† for k ≤ 2 as PathSum.QFT.Count does).  So for n ≥ 2 it has
-- 8(n − 1) path variables, 28(n − 1) T gates and 32(n − 1) + 11n − 8
-- Clifford gates (Adder-paths, Adder-tcount, Adder-cliffords).  At
-- n = 8 and n = 16 (Adder8, Adder16):
--
--                 qubits   path vars   Clifford     T
--    Adder8 here     40        56         304      196
--    table 2         40        56         334      196
--    Adder16 here    80       120         648      420
--    table 2         80       120         710      420
--
-- The qubits, path variables and T gates are the table's; the Clifford
-- counts are not.  The paper does not publish its circuit, but its
-- tool generates it -- Feynman (github.com/meamy/feynman), whose
-- src/Feynman/Verification/SOP.hs builds carryRipple, expands its
-- Toffoli gates by toffoli, and checks the result against adderOOPSpec
-- (verifyOOPAdder) -- and that circuit is formalised and verified here
-- too, for every n: PathSum.Adder.CarryRipple (the netlist and its
-- correctness), PathSum.Toffoli.Depth3 (the tool's Toffoli circuit)
-- and PathSum.Adder.Tool (the path-sum theorems Tool-spec, Tool-clean
-- and Tool-set0).  Its counts, computed from the circuit, are table
-- 2's rows exactly (PathSum.Adder.Tool.Adder8ᵀ and Adder16ᵀ: 40, 56,
-- 334, 196 and 80, 120, 710, 420).  So the Clifford column differs
-- for two reasons, both read off the tool's source, and separated one
-- circuit at a time in Adder8-gap and Adder16-gap.  The tool's Toffoli
-- circuit has seven CNOTs (nine Clifford gates) where
-- PathSum.Toffoli's has six.  And its netlist has 11n − 6 CNOTs, not
-- 11n − 8: at the first position it runs the full majority block
-- against a carry-in wire carry₀, 0 on input and output (one Toffoli
-- gate and two CNOTs more, each way), and it computes no carry out (two
-- Toffoli gates and two CNOTs fewer), its output register having n
-- bits: it adds modulo 2^n.  carry₀, which the text's "5n − 1 bits"
-- leaves out and the table's 5n counts, is also why the text and the
-- table disagree.  The adder here computes the whole sum, carry out
-- included, in the same 5n qubits and 4(n − 1) Toffoli gates.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat.Base using (ℕ)

module PathSum.Adder (M₀ : ℕ) where

open import Data.Bool.Base using (true; false)
open import Data.Empty using (⊥)
open import Data.Fin.Base using (Fin; _↑ˡ_; _↑ʳ_; splitAt)
open import Data.List.Base using (List; []; _∷_)
open import Data.Nat.Base using (zero; suc; _+_; _*_; _∸_)
open import Data.Nat.Properties using (+-suc)
open import Data.Product.Base using (_×_; _,_; proj₁; proj₂)
open import Data.Sum.Base using (_⊎_; inj₁; inj₂; [_,_]′)
open import Function.Bundles using (Equivalence)
open import Relation.Binary.PropositionalEquality using
  (_≡_; refl; sym; trans; cong; cong₂; subst)

import Data.Fin.Properties as Fin

open import PathSum.Adder.CarryRipple using
  (carryRipple; carryRipple-toffolis; carryRipple-cnots; standardᶠ)
open import PathSum.Adder.Circuit M₀ using
  (Adderᶜ; scratch; clean⇔blank; Adderᶜ-paths; Adderᶜ-tcount)
open import PathSum.Adder.Layout using
  (Wire; cw; sw; zw; Layout; wire; wire-inj; width; standard)
open import PathSum.Adder.Ripple using
  (adder; addition; adder-computes; Work; addition-work; adder-toffolis;
   adder-cnots)
open import PathSum.Adder.Spec M₀ using
  (adderˢ; fun-adderˢ; adderˢ-computes; adder₀ˢ; adder₀ˢ-computes;
   addition₀-addition)
open import PathSum.Adder.Tool M₀ using (expand₃; cliffords-expand₃)
open import PathSum.Ancillas M₀ using
  (Clean; set0ˢ; _≋[_]₀*_; ≋[]₀*⇔set0ˢ; computes⇒≋[]₀*; clean-ancillas)
open import PathSum.Classical M₀ using (_computes_; outBit-none)
open import PathSum.CRK.Path M₀ using (Circuit; ⟦_⟧; paths)
open import PathSum.Cyclotomic M₀ using (_≐_; 0ᴬ)
open import PathSum.Denotation M₀ using (Assign; amp; outBit; _≋_)
open import PathSum.QFT.Count M₀ using (cliffords; cliffords-++)
open import PathSum.Reversible using
  (Gate; ccx; cx; run; recover; toffolis; cnots)
open import PathSum.Reversible.Expand M₀ using (expand; expand-computes)
open import PathSum.Toffoli M₀ using (tof)
open import PathSum.Toffoli.Netlist M₀ using (tcount)

private
  variable
    n m N : ℕ


------------------------------------------------------------------------
-- The circuit on any layout

-- The netlist, each Toffoli gate expanded into the seven-T circuit.

adderᶜ : Layout (Wire false m) N → Circuit N
adderᶜ L = expand (adder L)

-- On all inputs it computes the permutation of its netlist.

adderᶜ-computes : (L : Layout (Wire false m) N) →
                  ⟦ adderᶜ L ⟧ computes run (adder L)
adderᶜ-computes L = expand-computes (adder L)


------------------------------------------------------------------------
-- The theorem: on the clean inputs, the specification

-- The circuit and the specification agree on the inputs where the
-- carries and the temporary register read 0.

adderᶜ-spec : (L : Layout (Wire false m) N) →
              ⟦ adderᶜ L ⟧ ≋[ scratch L ]₀* adderˢ L
adderᶜ-spec L =
  computes⇒≋[]₀* ⟦ adderᶜ L ⟧ (adderˢ L) (scratch L)
    (adderᶜ-computes L) (adderˢ-computes L)
    (λ x cl w → adder-computes L x (Equivalence.to (clean⇔blank L x) cl) w)

-- The ancillas are not the output.

private
  zw≢cw : ∀ {k j} → zw {false} {m} k ≡ cw j → ⊥
  zw≢cw ()

  zw≢sw : ∀ {k i} → zw {false} {m} k ≡ sw i → ⊥
  zw≢sw ()

scratch-work : (L : Layout (Wire false m) N) (i : Fin (m + suc m)) →
               Work L (scratch L i)
scratch-work {m} L i = go (splitAt m i)
  where
  go : (s : Fin m ⊎ Fin (suc m)) →
       Work L ([ (λ j → wire L (cw j)) , (λ i → wire L (sw i)) ]′ s)
  go (inj₁ j) k e = zw≢cw (wire-inj L (zw k) (cw j) e)
  go (inj₂ i) k e = zw≢sw (wire-inj L (zw k) (sw i) e)

-- The ancillas are left clean: from a clean input, no amplitude
-- reaches an output with an ancilla at 1.

adderᶜ-clean : (L : Layout (Wire false m) N) → ∀ x z →
               Clean (scratch L) x → (i : Fin (m + suc m)) →
               z (scratch L i) ≡ true → amp ⟦ adderᶜ L ⟧ x z ≐ 0ᴬ
adderᶜ-clean L = clean-ancillas (scratch L) (adderᶜ-spec L) out0
  where
  out0 : ∀ x (y : Assign 0) → Clean (scratch L) x →
         ∀ i → outBit (adderˢ L) x y (scratch L i) ≡ false
  out0 x y cl i =
    trans (outBit-none (adderˢ L) x y (scratch L i))
    (trans (fun-adderˢ L x (scratch L i))
    (trans (addition-work L x (scratch L i) (scratch-work L i)) (cl i)))

-- With the ancillas read as the constant 0 on both sides, the circuit's
-- path-sum is equivalent to the specification's.

adderᶜ-set0 : (L : Layout (Wire false m) N) →
              set0ˢ (scratch L) ⟦ adderᶜ L ⟧ ≋ set0ˢ (scratch L) (adderˢ L)
adderᶜ-set0 L =
  Equivalence.to (≋[]₀*⇔set0ˢ (scratch L) ⟦ adderᶜ L ⟧ (adderˢ L))
                 (adderᶜ-spec L)


------------------------------------------------------------------------
-- The paper's form: |x⟩|y⟩|0⟩ ↦ |x⟩|y⟩|x + y⟩

-- The ancillas, then the output register.

blank₀ : Layout (Wire false m) N → Fin ((m + suc m) + suc (suc m)) → Fin N
blank₀ {m} L j =
  [ scratch L , (λ k → wire L (zw k)) ]′ (splitAt (m + suc m) j)

-- An input clean on them is clean on the ancillas, and its output
-- register reads 0.

clean₀ : (L : Layout (Wire false m) N) (x : Assign N) → Clean (blank₀ L) x →
         Clean (scratch L) x × (∀ k → x (wire L (zw k)) ≡ false)
clean₀ {m} L x cl =
  (λ i → subst (λ s → x (at s) ≡ false)
               (Fin.splitAt-↑ˡ (m + suc m) i (suc (suc m)))
               (cl (i ↑ˡ suc (suc m)))) ,
  (λ k → subst (λ s → x (at s) ≡ false)
               (Fin.splitAt-↑ʳ (m + suc m) (suc (suc m)) k)
               (cl ((m + suc m) ↑ʳ k)))
  where
  at : Fin (m + suc m) ⊎ Fin (suc (suc m)) → Fin _
  at = [ scratch L , (λ k → wire L (zw k)) ]′

-- There the circuit is the specification that writes x + y into the
-- output register.

adderᶜ-spec₀ : (L : Layout (Wire false m) N) →
               ⟦ adderᶜ L ⟧ ≋[ blank₀ L ]₀* adder₀ˢ L
adderᶜ-spec₀ L =
  computes⇒≋[]₀* ⟦ adderᶜ L ⟧ (adder₀ˢ L) (blank₀ L)
    (adderᶜ-computes L) (adder₀ˢ-computes L)
    (λ x cl w →
       trans (adder-computes L x
                (Equivalence.to (clean⇔blank L x) (proj₁ (clean₀ L x cl))) w)
             (addition₀-addition L x (proj₂ (clean₀ L x cl)) w))

adderᶜ-set0₀ : (L : Layout (Wire false m) N) →
               set0ˢ (blank₀ L) ⟦ adderᶜ L ⟧ ≋ set0ˢ (blank₀ L) (adder₀ˢ L)
adderᶜ-set0₀ L =
  Equivalence.to (≋[]₀*⇔set0ˢ (blank₀ L) ⟦ adderᶜ L ⟧ (adder₀ˢ L))
                 (adderᶜ-spec₀ L)


------------------------------------------------------------------------
-- The adder on the standard layout, for every n ≥ 1

-- On 5n wires: x, y, z, the carries, the temporary register
-- (PathSum.Adder.Layout.standard; n = m + 1).

Adder-computes : (m : ℕ) → ⟦ Adderᶜ m ⟧ computes run (adder (standard m))
Adder-computes m = adderᶜ-computes (standard m)

Adder-spec : (m : ℕ) → ⟦ Adderᶜ m ⟧ ≋[ scratch (standard m) ]₀*
                         adderˢ (standard m)
Adder-spec m = adderᶜ-spec (standard m)

Adder-clean : (m : ℕ) → ∀ x z → Clean (scratch (standard m)) x →
              (i : Fin (m + suc m)) → z (scratch (standard m) i) ≡ true →
              amp ⟦ Adderᶜ m ⟧ x z ≐ 0ᴬ
Adder-clean m = adderᶜ-clean (standard m)

Adder-set0 : (m : ℕ) →
             set0ˢ (scratch (standard m)) ⟦ Adderᶜ m ⟧ ≋
             set0ˢ (scratch (standard m)) (adderˢ (standard m))
Adder-set0 m = adderᶜ-set0 (standard m)

Adder-spec₀ : (m : ℕ) → ⟦ Adderᶜ m ⟧ ≋[ blank₀ (standard m) ]₀*
                          adder₀ˢ (standard m)
Adder-spec₀ m = adderᶜ-spec₀ (standard m)

Adder-set0₀ : (m : ℕ) →
              set0ˢ (blank₀ (standard m)) ⟦ Adderᶜ m ⟧ ≋
              set0ˢ (blank₀ (standard m)) (adder₀ˢ (standard m))
Adder-set0₀ m = adderᶜ-set0₀ (standard m)


------------------------------------------------------------------------
-- Resources

-- Clifford gates (H, CNOT, and R_k, R_k† for k ≤ 2): eight per Toffoli
-- gate (two Hadamards, six CNOTs) and one per CNOT.

cliffords-expand : (gs : List (Gate n)) →
                   cliffords (expand gs) ≡ toffolis gs * 8 + cnots gs
cliffords-expand []                       = refl
cliffords-expand (ccx c₁ c₂ t p q r ∷ gs) =
  trans (cliffords-++ (tof c₁ c₂ t (recover p) (recover q) (recover r))
                      (expand gs))
        (cong (8 +_) (cliffords-expand gs))
cliffords-expand (cx c t p ∷ gs)          =
  trans (cong suc (cliffords-expand gs))
        (sym (+-suc (toffolis gs * 8) (cnots gs)))

Adder-cliffords-gates : (m : ℕ) →
                        cliffords (Adderᶜ m) ≡
                        toffolis (adder (standard m)) * 8 +
                        cnots (adder (standard m))
Adder-cliffords-gates m = cliffords-expand (adder (standard m))

-- For n = m + 2 ≥ 2 bits: 8(n − 1) path variables, 28(n − 1) T gates,
-- 32(n − 1) + 11n − 8 Clifford gates.

Adder-paths : (m : ℕ) → paths (Adderᶜ (suc m)) ≡ 4 * suc m * 2
Adder-paths m =
  trans (Adderᶜ-paths (suc m))
        (cong (_* 2) (adder-toffolis (standard (suc m))))

Adder-tcount : (m : ℕ) → tcount (Adderᶜ (suc m)) ≡ 4 * suc m * 7
Adder-tcount m =
  trans (Adderᶜ-tcount (suc m))
        (cong (_* 7) (adder-toffolis (standard (suc m))))

Adder-cliffords : (m : ℕ) → cliffords (Adderᶜ (suc m)) ≡
                  4 * suc m * 8 + (11 * suc (suc m) ∸ 8)
Adder-cliffords m =
  trans (Adder-cliffords-gates (suc m))
        (cong₂ (λ t c → t * 8 + c) (adder-toffolis (standard (suc m)))
                                   (adder-cnots (standard (suc m))))

-- Table 2's columns -- qubits, path variables, Clifford gates, T gates
-- -- for n = 8 and n = 16: the table's 40, 56, 196 and 80, 120, 420,
-- but 304 and 648 Clifford gates where the table has 334 and 710 (see
-- the header).  The qubits are the circuit's width, the index of its
-- type (Adderᶜ m : Circuit (width m)).  The circuits are never
-- computed: these are the counts above at n = 8 and n = 16.

Adder8 : (width 7 ≡ 40) × (paths (Adderᶜ 7) ≡ 56) ×
         (cliffords (Adderᶜ 7) ≡ 304) × (tcount (Adderᶜ 7) ≡ 196)
Adder8 =
  refl ,
  trans (Adderᶜ-paths 7) (cong (_* 2) (adder-toffolis (standard 7))) ,
  trans (Adder-cliffords-gates 7)
        (cong₂ (λ t c → t * 8 + c) (adder-toffolis (standard 7))
                                   (adder-cnots (standard 7))) ,
  trans (Adderᶜ-tcount 7) (cong (_* 7) (adder-toffolis (standard 7)))

Adder16 : (width 15 ≡ 80) × (paths (Adderᶜ 15) ≡ 120) ×
          (cliffords (Adderᶜ 15) ≡ 648) × (tcount (Adderᶜ 15) ≡ 420)
Adder16 =
  refl ,
  trans (Adderᶜ-paths 15) (cong (_* 2) (adder-toffolis (standard 15))) ,
  trans (Adder-cliffords-gates 15)
        (cong₂ (λ t c → t * 8 + c) (adder-toffolis (standard 15))
                                   (adder-cnots (standard 15))) ,
  trans (Adderᶜ-tcount 15) (cong (_* 7) (adder-toffolis (standard 15)))


------------------------------------------------------------------------
-- The Clifford gap, gate by gate

-- The two differences from the paper's circuit, one at a time: the
-- netlist here with the tool's Toffoli circuit has 332 and 708
-- Clifford gates (the netlists' two CNOTs apart from 334 and 710), and
-- the tool's netlist with PathSum.Toffoli's circuit 306 and 650 (one
-- Clifford gate per Toffoli gate apart).

Adder8-gap :
  (cliffords (expand₃ (adder (standard 7))) ≡ 332) ×
  (cliffords (expand (carryRipple (standardᶠ 7))) ≡ 306)
Adder8-gap =
  trans (cliffords-expand₃ (adder (standard 7)))
        (cong₂ (λ t c → t * 9 + c) (adder-toffolis (standard 7))
                                   (adder-cnots (standard 7))) ,
  trans (cliffords-expand (carryRipple (standardᶠ 7)))
        (cong₂ (λ t c → t * 8 + c) (carryRipple-toffolis (standardᶠ 7))
                                   (carryRipple-cnots (standardᶠ 7)))

Adder16-gap :
  (cliffords (expand₃ (adder (standard 15))) ≡ 708) ×
  (cliffords (expand (carryRipple (standardᶠ 15))) ≡ 650)
Adder16-gap =
  trans (cliffords-expand₃ (adder (standard 15)))
        (cong₂ (λ t c → t * 9 + c) (adder-toffolis (standard 15))
                                   (adder-cnots (standard 15))) ,
  trans (cliffords-expand (carryRipple (standardᶠ 15)))
        (cong₂ (λ t c → t * 8 + c) (carryRipple-toffolis (standardᶠ 15))
                                   (carryRipple-cnots (standardᶠ 15)))
