------------------------------------------------------------------------
-- Presentations of groups
--
-- Renaming the variables of a path-sum along bijections (Amy, QPL
-- 2018, remark 2.8)
--
-- Remark 2.8 says that "circuits which are equivalent up to symmetric
-- monoidal laws are strictly equal in the path-sum picture", naming
-- the bifunctoriality law and the naturality of SWAP.  In a path-sum
-- the path variables are bound -- summed over -- and the paper names
-- them by the order in which the gates introduce them, so "strictly
-- equal" can only mean equal once the bound variables are named
-- alike: equal up to a renaming of the path variables, the
-- α-conversion of path-sums.  This module supplies that renaming, and
-- the relation it induces; the rest of the work package uses it.
--
-- The plan of the work package (remark 2.8).
--
--  * Here, without M: the renaming of path variables along a
--    bijection π : Fin m ↔ Fin m′ (stdlib's Permutation), renumberᴾ
--    and renumber; the relabelling of the wires along σ : Fin n ↔
--    Fin n′, relabelᴾ and relabel, which renames the input variables
--    and moves the outputs (the structure maps of the monoidal
--    structure act on path-sums this way); that evaluation commutes
--    with both (eval-renumberᴾ, eval-relabelᴾ); and ξ ≡ᴿ⟨ π ⟩ ζ, the
--    relation "ζ is ξ with its path variables renamed by π": the same
--    normalisation, and every coefficient of ζ's phase and outputs
--    equal, as an integer, to the corresponding coefficient of ξ's.
--    It is an equivalence (≡ᴿ-refl, ≡ᴿ-sym, ≡ᴿ-trans), and it follows
--    from values alone (≡ᴿ-by-values, by Möbius uniqueness,
--    PathSum.Polynomial.Bind.poly-ext).
--
--  * PathSum.Permute.Sound: that renaming and relabelling act on
--    operators as they should -- renumber π ξ ≋ ξ, and relabel σ ξ is
--    ξ conjugated by the wire permutation (amp-relabel) -- and the
--    weaker relation ξ ≈ᴿ⟨ π ⟩ ζ: the same normalisation, phases
--    congruent modulo 2^M and outputs modulo 2 after the renaming,
--    i.e. PathSum.Congruence.Congruent (renumber π ξ) ζ.  Both
--    relations imply ≋.
--
--  * PathSum.Permute.Blocks: the structure maps of the monoidal
--    structure on wires -- the associator and the right unitor (casts
--    along +-assoc and +-identityʳ), the braiding (the exchange of two
--    blocks), bijections side by side -- and their coherence, as
--    pointwise equalities of bijections (the hexagon, the pentagon,
--    the triangle, the symmetry).
--
--  * PathSum.CRK.Structural: circuits over {H, CNOT, R_k, R_k†}.
--    Structural equivalence C ∼ C′ is the congruence on gate lists
--    generated by commuting adjacent gates on disjoint wires -- the
--    interchange law of monoidal categories, read on circuits.  Then
--    ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧ for a renaming π read off the derivation
--    (structural): commuting two Hadamards exchanges their path
--    variables, and nothing else changes a coefficient.  Relabelling
--    the wires of a circuit by a permutation relabels its path-sum
--    (relabel-⟦⟧), which is the naturality of the symmetry for
--    circuits.
--
--  * PathSum.Compose.Monoidal: the symmetric monoidal laws of ⊗ᴾ.
--    Associativity and the unit laws, up to the re-indexing of the
--    wires by the cast along +-assoc or +-identityʳ; the symmetry
--    (the block exchange) natural, involutive, and with the hexagon;
--    and remark 2.8's two examples, the interchange law and the
--    naturality of SWAP -- each up to a renaming of the path variables,
--    hence up to ≋.
--
-- What is here.  pullˢ f s pulls a subset back along f : Fin k →
-- Fin l.  The coefficient of x^α y^β in renumberᴾ π P is that of
-- x^α y^(π⁻¹ β) in P, where π⁻¹ β, the pull-back of β along π, is
-- the set of the old variables whose new names are in β; relabelᴾ
-- does the same to the input variables.  A path-sum is renumbered by
-- renumbering its phase and outputs; it is relabelled by relabelling
-- them and moving the output of wire i to wire σ i.  The evaluation
-- lemmas reindex the sums over all monomials along the bijection of
-- subsets that π induces (Σsub-pull), by induction on the number of
-- variables: π sends the first variable to some j and the rest by
-- remove 0 π, so the sum over subsets is split at j
-- (PathSum.Polynomial.Properties.Σsub-splitAt), as PathSum.Reorder
-- does for a single move to the front.
--
-- Nothing here is about circuits or amplitudes, and nothing depends
-- on M.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module PathSum.Permute where

open import Data.Bool.Base using (Bool; true; false; _∧_; if_then_else_)
open import Data.Fin.Base using (Fin; zero; suc; punchIn; punchOut)
open import Data.Fin.Permutation using
  (Permutation; _⟨$⟩ʳ_; _⟨$⟩ˡ_; inverseˡ; inverseʳ; id; flip; _∘ₚ_;
   remove; punchIn-permute)
open import Data.Fin.Properties using (punchIn-punchOut; ¬Fin0)
open import Data.Fin.Subset using (Subset; Side; inside; outside)
open import Data.Integer.Base using (ℤ; 0ℤ; _+_)
open import Data.Nat.Base using (ℕ; zero; suc)
open import Data.Product.Base using (_,_)
open import Data.Vec.Base using
  ([]; _∷_; tabulate; lookup; insertAt; removeAt)
open import Data.Vec.Properties using
  (lookup∘tabulate; tabulate∘lookup; tabulate-cong; insertAt-lookup;
   insertAt-punchIn; insertAt-removeAt)
open import Relation.Binary.PropositionalEquality using
  (_≡_; _≢_; refl; sym; trans; cong; cong₂)
open import Relation.Nullary.Decidable using (yes; no)
open import Relation.Nullary.Negation using (contradiction)

import Data.Fin.Properties as Fin

open import PathSum.Base using (PathSum; ⟨_,_⟩; phase; out)
open import PathSum.Polynomial using (Mon; Poly; Σsub; sat; eval)
open import PathSum.Polynomial.Bind using (poly-ext)
open import PathSum.Polynomial.Properties using
  (Σsub-cong; Σsub-+; Σsub-splitAt; sat-cong)
open import PathSum.Reorder using
  (insertᵃ; insertᵃ-here; insertᵃ-punchIn; sat-insertᵃ-in;
   sat-insertᵃ-out)

private
  variable
    k k′ k″ l n n′ n″ m m′ m″ o : ℕ


------------------------------------------------------------------------
-- Pulling subsets back

-- i is in pullˢ f s exactly when f i is in s.

pullˢ : (Fin k → Fin l) → Subset l → Subset k
pullˢ f s = tabulate (λ i → lookup s (f i))

pullˢ-cong : {f g : Fin k → Fin l} → (∀ i → f i ≡ g i) →
             ∀ s → pullˢ f s ≡ pullˢ g s
pullˢ-cong f≗g s = tabulate-cong (λ i → cong (lookup s) (f≗g i))

pullˢ-id : (s : Subset k) → pullˢ (λ i → i) s ≡ s
pullˢ-id s = tabulate∘lookup s

pullˢ-∘ : (f : Fin k → Fin l) (g : Fin l → Fin o) (s : Subset o) →
          pullˢ f (pullˢ g s) ≡ pullˢ (λ i → g (f i)) s
pullˢ-∘ f g s =
  tabulate-cong (λ i → lookup∘tabulate (λ i′ → lookup s (g i′)) (f i))

-- Along a bijection π of Fin (suc k) and Fin (suc l): π sends 0 to
-- some j, and suc i to punchIn j (remove 0 π i).  So a subset with b
-- inserted at j pulls back to b followed by the pull-back of the rest
-- along remove 0 π.

pullˢ-insertAt : (π : Permutation (suc k) (suc l)) (t : Subset l)
                 (b : Side) →
                 pullˢ (π ⟨$⟩ʳ_) (insertAt t (π ⟨$⟩ʳ zero) b) ≡
                 b ∷ pullˢ (remove zero π ⟨$⟩ʳ_) t
pullˢ-insertAt π t b = cong₂ _∷_ (insertAt-lookup t (π ⟨$⟩ʳ zero) b)
  (tabulate-cong (λ i →
    trans (cong (lookup (insertAt t (π ⟨$⟩ʳ zero) b))
                (punchIn-permute π zero i))
          (insertAt-punchIn t (π ⟨$⟩ʳ zero) b (remove zero π ⟨$⟩ʳ i))))

-- Every assignment is its value at j inserted into the rest.

insertᵃ-split : (j : Fin (suc l)) (y : Fin (suc l) → Bool) →
                ∀ i → insertᵃ j (y j) (λ i′ → y (punchIn j i′)) i ≡ y i
insertᵃ-split j y i with i Fin.≟ j
... | yes refl = insertᵃ-here j (y j) (λ i′ → y (punchIn j i′))
... | no  i≢j  =
  trans (cong (insertᵃ j (y j) (λ i′ → y (punchIn j i′))) (sym e))
        (trans (insertᵃ-punchIn j (y j) (λ i′ → y (punchIn j i′))
                                (punchOut j≢i))
               (cong y e))
  where
  j≢i : j ≢ i
  j≢i eq = i≢j (sym eq)

  e : punchIn j (punchOut j≢i) ≡ i
  e = punchIn-punchOut j≢i


------------------------------------------------------------------------
-- Satisfaction and sums, reindexed

-- A monomial pulled back along π is satisfied by an assignment read
-- through π exactly when the monomial is satisfied by the assignment.

sat-pull : (π : Permutation k l) (s : Subset l) (y : Fin l → Bool) →
           sat (pullˢ (π ⟨$⟩ʳ_) s) (λ i → y (π ⟨$⟩ʳ i)) ≡ sat s y
sat-pull {zero}  {zero}  π []  y = refl
sat-pull {zero}  {suc l} π s   y = contradiction (π ⟨$⟩ˡ zero) ¬Fin0
sat-pull {suc k} {zero}  π s   y = contradiction (π ⟨$⟩ʳ zero) ¬Fin0
sat-pull {suc k} {suc l} π s   y =
  trans (cong (λ s′ → sat (pullˢ (π ⟨$⟩ʳ_) s′) (λ i → y (π ⟨$⟩ʳ i)))
              (sym (insertAt-removeAt s j)))
  (trans (at (removeAt s j) (lookup s j))
         (cong (λ s′ → sat s′ y) (insertAt-removeAt s j)))
  where
  j : Fin (suc l)
  j = π ⟨$⟩ʳ zero

  ρ : Permutation k l
  ρ = remove zero π

  y′ : Fin l → Bool
  y′ i = y (punchIn j i)

  rest : (t : Subset l) →
         sat (pullˢ (ρ ⟨$⟩ʳ_) t) (λ i → y (π ⟨$⟩ʳ suc i)) ≡ sat t y′
  rest t = trans
    (sat-cong (pullˢ (ρ ⟨$⟩ʳ_) t) (λ i → cong y (punchIn-permute π zero i)))
    (sat-pull ρ t y′)

  y≗ : ∀ i → y i ≡ insertᵃ j (y j) y′ i
  y≗ i = sym (insertᵃ-split j y i)

  head : (b : Side) (t : Subset l) →
         sat (b ∷ pullˢ (ρ ⟨$⟩ʳ_) t) (λ i → y (π ⟨$⟩ʳ i)) ≡
         sat (insertAt t j b) y
  head inside  t = trans (cong (y j ∧_) (rest t)) (sym (trans
    (sat-cong (insertAt t j inside) y≗)
    (sat-insertᵃ-in t j (y j) y′)))
  head outside t = trans (rest t) (sym (trans
    (sat-cong (insertAt t j outside) y≗)
    (sat-insertᵃ-out t j (y j) y′)))

  at : (t : Subset l) (b : Side) →
       sat (pullˢ (π ⟨$⟩ʳ_) (insertAt t j b)) (λ i → y (π ⟨$⟩ʳ i)) ≡
       sat (insertAt t j b) y
  at t b = trans (cong (λ s′ → sat s′ (λ i → y (π ⟨$⟩ʳ i)))
                       (pullˢ-insertAt π t b))
                 (head b t)

-- A sum over all subsets is unchanged when they are pulled back along
-- a bijection.

Σsub-pull : (π : Permutation k l) (f : Subset k → ℤ) →
            Σsub (λ s → f (pullˢ (π ⟨$⟩ʳ_) s)) ≡ Σsub f
Σsub-pull {zero}  {zero}  π f = refl
Σsub-pull {zero}  {suc l} π f = contradiction (π ⟨$⟩ˡ zero) ¬Fin0
Σsub-pull {suc k} {zero}  π f = contradiction (π ⟨$⟩ʳ zero) ¬Fin0
Σsub-pull {suc k} {suc l} π f =
  trans (Σsub-splitAt j (λ s → f (pullˢ (π ⟨$⟩ʳ_) s)))
  (trans (Σsub-cong (λ t → cong₂ _+_
            (cong f (pullˢ-insertAt π t inside))
            (cong f (pullˢ-insertAt π t outside))))
  (trans (Σsub-+ (λ t → f (inside ∷ pullˢ (ρ ⟨$⟩ʳ_) t))
                 (λ t → f (outside ∷ pullˢ (ρ ⟨$⟩ʳ_) t)))
         (cong₂ _+_ (Σsub-pull ρ (λ s → f (inside ∷ s)))
                    (Σsub-pull ρ (λ s → f (outside ∷ s))))))
  where
  j : Fin (suc l)
  j = π ⟨$⟩ʳ zero

  ρ : Permutation k l
  ρ = remove zero π


------------------------------------------------------------------------
-- Renaming polynomials

-- renumberᴾ π renames the path variable y_j to y_(π j); relabelᴾ σ
-- renames the input variable x_i to x_(σ i).  The coefficient of a
-- monomial after the renaming is that of the monomial it came from.

renumberᴾ : Permutation m m′ → Poly n m → Poly n m′
renumberᴾ π P (α , β) = P (α , pullˢ (π ⟨$⟩ʳ_) β)

relabelᴾ : Permutation n n′ → Poly n m → Poly n′ m
relabelᴾ σ P (α , β) = P (pullˢ (σ ⟨$⟩ʳ_) α , β)

-- The value of a renamed polynomial is that of the original at the
-- assignment read through the renaming.

eval-renumberᴾ : (π : Permutation m m′) (P : Poly n m)
                 (x : Fin n → Bool) (y : Fin m′ → Bool) →
                 eval (renumberᴾ π P) x y ≡ eval P x (λ j → y (π ⟨$⟩ʳ j))
eval-renumberᴾ {m = m} {n = n} π P x y = Σsub-cong (λ α →
  trans (Σsub-cong (λ β → cong
          (λ b → if sat α x ∧ b then P (α , pullˢ (π ⟨$⟩ʳ_) β) else 0ℤ)
          (sym (sat-pull π β y))))
        (Σsub-pull π (G α)))
  where
  G : Subset n → Subset m → ℤ
  G α β = if sat α x ∧ sat β (λ j → y (π ⟨$⟩ʳ j)) then P (α , β) else 0ℤ

eval-relabelᴾ : (σ : Permutation n n′) (P : Poly n m)
                (x : Fin n′ → Bool) (y : Fin m → Bool) →
                eval (relabelᴾ σ P) x y ≡ eval P (λ i → x (σ ⟨$⟩ʳ i)) y
eval-relabelᴾ {n = n} {m = m} σ P x y =
  trans (Σsub-cong (λ α → Σsub-cong (λ β → cong
          (λ a → if a ∧ sat β y then P (pullˢ (σ ⟨$⟩ʳ_) α , β) else 0ℤ)
          (sym (sat-pull σ α x)))))
        (Σsub-pull σ (λ α → Σsub (G α)))
  where
  G : Subset n → Subset m → ℤ
  G α β = if sat α (λ i → x (σ ⟨$⟩ʳ i)) ∧ sat β y then P (α , β) else 0ℤ

-- Renaming along the identity, along a composite, and along pointwise
-- equal bijections.

renumberᴾ-id : (P : Poly n m) → ∀ γ → renumberᴾ id P γ ≡ P γ
renumberᴾ-id P (α , β) = cong (λ b → P (α , b)) (pullˢ-id β)

relabelᴾ-id : (P : Poly n m) → ∀ γ → relabelᴾ id P γ ≡ P γ
relabelᴾ-id P (α , β) = cong (λ a → P (a , β)) (pullˢ-id α)

renumberᴾ-∘ : (π : Permutation m m′) (ρ : Permutation m′ m″) (P : Poly n m) →
              ∀ γ → renumberᴾ ρ (renumberᴾ π P) γ ≡ renumberᴾ (π ∘ₚ ρ) P γ
renumberᴾ-∘ π ρ P (α , β) =
  cong (λ b → P (α , b)) (pullˢ-∘ (π ⟨$⟩ʳ_) (ρ ⟨$⟩ʳ_) β)

relabelᴾ-∘ : (σ : Permutation n n′) (τ : Permutation n′ n″) (P : Poly n m) →
             ∀ γ → relabelᴾ τ (relabelᴾ σ P) γ ≡ relabelᴾ (σ ∘ₚ τ) P γ
relabelᴾ-∘ σ τ P (α , β) =
  cong (λ a → P (a , β)) (pullˢ-∘ (σ ⟨$⟩ʳ_) (τ ⟨$⟩ʳ_) α)

renumberᴾ-cong : {π ρ : Permutation m m′} → (∀ j → π ⟨$⟩ʳ j ≡ ρ ⟨$⟩ʳ j) →
                 (P : Poly n m) → ∀ γ → renumberᴾ π P γ ≡ renumberᴾ ρ P γ
renumberᴾ-cong π≗ρ P (α , β) =
  cong (λ b → P (α , b)) (pullˢ-cong π≗ρ β)

relabelᴾ-cong : {σ τ : Permutation n n′} → (∀ i → σ ⟨$⟩ʳ i ≡ τ ⟨$⟩ʳ i) →
                (P : Poly n m) → ∀ γ → relabelᴾ σ P γ ≡ relabelᴾ τ P γ
relabelᴾ-cong σ≗τ P (α , β) =
  cong (λ a → P (a , β)) (pullˢ-cong σ≗τ α)

-- The two renamings commute.

renumber-relabelᴾ : (π : Permutation m m′) (σ : Permutation n n′)
                    (P : Poly n m) →
                    ∀ γ → renumberᴾ π (relabelᴾ σ P) γ ≡
                          relabelᴾ σ (renumberᴾ π P) γ
renumber-relabelᴾ π σ P (α , β) = refl


------------------------------------------------------------------------
-- Renaming path-sums

-- The path variables renamed along π.

renumber : Permutation m m′ → PathSum n k m → PathSum n k m′
renumber π ξ = ⟨ renumberᴾ π (phase ξ) , (λ w → renumberᴾ π (out ξ w)) ⟩

-- The wires relabelled along σ: the input variables renamed, and the
-- output of wire i moved to wire σ i.

relabel : Permutation n n′ → PathSum n k m → PathSum n′ k m
relabel σ ξ =
  ⟨ relabelᴾ σ (phase ξ) , (λ w → relabelᴾ σ (out ξ (σ ⟨$⟩ˡ w))) ⟩


------------------------------------------------------------------------
-- Equality up to renaming the path variables

-- ξ ≡ᴿ⟨ π ⟩ ζ: ζ is ξ with its path variables renamed along π.  The
-- normalisations are equal (as numbers: they are indices, and may be
-- written differently), and every coefficient of ζ's phase and of its
-- outputs is, as an integer, the coefficient of the corresponding
-- monomial of ξ's.  The coefficients are compared one by one, since
-- polynomials are functions and --safe has no function
-- extensionality.

infix 4 _≡ᴿ⟨_⟩_

record _≡ᴿ⟨_⟩_ (ξ : PathSum n k m) (π : Permutation m m′)
               (ζ : PathSum n k′ m′) : Set where
  constructor renamed
  field
    norm≡  : k ≡ k′
    phase≡ : ∀ γ → renumberᴾ π (phase ξ) γ ≡ phase ζ γ
    out≡   : ∀ w γ → renumberᴾ π (out ξ w) γ ≡ out ζ w γ

open _≡ᴿ⟨_⟩_ public

-- It is an equivalence: the identity renaming, the inverse one, and
-- the composite.

≡ᴿ-refl : (ξ : PathSum n k m) → ξ ≡ᴿ⟨ id ⟩ ξ
≡ᴿ-refl ξ = renamed refl (renumberᴾ-id (phase ξ))
                         (λ w → renumberᴾ-id (out ξ w))

private
  -- Renaming back along the inverse undoes a renaming; renaming along
  -- π and then ρ is renaming along the composite.

  sym-coeff : (π : Permutation m m′) (P : Poly n m) (Q : Poly n m′) →
              (∀ γ → renumberᴾ π P γ ≡ Q γ) →
              ∀ γ → renumberᴾ (flip π) Q γ ≡ P γ
  sym-coeff π P Q h (α , β) =
    trans (sym (h (α , pullˢ (π ⟨$⟩ˡ_) β)))
          (cong (λ b → P (α , b))
                (trans (pullˢ-∘ (π ⟨$⟩ʳ_) (π ⟨$⟩ˡ_) β)
                       (trans (pullˢ-cong (λ i → inverseˡ π) β)
                              (pullˢ-id β))))

  trans-coeff : (π : Permutation m m′) (ρ : Permutation m′ m″)
                (P : Poly n m) (Q : Poly n m′) (R : Poly n m″) →
                (∀ γ → renumberᴾ π P γ ≡ Q γ) →
                (∀ γ → renumberᴾ ρ Q γ ≡ R γ) →
                ∀ γ → renumberᴾ (π ∘ₚ ρ) P γ ≡ R γ
  trans-coeff π ρ P Q R h₁ h₂ (α , β) =
    trans (sym (renumberᴾ-∘ π ρ P (α , β)))
          (trans (h₁ (α , pullˢ (ρ ⟨$⟩ʳ_) β)) (h₂ (α , β)))

≡ᴿ-sym : {ξ : PathSum n k m} {π : Permutation m m′} {ζ : PathSum n k′ m′} →
         ξ ≡ᴿ⟨ π ⟩ ζ → ζ ≡ᴿ⟨ flip π ⟩ ξ
≡ᴿ-sym {ξ = ξ} {π} {ζ} (renamed k≡k′ ph ou) = renamed (sym k≡k′)
  (sym-coeff π (phase ξ) (phase ζ) ph)
  (λ w → sym-coeff π (out ξ w) (out ζ w) (ou w))

≡ᴿ-trans : {ξ : PathSum n k m} {π : Permutation m m′} {ζ : PathSum n k′ m′}
           {ρ : Permutation m′ m″} {χ : PathSum n k″ m″} →
           ξ ≡ᴿ⟨ π ⟩ ζ → ζ ≡ᴿ⟨ ρ ⟩ χ → ξ ≡ᴿ⟨ π ∘ₚ ρ ⟩ χ
≡ᴿ-trans {ξ = ξ} {π} {ζ} {ρ} {χ} (renamed e₁ ph₁ ou₁) (renamed e₂ ph₂ ou₂) =
  renamed (trans e₁ e₂)
    (trans-coeff π ρ (phase ξ) (phase ζ) (phase χ) ph₁ ph₂)
    (λ w → trans-coeff π ρ (out ξ w) (out ζ w) (out χ w) (ou₁ w) (ou₂ w))

-- Pointwise equal renamings rename alike.

≡ᴿ-cong : {ξ : PathSum n k m} {π ρ : Permutation m m′} {ζ : PathSum n k′ m′} →
          (∀ j → π ⟨$⟩ʳ j ≡ ρ ⟨$⟩ʳ j) → ξ ≡ᴿ⟨ π ⟩ ζ → ξ ≡ᴿ⟨ ρ ⟩ ζ
≡ᴿ-cong {ξ = ξ} {π} {ρ} π≗ρ (renamed e ph ou) = renamed e
  (λ γ → trans (sym (renumberᴾ-cong {π = π} {ρ} π≗ρ (phase ξ) γ)) (ph γ))
  (λ w γ → trans (sym (renumberᴾ-cong {π = π} {ρ} π≗ρ (out ξ w) γ))
                 (ou w γ))

-- Equality up to renaming follows from the values alone: polynomials
-- with the same values everywhere have the same coefficients (Möbius
-- uniqueness, poly-ext), and the values of the renamed polynomials are
-- those of the originals read through the renaming.

≡ᴿ-by-values : (ξ : PathSum n k m) (ζ : PathSum n k′ m′)
               (π : Permutation m m′) → k ≡ k′ →
               (∀ x y → eval (phase ξ) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                        eval (phase ζ) x y) →
               (∀ w x y → eval (out ξ w) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                          eval (out ζ w) x y) →
               ξ ≡ᴿ⟨ π ⟩ ζ
≡ᴿ-by-values ξ ζ π k≡k′ ph ou = renamed k≡k′
  (poly-ext (renumberᴾ π (phase ξ)) (phase ζ)
            (λ x y → trans (eval-renumberᴾ π (phase ξ) x y) (ph x y)))
  (λ w → poly-ext (renumberᴾ π (out ξ w)) (out ζ w)
                  (λ x y → trans (eval-renumberᴾ π (out ξ w) x y)
                                 (ou w x y)))


------------------------------------------------------------------------
-- Relabelling, coefficient by coefficient

-- Relabelling along the identity changes nothing, along τ after σ is
-- relabelling along the composite, and it depends only on the values
-- of the bijection.

relabel-id : (ξ : PathSum n k m) → relabel id ξ ≡ᴿ⟨ id ⟩ ξ
relabel-id ξ = renamed refl
  (λ { (α , β) → cong₂ (λ a b → phase ξ (a , b)) (pullˢ-id α) (pullˢ-id β) })
  (λ w → λ { (α , β) →
     cong₂ (λ a b → out ξ w (a , b)) (pullˢ-id α) (pullˢ-id β) })

relabel-∘ : (σ : Permutation n n′) (τ : Permutation n′ n″)
            (ξ : PathSum n k m) →
            relabel τ (relabel σ ξ) ≡ᴿ⟨ id ⟩ relabel (σ ∘ₚ τ) ξ
relabel-∘ σ τ ξ = renamed refl
  (λ { (α , β) → cong₂ (λ a b → phase ξ (a , b))
       (pullˢ-∘ (σ ⟨$⟩ʳ_) (τ ⟨$⟩ʳ_) α) (pullˢ-id β) })
  (λ w → λ { (α , β) → cong₂ (λ a b → out ξ (σ ⟨$⟩ˡ (τ ⟨$⟩ˡ w)) (a , b))
       (pullˢ-∘ (σ ⟨$⟩ʳ_) (τ ⟨$⟩ʳ_) α) (pullˢ-id β) })

relabel-cong : {σ τ : Permutation n n′} → (∀ i → σ ⟨$⟩ʳ i ≡ τ ⟨$⟩ʳ i) →
               (ξ : PathSum n k m) → relabel σ ξ ≡ᴿ⟨ id ⟩ relabel τ ξ
relabel-cong {σ = σ} {τ} σ≗τ ξ = renamed refl
  (λ { (α , β) → cong₂ (λ a b → phase ξ (a , b))
       (pullˢ-cong σ≗τ α) (pullˢ-id β) })
  (λ w → λ { (α , β) → cong₂ (λ v γ → out ξ v γ) inv⁻¹
       (cong₂ _,_ (pullˢ-cong σ≗τ α) (pullˢ-id β)) })
  where
  -- The inverses agree too.
  inv⁻¹ : ∀ {w} → σ ⟨$⟩ˡ w ≡ τ ⟨$⟩ˡ w
  inv⁻¹ {w} = trans (sym (inverseˡ τ {σ ⟨$⟩ˡ w}))
    (cong (τ ⟨$⟩ˡ_) (trans (sym (σ≗τ (σ ⟨$⟩ˡ w))) (inverseʳ σ)))

-- Relabelling respects equality up to renaming.

relabel-≡ᴿ : (σ : Permutation n n′) {ξ : PathSum n k m}
             {π : Permutation m m′} {ζ : PathSum n k′ m′} →
             ξ ≡ᴿ⟨ π ⟩ ζ → relabel σ ξ ≡ᴿ⟨ π ⟩ relabel σ ζ
relabel-≡ᴿ σ (renamed e ph ou) = renamed e
  (λ { (α , β) → ph (pullˢ (σ ⟨$⟩ʳ_) α , β) })
  (λ w → λ { (α , β) → ou (σ ⟨$⟩ˡ w) (pullˢ (σ ⟨$⟩ʳ_) α , β) })
