------------------------------------------------------------------------
-- Presentations of groups
--
-- Structurally equivalent circuits have the same path-sum, up to
-- renaming the path variables (Amy, QPL 2018, remark 2.8)
--
-- Remark 2.8: "circuits which are equivalent up to symmetric monoidal
-- laws are strictly equal in the path-sum picture."  For circuits
-- over {H, CNOT, R_k, R_k†} written as lists of gates on n wires
-- (PathSum.CRK.Circuit), the laws that can relate two such lists are
-- the interchange law -- two gates on disjoint wires may be applied in
-- either order -- and the symmetry, which here is a relabelling of the
-- wires; associativity and the unit laws are invisible in a list of
-- gates on a fixed set of wires.
--
-- Structural equivalence C ∼ C′ is the congruence on gate lists
-- generated by exchanging adjacent gates on disjoint wires
-- (Disjoint: no wire of one is a wire of the other): the reflexive,
-- symmetric, transitive closure of the exchange, closed under adding a
-- gate in front (∼-cons) and hence under concatenation on either side
-- (∼-++).  Circuits on disjoint wires commute as blocks
-- (∼-parallel), which is bifunctoriality, the first example of the
-- remark, read on circuits.
--
-- The theorem (structural): if C ∼ C′ then ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧ for a
-- bijection π of the path variables read off the derivation -- the
-- same normalisation, and the coefficients of the phase and of every
-- output of ⟦ C′ ⟧ equal, as integers, to those of ⟦ C ⟧ once its
-- path variables are renamed by π (PathSum.Permute).  A fortiori the
-- phases are congruent modulo 2^M and the outputs modulo 2 after the
-- renaming (structural-≈, PathSum.Permute.Sound's ≈ᴿ), and
-- ⟦ C ⟧ ≋ ⟦ C′ ⟧ (structural-≋).  The renaming is the only
-- difference, and it is needed: a Hadamard allocates its path
-- variable at the head, so exchanging two Hadamards exchanges two
-- path variables; exchanging any other pair renames nothing.
--
-- The symmetry: relabelling the wires of a circuit along a bijection
-- σ (relabelC, PathSum.CRK.Trace's mapC) relabels its path-sum
-- (relabel-⟦⟧): ⟦ relabelC σ C ⟧ is ⟦ C ⟧ with input x_i renamed
-- x_(σ i) and the output of wire i moved to wire σ i, coefficient by
-- coefficient, the path variables only re-indexed along
-- paths C ≡ paths (relabelC σ C).  So C ≃⟨ σ ⟩ C′ -- C′ structurally
-- equivalent to C relabelled -- gives relabel σ ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧
-- (structural-≃), and so relabel σ ⟦ C ⟧ ≋ ⟦ C′ ⟧: ⟦ C′ ⟧ is ⟦ C ⟧
-- conjugated by the permutation of the wires
-- (PathSum.Permute.Sound.amp-relabel).
--
-- How the proof goes.  The path-sum of a circuit is read path by path
-- through PathSum.CRK.Trace: along a path, given as a stream s of
-- bits, the phase and the outputs are a configuration that the gates
-- update one at a time, the gate g of g ∷ C reading the bit
-- s (norm C).  Two gates on disjoint wires update the configuration in
-- either order alike (gate-comm).  So a derivation of C ∼ C′ gives a
-- bijection ρ of the bit positions, fixing every position from norm C
-- on (a Reorder), with trace C′ s ≈ trace C (s ∘ ρ) (reorders): the
-- exchange of two Hadamards is the transposition of the two positions
-- they read, the other exchanges the identity.  The trace reads only
-- the first norm C bits (trace-below), so ρ restricts to a bijection
-- of the path variables of ⟦ C ⟧ and ⟦ C′ ⟧ (toPerm), along which
-- their phases take the same values and their outputs the same bits;
-- by Möbius uniqueness (PathSum.Permute.≡ᴿ-by-values) the
-- coefficients agree.  No polynomial is computed or compared.
--
-- How far "strictly equal" goes.  The coefficients agree exactly --
-- the phases as integers, not only modulo 2^M, and the outputs as
-- integers, not only modulo 2 -- but (1) only after renaming the
-- path variables, the bound variables of the sum, which is
-- α-conversion, and the renaming cannot be dropped: H on wire 0 then
-- H on wire 1 against the other order (HH-∼) have phases differing at
-- the coefficient of x₀ y₀ (renaming-needed); (2) coefficient by
-- coefficient, since polynomials are
-- functions and --safe has no function extensionality; (3) with the
-- normalisations and the numbers of path variables equal as numbers,
-- not definitionally (norm-∼, and π itself).
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat.Base using (ℕ; zero; suc)

module PathSum.CRK.Structural (M₀ : ℕ) where

open import Data.Bool.Base using (Bool; true; false; _∧_; _xor_)
open import Data.Fin.Base using (Fin; zero; suc; toℕ; fromℕ<)
open import Data.Fin.Permutation using
  (Permutation; permutation; _⟨$⟩ʳ_; _⟨$⟩ˡ_; inverseˡ; inverseʳ; id; _∘ₚ_)
open import Data.Fin.Properties using (toℕ-injective; toℕ-fromℕ<; toℕ<n)
open import Data.Fin.Subset using (inside; outside)
open import Data.Integer.Base using (ℤ; 0ℤ; 1ℤ; -_; _+_; _*_)
open import Data.Integer.Properties using
  (+-assoc; +-comm; +-identityˡ; *-zeroʳ; *-identityʳ; +-injective)
open import Data.List.Base using (List; []; _∷_; _++_)
open import Data.List.Properties using (++-identityʳ)
open import Data.List.Relation.Unary.All using (All; []; _∷_)
open import Data.Nat.Base using (_<_; _≤_; z≤n; s≤s; s<s⁻¹; _∸_)
  renaming (_+_ to _ℕ+_)
open import Data.Product.Base using (Σ; _,_; proj₁; proj₂)
open import Data.Vec.Base using ([]; _∷_)
open import Relation.Binary.PropositionalEquality using
  (_≡_; _≢_; refl; sym; trans; cong; cong₂; subst; ≢-sym)
open import Relation.Nullary.Decidable using (yes; no)
open import Relation.Nullary.Negation using (¬_)

import Data.List.Relation.Unary.All as All
import Data.Nat.Properties as ℕ

private
  M : ℕ
  M = suc (suc (suc M₀))

open import PathSum.Assign using ([_]ᶻ; _[_≔_]; ≔-there; ≔-comm)
open import PathSum.Base using (PathSum; phase; out)
open import PathSum.CRK.Amp M₀ using (outBit-liftᴸ)
open import PathSum.CRK.Circuit M using
  (Gate; H; CNOT; R; R†; Circuit; norm; paths; ⟦_⟧; paths≡norm; run; init;
   sig)
open import PathSum.CRK.Trace M₀ using
  (Stream; Conf; _≈ᶜ_; conf≈; ≈φ; ≈v; ≈ᶜ-refl; ≈ᶜ-sym; ≈ᶜ-trans; ≔-cong₂;
   gateᶜ; gateᶜ-cong; trace; trace-cong; str; start; eval-⟦⟧; Injective;
   mapC; norm-map; pull; trace-map)
open import PathSum.CRK.Trace M₀ using () renaming (outBit-⟦⟧ to outBit-trace)
open import PathSum.Denotation M₀ using (Assign; _≋_)
open import PathSum.Linear using (eval-liftᴸ)
open import PathSum.Order M using (pow)
open import PathSum.Permute using
  (relabelᴾ; relabel; eval-relabelᴾ; _≡ᴿ⟨_⟩_; phase≡; ≡ᴿ-trans;
   ≡ᴿ-by-values)
open import PathSum.Permute.Sound M₀ using (_≈ᴿ⟨_⟩_; ≡ᴿ⇒≈ᴿ; ≡ᴿ⇒≋)
open import PathSum.Polynomial using (Mon; eval)
open import PathSum.Reduction M using (½)

private
  variable
    n n′ : ℕ


------------------------------------------------------------------------
-- Gates on disjoint wires

-- The wires a gate acts on (PathSum.CRK.Qubits.wiresᶜ, repeated here
-- to keep this module light).

wiresᵍ : Gate n → List (Fin n)
wiresᵍ (H w)        = w ∷ []
wiresᵍ (CNOT c t _) = c ∷ t ∷ []
wiresᵍ (R _ w)      = w ∷ []
wiresᵍ (R† _ w)     = w ∷ []

-- No wire of g is a wire of h.

Disjoint : Gate n → Gate n → Set
Disjoint g h = All (λ u → All (u ≢_) (wiresᵍ h)) (wiresᵍ g)

Disjoint-sym : (g h : Gate n) → Disjoint g h → Disjoint h g
Disjoint-sym g h d =
  All.tabulate (λ v∈h → All.tabulate (λ u∈g eq →
    All.lookup (All.lookup d u∈g) v∈h (sym eq)))


------------------------------------------------------------------------
-- Structural equivalence

-- The congruence generated by exchanging adjacent gates on disjoint
-- wires.

infix 4 _∼_

data _∼_ {n : ℕ} : Circuit n → Circuit n → Set where
  ∼-refl  : {C : Circuit n} → C ∼ C
  ∼-swap  : (g h : Gate n) → Disjoint g h → (D : Circuit n) →
            (g ∷ h ∷ D) ∼ (h ∷ g ∷ D)
  ∼-cons  : (g : Gate n) {C C′ : Circuit n} → C ∼ C′ → (g ∷ C) ∼ (g ∷ C′)
  ∼-sym   : {C C′ : Circuit n} → C ∼ C′ → C′ ∼ C
  ∼-trans : {C C′ C″ : Circuit n} → C ∼ C′ → C′ ∼ C″ → C ∼ C″

-- It is a congruence for concatenation.

∼-++ˡ : {C C′ : Circuit n} (D : Circuit n) → C ∼ C′ → (C ++ D) ∼ (C′ ++ D)
∼-++ˡ D ∼-refl              = ∼-refl
∼-++ˡ D (∼-swap g h dis E)  = ∼-swap g h dis (E ++ D)
∼-++ˡ D (∼-cons g r)        = ∼-cons g (∼-++ˡ D r)
∼-++ˡ D (∼-sym r)           = ∼-sym (∼-++ˡ D r)
∼-++ˡ D (∼-trans r r′)      = ∼-trans (∼-++ˡ D r) (∼-++ˡ D r′)

∼-++ʳ : (C : Circuit n) {D D′ : Circuit n} → D ∼ D′ → (C ++ D) ∼ (C ++ D′)
∼-++ʳ []      r = r
∼-++ʳ (g ∷ C) r = ∼-cons g (∼-++ʳ C r)

∼-++ : {C C′ D D′ : Circuit n} → C ∼ C′ → D ∼ D′ → (C ++ D) ∼ (C′ ++ D′)
∼-++ {C′ = C′} {D = D} r r′ = ∼-trans (∼-++ˡ D r) (∼-++ʳ C′ r′)

-- Circuits on disjoint wires commute as blocks: bifunctoriality.

Apart : Circuit n → Circuit n → Set
Apart C D = All (λ g → All (Disjoint g) D) C

private
  -- A gate disjoint from every gate of D passes through D.
  pass : (g : Gate n) (D E : Circuit n) → All (Disjoint g) D →
         (g ∷ (D ++ E)) ∼ (D ++ (g ∷ E))
  pass g []      E []         = ∼-refl
  pass g (h ∷ D) E (d ∷ ds) =
    ∼-trans (∼-swap g h d (D ++ E)) (∼-cons h (pass g D E ds))

∼-parallel : (C D : Circuit n) → Apart C D → (C ++ D) ∼ (D ++ C)
∼-parallel []      D []         =
  subst (D ∼_) (sym (++-identityʳ D)) ∼-refl
∼-parallel (g ∷ C) D (dg ∷ ds) =
  ∼-trans (∼-cons g (∼-parallel C D ds)) (pass g D C dg)

-- Structurally equivalent circuits have the same normalisation.

private
  norm-∷ : (g : Gate n) (C : Circuit n) → norm (g ∷ C) ≡ norm (g ∷ []) ℕ+ norm C
  norm-∷ (H _)        C = refl
  norm-∷ (CNOT _ _ _) C = refl
  norm-∷ (R _ _)      C = refl
  norm-∷ (R† _ _)     C = refl

norm-∼ : {C C′ : Circuit n} → C ∼ C′ → norm C ≡ norm C′
norm-∼ ∼-refl = refl
norm-∼ (∼-swap g h dis D) =
  trans (norm-∷ g (h ∷ D))
  (trans (cong (norm (g ∷ []) ℕ+_) (norm-∷ h D))
  (trans (sym (ℕ.+-assoc (norm (g ∷ [])) (norm (h ∷ [])) (norm D)))
  (trans (cong (_ℕ+ norm D) (ℕ.+-comm (norm (g ∷ [])) (norm (h ∷ []))))
  (trans (ℕ.+-assoc (norm (h ∷ [])) (norm (g ∷ [])) (norm D))
  (trans (cong (norm (h ∷ []) ℕ+_) (sym (norm-∷ g D)))
         (sym (norm-∷ h (g ∷ D))))))))
norm-∼ (∼-cons g {C} {C′} r) =
  trans (norm-∷ g C) (trans (cong (norm (g ∷ []) ℕ+_) (norm-∼ r))
                            (sym (norm-∷ g C′)))
norm-∼ (∼-sym r)       = sym (norm-∼ r)
norm-∼ (∼-trans r r′)  = trans (norm-∼ r) (norm-∼ r′)


------------------------------------------------------------------------
-- Gates on disjoint wires commute on configurations

private
  -- Two increments of the phase, in either order.
  swap+ : ∀ φ x y x′ y′ → x ≡ x′ → y ≡ y′ → (φ + x) + y ≡ (φ + y′) + x′
  swap+ φ x y _ _ refl refl =
    trans (+-assoc φ x y)
          (trans (cong (φ +_) (+-comm x y)) (sym (+-assoc φ y x)))

  -- The ten pairs up to order.  A gate reads only its own wires, and
  -- writes only its target (a Hadamard and CNOT) or nothing.

  comm-HH : (w u : Fin n) → w ≢ u → ∀ b b′ (a : Conf n) →
            gateᶜ (H u) b′ (gateᶜ (H w) b a) ≈ᶜ gateᶜ (H w) b (gateᶜ (H u) b′ a)
  comm-HH w u w≢u b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ) (½ * [ (v [ w ≔ b ]) u ∧ b′ ]ᶻ)
             (½ * [ (v [ u ≔ b′ ]) w ∧ b ]ᶻ) (½ * [ v u ∧ b′ ]ᶻ)
             (cong (λ c → ½ * [ c ∧ b ]ᶻ) (sym (≔-there v b′ w≢u)))
             (cong (λ c → ½ * [ c ∧ b′ ]ᶻ) (≔-there v b (≢-sym w≢u))))
    (≔-comm v b b′ w≢u)

  comm-HC : (w c t : Fin n) (p : c ≢ t) → w ≢ c → w ≢ t → ∀ b b′ (a : Conf n) →
            gateᶜ (CNOT c t p) b′ (gateᶜ (H w) b a) ≈ᶜ
            gateᶜ (H w) b (gateᶜ (CNOT c t p) b′ a)
  comm-HC w c t p w≢c w≢t b b′ (φ , v) = conf≈
    (cong (λ e → φ + ½ * [ e ∧ b ]ᶻ) (sym (≔-there v (v t xor v c) w≢t)))
    (λ j → trans
      (≔-cong₂ {z = v [ w ≔ b ]} {z′ = v [ w ≔ b ]} t
               {b = (v [ w ≔ b ]) t xor (v [ w ≔ b ]) c} {b′ = v t xor v c}
               (cong₂ _xor_ (≔-there v b (≢-sym w≢t))
                            (≔-there v b (≢-sym w≢c)))
               (λ _ → refl) j)
      (≔-comm v b (v t xor v c) w≢t j))

  comm-HR : (w : Fin n) (k : ℕ) (u : Fin n) → w ≢ u → ∀ b b′ (a : Conf n) →
            gateᶜ (R k u) b′ (gateᶜ (H w) b a) ≈ᶜ gateᶜ (H w) b (gateᶜ (R k u) b′ a)
  comm-HR w k u w≢u b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ) (pow (M ∸ k) * [ (v [ w ≔ b ]) u ]ᶻ)
             (½ * [ v w ∧ b ]ᶻ) (pow (M ∸ k) * [ v u ]ᶻ)
             refl (cong (λ c → pow (M ∸ k) * [ c ]ᶻ)
                        (≔-there v b (≢-sym w≢u))))
    (λ _ → refl)

  comm-HR† : (w : Fin n) (k : ℕ) (u : Fin n) → w ≢ u → ∀ b b′ (a : Conf n) →
             gateᶜ (R† k u) b′ (gateᶜ (H w) b a) ≈ᶜ
             gateᶜ (H w) b (gateᶜ (R† k u) b′ a)
  comm-HR† w k u w≢u b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ) (- (pow (M ∸ k) * [ (v [ w ≔ b ]) u ]ᶻ))
             (½ * [ v w ∧ b ]ᶻ) (- (pow (M ∸ k) * [ v u ]ᶻ))
             refl (cong (λ c → - (pow (M ∸ k) * [ c ]ᶻ))
                        (≔-there v b (≢-sym w≢u))))
    (λ _ → refl)

  comm-CC : (c t : Fin n) (p : c ≢ t) (c′ t′ : Fin n) (p′ : c′ ≢ t′) →
            c ≢ t′ → t ≢ c′ → t ≢ t′ → ∀ b b′ (a : Conf n) →
            gateᶜ (CNOT c′ t′ p′) b′ (gateᶜ (CNOT c t p) b a) ≈ᶜ
            gateᶜ (CNOT c t p) b (gateᶜ (CNOT c′ t′ p′) b′ a)
  comm-CC c t p c′ t′ p′ c≢t′ t≢c′ t≢t′ b b′ (φ , v) = conf≈ refl (λ j →
    trans
      (≔-cong₂ {z = v₁} {z′ = v₁} t′ {b = v₁ t′ xor v₁ c′}
               {b′ = v t′ xor v c′}
               (cong₂ _xor_ (≔-there v (v t xor v c) (≢-sym t≢t′))
                            (≔-there v (v t xor v c) (≢-sym t≢c′)))
               (λ _ → refl) j)
    (trans (≔-comm v (v t xor v c) (v t′ xor v c′) t≢t′ j)
           (≔-cong₂ {z = v₂} {z′ = v₂} t {b = v t xor v c}
                    {b′ = v₂ t xor v₂ c}
                    (sym (cong₂ _xor_ (≔-there v (v t′ xor v c′) t≢t′)
                                      (≔-there v (v t′ xor v c′) c≢t′)))
                    (λ _ → refl) j)))
    where
    v₁ v₂ : Fin _ → Bool
    v₁ = v [ t ≔ v t xor v c ]
    v₂ = v [ t′ ≔ v t′ xor v c′ ]

  comm-CR : (c t : Fin n) (p : c ≢ t) (k : ℕ) (u : Fin n) → t ≢ u →
            ∀ b b′ (a : Conf n) →
            gateᶜ (R k u) b′ (gateᶜ (CNOT c t p) b a) ≈ᶜ
            gateᶜ (CNOT c t p) b (gateᶜ (R k u) b′ a)
  comm-CR c t p k u t≢u b b′ (φ , v) = conf≈
    (cong (λ e → φ + pow (M ∸ k) * [ e ]ᶻ)
          (≔-there v (v t xor v c) (≢-sym t≢u)))
    (λ _ → refl)

  comm-CR† : (c t : Fin n) (p : c ≢ t) (k : ℕ) (u : Fin n) → t ≢ u →
             ∀ b b′ (a : Conf n) →
             gateᶜ (R† k u) b′ (gateᶜ (CNOT c t p) b a) ≈ᶜ
             gateᶜ (CNOT c t p) b (gateᶜ (R† k u) b′ a)
  comm-CR† c t p k u t≢u b b′ (φ , v) = conf≈
    (cong (λ e → φ + - (pow (M ∸ k) * [ e ]ᶻ))
          (≔-there v (v t xor v c) (≢-sym t≢u)))
    (λ _ → refl)

  comm-RR : (k : ℕ) (w : Fin n) (k′ : ℕ) (u : Fin n) → ∀ b b′ (a : Conf n) →
            gateᶜ (R k′ u) b′ (gateᶜ (R k w) b a) ≈ᶜ
            gateᶜ (R k w) b (gateᶜ (R k′ u) b′ a)
  comm-RR k w k′ u b b′ (φ , v) = conf≈
    (swap+ φ (pow (M ∸ k) * [ v w ]ᶻ) (pow (M ∸ k′) * [ v u ]ᶻ)
             (pow (M ∸ k) * [ v w ]ᶻ) (pow (M ∸ k′) * [ v u ]ᶻ) refl refl)
    (λ _ → refl)

  comm-RR† : (k : ℕ) (w : Fin n) (k′ : ℕ) (u : Fin n) → ∀ b b′ (a : Conf n) →
             gateᶜ (R† k′ u) b′ (gateᶜ (R k w) b a) ≈ᶜ
             gateᶜ (R k w) b (gateᶜ (R† k′ u) b′ a)
  comm-RR† k w k′ u b b′ (φ , v) = conf≈
    (swap+ φ (pow (M ∸ k) * [ v w ]ᶻ) (- (pow (M ∸ k′) * [ v u ]ᶻ))
             (pow (M ∸ k) * [ v w ]ᶻ) (- (pow (M ∸ k′) * [ v u ]ᶻ)) refl refl)
    (λ _ → refl)

  comm-R†R† : (k : ℕ) (w : Fin n) (k′ : ℕ) (u : Fin n) → ∀ b b′ (a : Conf n) →
              gateᶜ (R† k′ u) b′ (gateᶜ (R† k w) b a) ≈ᶜ
              gateᶜ (R† k w) b (gateᶜ (R† k′ u) b′ a)
  comm-R†R† k w k′ u b b′ (φ , v) = conf≈
    (swap+ φ (- (pow (M ∸ k) * [ v w ]ᶻ)) (- (pow (M ∸ k′) * [ v u ]ᶻ))
             (- (pow (M ∸ k) * [ v w ]ᶻ)) (- (pow (M ∸ k′) * [ v u ]ᶻ))
             refl refl)
    (λ _ → refl)

-- Gates on disjoint wires update a configuration alike in either
-- order.

gate-comm : (g h : Gate n) → Disjoint g h → ∀ b b′ (a : Conf n) →
            gateᶜ h b′ (gateᶜ g b a) ≈ᶜ gateᶜ g b (gateᶜ h b′ a)
gate-comm (H w) (H u) ((w≢u ∷ []) ∷ []) = comm-HH w u w≢u
gate-comm (H w) (CNOT c t p) ((w≢c ∷ w≢t ∷ []) ∷ []) =
  comm-HC w c t p w≢c w≢t
gate-comm (H w) (R k u) ((w≢u ∷ []) ∷ []) = comm-HR w k u w≢u
gate-comm (H w) (R† k u) ((w≢u ∷ []) ∷ []) = comm-HR† w k u w≢u
gate-comm (CNOT c t p) (H u) ((c≢u ∷ []) ∷ (t≢u ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-HC u c t p (≢-sym c≢u) (≢-sym t≢u) b′ b a)
gate-comm (CNOT c t p) (CNOT c′ t′ p′)
          ((c≢c′ ∷ c≢t′ ∷ []) ∷ (t≢c′ ∷ t≢t′ ∷ []) ∷ []) =
  comm-CC c t p c′ t′ p′ c≢t′ t≢c′ t≢t′
gate-comm (CNOT c t p) (R k u) (_ ∷ (t≢u ∷ []) ∷ []) = comm-CR c t p k u t≢u
gate-comm (CNOT c t p) (R† k u) (_ ∷ (t≢u ∷ []) ∷ []) =
  comm-CR† c t p k u t≢u
gate-comm (R k w) (H u) ((w≢u ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-HR u k w (≢-sym w≢u) b′ b a)
gate-comm (R k w) (CNOT c t p) ((_ ∷ w≢t ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-CR c t p k w (≢-sym w≢t) b′ b a)
gate-comm (R k w) (R k′ u) _ = comm-RR k w k′ u
gate-comm (R k w) (R† k′ u) _ = comm-RR† k w k′ u
gate-comm (R† k w) (H u) ((w≢u ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-HR† u k w (≢-sym w≢u) b′ b a)
gate-comm (R† k w) (CNOT c t p) ((_ ∷ w≢t ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-CR† c t p k w (≢-sym w≢t) b′ b a)
gate-comm (R† k w) (R k′ u) _ b b′ a = ≈ᶜ-sym (comm-RR† k′ u k w b′ b a)
gate-comm (R† k w) (R† k′ u) _ = comm-R†R† k w k′ u


------------------------------------------------------------------------
-- Reordering the bits of a path

-- A bijection of the bit positions that fixes every position from N
-- on: the bits a circuit with N Hadamards reads, permuted.

record Reorder (N : ℕ) : Set where
  field
    fwd bwd : ℕ → ℕ
    bwd-fwd : ∀ i → bwd (fwd i) ≡ i
    fwd-bwd : ∀ i → fwd (bwd i) ≡ i
    fwd-fix : ∀ i → N ≤ i → fwd i ≡ i
    fwd-<   : ∀ i → i < N → fwd i < N
    bwd-<   : ∀ i → i < N → bwd i < N

open Reorder public

bwd-fix : ∀ {N} (ρ : Reorder N) i → N ≤ i → bwd ρ i ≡ i
bwd-fix ρ i N≤i = trans (cong (bwd ρ) (sym (fwd-fix ρ i N≤i))) (bwd-fwd ρ i)

-- The identity, the inverse, the composite, and the same bijection
-- seen with a larger bound.

reorder-id : ∀ {N} → Reorder N
reorder-id = record
  { fwd = λ i → i ; bwd = λ i → i
  ; bwd-fwd = λ _ → refl ; fwd-bwd = λ _ → refl
  ; fwd-fix = λ _ _ → refl ; fwd-< = λ _ i< → i< ; bwd-< = λ _ i< → i< }

reorder-inv : ∀ {N} → Reorder N → Reorder N
reorder-inv ρ = record
  { fwd = bwd ρ ; bwd = fwd ρ
  ; bwd-fwd = fwd-bwd ρ ; fwd-bwd = bwd-fwd ρ
  ; fwd-fix = bwd-fix ρ ; fwd-< = bwd-< ρ ; bwd-< = fwd-< ρ }

-- First ρ₁, then ρ₂: the stream read through ρ₂, then through ρ₁.

reorder-⨾ : ∀ {N} → Reorder N → Reorder N → Reorder N
reorder-⨾ ρ₁ ρ₂ = record
  { fwd = λ i → fwd ρ₂ (fwd ρ₁ i) ; bwd = λ i → bwd ρ₁ (bwd ρ₂ i)
  ; bwd-fwd = λ i → trans (cong (bwd ρ₁) (bwd-fwd ρ₂ (fwd ρ₁ i)))
                          (bwd-fwd ρ₁ i)
  ; fwd-bwd = λ i → trans (cong (fwd ρ₂) (fwd-bwd ρ₁ (bwd ρ₂ i)))
                          (fwd-bwd ρ₂ i)
  ; fwd-fix = λ i N≤i → trans (cong (fwd ρ₂) (fwd-fix ρ₁ i N≤i))
                              (fwd-fix ρ₂ i N≤i)
  ; fwd-< = λ i i< → fwd-< ρ₂ (fwd ρ₁ i) (fwd-< ρ₁ i i<)
  ; bwd-< = λ i i< → bwd-< ρ₁ (bwd ρ₂ i) (bwd-< ρ₂ i i<) }

reorder-weaken : ∀ {N N′} → N ≤ N′ → Reorder N → Reorder N′
reorder-weaken {N} {N′} N≤N′ ρ = record
  { fwd = fwd ρ ; bwd = bwd ρ
  ; bwd-fwd = bwd-fwd ρ ; fwd-bwd = fwd-bwd ρ
  ; fwd-fix = λ i N′≤i → fwd-fix ρ i (ℕ.≤-trans N≤N′ N′≤i)
  ; fwd-< = λ i i< → bound (fwd ρ) (fwd-fix ρ) (fwd-< ρ) i i<
  ; bwd-< = λ i i< → bound (bwd ρ) (bwd-fix ρ) (bwd-< ρ) i i< }
  where
  bound : (f : ℕ → ℕ) → (∀ i → N ≤ i → f i ≡ i) → (∀ i → i < N → f i < N) →
          ∀ i → i < N′ → f i < N′
  bound f fix lt i i<N′ with i ℕ.<? N
  ... | yes i<N = ℕ.<-≤-trans (lt i i<N) N≤N′
  ... | no  i≮N = subst (_< N′) (sym (fix i (ℕ.≮⇒≥ i≮N))) i<N′

-- (The bijection itself is unchanged, definitionally, so that the
-- traces it reorders compare without unfolding a transport.)

reorder-cast : ∀ {N N′} → N ≡ N′ → Reorder N → Reorder N′
reorder-cast e = reorder-weaken (ℕ.≤-reflexive e)

-- The exchange of the positions d and d + 1.

private
  tr : ℕ → ℕ → ℕ
  tr zero    zero          = 1
  tr zero    (suc zero)    = 0
  tr zero    (suc (suc i)) = suc (suc i)
  tr (suc d) zero          = zero
  tr (suc d) (suc i)       = suc (tr d i)

  tr-inv : ∀ d i → tr d (tr d i) ≡ i
  tr-inv zero    zero          = refl
  tr-inv zero    (suc zero)    = refl
  tr-inv zero    (suc (suc i)) = refl
  tr-inv (suc d) zero          = refl
  tr-inv (suc d) (suc i)       = cong suc (tr-inv d i)

  tr-fix : ∀ d i → suc (suc d) ≤ i → tr d i ≡ i
  tr-fix zero    (suc (suc i)) _         = refl
  tr-fix zero    (suc zero)    (s≤s ())
  tr-fix (suc d) (suc i)       (s≤s le)  = cong suc (tr-fix d i le)

  tr-< : ∀ d i → i < suc (suc d) → tr d i < suc (suc d)
  tr-< zero    zero          _         = s≤s (s≤s z≤n)
  tr-< zero    (suc zero)    _         = s≤s z≤n
  tr-< zero    (suc (suc i)) (s≤s (s≤s ()))
  tr-< (suc d) zero          _         = s≤s z≤n
  tr-< (suc d) (suc i)       (s≤s le)  = s≤s (tr-< d i le)

  tr-below : ∀ d i → i < d → tr d i ≡ i
  tr-below (suc d) zero    _        = refl
  tr-below (suc d) (suc i) (s≤s le) = cong suc (tr-below d i le)

  tr-d : ∀ d → tr d d ≡ suc d
  tr-d zero    = refl
  tr-d (suc d) = cong suc (tr-d d)

  tr-sd : ∀ d → tr d (suc d) ≡ d
  tr-sd zero    = refl
  tr-sd (suc d) = cong suc (tr-sd d)

reorder-swap : ∀ d → Reorder (suc (suc d))
reorder-swap d = record
  { fwd = tr d ; bwd = tr d
  ; bwd-fwd = tr-inv d ; fwd-bwd = tr-inv d
  ; fwd-fix = tr-fix d ; fwd-< = tr-< d ; bwd-< = tr-< d }


------------------------------------------------------------------------
-- Traces of structurally equivalent circuits

-- A trace reads only the first norm C bits of its stream.

trace-below : (C : Circuit n) {s s′ : Stream} {a a′ : Conf n} →
              (∀ i → i < norm C → s i ≡ s′ i) → a ≈ᶜ a′ →
              trace C s a ≈ᶜ trace C s′ a′
trace-below []              h a≈ = a≈
trace-below (H w ∷ C)       h a≈ =
  trace-below C (λ i i< → h i (ℕ.m<n⇒m<1+n i<))
              (gateᶜ-cong (H w) (h (norm C) (ℕ.n<1+n (norm C))) a≈)
trace-below (CNOT c t p ∷ C) {s} h a≈ =
  trace-below C h (gateᶜ-cong (CNOT c t p) {s (norm C)} {s (norm C)} refl a≈)
trace-below (R k w ∷ C)     {s} h a≈ =
  trace-below C h (gateᶜ-cong (R k w) {s (norm C)} {s (norm C)} refl a≈)
trace-below (R† k w ∷ C)    {s} h a≈ =
  trace-below C h (gateᶜ-cong (R† k w) {s (norm C)} {s (norm C)} refl a≈)

-- C ∼ C′ gives a reordering ρ of the bits with trace C′ s ≈ trace C
-- (s ∘ ρ).

Reorders : Circuit n → Circuit n → Set
Reorders C C′ =
  Σ (Reorder (norm C)) (λ ρ → ∀ s a → trace C′ s a ≈ᶜ trace C (λ i → s (fwd ρ i)) a)

private
  -- Exchanging two gates of which at most one is a Hadamard reorders
  -- nothing: the Hadamard reads the same bit either way, and the other
  -- gate reads none.
  plain : (g h : Gate n) (D : Circuit n) →
          (∀ (s : Stream) a →
             gateᶜ g (s (norm D)) (gateᶜ h (s (norm (g ∷ D))) a) ≈ᶜ
             gateᶜ h (s (norm D)) (gateᶜ g (s (norm (h ∷ D))) a)) →
          Reorders (g ∷ h ∷ D) (h ∷ g ∷ D)
  plain g h D eq = reorder-id , λ s a → trace-cong D (λ _ → refl) (eq s a)

  plain′ : (g h : Gate n) (dis : Disjoint g h) (D : Circuit n) →
           Reorders (g ∷ h ∷ D) (h ∷ g ∷ D)
  plain′ (H w) (H u) dis D = reorder-swap (norm D) , λ s a →
    ≈ᶜ-trans
      (trace-cong D (λ _ → refl)
        (≈ᶜ-sym (gate-comm (H w) (H u) dis (s (norm D)) (s (suc (norm D))) a)))
      (trace-below D (λ i i< → cong s (sym (tr-below (norm D) i i<)))
        (gateᶜ-cong (H u) (cong s (sym (tr-d (norm D))))
          (gateᶜ-cong (H w) (cong s (sym (tr-sd (norm D)))) (≈ᶜ-refl {a = a}))))
  plain′ g@(H _) h@(CNOT _ _ _) dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(H _) h@(R _ _) dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(H _) h@(R† _ _) dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(CNOT _ _ _) h dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(R _ _) h dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(R† _ _) h dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)

reorders : {C C′ : Circuit n} → C ∼ C′ → Reorders C C′
reorders ∼-refl = reorder-id , λ s a → ≈ᶜ-refl
reorders (∼-swap g h dis D) = plain′ g h dis D
reorders (∼-cons g {C} {C′} r) =
  reorder-weaken (≤-norm g C) ρ , λ s a →
    ≈ᶜ-trans (T s (gateᶜ g (s (norm C′)) a))
             (trace-cong C (λ _ → refl)
               (gateᶜ-cong g (cong s (trans (sym (norm-∼ r))
                                            (sym (fwd-fix ρ (norm C) ℕ.≤-refl))))
                           ≈ᶜ-refl))
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)

  ≤-norm : (g : Gate n) (C : Circuit n) → norm C ≤ norm (g ∷ C)
  ≤-norm (H _)        C = ℕ.n≤1+n (norm C)
  ≤-norm (CNOT _ _ _) C = ℕ.≤-refl
  ≤-norm (R _ _)      C = ℕ.≤-refl
  ≤-norm (R† _ _)     C = ℕ.≤-refl
reorders (∼-sym {C} {C′} r) =
  reorder-cast (norm-∼ r) (reorder-inv ρ) , λ s a →
    ≈ᶜ-sym (≈ᶜ-trans (T (λ i → s (bwd ρ i)) a)
                     (trace-cong C (λ i → cong s (bwd-fwd ρ i)) ≈ᶜ-refl))
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)
reorders (∼-trans {C} {C′} {C″} r₁ r₂) =
  reorder-⨾ ρ₁ (reorder-cast (sym (norm-∼ r₁)) ρ₂) , λ s a →
    ≈ᶜ-trans (T₂ s a) (T₁ (λ i → s (fwd ρ₂ i)) a)
  where
  ρ₁ = proj₁ (reorders r₁)
  T₁ = proj₂ (reorders r₁)
  ρ₂ = proj₁ (reorders r₂)
  T₂ = proj₂ (reorders r₂)


------------------------------------------------------------------------
-- From reordered bits to renamed path variables

-- A reordering of the first N bits, read as a bijection between the
-- path variables of two path-sums with N of them each.

toPerm : ∀ {K K′ N} → K ≡ N → K′ ≡ N → Reorder N → Permutation K K′
toPerm refl refl ρ = permutation f g f∘g g∘f
  where
  f g : Fin _ → Fin _
  f j = fromℕ< (fwd-< ρ (toℕ j) (toℕ<n j))
  g j = fromℕ< (bwd-< ρ (toℕ j) (toℕ<n j))

  f∘g : ∀ j → f (g j) ≡ j
  f∘g j = toℕ-injective (trans (toℕ-fromℕ< _)
    (trans (cong (fwd ρ) (toℕ-fromℕ< _)) (fwd-bwd ρ (toℕ j))))

  g∘f : ∀ j → g (f j) ≡ j
  g∘f j = toℕ-injective (trans (toℕ-fromℕ< _)
    (trans (cong (bwd ρ) (toℕ-fromℕ< _)) (bwd-fwd ρ (toℕ j))))

toℕ-toPerm : ∀ {K K′ N} (eK : K ≡ N) (eK′ : K′ ≡ N) (ρ : Reorder N)
             (j : Fin K) → toℕ (toPerm eK eK′ ρ ⟨$⟩ʳ j) ≡ fwd ρ (toℕ j)
toℕ-toPerm refl refl ρ j = toℕ-fromℕ< _

-- A path read as a stream: its bit i is the path's variable i.

private
  str-at : ∀ {K} (y : Assign K) i (i<K : i < K) → str y i ≡ y (fromℕ< i<K)
  str-at {suc K} y zero    _   = refl
  str-at {suc K} y (suc i) i<K = str-at (λ j → y (suc j)) i (s<s⁻¹ i<K)

-- Below N, the stream of a path read through toPerm ρ is the stream
-- of the path, read through ρ.

str-toPerm : ∀ {K K′ N} (eK : K ≡ N) (eK′ : K′ ≡ N) (ρ : Reorder N)
             (y : Assign K′) i → i < N →
             str (λ j → y (toPerm eK eK′ ρ ⟨$⟩ʳ j)) i ≡ str y (fwd ρ i)
str-toPerm {N = N} refl refl ρ y i i<N =
  trans (str-at (λ j → y (toPerm refl refl ρ ⟨$⟩ʳ j)) i i<N)
  (trans (cong y (toℕ-injective
           (trans (toℕ-toPerm refl refl ρ (fromℕ< i<N))
           (trans (cong (fwd ρ) (toℕ-fromℕ< i<N))
                  (sym (toℕ-fromℕ< (fwd-< ρ i i<N)))))))
         (sym (str-at y (fwd ρ i) (fwd-< ρ i i<N))))

-- The outputs of ⟦ C ⟧ along a path: lifted forms, whose values are
-- the bits the trace leaves on the wires.

eval-out : (C : Circuit n) (x : Assign n) (y : Assign (paths C)) (w : Fin n) →
           eval (out ⟦ C ⟧ w) x y ≡ [ proj₂ (trace C (str y) (start x)) w ]ᶻ
eval-out {n} C x y w =
  trans (eval-liftᴸ (sig r w) x y)
        (cong [_]ᶻ (trans (sym (outBit-liftᴸ ⟦ C ⟧ x y w (sig r w) refl))
                          (outBit-trace C x y w)))
  where
  r = proj₂ (run C (init {n}))


------------------------------------------------------------------------
-- The theorem

-- Structurally equivalent circuits have path-sums equal up to a
-- renaming of the path variables: the same normalisation, and the
-- coefficients of the phase and of every output equal as integers.

structural : {C C′ : Circuit n} → C ∼ C′ →
             Σ (Permutation (paths C) (paths C′))
               (λ π → ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧)
structural {C = C} {C′} r =
  π , ≡ᴿ-by-values ⟦ C ⟧ ⟦ C′ ⟧ π (norm-∼ r) ph ou
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)

  eK  = paths≡norm C
  eK′ = trans (paths≡norm C′) (sym (norm-∼ r))

  π : Permutation (paths C) (paths C′)
  π = toPerm eK eK′ ρ

  conf : ∀ x (y : Assign (paths C′)) →
         trace C (str (λ j → y (π ⟨$⟩ʳ j))) (start x) ≈ᶜ
         trace C′ (str y) (start x)
  conf x y = ≈ᶜ-trans (trace-below C (str-toPerm eK eK′ ρ y) ≈ᶜ-refl)
                      (≈ᶜ-sym (T (str y) (start x)))

  ph : ∀ x y → eval (phase ⟦ C ⟧) x (λ j → y (π ⟨$⟩ʳ j)) ≡
               eval (phase ⟦ C′ ⟧) x y
  ph x y = trans (eval-⟦⟧ C x (λ j → y (π ⟨$⟩ʳ j)))
                 (trans (≈φ (conf x y)) (sym (eval-⟦⟧ C′ x y)))

  ou : ∀ w x y → eval (out ⟦ C ⟧ w) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                 eval (out ⟦ C′ ⟧ w) x y
  ou w x y = trans (eval-out C x (λ j → y (π ⟨$⟩ʳ j)) w)
                   (trans (cong [_]ᶻ (≈v (conf x y) w))
                          (sym (eval-out C′ x y w)))

-- In particular, in the form PathSum.Congruence reads path-sums: the
-- same normalisation, phases congruent modulo 2^M and outputs modulo
-- 2, coefficient by coefficient, after the renaming.

structural-≈ : {C C′ : Circuit n} → C ∼ C′ →
               Σ (Permutation (paths C) (paths C′))
                 (λ π → ⟦ C ⟧ ≈ᴿ⟨ π ⟩ ⟦ C′ ⟧)
structural-≈ r = proj₁ (structural r) , ≡ᴿ⇒≈ᴿ (proj₂ (structural r))

-- Hence they are equivalent.

structural-≋ : {C C′ : Circuit n} → C ∼ C′ → ⟦ C ⟧ ≋ ⟦ C′ ⟧
structural-≋ {C = C} {C′} r =
  ≡ᴿ⇒≋ {ξ = ⟦ C ⟧} {π = proj₁ (structural r)} {ζ = ⟦ C′ ⟧}
       (proj₂ (structural r))

-- In particular, circuits on disjoint wires may be run in either
-- order: the bifunctoriality law of remark 2.8, for circuits.

parallel-⟦⟧ : (C D : Circuit n) → Apart C D →
              Σ (Permutation (paths (C ++ D)) (paths (D ++ C)))
                (λ π → ⟦ C ++ D ⟧ ≡ᴿ⟨ π ⟩ ⟦ D ++ C ⟧)
parallel-⟦⟧ C D ap = structural (∼-parallel C D ap)


------------------------------------------------------------------------
-- Relabelling the wires

-- A circuit moved along a bijection of the wires.

private
  injective : (σ : Permutation n n′) → Injective (σ ⟨$⟩ʳ_)
  injective σ {a} {b} eq =
    trans (sym (inverseˡ σ {a})) (trans (cong (σ ⟨$⟩ˡ_) eq) (inverseˡ σ {b}))

relabelC : Permutation n n′ → Circuit n → Circuit n′
relabelC σ = mapC (σ ⟨$⟩ʳ_) (injective σ)

-- Relabelling does not change the Hadamards, so the path variables
-- correspond one to one, in order: the renaming paths-cast is the
-- identity on indices (toℕ-paths-cast).

paths-cast : (σ : Permutation n n′) (C : Circuit n) →
             Permutation (paths C) (paths (relabelC σ C))
paths-cast σ C =
  toPerm (paths≡norm C)
         (trans (paths≡norm (relabelC σ C))
                (norm-map (σ ⟨$⟩ʳ_) (injective σ) C))
         reorder-id

toℕ-paths-cast : (σ : Permutation n n′) (C : Circuit n)
                 (j : Fin (paths C)) →
                 toℕ (paths-cast σ C ⟨$⟩ʳ j) ≡ toℕ j
toℕ-paths-cast σ C j =
  toℕ-toPerm (paths≡norm C)
             (trans (paths≡norm (relabelC σ C))
                    (norm-map (σ ⟨$⟩ʳ_) (injective σ) C))
             reorder-id j

-- The path-sum of a relabelled circuit is the relabelled path-sum:
-- input x_i renamed x_(σ i), the output of wire i moved to wire σ i,
-- coefficient by coefficient.  This is the naturality of the
-- symmetry for circuits: moving a circuit along a permutation of the
-- wires conjugates its operator by that permutation.

relabel-⟦⟧ : (σ : Permutation n n′) (C : Circuit n) →
             relabel σ ⟦ C ⟧ ≡ᴿ⟨ paths-cast σ C ⟩ ⟦ relabelC σ C ⟧
relabel-⟦⟧ {n} {n′} σ C =
  ≡ᴿ-by-values (relabel σ ⟦ C ⟧) ⟦ relabelC σ C ⟧ π
    (sym (norm-map (σ ⟨$⟩ʳ_) (injective σ) C)) ph ou
  where
  eK  = paths≡norm C
  eK′ = trans (paths≡norm (relabelC σ C))
              (norm-map (σ ⟨$⟩ʳ_) (injective σ) C)

  π : Permutation (paths C) (paths (relabelC σ C))
  π = paths-cast σ C

  xσ : Assign n′ → Assign n
  xσ x i = x (σ ⟨$⟩ʳ i)

  conf : ∀ (x : Assign n′) (y : Assign (paths (relabelC σ C))) →
         trace C (str (λ j → y (π ⟨$⟩ʳ j))) (start (xσ x)) ≈ᶜ
         pull (σ ⟨$⟩ʳ_) (trace (relabelC σ C) (str y) (start x))
  conf x y =
    ≈ᶜ-trans (trace-below C (str-toPerm eK eK′ reorder-id y) ≈ᶜ-refl)
             (≈ᶜ-sym (trace-map (σ ⟨$⟩ʳ_) (injective σ) C (str y) (start x)))

  ph : ∀ x y → eval (phase (relabel σ ⟦ C ⟧)) x (λ j → y (π ⟨$⟩ʳ j)) ≡
               eval (phase ⟦ relabelC σ C ⟧) x y
  ph x y = trans (eval-relabelᴾ σ (phase ⟦ C ⟧) x (λ j → y (π ⟨$⟩ʳ j)))
    (trans (eval-⟦⟧ C (xσ x) (λ j → y (π ⟨$⟩ʳ j)))
    (trans (≈φ (conf x y)) (sym (eval-⟦⟧ (relabelC σ C) x y))))

  ou : ∀ w x y → eval (out (relabel σ ⟦ C ⟧) w) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                 eval (out ⟦ relabelC σ C ⟧ w) x y
  ou w x y =
    trans (eval-relabelᴾ σ (out ⟦ C ⟧ (σ ⟨$⟩ˡ w)) x (λ j → y (π ⟨$⟩ʳ j)))
    (trans (eval-out C (xσ x) (λ j → y (π ⟨$⟩ʳ j)) (σ ⟨$⟩ˡ w))
    (trans (cong [_]ᶻ (trans (≈v (conf x y) (σ ⟨$⟩ˡ w))
             (cong (proj₂ (trace (relabelC σ C) (str y) (start x)))
                   (inverseʳ σ))))
           (sym (eval-out (relabelC σ C) x y w))))

-- C ≃⟨ σ ⟩ C′: C′ is C with its wires relabelled along σ, up to
-- structural equivalence.

infix 4 _≃⟨_⟩_

-- (A record, so that C, σ and C′ can be read off its type.)

record _≃⟨_⟩_ (C : Circuit n) (σ : Permutation n n′) (C′ : Circuit n′) :
              Set where
  constructor relabelled
  field
    up-to : relabelC σ C ∼ C′

open _≃⟨_⟩_ public

-- Then ⟦ C′ ⟧ is ⟦ C ⟧ relabelled, up to renaming its path variables,
-- and so is equivalent to it.

structural-≃ : {C : Circuit n} {σ : Permutation n n′} {C′ : Circuit n′} →
               C ≃⟨ σ ⟩ C′ →
               Σ (Permutation (paths C) (paths C′))
                 (λ π → relabel σ ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧)
structural-≃ {C = C} {σ} (relabelled r) =
  (paths-cast σ C ∘ₚ proj₁ (structural r)) ,
  ≡ᴿ-trans (relabel-⟦⟧ σ C) (proj₂ (structural r))

structural-≃-≋ : {C : Circuit n} {σ : Permutation n n′} {C′ : Circuit n′} →
                 C ≃⟨ σ ⟩ C′ → relabel σ ⟦ C ⟧ ≋ ⟦ C′ ⟧
structural-≃-≋ {C = C} {σ} {C′} r =
  ≡ᴿ⇒≋ {ξ = relabel σ ⟦ C ⟧} {π = proj₁ (structural-≃ r)} {ζ = ⟦ C′ ⟧}
       (proj₂ (structural-≃ r))


------------------------------------------------------------------------
-- The renaming cannot be dropped

-- Two Hadamards on different wires, in either order.  The first owns
-- y₁ and the second y₀ (PathSum.CRK.Trace), so the phase of HH₀₁ is
-- ½ x₀ y₁ + ½ x₁ y₀ and that of HH₁₀ is ½ x₁ y₁ + ½ x₀ y₀: the
-- coefficient of x₀ y₀ is 0 in the one and ½ in the other.  The
-- circuits are structurally equivalent (HH-∼), so their path-sums are
-- equal up to a renaming (structural, which renames along the
-- exchange of y₀ and y₁), but not without one (renaming-needed).

HH₀₁ HH₁₀ : Circuit 2
HH₀₁ = H zero ∷ H (suc zero) ∷ []
HH₁₀ = H (suc zero) ∷ H zero ∷ []

HH-∼ : HH₀₁ ∼ HH₁₀
HH-∼ = ∼-swap (H zero) (H (suc zero)) (((λ ()) ∷ []) ∷ []) []

private
  γ₀ : Mon 2 2
  γ₀ = inside ∷ outside ∷ [] , inside ∷ outside ∷ []

  ½≢0 : ½ ≢ 0ℤ
  ½≢0 eq = ℕ.<-irrefl refl
    (subst (0 <_) (+-injective eq) (ℕ.m^n>0 2 (M ∸ 1)))

renaming-needed : ¬ (⟦ HH₀₁ ⟧ ≡ᴿ⟨ id ⟩ ⟦ HH₁₀ ⟧)
renaming-needed r = ½≢0 (trans (sym at₁₀) (trans (sym (phase≡ r γ₀)) at₀₁))
  where
  at₀₁ : phase ⟦ HH₀₁ ⟧ γ₀ ≡ 0ℤ
  at₀₁ = trans (+-identityˡ (½ * 0ℤ)) (*-zeroʳ ½)

  at₁₀ : phase ⟦ HH₁₀ ⟧ γ₀ ≡ ½
  at₁₀ = trans (+-identityˡ (½ * 1ℤ)) (*-identityʳ ½)
