------------------------------------------------------------------------
-- Presentations of groups
--
-- The four cosets of the even-parity subgroup (Clément, Definition A.2)
--
-- The circuits on n ≥ 3 qubits denote the subgroup of even ZX- and
-- H-parity, of index 4 in the group generated by the auxiliary
-- generators (Lemma 4.7).  Appendix A.3 recovers a complete theory for
-- the subgroup from one for the whole group by the Reidemeister–Schreier
-- method, whose first datum is a representative of each coset:
--
--     ε,   (−1)_[1],   H_[0,1],   H_[0,1] (−1)_[1].
--
-- Their parities are (even, even), (odd, even), (even, odd) and
-- (odd, odd), so they do lie in four different cosets; and every
-- generator is one of them times an element of the subgroup, which is
-- what the coset action of Definition A.2 exhibits.
--
-- Two indices are enough to write them, so they are stated at width
-- m + 2; the alphabet P lives at width 2ⁿ, which is at least 8.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Real-Clifford+CH.Auxiliary.Cosets where

open import Data.Nat using (ℕ)
open import Word.Base using (Word ; ε ; _•_)

open import Notations using (₀ ; ₁ ; ₂₊)

open import Examples.Groups.Real-Clifford+CH.Auxiliary.Syntactics
  using (Gen ; −1 ; H)

private
  variable
    m : ℕ

------------------------------------------------------------------------
-- The cosets

-- ⟨ε⟩ is the subgroup itself, the identity coset; ⟨M⟩ carries odd
-- ZX-parity, ⟨K⟩ odd H-parity and ⟨KM⟩ both.
data Coset : Set where
  ⟨ε⟩ ⟨M⟩ ⟨K⟩ ⟨KM⟩ : Coset

-- The representatives.
rep : Coset → Word (Gen (₂₊ m))
rep ⟨ε⟩  = ε
rep ⟨M⟩  = −1 ₁
rep ⟨K⟩  = H ₀ ₁
rep ⟨KM⟩ = H ₀ ₁ • −1 ₁
