------------------------------------------------------------------------
-- Presentations of groups
--
-- The generators P of the even-parity subgroup (Clément, Proposition
-- 4.6)
--
-- On n ≥ 3 qubits the circuits denote the index-4 subgroup of
-- O_{2ⁿ}(ℤ[1/√2]) of even ZX- and H-parity (Lemma 4.7), generated by
-- the products of two auxiliary generators
--
--     (−1)_[a] (−1)_[b],   (−1)_[c] X_[a,b],   X_[a,b] X_[c,d],   H_[a,b] H_[c,d]
--
-- with a ≠ b and c ≠ d.  A letter of P is such a pair; a word over P
-- denotes the product of its letters' matrices in the order written,
-- as a word over the auxiliary generators does.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Real-Clifford+CH.Auxiliary.P where

open import Data.Fin using (Fin)
open import Data.Nat using (ℕ) renaming (_^_ to _^ℕ_)
open import Relation.Binary.PropositionalEquality using (_≢_)
open import Word.Base using (Word ; [_]ʷ ; _•_)

open import Examples.Groups.Real-Clifford+CH.Semantics using (Scaled ; _∙_)
open import Examples.Groups.Real-Clifford+CH.Auxiliary.Matrices using (⟦_⟧ᴳ)

import Examples.Groups.Real-Clifford+CH.Auxiliary.Syntactics as G
open G using (−1[_] ; X[_,_] ; H[_,_])

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- The generators

-- The inequalities are irrelevant fields: two letters with the same
-- indices are the same letter.
data GenP (n : ℕ) : Set where
  −1−1 : (a b : Fin (2 ^ℕ n)) → GenP n
  −1X  : (c a b : Fin (2 ^ℕ n)) → .(a ≢ b) → GenP n
  XX : (a b c d : Fin (2 ^ℕ n)) → .(a ≢ b) → .(c ≢ d) → GenP n
  HH : (a b c d : Fin (2 ^ℕ n)) → .(a ≢ b) → .(c ≢ d) → GenP n

-- A letter of P as a word over the auxiliary generators.
asG : GenP n → Word (G.Gen (2 ^ℕ n))
asG (−1−1 a b)     = [ −1[ a ] ]ʷ • [ −1[ b ] ]ʷ
asG (−1X c a b _)  = [ −1[ c ] ]ʷ • [ X[ a , b ] ]ʷ
asG (XX a b c d _ _) = [ X[ a , b ] ]ʷ • [ X[ c , d ] ]ʷ
asG (HH a b c d _ _) = [ H[ a , b ] ]ʷ • [ H[ c , d ] ]ʷ

------------------------------------------------------------------------
-- The matrices

⟦_⟧ᴾ : GenP n → Scaled n
⟦ −1−1 a b ⟧ᴾ       = ⟦ −1[ a ] ⟧ᴳ ∙ ⟦ −1[ b ] ⟧ᴳ
⟦ −1X c a b _ ⟧ᴾ    = ⟦ −1[ c ] ⟧ᴳ ∙ ⟦ X[ a , b ] ⟧ᴳ
⟦ XX a b c d _ _ ⟧ᴾ = ⟦ X[ a , b ] ⟧ᴳ ∙ ⟦ X[ c , d ] ⟧ᴳ
⟦ HH a b c d _ _ ⟧ᴾ = ⟦ H[ a , b ] ⟧ᴳ ∙ ⟦ H[ c , d ] ⟧ᴳ
