------------------------------------------------------------------------
-- Presentations of groups
--
-- The syntax of real Clifford circuits (Makary, Ross and Selinger,
-- "Generators and relations for real stabilizer operators", QPL 2021,
-- EPTCS 343, arXiv:2109.05655): the generators −1, H, Z and CZ, the
-- derived gate X, and the reduced relations R1 … R16 of Figure 1
--
-- Wires are numbered from the bottom: wire 0 is the paper's lowest
-- wire, and CZ sits on wires 0 and 1.  Words are in operator order, the
-- rightmost letter acting first, so a diagram read left to right as
-- "A then B" is the word B • A.  The structural rules of Circuit.Base
-- supply the commutation of gates on disjoint wires and the centrality
-- of the scalar −1, which the paper leaves implicit.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Real-Clifford.Syntactics where

open import Data.Nat using (ℕ)
open import Data.Product using (_,_)
open import Word.Base using (Word ; WRel ; [_]ʷ ; ε ; _•_ ; _^_)

open import Notations using (₁₊ ; ₂₊ ; ₃₊)
open import Presentation.GroupLike using (Grouplike)

import Circuit.Base
import Presentation.Base as PB
import Presentation.Properties as PP
import Relation.Binary.PropositionalEquality as Eq

private
  variable
    n : ℕ

------------------------------------------------------------------------
-- Gates

-- The scalar −1 is a gate on no wires.
data Gate : ℕ → Set where
  neg-gate         : Gate 0
  H-gate Z-gate    : Gate 1
  CZ-gate          : Gate 2

private module SC = Circuit.Base Gate

open SC public
  using ( Gen ; gate₀ ; gate₁ ; gate₂ ; Circuit
        ; _↥ ; _↑ ; _↓ ; _↥ᵏ_ ; _↑ᵏ_ ; _↓ᵏ_ ; _↧ᵏ_ )

pattern neg-gen = gate₀ neg-gate
pattern H-gen   = gate₁ H-gate
pattern Z-gen   = gate₁ Z-gate
pattern CZ-gen  = gate₂ CZ-gate

-- The generators as one-letter circuits.
neg : Circuit n
neg = [ neg-gen ]ʷ

H Z : Circuit (₁₊ n)
H = [ H-gen ]ʷ
Z = [ Z-gen ]ʷ

CZ : Circuit (₂₊ n)
CZ = [ CZ-gen ]ʷ

------------------------------------------------------------------------
-- Derived gates (Section 3)

-- The Pauli X gate.
X : Circuit (₁₊ n)
X = H • Z • H

-- H on both wires of a CZ.
HH : Circuit (₂₊ n)
HH = H • H ↑

------------------------------------------------------------------------
-- The reduced relations (Figure 1)
--
-- Each is stated at the width it is drawn on; the structural rules lift
-- it to every width.  Gates drawn in one column are written lower wire
-- first.

infix 4 _SRel,_===_
data _SRel,_===_ : (n : ℕ) → WRel (Gen n) where

  -- One-wire relations.
  R₁  : n SRel, neg • neg === ε
  R₂  : (₁₊ n) SRel, Z • Z === ε
  R₃  : (₁₊ n) SRel, H • H === ε
  R₄  : (₁₊ n) SRel, (H • Z) ^ 4 === neg

  -- Two-wire relations.
  R₅  : (₂₊ n) SRel, CZ • CZ === ε
  R₆  : (₂₊ n) SRel, CZ • Z ↑ === Z ↑ • CZ
  R₇  : (₂₊ n) SRel, CZ • Z === Z • CZ
  R₈  : (₂₊ n) SRel, CZ • H ↑ • Z ↑ • H ↑ === H ↑ • Z • Z ↑ • H ↑ • CZ
  R₉  : (₂₊ n) SRel, CZ • H • Z • H === H • Z • Z ↑ • H • CZ
  R₁₀ : (₂₊ n) SRel, CZ • H ↑ • CZ • H ↑ === Z • H ↑ • CZ • H ↑ • CZ
  R₁₁ : (₂₊ n) SRel, CZ • H • CZ • H === H • Z ↑ • CZ • H • CZ
  R₁₂ : (₂₊ n) SRel,
        CZ • HH • CZ • HH • CZ • H === H ↑ • CZ • HH • CZ • HH • CZ

  -- Three-wire relations.
  R₁₃ : (₃₊ n) SRel, CZ • CZ ↑ === CZ ↑ • CZ
  R₁₄ : (₃₊ n) SRel,
        H • CZ • HH • CZ • H ↑ • CZ ↑ • H ↑ • CZ • HH • CZ • H ===
        H ↑ ↑ • CZ ↑ • HH ↑ • CZ ↑ • H ↑ • CZ • H ↑ • CZ ↑ • HH ↑ • CZ ↑ • H ↑ ↑
  R₁₅ : (₃₊ n) SRel,
        CZ • HH ↑ • CZ ↑ • HH ↑ • CZ ↑ • CZ • HH ↑ • CZ ↑ • HH ↑ • CZ ↑ ===
        CZ ↑ • HH ↑ • CZ ↑ • HH ↑ • CZ
  R₁₆ : (₃₊ n) SRel,
        CZ ↑ • HH • CZ • HH • CZ • CZ ↑ • HH • CZ • HH • CZ ===
        CZ • HH • CZ • HH • CZ ↑

------------------------------------------------------------------------
-- The full relation: the structural rules of Circuit.Base on top

private module LR = SC.Lift-Relation _SRel,_===_

open LR public
  using ( srel ; cong↑ ; comm₀ ; comm₁ ; comm₂ ; ω↑=ω ; lemma-cong↑
        ; comm-gate₀-w ; comm-gate₁-w↑ ; comm-gate₂-w↑↑ ; _VRel,_===_ )

-- The monoid congruence generated by the relations at width n: the
-- paper's equality of circuits.
infix 4 _⊢_≈_
_⊢_≈_ : (n : ℕ) → Circuit n → Circuit n → Set
n ⊢ w ≈ v = PB._≈_ (n VRel,_===_) w v

------------------------------------------------------------------------
-- Every generator is invertible, so the presented monoid is a group

grouplike : Grouplike (_VRel,_===_ n)
grouplike neg-gen = neg , PB.axiom (srel R₁)
grouplike H-gen   = H   , PB.axiom (srel R₃)
grouplike Z-gen   = Z   , PB.axiom (srel R₂)
grouplike CZ-gen  = CZ  , PB.axiom (srel R₅)
grouplike (g ↥) with grouplike g
... | ig , prf = ig ↑ , lemma-cong↑ (ig • [ g ]ʷ) ε prf
