------------------------------------------------------------------------
-- Presentations of groups
--
-- Structurally equivalent circuits over {H, S, CZ} have the same
-- path-sum, and the same isometry restriction, up to renaming the path
-- variables (Amy, QPL 2018, remark 2.8 and section 4.1)
--
-- PathSum.CRK.Structural proves remark 2.8's "circuits which are
-- equivalent up to symmetric monoidal laws are strictly equal in the
-- path-sum picture" for circuits over {H, CNOT, R_k, R_k†}.  This
-- module proves it for the Clifford gate set {H, S, CZ} of
-- PathSum.Circuit, the one corollary 4.4's development is built on,
-- and for both of the path-sums PathSum.Circuit gives a circuit:
-- definition 2.9's ⟦ C ⟧, in which every Hadamard allocates a path
-- variable, and the isometry restriction ⟦ C ⟧ᴿ of section 4.1, in
-- which a Hadamard allocates one only when a later Hadamard acts on
-- its wire, the last one putting the input x_w there instead.
--
-- Structural equivalence C ∼ C′ is, as there, the congruence on gate
-- lists generated by exchanging adjacent gates on disjoint wires
-- (Disjoint: no wire of one is a wire of the other; CZ acts on both of
-- its wires), closed under adding a gate in front (∼-cons) and so
-- under concatenation (∼-++); circuits on disjoint wires commute as
-- blocks (∼-parallel), the interchange law.
--
-- The theorems.  If C ∼ C′ then
--
--    ⟦ C ⟧  ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧    (structural)    and
--    ⟦ C ⟧ᴿ ≡ᴿ⟨ π′ ⟩ ⟦ C′ ⟧ᴿ  (structuralᴿ),
--
-- for renamings π, π′ of the path variables read off the derivation:
-- the same normalisation, and every coefficient of the phase and of
-- every output equal, as an integer, once the path variables are
-- renamed (PathSum.Permute).  Hence the congruent forms (structural-≈,
-- structuralᴿ-≈) and ⟦ C ⟧ ≋ ⟦ C′ ⟧, ⟦ C ⟧ᴿ ≋ ⟦ C′ ⟧ᴿ (structural-≋,
-- structuralᴿ-≋).  The renaming is needed (renaming-needed,
-- renaming-needed-≈: H on wire 0 then on wire 1, against the other
-- order, differ at the coefficient of x₀ y₀, by ½, which is not 0
-- modulo 2^M).
--
-- The restriction too, because which Hadamards allocate is invariant:
-- a Hadamard allocates exactly when a later Hadamard acts on its wire,
-- and exchanging gates on disjoint wires changes, for no Hadamard,
-- whether a later one acts on its wire (hasH-∼); so the two circuits
-- have the same allocating Hadamards (allocs-∼), and exchanging two
-- that both allocate exchanges their path variables while any other
-- exchange renames nothing.
--
-- How the proofs go: as in PathSum.CRK.Structural, path by path, with
-- PathSum.Circuit.Trace's traces.  Two gates on disjoint wires update
-- a configuration alike in either order (gate-comm: a Hadamard reads
-- and writes only its wire, S and CZ change only the phase, reading
-- their wires); a derivation of C ∼ C′ gives a bijection of the bit
-- positions (PathSum.CRK.Structural's Reorder) under which the traces
-- agree (reorders, reordersᴿ); it restricts to a bijection of the path
-- variables (PathSum.CRK.Structural.toPerm), along which the phases
-- take the same values and the outputs the same bits; Möbius
-- uniqueness (PathSum.Permute.≡ᴿ-by-values) gives the coefficients.
-- No polynomial is computed or compared.
--
-- As for {H, CNOT, R_k}, "strictly equal" means: equal up to the
-- renaming of the bound path variables (α-conversion), coefficient by
-- coefficient (no function extensionality), with the normalisations
-- and the numbers of path variables equal as numbers.  Other sound
-- commutations (two phase gates on a shared wire, for instance) are
-- not monoidal laws and are not included.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat.Base using (ℕ; zero; suc)

module PathSum.Circuit.Structural (M₀ : ℕ) where

open import Data.Bool.Base using (Bool; true; false; _∧_; _∨_; if_then_else_)
open import Data.Fin.Base using (Fin; zero; suc)
open import Data.Fin.Permutation using (Permutation; _⟨$⟩ʳ_; id)
open import Data.Fin.Subset using (inside; outside)
open import Data.Integer.Base using (ℤ; 0ℤ; 1ℤ; -_; _+_; _-_; _*_)
open import Data.Integer.Divisibility.Signed using (_∣_; ∣⇒∣ᵤ; ∣m⇒∣-m)
open import Data.Integer.Properties using
  (+-assoc; +-comm; +-identityˡ; *-zeroʳ; *-identityʳ; neg-involutive)
open import Data.List.Base using (List; []; _∷_; _++_)
open import Data.List.Properties using (++-identityʳ)
open import Data.List.Relation.Unary.All using (All; []; _∷_)
open import Data.Nat.Base using (_<_; _≤_; _∸_; z≤n; s≤s)
  renaming (_+_ to _ℕ+_)
open import Data.Product.Base using (Σ; _,_; proj₁; proj₂)
open import Data.Vec.Base using ([]; _∷_)
open import Relation.Binary.PropositionalEquality using
  (_≡_; _≢_; refl; sym; trans; cong; cong₂; subst; ≢-sym)
open import Relation.Nullary.Decidable using (yes; no; ⌊_⌋)
open import Relation.Nullary.Negation using (¬_; contradiction)

import Data.Fin.Properties as Fin
import Data.List.Relation.Unary.All as All
import Data.Nat.Divisibility as ℕDiv
import Data.Nat.Properties as ℕ

private
  M : ℕ
  M = suc (suc (suc M₀))

open import PathSum.Assign using ([_]ᶻ; _[_≔_]; ≔-there; ≔-comm)
open import PathSum.Base using (PathSum; phase; out)
open import PathSum.Circuit M using
  (Gate; H; S; CZ; Circuit; norm; hasH; pathsᵁ; paths; ⟦_⟧; ⟦_⟧ᴿ;
   pathsᵁ≡norm)
open import PathSum.Circuit.Trace M₀ using
  (gateᶜ; gateᶜ-cong; trace; trace-cong; trace-below; allocs; hbit; bitᴿ;
   traceᴿ; traceᴿ-cong; traceᴿ-below; paths≡allocs; eval-⟦⟧;
   eval-out-⟦⟧; eval-⟦⟧ᴿ; eval-out-⟦⟧ᴿ)
open import PathSum.CRK.Structural M₀ using
  (Reorder; fwd; bwd; bwd-fwd; fwd-bwd; fwd-fix; fwd-<; bwd-<;
   reorder-id; reorder-inv; reorder-⨾; reorder-weaken; reorder-cast;
   toPerm; str-toPerm)
open import PathSum.CRK.Trace M₀ using
  (Stream; Conf; _≈ᶜ_; conf≈; ≈φ; ≈v; ≈ᶜ-refl; ≈ᶜ-sym; ≈ᶜ-trans; str;
   start)
open import PathSum.Denotation M₀ using (Assign; _≋_)
open import PathSum.Order M using (pow)
open import PathSum.Permute using
  (renumberᴾ; _≡ᴿ⟨_⟩_; phase≡; ≡ᴿ-by-values)
open import PathSum.Permute.Sound M₀ using
  (_≈ᴿ⟨_⟩_; congruent-renamed; ≡ᴿ⇒≈ᴿ; ≡ᴿ⇒≋)
open import PathSum.Polynomial using (Mon; eval)
open import PathSum.Reduction M using (¼; ½)

private
  variable
    n : ℕ


------------------------------------------------------------------------
-- Gates on disjoint wires

wiresᵍ : Gate n → List (Fin n)
wiresᵍ (H w)    = w ∷ []
wiresᵍ (S w)    = w ∷ []
wiresᵍ (CZ w u) = w ∷ u ∷ []

-- No wire of g is a wire of h.

Disjoint : Gate n → Gate n → Set
Disjoint g h = All (λ u → All (u ≢_) (wiresᵍ h)) (wiresᵍ g)

Disjoint-sym : (g h : Gate n) → Disjoint g h → Disjoint h g
Disjoint-sym g h d =
  All.tabulate (λ v∈h → All.tabulate (λ u∈g eq →
    All.lookup (All.lookup d u∈g) v∈h (sym eq)))


------------------------------------------------------------------------
-- Structural equivalence

infix 4 _∼_

data _∼_ {n : ℕ} : Circuit n → Circuit n → Set where
  ∼-refl  : {C : Circuit n} → C ∼ C
  ∼-swap  : (g h : Gate n) → Disjoint g h → (D : Circuit n) →
            (g ∷ h ∷ D) ∼ (h ∷ g ∷ D)
  ∼-cons  : (g : Gate n) {C C′ : Circuit n} → C ∼ C′ → (g ∷ C) ∼ (g ∷ C′)
  ∼-sym   : {C C′ : Circuit n} → C ∼ C′ → C′ ∼ C
  ∼-trans : {C C′ C″ : Circuit n} → C ∼ C′ → C′ ∼ C″ → C ∼ C″

-- A congruence for concatenation.

∼-++ˡ : {C C′ : Circuit n} (D : Circuit n) → C ∼ C′ → (C ++ D) ∼ (C′ ++ D)
∼-++ˡ D ∼-refl              = ∼-refl
∼-++ˡ D (∼-swap g h dis E)  = ∼-swap g h dis (E ++ D)
∼-++ˡ D (∼-cons g r)        = ∼-cons g (∼-++ˡ D r)
∼-++ˡ D (∼-sym r)           = ∼-sym (∼-++ˡ D r)
∼-++ˡ D (∼-trans r r′)      = ∼-trans (∼-++ˡ D r) (∼-++ˡ D r′)

∼-++ʳ : (C : Circuit n) {D D′ : Circuit n} → D ∼ D′ → (C ++ D) ∼ (C ++ D′)
∼-++ʳ []      r = r
∼-++ʳ (g ∷ C) r = ∼-cons g (∼-++ʳ C r)

∼-++ : {C C′ D D′ : Circuit n} → C ∼ C′ → D ∼ D′ → (C ++ D) ∼ (C′ ++ D′)
∼-++ {C′ = C′} {D = D} r r′ = ∼-trans (∼-++ˡ D r) (∼-++ʳ C′ r′)

-- Circuits on disjoint wires commute as blocks.

Apart : Circuit n → Circuit n → Set
Apart C D = All (λ g → All (Disjoint g) D) C

private
  pass : (g : Gate n) (D E : Circuit n) → All (Disjoint g) D →
         (g ∷ (D ++ E)) ∼ (D ++ (g ∷ E))
  pass g []      E []         = ∼-refl
  pass g (h ∷ D) E (d ∷ ds) =
    ∼-trans (∼-swap g h d (D ++ E)) (∼-cons h (pass g D E ds))

∼-parallel : (C D : Circuit n) → Apart C D → (C ++ D) ∼ (D ++ C)
∼-parallel []      D []         =
  subst (D ∼_) (sym (++-identityʳ D)) ∼-refl
∼-parallel (g ∷ C) D (dg ∷ ds) =
  ∼-trans (∼-cons g (∼-parallel C D ds)) (pass g D C dg)


------------------------------------------------------------------------
-- What structural equivalence keeps

-- The number of Hadamards.

private
  norm-∷ : (g : Gate n) (C : Circuit n) → norm (g ∷ C) ≡ norm (g ∷ []) ℕ+ norm C
  norm-∷ (H _)    C = refl
  norm-∷ (S _)    C = refl
  norm-∷ (CZ _ _) C = refl

norm-∼ : {C C′ : Circuit n} → C ∼ C′ → norm C ≡ norm C′
norm-∼ ∼-refl = refl
norm-∼ (∼-swap g h dis D) =
  trans (norm-∷ g (h ∷ D))
  (trans (cong (norm (g ∷ []) ℕ+_) (norm-∷ h D))
  (trans (sym (ℕ.+-assoc (norm (g ∷ [])) (norm (h ∷ [])) (norm D)))
  (trans (cong (_ℕ+ norm D) (ℕ.+-comm (norm (g ∷ [])) (norm (h ∷ []))))
  (trans (ℕ.+-assoc (norm (h ∷ [])) (norm (g ∷ [])) (norm D))
  (trans (cong (norm (h ∷ []) ℕ+_) (sym (norm-∷ g D)))
         (sym (norm-∷ h (g ∷ D))))))))
norm-∼ (∼-cons g {C} {C′} r) =
  trans (norm-∷ g C) (trans (cong (norm (g ∷ []) ℕ+_) (norm-∼ r))
                            (sym (norm-∷ g C′)))
norm-∼ (∼-sym r)       = sym (norm-∼ r)
norm-∼ (∼-trans r r′)  = trans (norm-∼ r) (norm-∼ r′)

-- Whether a later Hadamard acts on a wire.

private
  ⌊≢⌋ : {v w : Fin n} → v ≢ w → ⌊ v Fin.≟ w ⌋ ≡ false
  ⌊≢⌋ {v = v} {w} v≢w with v Fin.≟ w
  ... | yes p = contradiction p v≢w
  ... | no  _ = refl

  -- A Hadamard on another wire does not count.
  hasH-skip : (v u : Fin n) → v ≢ u → (D : Circuit n) →
              hasH v (H u ∷ D) ≡ hasH v D
  hasH-skip v u v≢u D = cong (_∨ hasH v D) (⌊≢⌋ v≢u)

  ∨-swap : ∀ p q r → p ∨ (q ∨ r) ≡ q ∨ (p ∨ r)
  ∨-swap true  true  r = refl
  ∨-swap true  false r = refl
  ∨-swap false q     r = refl

  hasH-swap : (g h : Gate n) (D : Circuit n) (v : Fin n) →
              hasH v (g ∷ h ∷ D) ≡ hasH v (h ∷ g ∷ D)
  hasH-swap (H a)    (H b)    D v = ∨-swap ⌊ v Fin.≟ a ⌋ ⌊ v Fin.≟ b ⌋ (hasH v D)
  hasH-swap (H a)    (S b)    D v = refl
  hasH-swap (H a)    (CZ b c) D v = refl
  hasH-swap (S a)    (H b)    D v = refl
  hasH-swap (S a)    (S b)    D v = refl
  hasH-swap (S a)    (CZ b c) D v = refl
  hasH-swap (CZ a d) (H b)    D v = refl
  hasH-swap (CZ a d) (S b)    D v = refl
  hasH-swap (CZ a d) (CZ b c) D v = refl

hasH-∼ : {C C′ : Circuit n} → C ∼ C′ → ∀ v → hasH v C ≡ hasH v C′
hasH-∼ ∼-refl               v = refl
hasH-∼ (∼-swap g h dis D)   v = hasH-swap g h D v
hasH-∼ (∼-cons (H a) r)     v = cong (⌊ v Fin.≟ a ⌋ ∨_) (hasH-∼ r v)
hasH-∼ (∼-cons (S a) r)     v = hasH-∼ r v
hasH-∼ (∼-cons (CZ a b) r)  v = hasH-∼ r v
hasH-∼ (∼-sym r)            v = sym (hasH-∼ r v)
hasH-∼ (∼-trans r r′)       v = trans (hasH-∼ r v) (hasH-∼ r′ v)

-- The number of Hadamards that allocate in the restriction.

private
  alloc2 : ∀ bw bu (A : ℕ) →
           (if bw then suc (if bu then suc A else A) else
                       (if bu then suc A else A)) ≡
           (if bu then suc (if bw then suc A else A) else
                       (if bw then suc A else A))
  alloc2 true  true  A = refl
  alloc2 true  false A = refl
  alloc2 false true  A = refl
  alloc2 false false A = refl

  -- allocs of a Hadamard in front, as a function of the flag.
  ifs : Bool → ℕ → ℕ
  ifs b A = if b then suc A else A

allocs-∼ : {C C′ : Circuit n} → C ∼ C′ → allocs C ≡ allocs C′
allocs-∼ ∼-refl = refl
allocs-∼ (∼-swap (H w) (H u) ((w≢u ∷ []) ∷ []) D) =
  trans (cong (λ b → ifs b (allocs (H u ∷ D))) (hasH-skip w u w≢u D))
  (trans (alloc2 (hasH w D) (hasH u D) (allocs D))
         (sym (cong (λ b → ifs b (allocs (H w ∷ D)))
                    (hasH-skip u w (≢-sym w≢u) D))))
allocs-∼ (∼-swap (H w)    (S u)    _ D) = refl
allocs-∼ (∼-swap (H w)    (CZ u t) _ D) = refl
allocs-∼ (∼-swap (S w)    (H u)    _ D) = refl
allocs-∼ (∼-swap (S w)    (S u)    _ D) = refl
allocs-∼ (∼-swap (S w)    (CZ u t) _ D) = refl
allocs-∼ (∼-swap (CZ w v) (H u)    _ D) = refl
allocs-∼ (∼-swap (CZ w v) (S u)    _ D) = refl
allocs-∼ (∼-swap (CZ w v) (CZ u t) _ D) = refl
allocs-∼ (∼-cons (H w) r) = cong₂ ifs (hasH-∼ r w) (allocs-∼ r)
allocs-∼ (∼-cons (S w) r) = allocs-∼ r
allocs-∼ (∼-cons (CZ w u) r) = allocs-∼ r
allocs-∼ (∼-sym r) = sym (allocs-∼ r)
allocs-∼ (∼-trans r r′) = trans (allocs-∼ r) (allocs-∼ r′)


------------------------------------------------------------------------
-- Gates on disjoint wires commute on configurations

private
  swap+ : ∀ φ x y x′ y′ → x ≡ x′ → y ≡ y′ → (φ + x) + y ≡ (φ + y′) + x′
  swap+ φ x y _ _ refl refl =
    trans (+-assoc φ x y)
          (trans (cong (φ +_) (+-comm x y)) (sym (+-assoc φ y x)))

  comm-HH : (w u : Fin n) → w ≢ u → ∀ b b′ (a : Conf n) →
            gateᶜ (H u) b′ (gateᶜ (H w) b a) ≈ᶜ gateᶜ (H w) b (gateᶜ (H u) b′ a)
  comm-HH w u w≢u b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ) (½ * [ (v [ w ≔ b ]) u ∧ b′ ]ᶻ)
             (½ * [ (v [ u ≔ b′ ]) w ∧ b ]ᶻ) (½ * [ v u ∧ b′ ]ᶻ)
             (cong (λ c → ½ * [ c ∧ b ]ᶻ) (sym (≔-there v b′ w≢u)))
             (cong (λ c → ½ * [ c ∧ b′ ]ᶻ) (≔-there v b (≢-sym w≢u))))
    (≔-comm v b b′ w≢u)

  comm-HS : (w u : Fin n) → w ≢ u → ∀ b b′ (a : Conf n) →
            gateᶜ (S u) b′ (gateᶜ (H w) b a) ≈ᶜ gateᶜ (H w) b (gateᶜ (S u) b′ a)
  comm-HS w u w≢u b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ) (¼ * [ (v [ w ≔ b ]) u ]ᶻ)
             (½ * [ v w ∧ b ]ᶻ) (¼ * [ v u ]ᶻ)
             refl (cong (λ c → ¼ * [ c ]ᶻ) (≔-there v b (≢-sym w≢u))))
    (λ _ → refl)

  comm-HCZ : (w u t : Fin n) → w ≢ u → w ≢ t → ∀ b b′ (a : Conf n) →
             gateᶜ (CZ u t) b′ (gateᶜ (H w) b a) ≈ᶜ
             gateᶜ (H w) b (gateᶜ (CZ u t) b′ a)
  comm-HCZ w u t w≢u w≢t b b′ (φ , v) = conf≈
    (swap+ φ (½ * [ v w ∧ b ]ᶻ)
             (½ * [ (v [ w ≔ b ]) u ∧ (v [ w ≔ b ]) t ]ᶻ)
             (½ * [ v w ∧ b ]ᶻ) (½ * [ v u ∧ v t ]ᶻ)
             refl (cong₂ (λ c d → ½ * [ c ∧ d ]ᶻ)
                         (≔-there v b (≢-sym w≢u)) (≔-there v b (≢-sym w≢t))))
    (λ _ → refl)

-- Gates on disjoint wires update a configuration alike in either
-- order.  (Two phase gates commute whatever their wires.)

gate-comm : (g h : Gate n) → Disjoint g h → ∀ b b′ (a : Conf n) →
            gateᶜ h b′ (gateᶜ g b a) ≈ᶜ gateᶜ g b (gateᶜ h b′ a)
gate-comm (H w) (H u) ((w≢u ∷ []) ∷ []) = comm-HH w u w≢u
gate-comm (H w) (S u) ((w≢u ∷ []) ∷ []) = comm-HS w u w≢u
gate-comm (H w) (CZ u t) ((w≢u ∷ w≢t ∷ []) ∷ []) = comm-HCZ w u t w≢u w≢t
gate-comm (S w) (H u) ((w≢u ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-HS u w (≢-sym w≢u) b′ b a)
gate-comm (S w) (S u) _ b b′ (φ , v) =
  conf≈ (swap+ φ _ _ _ _ refl refl) (λ _ → refl)
gate-comm (S w) (CZ u t) _ b b′ (φ , v) =
  conf≈ (swap+ φ _ _ _ _ refl refl) (λ _ → refl)
gate-comm (CZ w t) (H u) ((w≢u ∷ []) ∷ (t≢u ∷ []) ∷ []) b b′ a =
  ≈ᶜ-sym (comm-HCZ u w t (≢-sym w≢u) (≢-sym t≢u) b′ b a)
gate-comm (CZ w t) (S u) _ b b′ (φ , v) =
  conf≈ (swap+ φ _ _ _ _ refl refl) (λ _ → refl)
gate-comm (CZ w t) (CZ u r) _ b b′ (φ , v) =
  conf≈ (swap+ φ _ _ _ _ refl refl) (λ _ → refl)


------------------------------------------------------------------------
-- The exchange of two bit positions

private
  tr : ℕ → ℕ → ℕ
  tr zero    zero          = 1
  tr zero    (suc zero)    = 0
  tr zero    (suc (suc i)) = suc (suc i)
  tr (suc d) zero          = zero
  tr (suc d) (suc i)       = suc (tr d i)

  tr-inv : ∀ d i → tr d (tr d i) ≡ i
  tr-inv zero    zero          = refl
  tr-inv zero    (suc zero)    = refl
  tr-inv zero    (suc (suc i)) = refl
  tr-inv (suc d) zero          = refl
  tr-inv (suc d) (suc i)       = cong suc (tr-inv d i)

  tr-fix : ∀ d i → suc (suc d) ≤ i → tr d i ≡ i
  tr-fix zero    (suc (suc i)) _         = refl
  tr-fix zero    (suc zero)    (s≤s ())
  tr-fix (suc d) (suc i)       (s≤s le)  = cong suc (tr-fix d i le)

  tr-< : ∀ d i → i < suc (suc d) → tr d i < suc (suc d)
  tr-< zero    zero          _         = s≤s (s≤s z≤n)
  tr-< zero    (suc zero)    _         = s≤s z≤n
  tr-< zero    (suc (suc i)) (s≤s (s≤s ()))
  tr-< (suc d) zero          _         = s≤s z≤n
  tr-< (suc d) (suc i)       (s≤s le)  = s≤s (tr-< d i le)

  tr-below : ∀ d i → i < d → tr d i ≡ i
  tr-below (suc d) zero    _        = refl
  tr-below (suc d) (suc i) (s≤s le) = cong suc (tr-below d i le)

  tr-d : ∀ d → tr d d ≡ suc d
  tr-d zero    = refl
  tr-d (suc d) = cong suc (tr-d d)

  tr-sd : ∀ d → tr d (suc d) ≡ d
  tr-sd zero    = refl
  tr-sd (suc d) = cong suc (tr-sd d)

  -- The exchange of the positions d and d + 1.
  exchange : ∀ d → Reorder (suc (suc d))
  exchange d = record
    { fwd = tr d ; bwd = tr d
    ; bwd-fwd = tr-inv d ; fwd-bwd = tr-inv d
    ; fwd-fix = tr-fix d ; fwd-< = tr-< d ; bwd-< = tr-< d }


------------------------------------------------------------------------
-- Traces of structurally equivalent circuits: ⟦ C ⟧

-- C ∼ C′ gives a reordering ρ of the bits with
-- trace C′ s ≈ trace C (s ∘ ρ).

Reorders : Circuit n → Circuit n → Set
Reorders C C′ =
  Σ (Reorder (norm C))
    (λ ρ → ∀ s a → trace C′ s a ≈ᶜ trace C (λ i → s (fwd ρ i)) a)

private
  plain : (g h : Gate n) (D : Circuit n) →
          (∀ (s : Stream) a →
             gateᶜ g (s (norm D)) (gateᶜ h (s (norm (g ∷ D))) a) ≈ᶜ
             gateᶜ h (s (norm D)) (gateᶜ g (s (norm (h ∷ D))) a)) →
          Reorders (g ∷ h ∷ D) (h ∷ g ∷ D)
  plain g h D eq = reorder-id , λ s a → trace-cong D (λ _ → refl) (eq s a)

  plain′ : (g h : Gate n) (dis : Disjoint g h) (D : Circuit n) →
           Reorders (g ∷ h ∷ D) (h ∷ g ∷ D)
  plain′ (H w) (H u) dis D = exchange (norm D) , λ s a →
    ≈ᶜ-trans
      (trace-cong D (λ _ → refl)
        (≈ᶜ-sym (gate-comm (H w) (H u) dis (s (norm D)) (s (suc (norm D))) a)))
      (trace-below D (λ i i< → cong s (sym (tr-below (norm D) i i<)))
        (gateᶜ-cong (H u) (cong s (sym (tr-d (norm D))))
          (gateᶜ-cong (H w) (cong s (sym (tr-sd (norm D)))) (≈ᶜ-refl {a = a}))))
  plain′ g@(H _) h@(S _) dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(H _) h@(CZ _ _) dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(S _) h dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)
  plain′ g@(CZ _ _) h dis D = plain g h D λ s a →
    ≈ᶜ-sym (gate-comm g h dis (s (norm D)) (s (norm D)) a)

  ≤-norm : (g : Gate n) (C : Circuit n) → norm C ≤ norm (g ∷ C)
  ≤-norm (H _)    C = ℕ.n≤1+n (norm C)
  ≤-norm (S _)    C = ℕ.≤-refl
  ≤-norm (CZ _ _) C = ℕ.≤-refl

reorders : {C C′ : Circuit n} → C ∼ C′ → Reorders C C′
reorders ∼-refl = reorder-id , λ s a → ≈ᶜ-refl
reorders (∼-swap g h dis D) = plain′ g h dis D
reorders (∼-cons g {C} {C′} r) =
  reorder-weaken (≤-norm g C) ρ , λ s a →
    ≈ᶜ-trans (T s (gateᶜ g (s (norm C′)) a))
             (trace-cong C (λ _ → refl)
               (gateᶜ-cong g (cong s (trans (sym (norm-∼ r))
                                            (sym (fwd-fix ρ (norm C) ℕ.≤-refl))))
                           ≈ᶜ-refl))
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)
reorders (∼-sym {C} {C′} r) =
  reorder-cast (norm-∼ r) (reorder-inv ρ) , λ s a →
    ≈ᶜ-sym (≈ᶜ-trans (T (λ i → s (bwd ρ i)) a)
                     (trace-cong C (λ i → cong s (bwd-fwd ρ i)) ≈ᶜ-refl))
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)
reorders (∼-trans {C} {C′} {C″} r₁ r₂) =
  reorder-⨾ ρ₁ (reorder-cast (sym (norm-∼ r₁)) ρ₂) , λ s a →
    ≈ᶜ-trans (T₂ s a) (T₁ (λ i → s (fwd ρ₂ i)) a)
  where
  ρ₁ = proj₁ (reorders r₁)
  T₁ = proj₂ (reorders r₁)
  ρ₂ = proj₁ (reorders r₂)
  T₂ = proj₂ (reorders r₂)


------------------------------------------------------------------------
-- Traces of structurally equivalent circuits: ⟦ C ⟧ᴿ

Reordersᴿ : Circuit n → Circuit n → Set
Reordersᴿ C C′ =
  Σ (Reorder (allocs C))
    (λ ρ → ∀ s x a → traceᴿ C′ s x a ≈ᶜ traceᴿ C (λ i → s (fwd ρ i)) x a)

private
  -- The bit of a Hadamard that allocates, and of one that does not.
  hbit-on : ∀ {b} → b ≡ true → (t : Stream) (i : ℕ) (c : Bool) →
            hbit b t i c ≡ t i
  hbit-on refl t i c = refl

  hbit-off : ∀ {b} → b ≡ false → (t : Stream) (i : ℕ) (c : Bool) →
             hbit b t i c ≡ c
  hbit-off refl t i c = refl

  -- Streams agreeing at the position read.
  hbit-at : (b : Bool) (t t′ : Stream) (i : ℕ) (c : Bool) → t i ≡ t′ i →
            hbit b t i c ≡ hbit b t′ i c
  hbit-at true  t t′ i c e = e
  hbit-at false t t′ i c e = refl

  ifs-on : ∀ {b} A → b ≡ true → ifs b A ≡ suc A
  ifs-on A refl = refl

  ifs-off : ∀ {b} A → b ≡ false → ifs b A ≡ A
  ifs-off A refl = refl

  plainᴿ : (g h : Gate n) (D : Circuit n) →
           (∀ (s : Stream) x a →
              gateᶜ g (bitᴿ g D s x) (gateᶜ h (bitᴿ h (g ∷ D) s x) a) ≈ᶜ
              gateᶜ h (bitᴿ h D s x) (gateᶜ g (bitᴿ g (h ∷ D) s x) a)) →
           Reordersᴿ (g ∷ h ∷ D) (h ∷ g ∷ D)
  plainᴿ g h D eq =
    reorder-id , λ s x a → traceᴿ-cong D x (λ _ → refl) (eq s x a)

  -- Two Hadamards: their variables are exchanged when both allocate,
  -- and nothing is renamed otherwise.
  hhᴿ : (w u : Fin n) (w≢u : w ≢ u) (D : Circuit n) →
        Reordersᴿ (H w ∷ H u ∷ D) (H u ∷ H w ∷ D)
  hhᴿ w u w≢u D = go (hasH w D) (hasH u D) refl refl
    where
    A = allocs D

    sw : hasH w (H u ∷ D) ≡ hasH w D
    sw = hasH-skip w u w≢u D

    su : hasH u (H w ∷ D) ≡ hasH u D
    su = hasH-skip u w (≢-sym w≢u) D

    step : (ρ : Reorder (allocs (H w ∷ H u ∷ D))) →
           (∀ i → i < A → fwd ρ i ≡ i) →
           (∀ (s : Stream) (x : Assign _) →
              hbit (hasH w D) s A (x w) ≡
              hbit (hasH w (H u ∷ D)) (λ i → s (fwd ρ i))
                   (allocs (H u ∷ D)) (x w)) →
           (∀ (s : Stream) (x : Assign _) →
              hbit (hasH u (H w ∷ D)) s (allocs (H w ∷ D)) (x u) ≡
              hbit (hasH u D) (λ i → s (fwd ρ i)) A (x u)) →
           Reordersᴿ (H w ∷ H u ∷ D) (H u ∷ H w ∷ D)
    step ρ below ew eu = ρ , λ s x a →
      ≈ᶜ-trans
        (traceᴿ-cong D x (λ _ → refl)
          (≈ᶜ-sym (gate-comm (H w) (H u) ((w≢u ∷ []) ∷ [])
                    (hbit (hasH w D) s A (x w))
                    (hbit (hasH u (H w ∷ D)) s (allocs (H w ∷ D)) (x u)) a)))
        (traceᴿ-below D x (λ i i< → cong s (sym (below i i<)))
          (gateᶜ-cong (H u) (eu s x)
            (gateᶜ-cong (H w) (ew s x) (≈ᶜ-refl {a = a}))))

    go : ∀ bw bu → hasH w D ≡ bw → hasH u D ≡ bu →
         Reordersᴿ (H w ∷ H u ∷ D) (H u ∷ H w ∷ D)
    go true true hw hu =
      step (reorder-cast (sym N≡) (exchange A)) (λ i i< → tr-below A i i<)
        (λ s x → trans (hbit-on hw s A (x w))
          (sym (trans (hbit-on (trans sw hw) (λ i → s (tr A i))
                                 (allocs (H u ∷ D)) (x w))
                      (trans (cong (λ i → s (tr A i)) (ifs-on A hu))
                             (cong s (tr-sd A))))))
        (λ s x → trans (hbit-on (trans su hu) s (allocs (H w ∷ D)) (x u))
          (trans (cong s (ifs-on A hw))
            (sym (trans (hbit-on hu (λ i → s (tr A i)) A (x u))
                        (cong s (tr-d A))))))
      where
      N≡ : allocs (H w ∷ H u ∷ D) ≡ suc (suc A)
      N≡ = trans (ifs-on (allocs (H u ∷ D)) (trans sw hw))
                 (cong suc (ifs-on A hu))
    go true false hw hu =
      step reorder-id (λ _ _ → refl)
        (λ s x → trans (hbit-on hw s A (x w))
          (sym (trans (hbit-on (trans sw hw) s (allocs (H u ∷ D)) (x w))
                      (cong s (ifs-off A hu)))))
        (λ s x → trans (hbit-off (trans su hu) s (allocs (H w ∷ D)) (x u))
                       (sym (hbit-off hu s A (x u))))
    go false true hw hu =
      step reorder-id (λ _ _ → refl)
        (λ s x → trans (hbit-off hw s A (x w))
          (sym (hbit-off (trans sw hw) s (allocs (H u ∷ D)) (x w))))
        (λ s x → trans (hbit-on (trans su hu) s (allocs (H w ∷ D)) (x u))
          (trans (cong s (ifs-off A hw)) (sym (hbit-on hu s A (x u)))))
    go false false hw hu =
      step reorder-id (λ _ _ → refl)
        (λ s x → trans (hbit-off hw s A (x w))
          (sym (hbit-off (trans sw hw) s (allocs (H u ∷ D)) (x w))))
        (λ s x → trans (hbit-off (trans su hu) s (allocs (H w ∷ D)) (x u))
                       (sym (hbit-off hu s A (x u))))

  plain′ᴿ : (g h : Gate n) (dis : Disjoint g h) (D : Circuit n) →
            Reordersᴿ (g ∷ h ∷ D) (h ∷ g ∷ D)
  plain′ᴿ (H w) (H u) ((w≢u ∷ []) ∷ []) D = hhᴿ w u w≢u D
  plain′ᴿ g@(H _) h@(S _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis (bitᴿ g D s x) false a)
  plain′ᴿ g@(H _) h@(CZ _ _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis (bitᴿ g D s x) false a)
  plain′ᴿ g@(S _) h@(H _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false (bitᴿ h D s x) a)
  plain′ᴿ g@(S _) h@(S _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false false a)
  plain′ᴿ g@(S _) h@(CZ _ _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false false a)
  plain′ᴿ g@(CZ _ _) h@(H _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false (bitᴿ h D s x) a)
  plain′ᴿ g@(CZ _ _) h@(S _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false false a)
  plain′ᴿ g@(CZ _ _) h@(CZ _ _) dis D = plainᴿ g h D λ s x a →
    ≈ᶜ-sym (gate-comm g h dis false false a)

  ≤-allocs : (g : Gate n) (C : Circuit n) → allocs C ≤ allocs (g ∷ C)
  ≤-allocs (H w) C = at (hasH w C)
    where
    at : ∀ b → allocs C ≤ ifs b (allocs C)
    at true  = ℕ.n≤1+n (allocs C)
    at false = ℕ.≤-refl
  ≤-allocs (S _)    C = ℕ.≤-refl
  ≤-allocs (CZ _ _) C = ℕ.≤-refl

reordersᴿ : {C C′ : Circuit n} → C ∼ C′ → Reordersᴿ C C′
reordersᴿ ∼-refl = reorder-id , λ s x a → ≈ᶜ-refl
reordersᴿ (∼-swap g h dis D) = plain′ᴿ g h dis D
reordersᴿ (∼-cons g {C} {C′} r) =
  reorder-weaken (≤-allocs g C) ρ , λ s x a →
    ≈ᶜ-trans (T s x (gateᶜ g (bitᴿ g C′ s x) a))
             (traceᴿ-cong C x (λ _ → refl)
               (gateᶜ-cong g (bit g s x) ≈ᶜ-refl))
  where
  ρ = proj₁ (reordersᴿ r)
  T = proj₂ (reordersᴿ r)

  bit : (g : Gate _) (s : Stream) (x : Assign _) →
        bitᴿ g C′ s x ≡ bitᴿ g C (λ i → s (fwd ρ i)) x
  bit (H w) s x =
    trans (cong₂ (λ b i → hbit b s i (x w))
                 (sym (hasH-∼ r w)) (sym (allocs-∼ r)))
          (hbit-at (hasH w C) s (λ i → s (fwd ρ i)) (allocs C) (x w)
                   (cong s (sym (fwd-fix ρ (allocs C) ℕ.≤-refl))))
  bit (S _)    s x = refl
  bit (CZ _ _) s x = refl
reordersᴿ (∼-sym {C} {C′} r) =
  reorder-cast (allocs-∼ r) (reorder-inv ρ) , λ s x a →
    ≈ᶜ-sym (≈ᶜ-trans (T (λ i → s (bwd ρ i)) x a)
                     (traceᴿ-cong C x (λ i → cong s (bwd-fwd ρ i)) ≈ᶜ-refl))
  where
  ρ = proj₁ (reordersᴿ r)
  T = proj₂ (reordersᴿ r)
reordersᴿ (∼-trans {C} {C′} {C″} r₁ r₂) =
  reorder-⨾ ρ₁ (reorder-cast (sym (allocs-∼ r₁)) ρ₂) , λ s x a →
    ≈ᶜ-trans (T₂ s x a) (T₁ (λ i → s (fwd ρ₂ i)) x a)
  where
  ρ₁ = proj₁ (reordersᴿ r₁)
  T₁ = proj₂ (reordersᴿ r₁)
  ρ₂ = proj₁ (reordersᴿ r₂)
  T₂ = proj₂ (reordersᴿ r₂)


------------------------------------------------------------------------
-- The theorems

-- Structurally equivalent circuits have path-sums equal up to a
-- renaming of the path variables.

structural : {C C′ : Circuit n} → C ∼ C′ →
             Σ (Permutation (pathsᵁ C) (pathsᵁ C′))
               (λ π → ⟦ C ⟧ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧)
structural {C = C} {C′} r =
  π , ≡ᴿ-by-values ⟦ C ⟧ ⟦ C′ ⟧ π (norm-∼ r) ph ou
  where
  ρ = proj₁ (reorders r)
  T = proj₂ (reorders r)

  eK  = pathsᵁ≡norm C
  eK′ = trans (pathsᵁ≡norm C′) (sym (norm-∼ r))

  π : Permutation (pathsᵁ C) (pathsᵁ C′)
  π = toPerm eK eK′ ρ

  conf : ∀ x (y : Assign (pathsᵁ C′)) →
         trace C (str (λ j → y (π ⟨$⟩ʳ j))) (start x) ≈ᶜ
         trace C′ (str y) (start x)
  conf x y = ≈ᶜ-trans (trace-below C (str-toPerm eK eK′ ρ y) ≈ᶜ-refl)
                      (≈ᶜ-sym (T (str y) (start x)))

  ph : ∀ x y → eval (phase ⟦ C ⟧) x (λ j → y (π ⟨$⟩ʳ j)) ≡
               eval (phase ⟦ C′ ⟧) x y
  ph x y = trans (eval-⟦⟧ C x (λ j → y (π ⟨$⟩ʳ j)))
                 (trans (≈φ (conf x y)) (sym (eval-⟦⟧ C′ x y)))

  ou : ∀ w x y → eval (out ⟦ C ⟧ w) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                 eval (out ⟦ C′ ⟧ w) x y
  ou w x y = trans (eval-out-⟦⟧ C x (λ j → y (π ⟨$⟩ʳ j)) w)
                   (trans (cong [_]ᶻ (≈v (conf x y) w))
                          (sym (eval-out-⟦⟧ C′ x y w)))

structural-≈ : {C C′ : Circuit n} → C ∼ C′ →
               Σ (Permutation (pathsᵁ C) (pathsᵁ C′))
                 (λ π → ⟦ C ⟧ ≈ᴿ⟨ π ⟩ ⟦ C′ ⟧)
structural-≈ r = proj₁ (structural r) , ≡ᴿ⇒≈ᴿ (proj₂ (structural r))

structural-≋ : {C C′ : Circuit n} → C ∼ C′ → ⟦ C ⟧ ≋ ⟦ C′ ⟧
structural-≋ {C = C} {C′} r =
  ≡ᴿ⇒≋ {ξ = ⟦ C ⟧} {π = proj₁ (structural r)} {ζ = ⟦ C′ ⟧}
       (proj₂ (structural r))

-- The same for the isometry restriction.

structuralᴿ : {C C′ : Circuit n} → C ∼ C′ →
              Σ (Permutation (paths C) (paths C′))
                (λ π → ⟦ C ⟧ᴿ ≡ᴿ⟨ π ⟩ ⟦ C′ ⟧ᴿ)
structuralᴿ {C = C} {C′} r =
  π , ≡ᴿ-by-values ⟦ C ⟧ᴿ ⟦ C′ ⟧ᴿ π (norm-∼ r) ph ou
  where
  ρ = proj₁ (reordersᴿ r)
  T = proj₂ (reordersᴿ r)

  eK  = paths≡allocs C
  eK′ = trans (paths≡allocs C′) (sym (allocs-∼ r))

  π : Permutation (paths C) (paths C′)
  π = toPerm eK eK′ ρ

  conf : ∀ x (y : Assign (paths C′)) →
         traceᴿ C (str (λ j → y (π ⟨$⟩ʳ j))) x (start x) ≈ᶜ
         traceᴿ C′ (str y) x (start x)
  conf x y = ≈ᶜ-trans (traceᴿ-below C x (str-toPerm eK eK′ ρ y) ≈ᶜ-refl)
                      (≈ᶜ-sym (T (str y) x (start x)))

  ph : ∀ x y → eval (phase ⟦ C ⟧ᴿ) x (λ j → y (π ⟨$⟩ʳ j)) ≡
               eval (phase ⟦ C′ ⟧ᴿ) x y
  ph x y = trans (eval-⟦⟧ᴿ C x (λ j → y (π ⟨$⟩ʳ j)))
                 (trans (≈φ (conf x y)) (sym (eval-⟦⟧ᴿ C′ x y)))

  ou : ∀ w x y → eval (out ⟦ C ⟧ᴿ w) x (λ j → y (π ⟨$⟩ʳ j)) ≡
                 eval (out ⟦ C′ ⟧ᴿ w) x y
  ou w x y = trans (eval-out-⟦⟧ᴿ C x (λ j → y (π ⟨$⟩ʳ j)) w)
                   (trans (cong [_]ᶻ (≈v (conf x y) w))
                          (sym (eval-out-⟦⟧ᴿ C′ x y w)))

structuralᴿ-≈ : {C C′ : Circuit n} → C ∼ C′ →
                Σ (Permutation (paths C) (paths C′))
                  (λ π → ⟦ C ⟧ᴿ ≈ᴿ⟨ π ⟩ ⟦ C′ ⟧ᴿ)
structuralᴿ-≈ r = proj₁ (structuralᴿ r) , ≡ᴿ⇒≈ᴿ (proj₂ (structuralᴿ r))

structuralᴿ-≋ : {C C′ : Circuit n} → C ∼ C′ → ⟦ C ⟧ᴿ ≋ ⟦ C′ ⟧ᴿ
structuralᴿ-≋ {C = C} {C′} r =
  ≡ᴿ⇒≋ {ξ = ⟦ C ⟧ᴿ} {π = proj₁ (structuralᴿ r)} {ζ = ⟦ C′ ⟧ᴿ}
       (proj₂ (structuralᴿ r))

-- Circuits on disjoint wires may be run in either order:
-- bifunctoriality, for circuits over {H, S, CZ}.

parallel-⟦⟧ : (C D : Circuit n) → Apart C D →
              Σ (Permutation (pathsᵁ (C ++ D)) (pathsᵁ (D ++ C)))
                (λ π → ⟦ C ++ D ⟧ ≡ᴿ⟨ π ⟩ ⟦ D ++ C ⟧)
parallel-⟦⟧ C D ap = structural (∼-parallel C D ap)

parallel-⟦⟧ᴿ : (C D : Circuit n) → Apart C D →
               Σ (Permutation (paths (C ++ D)) (paths (D ++ C)))
                 (λ π → ⟦ C ++ D ⟧ᴿ ≡ᴿ⟨ π ⟩ ⟦ D ++ C ⟧ᴿ)
parallel-⟦⟧ᴿ C D ap = structuralᴿ (∼-parallel C D ap)


------------------------------------------------------------------------
-- The renaming cannot be dropped

-- H on wire 0 then on wire 1, against the other order.  The first
-- Hadamard owns y₁ and the second y₀, so the phase of HH₀₁ is
-- ½ x₀ y₁ + ½ x₁ y₀ and that of HH₁₀ is ½ x₁ y₁ + ½ x₀ y₀: the
-- coefficient of x₀ y₀ is 0 in the one and ½ = 2^(M-1) in the other,
-- not even congruent modulo 2^M.

HH₀₁ HH₁₀ : Circuit 2
HH₀₁ = H zero ∷ H (suc zero) ∷ []
HH₁₀ = H (suc zero) ∷ H zero ∷ []

HH-∼ : HH₀₁ ∼ HH₁₀
HH-∼ = ∼-swap (H zero) (H (suc zero)) (((λ ()) ∷ []) ∷ []) []

private
  γ₀ : Mon 2 2
  γ₀ = inside ∷ outside ∷ [] , inside ∷ outside ∷ []

  at₀₁ : renumberᴾ id (phase ⟦ HH₀₁ ⟧) γ₀ ≡ 0ℤ
  at₀₁ = trans (+-identityˡ (½ * 0ℤ)) (*-zeroʳ ½)

  at₁₀ : phase ⟦ HH₁₀ ⟧ γ₀ ≡ ½
  at₁₀ = trans (+-identityˡ (½ * 1ℤ)) (*-identityʳ ½)

  -- 2^(e+1) does not divide 2^e.
  pow-∤ : ∀ e → ¬ (pow (suc e) ∣ pow e)
  pow-∤ e h = ℕ.<⇒≱ (ℕ.^-monoʳ-< 2 (s≤s (s≤s z≤n)) (ℕ.n<1+n e))
                    (ℕDiv.∣⇒≤ {{ℕ.m^n≢0 2 e}} (∣⇒∣ᵤ h))

-- Not even congruent without the renaming, and so not equal.

renaming-needed-≈ : ¬ (⟦ HH₀₁ ⟧ ≈ᴿ⟨ id ⟩ ⟦ HH₁₀ ⟧)
renaming-needed-≈ (congruent-renamed _ (_ , ph)) = pow-∤ (M ∸ 1) ∣½
  where
  ∣0-½ : pow M ∣ (0ℤ - ½)
  ∣0-½ = subst (pow M ∣_) (cong₂ _-_ at₀₁ at₁₀) (ph γ₀)

  ∣½ : pow M ∣ ½
  ∣½ = subst (pow M ∣_) (neg-involutive ½)
         (∣m⇒∣-m (subst (pow M ∣_) (+-identityˡ (- ½)) ∣0-½))

renaming-needed : ¬ (⟦ HH₀₁ ⟧ ≡ᴿ⟨ id ⟩ ⟦ HH₁₀ ⟧)
renaming-needed r = renaming-needed-≈ (≡ᴿ⇒≈ᴿ r)
