------------------------------------------------------------------------
-- Presentations of groups
--
-- The kernel of the quotient map Figure 8 ↠ Figure 8 mod scalars.
--
-- Figure8-Mod-Scalar is Figure 8 with ω set to 1, so two words equal
-- there are equal in Figure 8 only up to a scalar.  This module proves
-- that this is exactly what is lost:
--
--     w ≈ᵐˢ v  →  ∃ k,  w ≈ᶠ v · ωᵏ                     (kernel)
--
-- by induction on the mod-scalar derivation.  The cases are:
--
--   * refl / assoc / units — the same structural rule of Figure 8, with
--     k = 0 (Ω n ₀ is ε on the nose, which is why Ω is a power rather
--     than a case on the width);
--   * trans, cong — add the two exponents.  cong is the case that needs
--     ω to be CENTRAL: the scalar collected by the left factor has to
--     travel across the right one (Figure8.ω-central);
--   * sym — invert the exponent.  With ℕ exponents that is k ↦ 7k, since
--     ω⁸ = 1 (C1) and k + 7k = 8k definitionally;
--   * axiom — the case analysis proper.  Every mod-scalar axiom is its
--     Figure-8 namesake with a scalar attached: C4 (SHSHSH = 1 there,
--     = ω here) contributes ω¹, C10 and C11 (whose ω⁻¹ tails the quotient
--     drops) contribute ω⁷, and the other eleven contribute nothing.
--     The structural axioms comm₁ / comm₂ are shared verbatim, and
--     cong↑ recurses — which is where the scalar has to be moved from
--     one wire to another (Figure8.ω↑≈ω).
--
-- The scalar word Ω n k is ωᵏ where ω exists (width ≥ 1) and ε at width
-- 0, where the whole circuit type is generated by the empty alphabet.
--
-- What this is for: Qubit.ExactExtension.ExactData asks for `scalars` —
-- a word acting trivially on P4 is a power of ω.  Composing this lemma
-- with completeness of Figure 8 mod scalars (Selinger.Iso, one layer
-- down) gives exactly that.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat using (ℕ ; 2+ ; _+_ ; _*_)
open import Data.Nat.Primality using (Prime)

module Examples.Groups.Clifford.Qubit.Selinger.ScalarKernel
  (p-2 : ℕ) (p-prime : Prime (2+ p-2)) where

open import Data.Nat.Properties using (*-suc)
open import Data.Product using (∃ ; _,_ ; proj₁ ; proj₂)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)

open import Notations
open import Word.Base using (Word ; [_]ʷ ; ε ; _•_ ; _^_)
import Presentation.Base as PB
import Presentation.Properties
open import Presentation.Tactic.AssociativitySolver using (module Assoc)

open import Examples.Groups.Symplectic.Syntactics p-2 p-prime
  using (module Symplectic)
open Symplectic using (Gen ; Circuit ; _↑)

import Examples.Groups.Clifford.Qubit.Selinger.Figure8 p-2 p-prime as F8
import Examples.Groups.Clifford.Qubit.Selinger.Figure8-Mod-Scalar p-2 p-prime as MS
open F8 using (ω ; _≈ᶠ_ ; ω^-central ; ω^↑≈ω^ ; ↑-^)

private
  variable
    n : ℕ

  -- Word-power and associativity machinery, at each width of Figure 8.
  module P (m : ℕ) = Presentation.Properties (m F8.CRel,_===_)
  module A (m : ℕ) = Assoc (m F8.CRel,_===_)

-- Equality in Figure 8 mod scalars.
infix 4 _≈ᵐˢ_
_≈ᵐˢ_ : {n : ℕ} → Circuit n → Circuit n → Set
_≈ᵐˢ_ {n} = PB._≈_ (n MS.CRel,_===_)

------------------------------------------------------------------------
-- The scalar word
--
-- Width 0 has no gates at all, so there is nothing for ω to be; every
-- word is ε there, and taking the scalar to be ε keeps Ω total.  Writing
-- Ω as a POWER (rather than by cases on the width) is what makes
-- Ω n ₀ ≡ ε hold for a variable width — the k = 0 cases below are then
-- literally the Figure-8 rule with a unit appended.

Ω₁ : (n : ℕ) → Circuit n
Ω₁ ₀      = ε
Ω₁ (₁₊ n) = ω

Ω : (n : ℕ) → ℕ → Circuit n
Ω n k = Ω₁ n ^ k

-- At width 0 the scalar is trivial.  (Stated at every width: the
-- width-0 scalar is also met one wire up, as ε ↑.)
ε^ : {m : ℕ} (k : ℕ) → (ε {X = Gen m} ^ k) ≈ᶠ ε
ε^ ₀       = PB.refl
ε^ (₁₊ ₀)  = PB.refl
ε^ (₂₊ k)  = PB.trans PB.left-unit (ε^ (₁₊ k))

-- Exponents add.
Ω-+ : (n j k : ℕ) → Ω n (j + k) ≈ᶠ (Ω n j • Ω n k)
Ω-+ n j k = P.^-+ n (Ω₁ n) j k

-- The scalar is central (this is the point of Figure8.cω).
Ω-central : (n k : ℕ) (w : Circuit n) → (Ω n k • w) ≈ᶠ (w • Ω n k)
Ω-central ₀      k w =
  PB.trans (PB.cong (ε^ k) PB.refl)
    (PB.trans PB.left-unit
      (PB.trans (PB.sym PB.right-unit) (PB.cong PB.refl (PB.sym (ε^ k)))))
Ω-central (₁₊ n) k w = ω^-central k w

-- ω⁸ = 1, so every eighth power vanishes.
Ω-8 : (n k : ℕ) → Ω n (8 * k) ≈ᶠ ε
Ω-8 ₀      k       = ε^ (8 * k)
Ω-8 (₁₊ n) ₀       = PB.refl
Ω-8 (₁₊ n) (₁₊ k)  =
  PB.trans (PB.refl' ((₁₊ n) F8.CRel,_===_) (Eq.cong (ω ^_) (*-suc 8 k)))
    (PB.trans (P.^-+ (₁₊ n) ω 8 (8 * k))
      (PB.trans (PB.cong (PB.axiom (F8.srel F8.c1)) (Ω-8 (₁₊ n) k))
                PB.left-unit))

-- Hence every exponent has an inverse: k + 7k = 8k, on the nose.
Ω-inv : (n k : ℕ) → (Ω n k • Ω n (7 * k)) ≈ᶠ ε
Ω-inv n k = PB.trans (PB.sym (Ω-+ n k (7 * k))) (Ω-8 n k)

-- The scalar moves up a wire (this is the point of Figure8.cω↑).  At
-- width 0 the exponent is simply dropped: ε lifts to ε, which is ω⁰.
Ω-↑ : (n k : ℕ) → ∃ λ k' → ((Ω n k) ↑) ≈ᶠ Ω (₁₊ n) k'
Ω-↑ ₀      k = ₀ ,
  PB.trans (PB.refl' (₁ F8.CRel,_===_) (↑-^ ε k)) (ε^ k)
Ω-↑ (₁₊ n) k = k , ω^↑≈ω^ k

------------------------------------------------------------------------
-- The axioms
--
-- Eleven relations are shared with Figure 8 verbatim, so they need no
-- scalar; C4 needs ω, and C10 / C11 need ω⁻¹ = ω⁷, which is exactly the
-- tail the quotient drops.  (Only those two need re-bracketing: _•_ is
-- infixr, so appending the scalar to the whole right-hand side is not
-- the same term as Figure 8's, which has it inside.)

shared : {w v : Circuit n} → (w ≈ᶠ v) → ∃ λ k → w ≈ᶠ (v • Ω n k)
shared e = ₀ , PB.trans e (PB.sym PB.right-unit)

srel-kernel : {w v : Circuit n} → (n MS.Sel, w === v) → ∃ λ k → w ≈ᶠ (v • Ω n k)
srel-kernel MS.c2  = shared (PB.axiom (F8.srel F8.c2))
srel-kernel MS.c3  = shared (PB.axiom (F8.srel F8.c3))
srel-kernel MS.c5  = shared (PB.axiom (F8.srel F8.c5))
srel-kernel MS.c6  = shared (PB.axiom (F8.srel F8.c6))
srel-kernel MS.c7  = shared (PB.axiom (F8.srel F8.c7))
srel-kernel MS.c8  = shared (PB.axiom (F8.srel F8.c8))
srel-kernel MS.c9  = shared (PB.axiom (F8.srel F8.c9))
srel-kernel MS.c12 = shared (PB.axiom (F8.srel F8.c12))
srel-kernel MS.c13 = shared (PB.axiom (F8.srel F8.c13))
srel-kernel MS.c14 = shared (PB.axiom (F8.srel F8.c14))
srel-kernel MS.c15 = shared (PB.axiom (F8.srel F8.c15))

-- C4: mod scalars (SH)³ = 1, and in Figure 8 that word IS ω.
srel-kernel MS.c4 = ₁ , PB.sym PB.left-unit

-- C10 / C11: Figure 8 keeps a trailing ω⁻¹ = ω⁷ inside the right-hand
-- side; the quotient drops it.  Same letters, different brackets.
srel-kernel (MS.c10 {n}) =
  ₇ , A.by-assoc-and (₂₊ n) (PB.axiom (F8.srel F8.c10)) Eq.refl Eq.refl
srel-kernel (MS.c11 {n}) =
  ₇ , A.by-assoc-and (₂₊ n) (PB.axiom (F8.srel F8.c11)) Eq.refl Eq.refl

------------------------------------------------------------------------
-- The induction

axiom-kernel : {w v : Circuit n} → (n MS.VRel, w === v) → ∃ λ k → w ≈ᶠ (v • Ω n k)
axiom-kernel (MS.srel r)     = srel-kernel r
axiom-kernel (MS.comm₁ h g)  = shared (PB.axiom (F8.comm₁ h g))
axiom-kernel (MS.comm₂ h g)  = shared (PB.axiom (F8.comm₂ h g))
axiom-kernel (MS.cong↑ {n} x) with axiom-kernel x
... | k , e with Ω-↑ n k
...   | k' , e' = k' ,
  PB.trans (F8.lemma-cong↑ _ _ e) (PB.cong PB.refl e')

kernel : {w v : Circuit n} → w ≈ᵐˢ v → ∃ λ k → w ≈ᶠ (v • Ω n k)
kernel PB.refl        = ₀ , PB.sym PB.right-unit
kernel PB.assoc       = ₀ , PB.trans PB.assoc (PB.sym PB.right-unit)
kernel PB.left-unit   = ₀ , PB.trans PB.left-unit (PB.sym PB.right-unit)
kernel PB.right-unit  = ₀ , PB.trans PB.right-unit (PB.sym PB.right-unit)
kernel (PB.axiom x)   = axiom-kernel x

kernel {n} (PB.sym e) with kernel e
... | k , d = 7 * k , PB.sym
  (PB.trans (PB.cong d PB.refl)
    (PB.trans PB.assoc
      (PB.trans (PB.cong PB.refl (Ω-inv n k)) PB.right-unit)))

kernel {n} (PB.trans e f) with kernel e | kernel f
... | k₁ , d₁ | k₂ , d₂ = k₂ + k₁ ,
  PB.trans d₁
    (PB.trans (PB.cong d₂ PB.refl)
      (PB.trans PB.assoc (PB.cong PB.refl (PB.sym (Ω-+ n k₂ k₁)))))

kernel {n} (PB.cong {v = w'} {v' = v'} e f) with kernel e | kernel f
... | k , d | k' , d' = k + k' ,
  PB.trans (PB.cong d d')
    (PB.trans PB.assoc
      (PB.trans (PB.cong PB.refl (PB.sym PB.assoc))
        (PB.trans (PB.cong PB.refl (PB.cong (Ω-central n k v') PB.refl))
          (PB.trans (PB.cong PB.refl PB.assoc)
            (PB.trans (PB.sym PB.assoc)
                      (PB.cong PB.refl (PB.sym (Ω-+ n k k'))))))))

------------------------------------------------------------------------
-- The form the exact layer needs
--
-- A word that dies in the quotient is a scalar.  This is `scalars` of
-- Qubit.ExactExtension.ExactData except for its hypothesis, which is
-- semantic (w acts trivially on P4) where this one is syntactic (w = 1
-- mod scalars); bridging the two is completeness of Figure 8 mod
-- scalars, i.e. Selinger.Iso together with the extension presentation.

kernel-ε : {w : Circuit n} → w ≈ᵐˢ ε → ∃ λ k → w ≈ᶠ Ω n k
kernel-ε e with kernel e
... | k , d = k , PB.trans d PB.left-unit
