------------------------------------------------------------------------
-- Presentations of groups
--
-- The kernel of the quotient map Figure 8 ↠ Figure 8 mod scalars.
--
-- Figure8-Mod-Scalar is Figure 8 with ω set to 1, so two words equal
-- there are equal in Figure 8 only up to a scalar.  This module proves
-- that this is exactly what is lost:
--
--     w ≈ᵐˢ v  →  ∃ k,  w ≈ᶠ v · ωᵏ                     (kernel)
--
-- by induction on the mod-scalar derivation.  The cases are:
--
--   * refl / assoc / units — the same structural rule of Figure 8, with
--     k = 0 (Ω n ₀ is ε on the nose, which is why Ω is a power rather
--     than a case on the width);
--   * trans, cong — add the two exponents.  cong is the case that needs
--     ω to be CENTRAL: the scalar collected by the left factor has to
--     travel across the right one (Figure8.ω-central);
--   * sym — invert the exponent.  With ℕ exponents that is k ↦ 7k, since
--     ω⁸ = 1 (C1) and k + 7k = 8k definitionally;
--   * axiom — the case analysis proper.  Every mod-scalar axiom is its
--     Figure-8 namesake with a scalar attached: C4 (SHSHSH = 1 there,
--     = ω here) contributes ω¹, C10 and C11 (whose ω⁻¹ tails the quotient
--     drops) contribute ω⁷, and the other eleven contribute nothing.
--     The structural axioms comm₁ / comm₂ are shared verbatim, and
--     cong↑ recurses — which is where the scalar has to be moved from
--     one wire to another (Figure8.ω↑≈ω).
--
-- The scalar word Ω n k is ωᵏ where ω exists (width ≥ 1) and ε at width
-- 0, where the whole circuit type is generated by the empty alphabet.
--
-- What this is for: Qubit.ExactExtension.ExactData asks for `scalars` —
-- a word acting trivially on P4 is a power of ω.  Composing this lemma
-- with completeness of Figure 8 mod scalars (Selinger.Iso, one layer
-- down) gives exactly that.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

open import Data.Nat using (ℕ ; 2+ ; _+_ ; _*_)
open import Data.Nat.Primality using (Prime)

module Examples.Groups.Clifford.Qubit.Selinger.ScalarKernel
  (p-2 : ℕ) (p-prime : Prime (2+ p-2)) where

open import Data.Nat.Properties using (*-suc)
open import Data.Product using (∃ ; _,_ ; proj₁ ; proj₂)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)

open import Notations
open import Word.Base using (Word ; [_]ʷ ; ε ; _•_ ; _^_)
import Presentation.Base as PB
import Presentation.Properties
open import Presentation.Tactic.AssociativitySolver using (module Assoc)

open import Examples.Groups.Symplectic.Syntactics p-2 p-prime
  using (module Symplectic)
open Symplectic using (Gen ; Circuit ; _↑)

import Examples.Groups.Clifford.Qubit.Selinger.Figure8 p-2 p-prime as F8
import Examples.Groups.Clifford.Qubit.Selinger.Figure8-Mod-Scalar p-2 p-prime as MS
open F8 using (ω ; _≈ᶠ_ ; ω^-central ; ω^↑≈ω^ ; ↑-^)

-- Figure 8 and its mod-scalar quotient no longer share an alphabet: the
-- quotient kept SympGate, Figure 8 has ExactGate.  E relabels a
-- mod-scalar word into Figure 8's, and every statement below compares
-- E-images rather than words.
import Examples.Groups.Clifford.Qubit.Selinger.Relabel p-2 p-prime as RL
open RL using (E ; E-↑)

private
  variable
    n : ℕ

  -- Word-power and associativity machinery, at each width of Figure 8.
  module P (m : ℕ) = Presentation.Properties (m F8.CRel,_===_)
  module A (m : ℕ) = Assoc (m F8.CRel,_===_)

-- Equality in Figure 8 mod scalars.
infix 4 _≈ᵐˢ_
_≈ᵐˢ_ : {n : ℕ} → Circuit n → Circuit n → Set
_≈ᵐˢ_ {n} = PB._≈_ (n MS.CRel,_===_)

------------------------------------------------------------------------
-- The scalar word
--
-- ω is a 0-ary generator now, so it exists at every width and Ω is a
-- plain power.  The width-0 special case this section used to carry —
-- there was no ω to write at width 0, so Ω₁ put ε there, and ε^ and a
-- split in every lemma followed — has gone entirely.

Ω : (n : ℕ) → ℕ → F8.Circuit n
Ω n k = ω ^ k

-- Exponents add.
Ω-+ : (n j k : ℕ) → Ω n (j + k) ≈ᶠ (Ω n j • Ω n k)
Ω-+ n j k = P.^-+ n ω j k

-- The scalar is central (Circuit.Base's comm₀, via Figure8.ω^-central).
Ω-central : (n k : ℕ) (w : F8.Circuit n) → (Ω n k • w) ≈ᶠ (w • Ω n k)
Ω-central n k w = ω^-central k w

-- ω⁸ = 1, so every eighth power vanishes.
Ω-8 : (n k : ℕ) → Ω n (8 * k) ≈ᶠ ε
Ω-8 n ₀      = PB.refl
Ω-8 n (₁₊ k) =
  PB.trans (PB.refl' (n F8.CRel,_===_) (Eq.cong (ω ^_) (*-suc 8 k)))
    (PB.trans (P.^-+ n ω 8 (8 * k))
      (PB.trans (PB.cong (PB.axiom (F8.srel F8.c1)) (Ω-8 n k))
                PB.left-unit))

-- Hence every exponent has an inverse: k + 7k = 8k, on the nose.
Ω-inv : (n k : ℕ) → (Ω n k • Ω n (7 * k)) ≈ᶠ ε
Ω-inv n k = PB.trans (PB.sym (Ω-+ n k (7 * k))) (Ω-8 n k)

-- The scalar moves up a wire (Circuit.Base's ω↑=ω).  The exponent is
-- carried across unchanged, so the ∃ this used to return — needed only
-- to drop the exponent at width 0 — has gone with it.
Ω-↑ : (n k : ℕ) → ((Ω n k) F8.↑) ≈ᶠ Ω (₁₊ n) k
Ω-↑ n k = ω^↑≈ω^ k

------------------------------------------------------------------------
-- The axioms
--
-- Eleven relations are shared with Figure 8 verbatim, so they need no
-- scalar; C4 needs ω, and C10 / C11 need ω⁻¹ = ω⁷, which is exactly the
-- tail the quotient drops.  (Only those two need re-bracketing: _•_ is
-- infixr, so appending the scalar to the whole right-hand side is not
-- the same term as Figure 8's, which has it inside.)

shared : {w v : F8.Circuit n} → (w ≈ᶠ v) → ∃ λ k → w ≈ᶠ (v • Ω n k)
shared e = ₀ , PB.trans e (PB.sym PB.right-unit)

srel-kernel : {w v : Circuit n} →
              (n MS.Sel, w === v) → ∃ λ k → E w ≈ᶠ (E v • Ω n k)
srel-kernel MS.c2  = shared (PB.axiom (F8.srel F8.c2))
srel-kernel MS.c3  = shared (PB.axiom (F8.srel F8.c3))
srel-kernel MS.c5  = shared (PB.axiom (F8.srel F8.c5))
srel-kernel MS.c6  = shared (PB.axiom (F8.srel F8.c6))
srel-kernel MS.c7  = shared (PB.axiom (F8.srel F8.c7))
srel-kernel MS.c8  = shared (PB.axiom (F8.srel F8.c8))
srel-kernel MS.c9  = shared (PB.axiom (F8.srel F8.c9))
srel-kernel MS.c12 = shared (PB.axiom (F8.srel F8.c12))
srel-kernel MS.c13 = shared (PB.axiom (F8.srel F8.c13))
srel-kernel MS.c14 = shared (PB.axiom (F8.srel F8.c14))
srel-kernel MS.c15 = shared (PB.axiom (F8.srel F8.c15))

-- C4: mod scalars (SH)³ = 1, and in Figure 8 that word IS ω — but only
-- by C4 now.  It used to hold definitionally, back when Figure 8 defined
-- ω to BE (SH)³; with ω a generator the axiom has to be invoked.
srel-kernel MS.c4 =
  ₁ , PB.trans (PB.axiom (F8.srel F8.c4)) (PB.sym PB.left-unit)

-- C10 / C11: Figure 8 keeps a trailing ω⁻¹ = ω⁷ inside the right-hand
-- side; the quotient drops it.  Same letters, different brackets.
srel-kernel (MS.c10 {n}) =
  ₇ , A.by-assoc-and (₂₊ n) (PB.axiom (F8.srel F8.c10)) Eq.refl Eq.refl
srel-kernel (MS.c11 {n}) =
  ₇ , A.by-assoc-and (₂₊ n) (PB.axiom (F8.srel F8.c11)) Eq.refl Eq.refl

------------------------------------------------------------------------
-- The induction

axiom-kernel : {w v : Circuit n} →
               (n MS.VRel, w === v) → ∃ λ k → E w ≈ᶠ (E v • Ω n k)
axiom-kernel (MS.srel r)     = srel-kernel r
axiom-kernel (MS.comm₁ h g)  =
  shared (PB.axiom (F8.comm₁ (RL.gate→ h) (RL.sym→ex g)))
axiom-kernel (MS.comm₂ h g)  =
  shared (PB.axiom (F8.comm₂ (RL.gate→ h) (RL.sym→ex g)))
-- E commutes with the shift, so the induction is the width-n result one
-- wire up, with the scalar carried across by Ω-↑.
axiom-kernel (MS.cong↑ {n} {w = u} {v = v} x) with axiom-kernel x
... | k , e = k ,
  Eq.subst₂ _≈ᶠ_ (Eq.sym (E-↑ u))
            (Eq.cong (_• Ω (₁₊ n) k) (Eq.sym (E-↑ v)))
            (PB.trans (F8.lemma-cong↑ _ _ e) (PB.cong PB.refl (Ω-↑ n k)))

kernel : {w v : Circuit n} → w ≈ᵐˢ v → ∃ λ k → E w ≈ᶠ (E v • Ω n k)
kernel PB.refl        = ₀ , PB.sym PB.right-unit
kernel PB.assoc       = ₀ , PB.trans PB.assoc (PB.sym PB.right-unit)
kernel PB.left-unit   = ₀ , PB.trans PB.left-unit (PB.sym PB.right-unit)
kernel PB.right-unit  = ₀ , PB.trans PB.right-unit (PB.sym PB.right-unit)
kernel (PB.axiom x)   = axiom-kernel x

kernel {n} (PB.sym e) with kernel e
... | k , d = 7 * k , PB.sym
  (PB.trans (PB.cong d PB.refl)
    (PB.trans PB.assoc
      (PB.trans (PB.cong PB.refl (Ω-inv n k)) PB.right-unit)))

kernel {n} (PB.trans e f) with kernel e | kernel f
... | k₁ , d₁ | k₂ , d₂ = k₂ + k₁ ,
  PB.trans d₁
    (PB.trans (PB.cong d₂ PB.refl)
      (PB.trans PB.assoc (PB.cong PB.refl (PB.sym (Ω-+ n k₂ k₁)))))

kernel {n} (PB.cong {v = w'} {v' = v'} e f) with kernel e | kernel f
... | k , d | k' , d' = k + k' ,
  PB.trans (PB.cong d d')
    (PB.trans PB.assoc
      (PB.trans (PB.cong PB.refl (PB.sym PB.assoc))
        (PB.trans (PB.cong PB.refl (PB.cong (Ω-central n k (E v')) PB.refl))
          (PB.trans (PB.cong PB.refl PB.assoc)
            (PB.trans (PB.sym PB.assoc)
                      (PB.cong PB.refl (PB.sym (Ω-+ n k k'))))))))

------------------------------------------------------------------------
-- The form the exact layer needs
--
-- A word that dies in the quotient is a scalar.  This is `scalars` of
-- Qubit.ExactExtension.ExactData except for its hypothesis, which is
-- semantic (w acts trivially on P4) where this one is syntactic (w = 1
-- mod scalars); bridging the two is completeness of Figure 8 mod
-- scalars, i.e. Selinger.Iso together with the extension presentation.

kernel-ε : {w : Circuit n} → w ≈ᵐˢ ε → ∃ λ k → E w ≈ᶠ Ω n k
kernel-ε e with kernel e
... | k , d = k , PB.trans d PB.left-unit
