------------------------------------------------------------------------
-- Presentations of groups
--
-- Selinger step 1, continued: the Figure-8 relations left unproved by
-- Qubit.Selinger.Action are sound for the P4 action.
--
-- Action proves C1, C2, C3, C5-C9, C12 and C13 (C4 is an identity, ω
-- being the derived word (SH)³).  This module adds the four that were
-- left — C10, C11, C14, C15 — and the structural rules of Lift-Relation
-- (cong↑, comm₁, comm₂).  Together with Action's lemmas these are all the
-- axiom cases of
--
--     sound : w ≈ᶠ v → w ≈ᶜ v,
--
-- i.e. of the `sound` field of Qubit.ExactExtension.ExactData.  (The two
-- other fields of that record — completeness on the scalars, and
-- faithfulness of ω — are about the datum the P4 action discards, and
-- cannot come from here at all.)
--
-- THE ASSEMBLY, once open, is now closed — see axiom-soundᶠ and sound at
-- the end.  It had resisted every workaround tried (naming the word
-- behind a definition, rewriting through Eq.subst, re-proving C1 by case
-- analysis, sharing Action's p-2 / p-prime so the two ω's are one term);
-- each pushed the failure later without removing it.  The fix was none
-- of those: it is the module's --call-by-name flag.  Call-by-NEED is what
-- duplicates the Pauli once per letter, so the C1 clause over ω⁸ never
-- finished; under call-by-name the whole induction checks in ~310 s.
-- (The heavy symplectic files carry the same flag for the same reason.)
--
-- The shape of the four proofs is forced by how `cact` computes.  Only
-- the phase depends on the incoming phase, and additively, so `lift-eq`
-- (Action) reduces a relation to phase 0.  But `cact` must be applied to
-- a CONCRETE Pauli: cact1 g (s , P) = (s + δ g P , actg g P) mentions P
-- twice, so with a symbolic P the argument is duplicated once per letter
-- — for the 49 letters of C10's right-hand side that is 2⁴⁹ copies, and
-- the check does not terminate.  With the bits concrete every step
-- evaluates to a value and the phase grows linearly.  So each relation is
-- case-split on the Pauli FIRST (16 cases on two qubits, 64 on three) and
-- lift-eq is applied inside each case, where its phase-0 premise is refl.
-- The same reason keeps the ω⁻¹ tail of C10/C11 inside the case analysis
-- rather than being peeled off by cact-ω^ beforehand.
--
-- Everything here is green, in about 310 s.  `sound` at the end is the
-- `sound` field of ExactData; the record's other two fields —
-- completeness on the scalars, and faithfulness of ω — are about the
-- datum the P4 action discards, and cannot come from this module.
------------------------------------------------------------------------

-- --call-by-name: this is what makes the final assembly (axiom-soundᶠ /
-- sound, at the end) typecheck.  Call-by-need duplicates the Pauli once
-- per letter of the word being normalised; call-by-name does not.
{-# OPTIONS --cubical-compatible --safe --call-by-name #-}

module Examples.Groups.Clifford.Qubit.Selinger.Soundness where

open import Data.Nat using (ℕ)
open import Data.Product using (_,_ ; proj₁ ; proj₂)
open import Data.Vec using (_∷_)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)

open import Notations
open import Zp.ModularArithmetic
open import Word.Base using (Word ; [_]ʷ ; ε ; _•_ ; _^_)

import Presentation.Base as PB

-- The prime and its proof are taken FROM Action rather than restated.
-- They would be convertible either way, but not syntactically equal, and
-- then the ω of Action.c1-sound and the ω of this module's Figure 8 would
-- be two different terms: comparing them forces cact to be unfolded along
-- ω⁸'s 48 letters, which is the blow-up described above.
open import Examples.Groups.Clifford.Qubit.Selinger.Action
  using ( p-2 ; p-prime ; swap-add ; lift-eq ; cact-ω
        ; c2-sound ; c3-sound ; c5-sound ; c6-sound ; c7-sound
        ; c8-sound ; c9-sound ; c12-sound ; c13-sound )

open PrimeModulus p-2 p-prime

import Examples.Groups.Symplectic.Syntactics p-2 p-prime as Syn
open Syn.Symplectic
  using ( Gen ; SympGate ; gate₁ ; gate₂ ; H-gate ; S-gate ; CZ-gate
        ; S ; H ; CZ ; ⊤⊥ ; ⊥⊤ ; _↥ ; _↑ ; _↓)

open import Examples.Groups.Pauli.Semantics p-2 p-prime using (Pauli)
open import Examples.Groups.Clifford.Qubit.SignedPauli using (Φ ; P4Carrier ; ι)
open import Examples.Groups.Clifford.Qubit.CliffordAction using (cact ; δ ; incl)
open import Examples.Groups.Clifford.Qubit.CliffordGroup
  using (_≈ᶜ_ ; cact-↑ ; ≈ᶜ-refl ; ≈ᶜ-sym ; ≈ᶜ-trans ; ∙-congᶜ)

import Examples.Groups.Clifford.Qubit.Selinger.Figure8 p-2 p-prime as F8
open F8
  using ( _CRel,_===_ ; srel ; cong↑ ; comm₁ ; comm₂ ; SH ; ω ; ω⁻¹
        ; c1 ; c2 ; c3 ; c4 ; c5 ; c6 ; c7 ; c8 ; c9 ; c10 ; c11
        ; c12 ; c13 ; c14 ; c15 ; cω ; cω↑ )

private
  variable
    n : ℕ

-- Equality of Figure-8 words: the congruence generated by the rule set.
infix 4 _≈ᶠ_
_≈ᶠ_ : {n : ℕ} → Word (Gen n) → Word (Gen n) → Set
_≈ᶠ_ {n} = PB._≈_ (n CRel,_===_)

------------------------------------------------------------------------
-- The four words, named
--
-- Naming them is not cosmetic: a name blocks unfolding.  Conversion
-- checking a goal that mentions the 49 letters of C10's right-hand side
-- literally unfolds cact along all of them, with the blow-up described
-- above; behind a definition the same goals go through.  The equations
-- R10≡ … W15≡ convert back to the literal words of Figure 8, and are
-- cheap because they compare WORDS, never their action.

private

  L10 R10 L11 R11 : Word (Gen (₂₊ n))
  L10 = CZ • H ↑ • CZ
  R10 = SH ↑ • CZ • (S • H • S) ↑ • S ↓ • ω⁻¹
  L11 = CZ • H ↓ • CZ
  R11 = SH ↓ • CZ • (S • H • S) ↓ • S ↑ • ω⁻¹

  W1 : Word (Gen (₁₊ n))
  W1 = ω ^ 8

  W14 W15 : Word (Gen (₃₊ n))
  W14 = (⊤⊥ ↑ • CZ ↓) ^ 3
  W15 = (⊥⊤ ↓ • CZ ↑) ^ 3

  W1≡ : W1 {n} ≡ ω ^ 8
  W1≡ = Eq.refl

  R10≡ : R10 {n} ≡ SH ↑ • CZ • (S • H • S) ↑ • S ↓ • ω⁻¹
  R10≡ = Eq.refl

  R11≡ : R11 {n} ≡ SH ↓ • CZ • (S • H • S) ↓ • S ↑ • ω⁻¹
  R11≡ = Eq.refl

  W14≡ : W14 {n} ≡ (⊤⊥ ↑ • CZ ↓) ^ 3
  W14≡ = Eq.refl

  W15≡ : W15 {n} ≡ (⊥⊤ ↓ • CZ ↑) ^ 3
  W15≡ = Eq.refl

  -- The empty word acts as the identity.  Rewriting with this, rather
  -- than letting the conversion checker discover it, is what keeps the
  -- C1 clause of axiom-sound from unfolding cact along ω⁸'s 48 letters.
  cact-ε : (x : P4Carrier n) → cact ε x ≡ x
  cact-ε x = Eq.refl

  -- C4 is an identity: ω is the derived word (SH)³.  Again a word
  -- equation, so that the C4 clause never compares the two actions.
  ω≡SH^3 : ω {n} ≡ SH ^ 3
  ω≡SH^3 = Eq.refl

------------------------------------------------------------------------
-- The structural rules
--
-- cong↑: shifting a circuit up one wire leaves the new wire 0 alone and
-- runs the old action on the tail (CliffordGroup.cact-↑), so equal action
-- is preserved.

sound-↑ : {w v : Word (Gen n)} → w ≈ᶜ v → (w ↑) ≈ᶜ (v ↑)
sound-↑ {w = w} {v = v} h (s , q ∷ qs) = begin
  cact (w ↑) (s , q ∷ qs)
    ≡⟨ cact-↑ w s q qs ⟩
  proj₁ (cact w (s , qs)) , q ∷ proj₂ (cact w (s , qs))
    ≡⟨ Eq.cong (λ y → proj₁ y , q ∷ proj₂ y) (h (s , qs)) ⟩
  proj₁ (cact v (s , qs)) , q ∷ proj₂ (cact v (s , qs))
    ≡⟨ Eq.sym (cact-↑ v s q qs) ⟩
  cact (v ↑) (s , q ∷ qs) ∎
  where open Eq.≡-Reasoning

-- comm₁/comm₂: a gate at the bottom and a generator shifted up past it
-- touch disjoint wires.  Their Pauli components therefore commute on the
-- nose, and the two conjugation phases — neither of which sees the other
-- gate's wires — only swap order.

comm₁-sound : (h : SympGate 1) (g : Gen n) →
              ([ g ↥ ]ʷ • [ gate₁ h ]ʷ) ≈ᶜ ([ gate₁ h ]ʷ • [ g ↥ ]ʷ)
comm₁-sound H-gate g (s , (a , b) ∷ ps) =
  Eq.cong₂ _,_ (swap-add s (ι (a * b)) (δ g ps)) Eq.refl
comm₁-sound S-gate g (s , (a , b) ∷ ps) =
  Eq.cong₂ _,_ (swap-add s (incl a) (δ g ps)) Eq.refl

comm₂-sound : (h : SympGate 2) (g : Gen n) →
              ([ g ↥ ↥ ]ʷ • [ gate₂ h ]ʷ) ≈ᶜ ([ gate₂ h ]ʷ • [ g ↥ ↥ ]ʷ)
comm₂-sound CZ-gate g (s , (a , b) ∷ (a' , b') ∷ ps) =
  Eq.cong₂ _,_ (swap-add s (ι (a * a')) (δ g ps)) Eq.refl

------------------------------------------------------------------------
-- Centrality of the scalar
--
-- cω is sound for a cheaper reason than the numbered relations: ω acts
-- as the identity on P4 (Action.cact-ω), so both sides of ω · g = g · ω
-- act exactly as g does.  No case analysis on the Pauli is needed —
-- cact-ω has already done it.

cω-sound : (g : Gen (₁₊ n)) → (ω • [ g ]ʷ) ≈ᶜ ([ g ]ʷ • ω)
cω-sound g x = Eq.trans (cact-ω (cact [ g ]ʷ x))
                        (Eq.sym (Eq.cong (cact [ g ]ʷ) (cact-ω x)))

-- ... and so is cω↑, for the same reason one wire up: cact-↑ runs the
-- action of ω on the tail, where cact-ω says it is the identity.
cω↑-sound : ((ω {n}) ↑) ≈ᶜ (ω {₁₊ n})
cω↑-sound (s , q ∷ qs) =
  Eq.trans (cact-↑ ω s q qs)
    (Eq.trans (Eq.cong (λ y → proj₁ y , q ∷ proj₂ y) (cact-ω (s , qs)))
              (Eq.sym (cact-ω (s , q ∷ qs))))

------------------------------------------------------------------------
-- C1
--
-- Action.c1-sound proves cact ω⁸ = id, but *using* it here would compare
-- its statement against this clause's goal and unfold cact along the 48
-- letters of ω⁸ with a symbolic argument.  Re-proving it by the case
-- analysis below costs four concrete evaluations instead.

c1-sound' : (x : P4Carrier (₁₊ n)) → cact W1 x ≡ cact ε x
c1-sound' (s , P@((₀ , ₀) ∷ ps)) = lift-eq W1 ε s P Eq.refl
c1-sound' (s , P@((₀ , ₁) ∷ ps)) = lift-eq W1 ε s P Eq.refl
c1-sound' (s , P@((₁ , ₀) ∷ ps)) = lift-eq W1 ε s P Eq.refl
c1-sound' (s , P@((₁ , ₁) ∷ ps)) = lift-eq W1 ε s P Eq.refl

------------------------------------------------------------------------
-- C10 and C11
--
-- 16 two-qubit cases each, ω⁻¹ tail included.

c10-sound : (x : P4Carrier (₂₊ n)) → cact L10 x ≡ cact R10 x
c10-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl
c10-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L10 R10 s P Eq.refl

c11-sound : (x : P4Carrier (₂₊ n)) → cact L11 x ≡ cact R11 x
c11-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl
c11-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ ps)) =
  lift-eq L11 R11 s P Eq.refl

------------------------------------------------------------------------
-- C14 and C15
--
-- Order-3 relations on three wires, in the H/CZ words ⊤⊥ and ⊥⊤: 64
-- three-qubit cases each.

c14-sound : (x : P4Carrier (₃₊ n)) → cact W14 x ≡ cact ε x
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W14 ε s P Eq.refl
c14-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W14 ε s P Eq.refl

c15-sound : (x : P4Carrier (₃₊ n)) → cact W15 x ≡ cact ε x
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₀ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₀) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₀ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₀) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₀ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₀) ∷ ps)) = lift-eq W15 ε s P Eq.refl
c15-sound (s , P@((₁ , ₁) ∷ (₁ , ₁) ∷ (₁ , ₁) ∷ ps)) = lift-eq W15 ε s P Eq.refl


------------------------------------------------------------------------
-- Closing the induction: Figure 8 is sound for the P4 action
--
-- Every axiom has its lemma above (or in Selinger.Action); cong↑ is
-- sound-↑, comm₁ / comm₂ are the two lemmas of the structural section,
-- and C4 is an identity since ω is the derived word (SH)³.  The
-- congruence cases are structural: cact of a concatenation is the
-- composite, so assoc and the two unit laws hold on the nose.
--
-- This is the sound field of Qubit.ExactExtension.ExactData.

axiom-soundᶠ : {n : ℕ} {w v : Word (Gen n)} → (n CRel, w === v) → w ≈ᶜ v
axiom-soundᶠ (srel c1)      = c1-sound'
axiom-soundᶠ (srel c2)      = c2-sound
axiom-soundᶠ (srel c3)      = c3-sound
axiom-soundᶠ (srel c4)      = λ _ → Eq.refl
axiom-soundᶠ (srel c5)      = c5-sound
axiom-soundᶠ (srel c6)      = c6-sound
axiom-soundᶠ (srel c7)      = c7-sound
axiom-soundᶠ (srel c8)      = c8-sound
axiom-soundᶠ (srel c9)      = c9-sound
axiom-soundᶠ (srel c10)     = c10-sound
axiom-soundᶠ (srel c11)     = c11-sound
axiom-soundᶠ (srel c12)     = c12-sound
axiom-soundᶠ (srel c13)     = c13-sound
axiom-soundᶠ (srel c14)     = c14-sound
axiom-soundᶠ (srel c15)     = c15-sound
axiom-soundᶠ (srel (cω g))  = cω-sound g
axiom-soundᶠ (srel cω↑)     = cω↑-sound
axiom-soundᶠ (cong↑ {w = w} {v = v} r) =
  sound-↑ {w = w} {v = v} (axiom-soundᶠ r)
axiom-soundᶠ (comm₁ h g)    = comm₁-sound h g
axiom-soundᶠ (comm₂ h g)    = comm₂-sound h g

sound : {n : ℕ} {w v : Word (Gen n)} → w ≈ᶠ v → w ≈ᶜ v
sound {w = w}          PB.refl         = ≈ᶜ-refl {w = w}
sound {w = w} {v}      (PB.sym e)      = ≈ᶜ-sym {w = v} {v = w} (sound e)
sound {w = w} {v}      (PB.trans {v = u} e f) =
  ≈ᶜ-trans {w = w} {v = u} {u = v} (sound e) (sound f)
sound (PB.cong {w = a} {w' = a'} {v = b} {v' = b'} e f) =
  ∙-congᶜ {w = a} {a'} {b} {b'} (sound e) (sound f)
sound {w = w}          PB.assoc        = ≈ᶜ-refl {w = w}
sound {w = w}          PB.left-unit    = ≈ᶜ-refl {w = w}
sound {w = w}          PB.right-unit   = ≈ᶜ-refl {w = w}
sound (PB.axiom x)                     = axiom-soundᶠ x
