------------------------------------------------------------------------
-- Presentations of groups
--
-- The Clifford extension as a twisted product of *presented* groups
-- (p = 2):
--
--     1 ─→ K ─→ K ×_f Q ─→ Q ─→ 1
--
-- where both sides are groups of words modulo a congruence:
--
--   * K = the Pauli group presented by
--     Examples.Groups.ProjectivePauli.Presentation-Alt — words over the
--     circuit generators X, Z on each wire, modulo order-X, order-Z,
--     comm-Z-X and the structural circuit rules.  It is abelian
--     (Presentation-Alt.word-comm), which is what the factor-set
--     construction needs of a kernel;
--   * Q = the symplectic group presented by the SIMPLIFIED rule set,
--     Examples.Groups.Symplectic.Simplified.Syntactics — words over the
--     Clifford generators H, S, CZ modulo order-S, order-H, M-power,
--     semi-MS, the two semi-M·CZ rules, order-CZ, the two comm-CZ-S
--     rules and selinger-c10 … c15.
--
-- Both are `•-ε-group` of Presentation.GroupLike.Group-Lemmas: the
-- carrier is Word Gen, the equality is the congruence generated by the
-- rules, and the inverse comes from the Grouplike witness each
-- development supplies.
--
-- φ, the action of Q on K, is conjugation.  A symplectic generator g
-- sends a Pauli generator y to the normal form of the vector
-- actg g ⟦ y ⟧₀, and this extends to Pauli words by (_ ⁿ') and to
-- symplectic words by (_ ʰ').  Its two structural laws hold on the nose,
-- as propositional equalities of words — act u is a monoid endomorphism
-- of the free monoid, before any quotient.  That it descends to the two
-- quotients is proved through the semantics, exactly as
-- ProjectiveClifford.Qupit.SemiDirect.ConjAction does for odd p:
-- conjugating a Pauli word computes the symplectic action on its vector
-- (actw-sem), so
--
--   * act u respects the Pauli rules because they have equal readings
--     and the Pauli presentation is complete (act-congʳ);
--   * act respects the symplectic rules because their two sides denote
--     the same symplectic transformation, hence act alike (act-congˡ).
--
-- Both presentation theorems used here are proved for every prime, so
-- they hold at p = 2: Presentation-Alt.Build.sound / .complete, and
-- Simplified.Presentation.presentation (which rests in turn on
-- Symplectic.PresentationFull).
--
-- γ, the factor set, comes from Presentation.Construct.Properties.
-- CocycleGen, which also supplies K and Q here: give the correction one
-- symplectic generator carries against a word and it extends that along
-- the first argument, the recursion being the cocycle identity itself.
-- So the identity and the left normalisation are free.  The correction
-- itself is built here, out of the ε-patched symplectic normal form
-- (Simplified.Bijective) as a lifting ℓ = secn and the Clifford group's
-- kernel witness (CliffordGroup.ker-witness) to read off the Pauli part
-- of ℓ u · ℓ v · ℓ (u • v)⁻¹.  Its congruence and normalisation follow
-- from the section's congruence, which is PROPOSITIONAL — the normal
-- forms are a datatype — and from the uniqueness of the kernel witness.
--
-- That the extension really is the Clifford group is what makes the last
-- condition true: CocycleGen's recursion, applied to a correction that
-- is a defect at generators, produces the defect at every pair of words
-- (incl-sem-defect), because conjugating incl P by a Clifford word is
-- incl of the symplectic action (CliffordGroup.conj-incl).  The relator
-- condition f-axiom is then immediate, the defect seeing only secn.  Its
-- shadow is `corr` of Qubit.Cocycle, whose single nontrivial entry is
-- corr (order-S) = Z₀ — the syntactic counterpart of S² = Z.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.ProjectiveClifford.Qubit.Semantics.Sem3 where

open import Algebra.Bundles using (AbelianGroup ; Group)
open import Algebra.Morphism.Structures
  using (module GroupMorphisms ; module MonoidMorphisms)
open import Data.Nat using (ℕ ; zero)
open import Level using (0ℓ)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_ ; _≗_)

open import Notations using (₁₊)
open import Word.Base using (Word ; WRel ; [_]ʷ ; ε ; _•_ ; _ⁿ' ; _ʰ')

import Algebra.Properties.Group as GroupProperties
import Relation.Binary.Reasoning.Setoid as ≈-Reasoning
import Presentation.Base as PB
import Presentation.Construct.Properties.CocycleGen as CG
open import Presentation.Definitions using (_IsPresentationOf_)

open import ForStdlib.Algebra.Construct.Extension using (Extension)
open import ForStdlib.Algebra.Construct.SemiDirectProduct using (Action)
open import ForStdlib.Algebra.Morphism.Consequences
  using (isMonoidHomomorphism⇒isGroupHomomorphism)
import ForStdlib.Algebra.Construct.FactorSetExtension as FSE
open FSE using (FactorSet)

-- Qubit case: fix the prime to 2 (and with it the primitive root, ℤ*₂
-- being trivial).
open import ForStdlib.Data.Fin.Mod.Prime.Two using (p-2 ; p-prime ; g* ; g-gen)

open import Examples.Groups.ProjectivePauli.Semantics p-2 p-prime
  using (_+ₚ_ ; pIₙ)
open import Examples.Groups.Symplectic.Semantics p-2 p-prime
  using (Symplectic ; _≈ˢ_ ; _∘ˢ_ ; εˢ ; _⁻¹ˢ ; module Interpretation)
open import Examples.Construct.SemiDirectProduct.Clifford p-2 p-prime
  using (ap-ε)
import Examples.Groups.ProjectivePauli.Presentation-Alt p-2 p-prime as PA
import Examples.Groups.Symplectic.Simplified.Syntactics p-2 p-prime g* g-gen
  as SS
import Examples.Groups.Symplectic.Simplified.Lemmas p-2 p-prime g* g-gen as SL
import Examples.Groups.Symplectic.Simplified.Presentation p-2 p-prime g* g-gen
  as SimPres
import Examples.Groups.Symplectic.Simplified.Bijective p-2 p-prime g* g-gen as SB
open import Examples.Groups.ProjectiveClifford.Qubit.CliffordAction using (cact)
import Examples.Groups.ProjectiveClifford.Qubit.CliffordGroup as CLG
import Normalization.NormalForm.Setoid as SNF

open Symplectic using (ap ; ap⁻¹ ; invʳ ; linear-+)
open Interpretation using (actg ; ⟦_⟧ᵍ ; ⟦_⟧)

------------------------------------------------------------------------
-- The two alphabets and the two rule sets

-- Pauli side: the X/Z circuit generators of Presentation-Alt.
PGen : ℕ → Set
PGen = PA.Gen

-- Symplectic side: the H/S/CZ circuit generators, shared between the
-- plain and the simplified symplectic presentations.
SGen : ℕ → Set
SGen = SS.Symplectic.Gen

ΓK : (n : ℕ) → WRel (PGen n)
ΓK n = PA._QRel,_===_ n

ΓQ : (n : ℕ) → WRel (SGen n)
ΓQ n = SS.Simplified-Relations._QRel,_===_ n

------------------------------------------------------------------------
-- Conjugation, on words
--
-- A Pauli generator reads as a basis vector of the phase space, a
-- symplectic generator moves that vector by actg, and inv-nf reads the
-- result back as a Pauli word.  So conjGen g y is the Pauli word equal,
-- inside Clifford, to g · y · g⁻¹.

conjGen : ∀ {n} → SGen n → PGen n → Word (PGen n)
conjGen g y = PA.inv-nf (actg g PA.⟦ y ⟧₀)

-- The action of a symplectic word on a Pauli word: a generator acts on a
-- word letter by letter, and a product acts by its factors in turn (the
-- right one first, matching ⟦ u • v ⟧ = ⟦ u ⟧ ∘ˢ ⟦ v ⟧).
act : ∀ {n} → Word (SGen n) → Word (PGen n) → Word (PGen n)
act = (conjGen ʰ')

------------------------------------------------------------------------
-- The structural action laws
--
-- act u is a monoid endomorphism of the free monoid of Pauli words, and
-- act is a monoid homomorphism from symplectic words into those
-- endomorphisms.  All of this holds before any quotient is taken, so
-- these are propositional equalities of words.

act-ε : ∀ {n} (u : Word (SGen n)) → act u ε ≡ ε
act-ε [ g ]ʷ  = Eq.refl
act-ε ε       = Eq.refl
act-ε (u • v) = Eq.trans (Eq.cong (act u) (act-ε v)) (act-ε u)

act-• : ∀ {n} (u : Word (SGen n)) (w w′ : Word (PGen n)) →
        act u (w • w′) ≡ act u w • act u w′
act-• [ g ]ʷ  w w′ = Eq.refl
act-• ε       w w′ = Eq.refl
act-• (u • v) w w′ =
  Eq.trans (Eq.cong (act u) (act-• v w w′)) (act-• u (act v w) (act v w′))

------------------------------------------------------------------------
-- The bridge to the semantics
--
-- Conjugating a Pauli word computes the symplectic action on the vector
-- it reads as.  The generator case is exactly sem-inv, that inv-nf is a
-- section of sem; the rest is that both sides are additive.

conj-sem : ∀ {n} (g : SGen n) (w : Word (PGen n)) →
           PA.sem ((conjGen ⁿ') g w) ≡ actg g (PA.sem w)
conj-sem g [ y ]ʷ  = PA.sem-inv (actg g PA.⟦ y ⟧₀)
conj-sem g ε       = Eq.sym (ap-ε ⟦ g ⟧ᵍ)
conj-sem g (w • w′) =
  Eq.trans (Eq.cong₂ _+ₚ_ (conj-sem g w) (conj-sem g w′))
           (Eq.sym (linear-+ ⟦ g ⟧ᵍ (PA.sem w) (PA.sem w′)))

actw-sem : ∀ {n} (u : Word (SGen n)) (w : Word (PGen n)) →
           PA.sem (act u w) ≡ ap ⟦ u ⟧ (PA.sem w)
actw-sem [ g ]ʷ  w = conj-sem g w
actw-sem ε       w = Eq.refl
actw-sem (u • v) w =
  Eq.trans (actw-sem u (act v w)) (Eq.cong (ap ⟦ u ⟧) (actw-sem v w))

------------------------------------------------------------------------
-- Soundness of the simplified symplectic presentation
--
-- Equal symplectic words denote the same transformation, so they act
-- alike.  The presentation's own interpretation is the extension of
-- ⟦_⟧ᵍ, which is ⟦_⟧ written out, so the two agree.

private
  module SimP {n : ℕ} = _IsPresentationOf_ (SimPres.presentation {n})
  module SIso {n : ℕ} = GroupMorphisms.IsGroupIsomorphism
                          (_IsPresentationOf_.iso (SimPres.presentation {n}))

denote-agrees : ∀ {n} (u : Word (SGen n)) → SimP.⟦ u ⟧ ≡ ⟦ u ⟧
denote-agrees [ g ]ʷ  = Eq.refl
denote-agrees ε       = Eq.refl
denote-agrees (u • v) = Eq.cong₂ _∘ˢ_ (denote-agrees u) (denote-agrees v)

denote-eq : ∀ {n} {u v : Word (SGen n)} →
            PB._≈_ (ΓQ n) u v → ap ⟦ u ⟧ ≗ ap ⟦ v ⟧
denote-eq {n} {u} {v} e x = begin
  ap ⟦ u ⟧ x       ≡⟨ Eq.cong (λ S → ap S x) (Eq.sym (denote-agrees u)) ⟩
  ap SimP.⟦ u ⟧ x  ≡⟨ SIso.⟦⟧-cong e x ⟩
  ap SimP.⟦ v ⟧ x  ≡⟨ Eq.cong (λ S → ap S x) (denote-agrees v) ⟩
  ap ⟦ v ⟧ x       ∎
  where open Eq.≡-Reasoning

-- Conversely, words that denote the same transformation are equal: the
-- simplified rule set is complete, so the presentation's isomorphism is
-- injective.
denote-injective : ∀ {n} {u v : Word (SGen n)} →
                   ap ⟦ u ⟧ ≗ ap ⟦ v ⟧ → PB._≈_ (ΓQ n) u v
denote-injective {n} {u} {v} e = SIso.injective (λ x → begin
  ap SimP.⟦ u ⟧ x  ≡⟨ Eq.cong (λ S → ap S x) (denote-agrees u) ⟩
  ap ⟦ u ⟧ x       ≡⟨ e x ⟩
  ap ⟦ v ⟧ x       ≡⟨ Eq.cong (λ S → ap S x) (Eq.sym (denote-agrees v)) ⟩
  ap SimP.⟦ v ⟧ x  ∎)
  where open Eq.≡-Reasoning

------------------------------------------------------------------------
-- K, Q and φ

module _ (n : ℕ) where

  private
    -- Both presented groups, and the machinery that turns generator-level
    -- cocycle data into a factor set, come from CocycleGen: K is its
    -- abelian group of Pauli words (abelian by PA.gen-comm, lifted there
    -- to words), Q its group of symplectic words.
    module CGn = CG.Generator-Data (ΓK n) (ΓQ n)
                   (PA.XZ-GroupLike.grouplike {n})
                   (SL.Symplectic-Sim-GroupLike.grouplike {n})
                   (PA.gen-comm {n})
    module KB = PB (ΓK n)
    module QB = PB (ΓQ n)
    module BK = PA.Build n

  -- K: the Pauli presentation, an abelian group of words.
  K : AbelianGroup 0ℓ 0ℓ
  K = CGn.K

  -- Q: the simplified symplectic presentation, a group of words.
  Q : Group 0ℓ 0ℓ
  Q = CGn.Q

  private
    module KA = AbelianGroup K

  -- act u respects the Pauli rules: equal Pauli words go in, words with
  -- equal readings come out, and the Pauli presentation is complete.
  act-congʳ : ∀ (u : Word (SGen n)) {w w′ : Word (PGen n)} →
              KB._≈_ w w′ → KB._≈_ (act u w) (act u w′)
  act-congʳ u {w} {w′} e = BK.complete
    (Eq.trans (actw-sem u w)
      (Eq.trans (Eq.cong (ap ⟦ u ⟧) (BK.sound e))
                (Eq.sym (actw-sem u w′))))

  -- act respects the symplectic rules: equal symplectic words act alike,
  -- so the action factors through Q.
  act-congˡ : ∀ {u v : Word (SGen n)} (w : Word (PGen n)) →
              QB._≈_ u v → KB._≈_ (act u w) (act v w)
  act-congˡ {u} {v} w e = BK.complete
    (Eq.trans (actw-sem u w)
      (Eq.trans (denote-eq e (PA.sem w)) (Eq.sym (actw-sem v w))))

  φ : Action (AbelianGroup.rawMonoid K) (Group.rawMonoid Q)
  φ = record
    { act          = act
    ; act-cong     = λ {u} {u′} {w} {w′} eu ew →
                       KB.trans (act-congˡ w eu) (act-congʳ u′ ew)
    ; act-ε-homo   = λ u → KB.refl' (act-ε u)
    ; act-∙-homo   = λ u w w′ → KB.refl' (act-• u w w′)
    ; act-identity = λ _ → KB.refl
    ; act-compose  = λ _ _ _ → KB.refl
    }

  ------------------------------------------------------------------------
  -- γ: the factor set
  --
  -- The four cocycle laws are not separate obligations: by Theorem 9.8's
  -- necessity direction, an extension of Q by K realising φ, together
  -- with a unit-preserving lifting, determines its factor set and proves
  -- them all.  So the whole of γ reduces to one record.

  γ-of-lifting : {f : Word (SGen n) → Word (SGen n) → Word (PGen n)} →
                 FSE.IsFactorSet K Q φ f → FactorSet K Q φ
  γ-of-lifting {f} ifs = record
    { f                   = f
    ; isNormalisedCocycle = FSE.isFactorSet⇒isNormalisedCocycle K Q φ ifs
    }

  -- That route needs the Clifford group as an extension of Q by K
  -- together with a lifting, i.e. a symplectic normal form; two lemmas
  -- are missing for it (that conjugating incl P by a Clifford word is
  -- incl of the symplectic action, and a UniqueNormalForm for the
  -- SIMPLIFIED rule set).
  --
  -- The second route, taken here, is Presentation.Construct.Properties.
  -- CocycleGen: give the corrections carried by ONE symplectic generator
  -- against a word and let it extend them along the first argument.  The
  -- recursion there is the cocycle identity, so the identity and
  -- normalisation on the left come for free, and the four things it asks
  -- for are all proved below:
  --
  --   G       the Pauli word by which the lifts of a and of v fail to
  --           compose — built below out of the symplectic normal form
  --           and the Clifford group's kernel witness;
  --   G-cong  G a descends to Q — because the section's congruence is
  --           propositional and the kernel witness is unique;
  --   G-ε     G a ε ≈ ε — because the section takes ε to ε;
  --   f-axiom each relator of the simplified rule set carries the same
  --           correction on either side — because the recursion extends
  --           the defect at generators to the defect at all word pairs
  --           (incl-sem-defect), and the defect sees only secn.
  --
  -- NOT CocycleGen.Pairs, which would narrow G to a map on pairs of
  -- generators: extending letterwise makes each `pair-word a` a
  -- HOMOMORPHISM Q → K, so it factors through the abelianisation of
  -- Sp(2n, 2).  That group is perfect once n ≥ 3, which would force the
  -- correction to be ε and the extension to split.  The Clifford cocycle
  -- has to sit in the general G.

  ------------------------------------------------------------------------
  -- The lifting, and the correction it carries
  --
  -- secn is the ε-patched bijective normal form of the simplified rule
  -- set (Simplified.Bijective), read as a map on words: it picks one
  -- word out of each ≈-class, sends ε to ε, and — this is what matters —
  -- respects the congruence PROPOSITIONALLY, since the normal forms are
  -- a datatype.  That is the lifting of Q into the Clifford group.

  private
    nfQ  = SNF.BijectiveNormalForm.nf      (SB.bijective₂ε n)
    invQ = SNF.BijectiveNormalForm.inv-nf  (SB.bijective₂ε n)

    module C = Group (CLG.CMS-group n)

  secn : Word (SGen n) → Word (SGen n)
  secn u = invQ (nfQ u)

  -- secn u is ≈-equal to u, …
  secn-≈ : ∀ (u : Word (SGen n)) → QB._≈_ (secn u) u
  secn-≈ u = SNF.BijectiveNormalForm.inv-nf∘nf=id (SB.bijective₂ε n)

  -- … equal on the nose on ≈-equal words, …
  secn-cong : ∀ {u v : Word (SGen n)} → QB._≈_ u v → secn u ≡ secn v
  secn-cong e = Eq.cong invQ (SNF.BijectiveNormalForm.nf-cong (SB.bijective₂ε n) e)

  -- … and it takes the empty word to the empty word (the ε-patch).
  secn-ε : secn ε ≡ ε
  secn-ε = SB.rep-ε

  -- The Clifford word by which the lifts of a and of v fail to compose.
  -- Its symplectic image is trivial, so it lies in the image of the
  -- Pauli group, and G reads off which Pauli it is.
  defect : Word (SGen n) → Word (SGen n) → Word (SGen n)
  defect u v = (secn u • secn v) • CLG._⁻¹ᶜ (secn (u • v))

  private
    proj-⁻¹ᶜ : ∀ (w : Word (SGen n)) →
               _≈ˢ_ (CLG.proj (CLG._⁻¹ᶜ w)) (CLG.proj w ⁻¹ˢ)
    proj-⁻¹ᶜ = GroupMorphisms.IsGroupHomomorphism.⁻¹-homo
                 (Extension.proj-homo (CLG.CMS-extension n))

  defect-triv : ∀ (u v : Word (SGen n)) →
                _≈ˢ_ (CLG.proj (defect u v)) εˢ
  defect-triv u v x = begin
    ap ⟦ secn u ⟧ (ap ⟦ secn v ⟧ (ap ⟦ CLG._⁻¹ᶜ (secn (u • v)) ⟧ x))
      ≡⟨ Eq.cong (λ z → ap ⟦ secn u ⟧ (ap ⟦ secn v ⟧ z))
                 (proj-⁻¹ᶜ (secn (u • v)) x) ⟩
    ap ⟦ secn u ⟧ (ap ⟦ secn v ⟧ (ap⁻¹ ⟦ secn (u • v) ⟧ x))
      ≡⟨ denote-eq (secn-≈ u) _ ⟩
    ap ⟦ u ⟧ (ap ⟦ secn v ⟧ (ap⁻¹ ⟦ secn (u • v) ⟧ x))
      ≡⟨ Eq.cong (ap ⟦ u ⟧) (denote-eq (secn-≈ v) _) ⟩
    ap ⟦ u • v ⟧ (ap⁻¹ ⟦ secn (u • v) ⟧ x)
      ≡⟨ Eq.sym (denote-eq (secn-≈ (u • v)) _) ⟩
    ap ⟦ secn (u • v) ⟧ (ap⁻¹ ⟦ secn (u • v) ⟧ x)
      ≡⟨ invʳ ⟦ secn (u • v) ⟧ x ⟩
    x ∎
    where open Eq.≡-Reasoning

  G : SGen n → Word (SGen n) → Word (PGen n)
  G a v = PA.inv-nf (CLG.ker-witness (defect [ a ]ʷ v) (defect-triv [ a ]ʷ v))

  ------------------------------------------------------------------------
  -- G's congruence and normalisation
  --
  -- The Pauli witness of a kernel element is unique, incl being
  -- injective, so it depends on neither the triviality proof nor the
  -- representative of the ≈ᶜ-class.

  private
    kw-unique : ∀ (w w' : Word (SGen n))
                  (t : _≈ˢ_ (CLG.proj w) εˢ) (t' : _≈ˢ_ (CLG.proj w') εˢ) →
                w C.≈ w' →
                CLG.ker-witness w t ≡ CLG.ker-witness w' t'
    kw-unique w w' t t' e = CLG.incl-injective chain
      where
      open ≈-Reasoning C.setoid
      chain : CLG._≈ᶜ_ (CLG.incl (CLG.ker-witness w t))
                       (CLG.incl (CLG.ker-witness w' t'))
      chain = begin
        CLG.incl (CLG.ker-witness w t)    ≈⟨ CLG.ker-witness-correct w t ⟩
        w                                 ≈⟨ e ⟩
        w'                                ≈⟨ CLG.ker-witness-correct w' t' ⟨
        CLG.incl (CLG.ker-witness w' t')  ∎

    -- The identity Pauli's normal form is the empty word: on each wire
    -- it contributes X ^ 0 • Z ^ 0, and the tail is shifted up.
    inv-nf-pIₙ : ∀ {m : ℕ} → PB._≈_ (ΓK m) (PA.inv-nf (pIₙ {m})) ε
    inv-nf-pIₙ {zero}  = PB.refl
    inv-nf-pIₙ {₁₊ m} = PB.trans (PB.cong PB.refl tail≈ε) PB.left-unit
      where
      tail≈ε : PB._≈_ (ΓK (₁₊ m)) (ε • PA._↑ (PA.inv-nf (pIₙ {m}))) ε
      tail≈ε = PB.trans PB.left-unit
                        (PA.lemma-cong↑ (PA.inv-nf pIₙ) ε inv-nf-pIₙ)

  G-cong : ∀ (a : SGen n) {v v' : Word (SGen n)} →
           QB._≈_ v v' → KB._≈_ (G a v) (G a v')
  G-cong a {v} {v'} e =
    KB.refl' (Eq.cong PA.inv-nf
      (kw-unique (defect [ a ]ʷ v) (defect [ a ]ʷ v')
                 (defect-triv [ a ]ʷ v) (defect-triv [ a ]ʷ v')
                 (C.reflexive defect-≡)))
    where
    -- Both normal forms are hit by secn-cong, so the two defects are the
    -- same word — the congruence of the section is propositional.
    defect-≡ : defect [ a ]ʷ v ≡ defect [ a ]ʷ v'
    defect-≡ = Eq.cong₂ (λ z w → (secn [ a ]ʷ • z) • CLG._⁻¹ᶜ w)
                        (secn-cong e)
                        (secn-cong (QB.cong QB.refl e))

  G-ε : ∀ (a : SGen n) → KB._≈_ (G a ε) ε
  G-ε a = KB.trans (KB.refl' (Eq.cong PA.inv-nf witness-pIₙ)) inv-nf-pIₙ
    where
    -- secn ε is ε and secn (a • ε) is secn a, so defect a ε is
    -- (secn a • ε) • (secn a) ⁻¹ᶜ, which cancels in CMS.
    defect-≡ : defect [ a ]ʷ ε ≡ (secn [ a ]ʷ • ε) • CLG._⁻¹ᶜ (secn [ a ]ʷ)
    defect-≡ = Eq.cong₂ (λ z w → (secn [ a ]ʷ • z) • CLG._⁻¹ᶜ w)
                        secn-ε (secn-cong QB.right-unit)

    open ≈-Reasoning C.setoid

    defect-ε : defect [ a ]ʷ ε C.≈ C.ε
    defect-ε = begin
      defect [ a ]ʷ ε
        ≈⟨ C.reflexive defect-≡ ⟩
      (secn [ a ]ʷ • ε) • CLG._⁻¹ᶜ (secn [ a ]ʷ)
        -- the empty word acts as the identity, so this step is by
        -- computation
        ≈⟨ (λ _ → Eq.refl) ⟩
      secn [ a ]ʷ • CLG._⁻¹ᶜ (secn [ a ]ʷ)
        ≈⟨ C.inverseʳ (secn [ a ]ʷ) ⟩
      C.ε ∎

    witness-pIₙ : CLG.ker-witness (defect [ a ]ʷ ε) (defect-triv [ a ]ʷ ε) ≡ pIₙ
    witness-pIₙ = CLG.incl-injective (begin
      CLG.incl (CLG.ker-witness (defect [ a ]ʷ ε) (defect-triv [ a ]ʷ ε))
        ≈⟨ CLG.ker-witness-correct (defect [ a ]ʷ ε) (defect-triv [ a ]ʷ ε) ⟩
      defect [ a ]ʷ ε
        ≈⟨ defect-ε ⟩
      C.ε
        ≈⟨ CLG.incl-ε ⟨
      CLG.incl pIₙ ∎)

  ------------------------------------------------------------------------
  -- f is the defect of the lifting
  --
  -- G was read off the defect of secn at a generator; CocycleGen's
  -- recursion extends it along the first argument.  What it extends to
  -- is again a defect — of the same lifting, at arbitrary word pairs.
  -- That is incl-sem-defect below, and f-axiom falls out of it: the
  -- defect only ever sees secn, and secn is congruent on the nose.

  private
    -- A Pauli word read into the Clifford group.  It is a group
    -- homomorphism: sem is one by computation, incl by incl-∙ / incl-ε.
    IS : Word (PGen n) → Word (SGen n)
    IS w = CLG.incl (PA.sem w)

    IS-∙ : ∀ (w w' : Word (PGen n)) → CLG._≈ᶜ_ (IS (w • w')) (IS w • IS w')
    IS-∙ w w' = CLG.incl-∙ (PA.sem w) (PA.sem w')

    IS-cong : ∀ {w w' : Word (PGen n)} →
              KB._≈_ w w' → CLG._≈ᶜ_ (IS w) (IS w')
    IS-cong e = C.reflexive (Eq.cong CLG.incl (BK.sound e))

    module MIS = MonoidMorphisms (Group.rawMonoid (AbelianGroup.group K))
                                 (Group.rawMonoid (CLG.CMS-group n))

    IS-mon : MIS.IsMonoidHomomorphism IS
    IS-mon = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = IS-cong }
        ; homo              = IS-∙
        }
      ; ε-homo = CLG.incl-ε
      }

    IS-⁻¹ : ∀ (w : Word (PGen n)) →
            CLG._≈ᶜ_ (IS (KA._⁻¹ w)) (CLG._⁻¹ᶜ (IS w))
    IS-⁻¹ = GroupMorphisms.IsGroupHomomorphism.⁻¹-homo
              (isMonoidHomomorphism⇒isGroupHomomorphism
                (AbelianGroup.group K) (CLG.CMS-group n) IS-mon)

    -- Acting on a Pauli word is conjugating its image by the lift: this
    -- is CliffordGroup.conj-incl, with ⟦ secn u ⟧ traded for ⟦ u ⟧.
    IS-act : ∀ (u : Word (SGen n)) (w : Word (PGen n)) →
             CLG._≈ᶜ_ (IS (act u w)) ((secn u • IS w) • CLG._⁻¹ᶜ (secn u))
    IS-act u w =
      C.trans {i = IS (act u w)}
              {j = CLG.incl (ap ⟦ secn u ⟧ (PA.sem w))}
              {k = (secn u • IS w) • CLG._⁻¹ᶜ (secn u)}
        (C.reflexive (Eq.cong CLG.incl
          (Eq.trans (actw-sem u w)
                    (Eq.sym (denote-eq (secn-≈ u) (PA.sem w))))))
        (C.sym {x = (secn u • IS w) • CLG._⁻¹ᶜ (secn u)}
               {y = CLG.incl (ap ⟦ secn u ⟧ (PA.sem w))}
          (CLG.conj-incl (secn u) (PA.sem w)))

    -- The defining property of the defect: it is what the two lifts
    -- overshoot the lift of the product by.
    defect-· : ∀ (u v : Word (SGen n)) →
               CLG._≈ᶜ_ (defect u v • secn (u • v)) (secn u • secn v)
    defect-· u v x =
      Eq.cong (λ z → cact (secn u) (cact (secn v) z))
              (CLG.invˡ-lemma (secn (u • v)) x)

  incl-sem-defect : ∀ (u v : Word (SGen n)) →
                    CLG._≈ᶜ_ (IS (CGn.f φ G u v)) (defect u v)

  -- The empty word lifts to the empty word, so there is no defect.
  incl-sem-defect ε v = begin
    IS (CGn.f φ G ε v)                          ≈⟨ CLG.incl-ε ⟩
    ε                                           ≈⟨ cancel ⟩
    (ε • secn v) • CLG._⁻¹ᶜ (secn v)            ≈⟨ C.reflexive (Eq.sym shape) ⟩
    defect ε v                                  ∎
    where
    open ≈-Reasoning C.setoid
    cancel : CLG._≈ᶜ_ ε ((ε • secn v) • CLG._⁻¹ᶜ (secn v))
    cancel x = Eq.sym (CLG.invʳ-lemma (secn v) x)
    shape : defect ε v ≡ (ε • secn v) • CLG._⁻¹ᶜ (secn v)
    shape = Eq.cong₂ (λ z w → (z • secn v) • CLG._⁻¹ᶜ w)
                     secn-ε (secn-cong (QB.left-unit {w = v}))

  -- At a generator this is what G was defined to be.
  incl-sem-defect [ a ]ʷ v =
    C.trans {i = IS (CGn.f φ G [ a ]ʷ v)}
            {j = CLG.incl witness}
            {k = defect [ a ]ʷ v}
      (C.reflexive (Eq.cong CLG.incl (PA.sem-inv witness)))
      (CLG.ker-witness-correct (defect [ a ]ʷ v) (defect-triv [ a ]ʷ v))
    where
    witness = CLG.ker-witness (defect [ a ]ʷ v) (defect-triv [ a ]ʷ v)

  -- The step.  The recursion's three terms are three defects; multiplying
  -- back by the lift of the product cancels them down to the two lifts,
  -- which is the defect of the product.
  incl-sem-defect (u₁ • u₂) v =
    ∙-cancelʳ (secn ((u₁ • u₂) • v))
              (IS (CGn.f φ G (u₁ • u₂) v)) (defect (u₁ • u₂) v) (begin
      IS (CGn.f φ G (u₁ • u₂) v) • secn ((u₁ • u₂) • v)
        ≈⟨ (λ x → step-IS (cact (secn ((u₁ • u₂) • v)) x)) ⟩
      ((CLG._⁻¹ᶜ D₁ • ((a • D₂) • CLG._⁻¹ᶜ a)) • D₃) • secn ((u₁ • u₂) • v)
        ≈⟨ C.reflexive (Eq.cong (λ z → M • z) (secn-cong (QB.assoc {w = u₁} {v = u₂} {u = v}))) ⟩
      ((CLG._⁻¹ᶜ D₁ • ((a • D₂) • CLG._⁻¹ᶜ a)) • D₃) • secn (u₁ • (u₂ • v))
        ≈⟨ (λ x → Eq.cong (λ z → cact (CLG._⁻¹ᶜ D₁)
                                   (cact ((a • D₂) • CLG._⁻¹ᶜ a) z))
                          (defect-· u₁ (u₂ • v) x)) ⟩
      (CLG._⁻¹ᶜ D₁ • ((a • D₂) • CLG._⁻¹ᶜ a)) • (a • secn (u₂ • v))
        ≈⟨ (λ x → Eq.cong (λ z → cact (CLG._⁻¹ᶜ D₁) (cact a (cact D₂ z)))
                          (CLG.invˡ-lemma a (cact (secn (u₂ • v)) x))) ⟩
      CLG._⁻¹ᶜ D₁ • (a • (D₂ • secn (u₂ • v)))
        ≈⟨ (λ x → Eq.cong (λ z → cact (CLG._⁻¹ᶜ D₁) (cact a z))
                          (defect-· u₂ v x)) ⟩
      CLG._⁻¹ᶜ D₁ • (a • (b • c))
        ≈⟨ (λ x → Eq.cong (cact (CLG._⁻¹ᶜ D₁))
                          (Eq.sym (defect-· u₁ u₂ (cact c x)))) ⟩
      CLG._⁻¹ᶜ D₁ • ((D₁ • secn (u₁ • u₂)) • c)
        ≈⟨ (λ x → CLG.invˡ-lemma D₁ (cact (secn (u₁ • u₂)) (cact c x))) ⟩
      secn (u₁ • u₂) • c
        ≈⟨ (λ x → Eq.sym (defect-· (u₁ • u₂) v x)) ⟩
      defect (u₁ • u₂) v • secn ((u₁ • u₂) • v) ∎)
    where
    open ≈-Reasoning C.setoid
    open GroupProperties (CLG.CMS-group n) using (∙-cancelʳ)

    a  = secn u₁
    b  = secn u₂
    c  = secn v
    F₁ = CGn.f φ G u₁ u₂
    F₂ = CGn.f φ G u₂ v
    F₃ = CGn.f φ G u₁ (u₂ • v)
    D₁ = defect u₁ u₂
    D₂ = defect u₂ v
    D₃ = defect u₁ (u₂ • v)
    M  = (CLG._⁻¹ᶜ D₁ • ((a • D₂) • CLG._⁻¹ᶜ a)) • D₃

    -- The recursion's term, with each factor replaced by its defect.
    step-IS : CLG._≈ᶜ_ (IS (CGn.f φ G (u₁ • u₂) v)) M
    step-IS = begin
      IS ((KA._⁻¹ F₁ • act u₁ F₂) • F₃)
        ≈⟨ IS-∙ (KA._⁻¹ F₁ • act u₁ F₂) F₃ ⟩
      IS (KA._⁻¹ F₁ • act u₁ F₂) • IS F₃
        ≈⟨ (λ x → IS-∙ (KA._⁻¹ F₁) (act u₁ F₂) (cact (IS F₃) x)) ⟩
      (IS (KA._⁻¹ F₁) • IS (act u₁ F₂)) • IS F₃
        ≈⟨ (λ x → IS-⁻¹ F₁ (cact (IS (act u₁ F₂)) (cact (IS F₃) x))) ⟩
      (CLG._⁻¹ᶜ (IS F₁) • IS (act u₁ F₂)) • IS F₃
        ≈⟨ (λ x → Eq.cong (cact (CLG._⁻¹ᶜ (IS F₁)))
                          (IS-act u₁ F₂ (cact (IS F₃) x))) ⟩
      (CLG._⁻¹ᶜ (IS F₁) • ((a • IS F₂) • CLG._⁻¹ᶜ a)) • IS F₃
        ≈⟨ (λ x → Eq.cong (λ z → cact (CLG._⁻¹ᶜ (IS F₁))
                                   (cact ((a • IS F₂) • CLG._⁻¹ᶜ a) z))
                          (incl-sem-defect u₁ (u₂ • v) x)) ⟩
      (CLG._⁻¹ᶜ (IS F₁) • ((a • IS F₂) • CLG._⁻¹ᶜ a)) • D₃
        ≈⟨ (λ x → Eq.cong (λ z → cact (CLG._⁻¹ᶜ (IS F₁)) (cact a z))
                          (incl-sem-defect u₂ v
                            (cact (CLG._⁻¹ᶜ a) (cact D₃ x)))) ⟩
      (CLG._⁻¹ᶜ (IS F₁) • ((a • D₂) • CLG._⁻¹ᶜ a)) • D₃
        ≈⟨ (λ x → CLG.⁻¹-congᶜ {w = IS F₁} {v = D₁} (incl-sem-defect u₁ u₂)
                    (cact ((a • D₂) • CLG._⁻¹ᶜ a) (cact D₃ x))) ⟩
      M ∎

  f-axiom : ∀ {u u' : Word (SGen n)} → ΓQ n u u' → ∀ (v : Word (SGen n)) →
            KB._≈_ (CGn.f φ G u v) (CGn.f φ G u' v)
  f-axiom {u} {u'} r v = BK.complete (CLG.incl-injective
    {P = PA.sem (CGn.f φ G u v)} {P' = PA.sem (CGn.f φ G u' v)} (begin
    CLG.incl (PA.sem (CGn.f φ G u v))   ≈⟨ incl-sem-defect u v ⟩
    defect u v                          ≈⟨ C.reflexive shape ⟩
    defect u' v                         ≈⟨ incl-sem-defect u' v ⟨
    CLG.incl (PA.sem (CGn.f φ G u' v))  ∎))
    where
    open ≈-Reasoning C.setoid
    shape : defect u v ≡ defect u' v
    shape = Eq.cong₂ (λ z w → (z • secn v) • CLG._⁻¹ᶜ w)
                     (secn-cong (QB.axiom r))
                     (secn-cong (QB.cong (QB.axiom r) (QB.refl {w = v})))

  γ : FactorSet K Q φ
  γ = CGn.factorSet φ G G-cong G-ε f-axiom

  ------------------------------------------------------------------------
  -- The twisted product K ×_f Q
  --
  -- Pauli words paired with Clifford words, multiplied by
  --
  --     (a , u) ∙ (b , v) = ((a • act u b) • f u v , u • v),
  --
  -- and the short exact sequence 1 → K → K ×_f Q → Q → 1 it carries.

  Twisted : Group 0ℓ 0ℓ
  Twisted = FSE.group K Q φ γ

  Twisted-extension : Extension (AbelianGroup.group K) Q
  Twisted-extension = FSE.factorSetExtension K Q φ γ

  ------------------------------------------------------------------------
  -- The split instance
  --
  -- Independently of γ, the trivial factor set is available, and with it
  -- the semidirect product K ⋊ Q — the extension whose lifting
  -- u ↦ (ε , u) is a homomorphism.  This one is complete: it rests only
  -- on φ.

  γ-split : FactorSet K Q φ
  γ-split = FSE.trivialFactorSet K Q φ

  Affine : Group 0ℓ 0ℓ
  Affine = FSE.group K Q φ γ-split

  Affine-extension : Extension (AbelianGroup.group K) Q
  Affine-extension = FSE.factorSetExtension K Q φ γ-split
