------------------------------------------------------------------------
-- Presentations of groups
--
-- The relations of Table 2 as identities of actions on vectors of
-- length 2k (Scaled.Action), over any ring with the scalars h and s.
--
-- (7b) and (7c) act on the first blocks; the others, by induction on
-- the block of their indices: a generator two indices up acts on the
-- tail of a vector (shift-actV, from EmbedAction), and I ⊗ H on its
-- first block and its tail separately, so the relation at indices ≥ 2
-- follows from the same relation two indices down, the first block
-- coming back by I ⊗ H being an involution.  The base cases are ring
-- identities, some of which need s² = h (generated by a script).
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

open import Algebra.Structures using (IsCommutativeRing)
open import Relation.Binary.PropositionalEquality using (_≡_)
open import Instances using (Ring ; Adjoint ; adj ; _+_ ; _*_ ; -_ ; 0# ; 1#)
open import Quantum.Synthesis.Ring.Properties.Hom using (IsInvolutiveRingEndo)

module Examples.Groups.CCX+HH-TwoLevel.Scaled.Table2
  {A : Set} {{RA : Ring A}} {{AA : Adjoint A}}
  (isCR : IsCommutativeRing (_≡_ {A = A}) _+_ _*_ -_ 0# 1#)
  (adjI : IsInvolutiveRingEndo {A} adj)
  (h : A) (h-self : adj h ≡ h) (h-quarter : h * h + h * h + h * h + h * h ≡ 1#)
  (s : A) (s-self : adj s ≡ s) (s-sq : s * s ≡ h) (s-half : s * s + s * s ≡ 1#)
  where

open import Data.Fin.Base using (Fin ; zero ; suc ; toℕ ; _<_)
open import Data.Nat.Base as ℕ using (ℕ ; zero ; suc ; _%_ ; s≤s ; z≤n)
import Data.Nat.Properties as ℕP
import Data.Integer.Base as ℤ
open import Data.Vec.Base using (Vec ; [] ; _∷_)
open import Relation.Binary.PropositionalEquality

import Quantum.Synthesis.Ring.Properties.Common as Common

open import Examples.Groups.CCX+HH-TwoLevel.Syntactics using (Gen ; M-gen ; X-gen ; K-gen)
open import Examples.Groups.CCX+HH-TwoLevel.Embedding using (Emb ; gen)
import Examples.Groups.CCX+HH-TwoLevel.Scaled.Action as SA
import Examples.Groups.CCX+HH-TwoLevel.EmbedAction as EmbedAction

open SA isCR adjI h h-self h-quarter s s-self s-sq s-half
open EmbedAction isCR adjI h using (restrict ; restrict-! ; emb-restrict ; emb-actV-out)

private
  module S = Common.ZSolver R
  open S using (_:+_ ; _:*_ ; :-_ ; _:=_ ; con)

  half : ∀ x → (s * s + s * s) * x ≡ x
  half x = trans (cong (_* x) s-half) (AR.*-identityˡ x)

------------------------------------------------------------------------
-- Generators two indices up

-- The embedding y ↦ y + 2.
sh : ∀ k → Emb (k ℕ.* 2) (suc k ℕ.* 2)
sh k = record { ι = λ y → suc (suc y) ; mono = λ p → s≤s (s≤s p) }

shift-actV : ∀ k (g : Gen (k ℕ.* 2)) (p q : A) (w : Vec A (k ℕ.* 2)) →
             actV (gen (sh k) g) (p ∷ q ∷ w) ≡ p ∷ q ∷ actV g w
shift-actV k g p q w = vec-ext at
  where
  v = p ∷ q ∷ w
  e = sh k
  rcons : restrict e v ≡ w
  rcons = vec-ext (λ y → restrict-! e v y)
  at : ∀ x → actV (gen e g) v ! x ≡ (p ∷ q ∷ actV g w) ! x
  at zero = emb-actV-out e g v zero (λ y ())
  at (suc zero) = emb-actV-out e g v (suc zero) (λ y ())
  at (suc (suc x)) = trans (sym (restrict-! e (actV (gen e g) v) x))
                       (trans (cong (_! x) (emb-restrict e g v)) (cong (λ u → actV g u ! x) rcons))

------------------------------------------------------------------------
-- Generators on the first block

module _ {n : ℕ} where

  M0-cons : (p : A) (w : Vec A n) → actV (M-gen zero) (p ∷ w) ≡ - p ∷ w
  M0-cons p w = vec-ext at
    where
    at : ∀ x → actV (M-gen zero) (p ∷ w) ! x ≡ (- p ∷ w) ! x
    at zero = actV-Ma zero (p ∷ w)
    at (suc x) = actV-M≢ zero (p ∷ w) (λ ())

  M1-cons : (p q : A) (w : Vec A n) → actV (M-gen (suc zero)) (p ∷ q ∷ w) ≡ p ∷ - q ∷ w
  M1-cons p q w = vec-ext at
    where
    v = p ∷ q ∷ w
    at : ∀ x → actV (M-gen (suc zero)) v ! x ≡ (p ∷ - q ∷ w) ! x
    at zero = actV-M≢ (suc zero) v (λ ())
    at (suc zero) = actV-Ma (suc zero) v
    at (suc (suc x)) = actV-M≢ (suc zero) v (λ ())

  X01-cons : .(r : _<_ {suc (suc n)} {suc (suc n)} zero (suc zero)) (p q : A) (w : Vec A n) → actV (X-gen zero (suc zero) r) (p ∷ q ∷ w) ≡ q ∷ p ∷ w
  X01-cons r p q w = vec-ext at
    where
    v = p ∷ q ∷ w
    at : ∀ x → actV (X-gen zero (suc zero) r) v ! x ≡ (q ∷ p ∷ w) ! x
    at zero = actV-Xa r v
    at (suc zero) = actV-Xb r v
    at (suc (suc x)) = actV-X≢ r v (λ ()) (λ ())

  X12-cons : .(r : _<_ {suc (suc (suc n))} {suc (suc (suc n))} (suc zero) (suc (suc zero))) (p q t : A) (w : Vec A n) →
             actV (X-gen (suc zero) (suc (suc zero)) r) (p ∷ q ∷ t ∷ w) ≡ p ∷ t ∷ q ∷ w
  X12-cons r p q t w = vec-ext at
    where
    v = p ∷ q ∷ t ∷ w
    at : ∀ x → actV (X-gen (suc zero) (suc (suc zero)) r) v ! x ≡ (p ∷ t ∷ q ∷ w) ! x
    at zero = actV-X≢ r v (λ ()) (λ ())
    at (suc zero) = actV-Xa r v
    at (suc (suc zero)) = actV-Xb r v
    at (suc (suc (suc x))) = actV-X≢ r v (λ ()) (λ ())

  K-cons : .(p₁ : _<_ {4 ℕ.+ n} {4 ℕ.+ n} zero (suc zero)) .(p₂ : _<_ {4 ℕ.+ n} {4 ℕ.+ n} (suc zero) (suc (suc zero)))
           .(p₃ : _<_ {4 ℕ.+ n} {4 ℕ.+ n} (suc (suc zero)) (suc (suc (suc zero))))
           (a b c d : A) (w : Vec A n) →
           actV (K-gen zero (suc zero) (suc (suc zero)) (suc (suc (suc zero))) p₁ p₂ p₃) (a ∷ b ∷ c ∷ d ∷ w)
           ≡ rowA a b c d ∷ rowB a b c d ∷ rowC a b c d ∷ rowD a b c d ∷ w
  K-cons p₁ p₂ p₃ a b c d w = vec-ext at
    where
    v = a ∷ b ∷ c ∷ d ∷ w
    g = K-gen zero (suc zero) (suc (suc zero)) (suc (suc (suc zero))) p₁ p₂ p₃
    at : ∀ x → actV g v ! x ≡ (rowA a b c d ∷ rowB a b c d ∷ rowC a b c d ∷ rowD a b c d ∷ w) ! x
    at zero = actV-Ka p₁ p₂ p₃ v
    at (suc zero) = actV-Kb p₁ p₂ p₃ v
    at (suc (suc zero)) = actV-Kc p₁ p₂ p₃ v
    at (suc (suc (suc zero))) = actV-Kd p₁ p₂ p₃ v
    at (suc (suc (suc (suc x)))) = actV-K≢ p₁ p₂ p₃ v (λ ()) (λ ()) (λ ()) (λ ())

------------------------------------------------------------------------
-- The ring identities

private
  b0 : ∀ s h a b c d → (s * ((h * ((((1# * (s * (a + b))) + (1# * (s * (a + (- b))))) + (1# * (s * (c + d)))) + (1# * (s * (c + (- d)))))) + (h * ((((1# * (s * (a + b))) + ((- 1#) * (s * (a + (- b))))) + (1# * (s * (c + d)))) + ((- 1#) * (s * (c + (- d)))))))) ≡ (((s * s) + (s * s)) * (h * ((((1# * a) + (1# * b)) + (1# * c)) + (1# * d))))
  b0 = S.solve 6 (λ s h a b c d → (s :* ((h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((con (ℤ.+ 1)) :* (s :* (a :+ (:- b))))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ d)))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ (:- d)))))) :+ (h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (a :+ (:- b))))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ d)))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ (:- d)))))))) := (((s :* s) :+ (s :* s)) :* (h :* (((((con (ℤ.+ 1)) :* a) :+ ((con (ℤ.+ 1)) :* b)) :+ ((con (ℤ.+ 1)) :* c)) :+ ((con (ℤ.+ 1)) :* d))))) AR.refl

  b1 : ∀ s h a b c d → (s * ((h * ((((1# * (s * (a + b))) + (1# * (s * (a + (- b))))) + (1# * (s * (c + d)))) + (1# * (s * (c + (- d)))))) + (- (h * ((((1# * (s * (a + b))) + ((- 1#) * (s * (a + (- b))))) + (1# * (s * (c + d)))) + ((- 1#) * (s * (c + (- d))))))))) ≡ (((s * s) + (s * s)) * (h * ((((1# * a) + ((- 1#) * b)) + (1# * c)) + ((- 1#) * d))))
  b1 = S.solve 6 (λ s h a b c d → (s :* ((h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((con (ℤ.+ 1)) :* (s :* (a :+ (:- b))))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ d)))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ (:- d)))))) :+ (:- (h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (a :+ (:- b))))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ d)))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ (:- d))))))))) := (((s :* s) :+ (s :* s)) :* (h :* (((((con (ℤ.+ 1)) :* a) :+ ((:- (con (ℤ.+ 1))) :* b)) :+ ((con (ℤ.+ 1)) :* c)) :+ ((:- (con (ℤ.+ 1))) :* d))))) AR.refl

  b2 : ∀ s h a b c d → (s * ((h * ((((1# * (s * (a + b))) + (1# * (s * (a + (- b))))) + ((- 1#) * (s * (c + d)))) + ((- 1#) * (s * (c + (- d)))))) + (h * ((((1# * (s * (a + b))) + ((- 1#) * (s * (a + (- b))))) + ((- 1#) * (s * (c + d)))) + (1# * (s * (c + (- d)))))))) ≡ (((s * s) + (s * s)) * (h * ((((1# * a) + (1# * b)) + ((- 1#) * c)) + ((- 1#) * d))))
  b2 = S.solve 6 (λ s h a b c d → (s :* ((h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((con (ℤ.+ 1)) :* (s :* (a :+ (:- b))))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ d)))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ (:- d)))))) :+ (h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (a :+ (:- b))))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ d)))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ (:- d)))))))) := (((s :* s) :+ (s :* s)) :* (h :* (((((con (ℤ.+ 1)) :* a) :+ ((con (ℤ.+ 1)) :* b)) :+ ((:- (con (ℤ.+ 1))) :* c)) :+ ((:- (con (ℤ.+ 1))) :* d))))) AR.refl

  b3 : ∀ s h a b c d → (s * ((h * ((((1# * (s * (a + b))) + (1# * (s * (a + (- b))))) + ((- 1#) * (s * (c + d)))) + ((- 1#) * (s * (c + (- d)))))) + (- (h * ((((1# * (s * (a + b))) + ((- 1#) * (s * (a + (- b))))) + ((- 1#) * (s * (c + d)))) + (1# * (s * (c + (- d))))))))) ≡ (((s * s) + (s * s)) * (h * ((((1# * a) + ((- 1#) * b)) + ((- 1#) * c)) + (1# * d))))
  b3 = S.solve 6 (λ s h a b c d → (s :* ((h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((con (ℤ.+ 1)) :* (s :* (a :+ (:- b))))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ d)))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ (:- d)))))) :+ (:- (h :* (((((con (ℤ.+ 1)) :* (s :* (a :+ b))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (a :+ (:- b))))) :+ ((:- (con (ℤ.+ 1))) :* (s :* (c :+ d)))) :+ ((con (ℤ.+ 1)) :* (s :* (c :+ (:- d))))))))) := (((s :* s) :+ (s :* s)) :* (h :* (((((con (ℤ.+ 1)) :* a) :+ ((:- (con (ℤ.+ 1))) :* b)) :+ ((:- (con (ℤ.+ 1))) :* c)) :+ ((con (ℤ.+ 1)) :* d))))) AR.refl

  c0 : ∀ s a b → (s * ((- (s * (a + b))) + (s * (a + (- b))))) ≡ (((s * s) + (s * s)) * (- b))
  c0 = S.solve 3 (λ s a b → (s :* ((:- (s :* (a :+ b))) :+ (s :* (a :+ (:- b))))) := (((s :* s) :+ (s :* s)) :* (:- b))) AR.refl

  c1 : ∀ s a b → (s * ((- (s * (a + b))) + (- (s * (a + (- b)))))) ≡ (((s * s) + (s * s)) * (- a))
  c1 = S.solve 3 (λ s a b → (s :* ((:- (s :* (a :+ b))) :+ (:- (s :* (a :+ (:- b)))))) := (((s :* s) :+ (s :* s)) :* (:- a))) AR.refl

  d0 : ∀ s a b → (s * ((s * (a + (- b))) + (s * (a + b)))) ≡ (((s * s) + (s * s)) * a)
  d0 = S.solve 3 (λ s a b → (s :* ((s :* (a :+ (:- b))) :+ (s :* (a :+ b)))) := (((s :* s) :+ (s :* s)) :* a)) AR.refl

  d1 : ∀ s a b → (s * ((s * (a + (- b))) + (- (s * (a + b))))) ≡ (((s * s) + (s * s)) * (- b))
  d1 = S.solve 3 (λ s a b → (s :* ((s :* (a :+ (:- b))) :+ (:- (s :* (a :+ b))))) := (((s :* s) :+ (s :* s)) :* (:- b))) AR.refl

  e0 : ∀ s a b c d → (s * ((s * (a + b)) + (s * (c + d)))) ≡ ((s * s) * ((((1# * a) + (1# * b)) + (1# * c)) + (1# * d)))
  e0 = S.solve 5 (λ s a b c d → (s :* ((s :* (a :+ b)) :+ (s :* (c :+ d)))) := ((s :* s) :* (((((con (ℤ.+ 1)) :* a) :+ ((con (ℤ.+ 1)) :* b)) :+ ((con (ℤ.+ 1)) :* c)) :+ ((con (ℤ.+ 1)) :* d)))) AR.refl

  e1 : ∀ s a b c d → (s * ((s * (a + b)) + (- (s * (c + d))))) ≡ ((s * s) * ((((1# * a) + (1# * b)) + ((- 1#) * c)) + ((- 1#) * d)))
  e1 = S.solve 5 (λ s a b c d → (s :* ((s :* (a :+ b)) :+ (:- (s :* (c :+ d))))) := ((s :* s) :* (((((con (ℤ.+ 1)) :* a) :+ ((con (ℤ.+ 1)) :* b)) :+ ((:- (con (ℤ.+ 1))) :* c)) :+ ((:- (con (ℤ.+ 1))) :* d)))) AR.refl

  e2 : ∀ s a b c d → (s * ((s * (a + (- b))) + (s * (c + (- d))))) ≡ ((s * s) * ((((1# * a) + ((- 1#) * b)) + (1# * c)) + ((- 1#) * d)))
  e2 = S.solve 5 (λ s a b c d → (s :* ((s :* (a :+ (:- b))) :+ (s :* (c :+ (:- d))))) := ((s :* s) :* (((((con (ℤ.+ 1)) :* a) :+ ((:- (con (ℤ.+ 1))) :* b)) :+ ((con (ℤ.+ 1)) :* c)) :+ ((:- (con (ℤ.+ 1))) :* d)))) AR.refl

  e3 : ∀ s a b c d → (s * ((s * (a + (- b))) + (- (s * (c + (- d)))))) ≡ ((s * s) * ((((1# * a) + ((- 1#) * b)) + ((- 1#) * c)) + (1# * d)))
  e3 = S.solve 5 (λ s a b c d → (s :* ((s :* (a :+ (:- b))) :+ (:- (s :* (c :+ (:- d)))))) := ((s :* s) :* (((((con (ℤ.+ 1)) :* a) :+ ((:- (con (ℤ.+ 1))) :* b)) :+ ((:- (con (ℤ.+ 1))) :* c)) :+ ((con (ℤ.+ 1)) :* d)))) AR.refl


  inv₁ : ∀ a b → s * (s * (a + b) + s * (a + - b)) ≡ a
  inv₁ a b = trans (S.solve 3 (λ s a b → s :* (s :* (a :+ b) :+ s :* (a :+ :- b)) := (s :* s :+ s :* s) :* a) AR.refl s a b) (half a)

  inv₂ : ∀ a b → s * (s * (a + b) + - (s * (a + - b))) ≡ b
  inv₂ a b = trans (S.solve 3 (λ s a b → s :* (s :* (a :+ b) :+ :- (s :* (a :+ :- b))) := (s :* s :+ s :* s) :* b) AR.refl s a b) (half b)

  pred₂ : ∀ {i j} → suc (suc i) ≡ suc (suc j) → i ≡ j
  pred₂ e = ℕP.suc-injective (ℕP.suc-injective e)

------------------------------------------------------------------------
-- The relations of Table 2

-- (7a)
r7a-act : ∀ k (v : Vec A (k ℕ.* 2)) → actIH k (actIH k v) ≡ v
r7a-act = actIH-invol

-- (7b), on the first two blocks.
r7b-act : ∀ k (v : Vec A (suc (suc k) ℕ.* 2)) →
          actIH (suc (suc k)) (actV (K-gen zero (suc zero) (suc (suc zero)) (suc (suc (suc zero)))
                                       (s≤s z≤n) (s≤s (s≤s z≤n)) (s≤s (s≤s (s≤s z≤n))))
                                (actIH (suc (suc k)) v))
          ≡ actV (K-gen zero (suc zero) (suc (suc zero)) (suc (suc (suc zero))) (s≤s z≤n) (s≤s (s≤s z≤n)) (s≤s (s≤s (s≤s z≤n)))) v
r7b-act k (a ∷ b ∷ c ∷ d ∷ v) =
  trans (cong (actIH (suc (suc k))) (K-cons _ _ _ (s * (a + b)) (s * (a + - b)) (s * (c + d)) (s * (c + - d)) (actIH k v)))
    (trans (cong₂ _∷_ (trans (b0 s h a b c d) (half _))
             (cong₂ _∷_ (trans (b1 s h a b c d) (half _))
               (cong₂ _∷_ (trans (b2 s h a b c d) (half _))
                 (cong₂ _∷_ (trans (b3 s h a b c d) (half _)) (actIH-invol k v)))))
      (sym (K-cons _ _ _ a b c d v)))

-- (7c), on the first block.
r7c-act : ∀ k (v : Vec A (suc k ℕ.* 2)) →
          actIH (suc k) (actV (M-gen zero) (actIH (suc k) v)) ≡
          actV (M-gen zero) (actV (X-gen zero (suc zero) (s≤s z≤n)) (actV (M-gen zero) v))
r7c-act k (a ∷ b ∷ v) =
  trans (cong (actIH (suc k)) (M0-cons (s * (a + b)) (s * (a + - b) ∷ actIH k v)))
    (trans (cong₂ _∷_ (trans (c0 s a b) (half _)) (cong₂ _∷_ (trans (c1 s a b) (half _)) (actIH-invol k v)))
      (sym (trans (cong (λ u → actV (M-gen zero) (actV (X-gen zero (suc zero) (s≤s z≤n)) u)) (M0-cons a (b ∷ v)))
             (trans (cong (actV (M-gen zero)) (X01-cons _ (- a) b v)) (M0-cons b (- a ∷ v))))))

-- (7d), x even: by induction on the block of x.
r7d₀-act : ∀ k (x y : Fin (k ℕ.* 2)) .(p : x < y) → toℕ y ≡ suc (toℕ x) → toℕ x % 2 ≡ 0 →
           ∀ v → actIH k (actV (X-gen x y p) (actIH k v)) ≡ actV (M-gen y) v
r7d₀-act zero () y p ty px v
r7d₀-act (suc k) zero zero p () px v
r7d₀-act (suc k) zero (suc zero) p ty px (a ∷ b ∷ v) =
  trans (cong (actIH (suc k)) (X01-cons p (s * (a + b)) (s * (a + - b)) (actIH k v)))
    (trans (cong₂ _∷_ (trans (d0 s a b) (half _)) (cong₂ _∷_ (trans (d1 s a b) (half _)) (actIH-invol k v)))
      (sym (M1-cons a b v)))
r7d₀-act (suc k) zero (suc (suc y)) p () px v
r7d₀-act (suc k) (suc zero) y p ty () v
r7d₀-act (suc k) (suc (suc x)) zero p () px v
r7d₀-act (suc k) (suc (suc x)) (suc zero) p () px v
r7d₀-act (suc k) (suc (suc x)) (suc (suc y)) p ty px (a ∷ b ∷ v) =
  trans (cong (actIH (suc k)) (shift-actV k (X-gen x y (ℕP.≤-pred (ℕP.≤-pred p))) (s * (a + b)) (s * (a + - b)) (actIH k v)))
    (trans (cong₂ _∷_ (inv₁ a b) (cong₂ _∷_ (inv₂ a b) (r7d₀-act k x y (ℕP.≤-pred (ℕP.≤-pred p)) (pred₂ ty) px v)))
      (sym (shift-actV k (M-gen y) a b v)))

-- (7d), x odd: by induction on the block of x, from x = 1.
r7d₁-act : ∀ k (w x y z : Fin (k ℕ.* 2)) .(p : w < x) .(q : x < y) .(r : y < z) →
           toℕ x ≡ suc (toℕ w) → toℕ y ≡ suc (toℕ x) → toℕ z ≡ suc (toℕ y) → toℕ x % 2 ≡ 1 →
           ∀ v → actIH k (actV (X-gen x y q) (actIH k v)) ≡ actV (X-gen x y q) (actV (K-gen w x y z p q r) v)
r7d₁-act zero () x y z p q r tx ty tz px v
r7d₁-act (suc k) w zero y z p q r tx ty tz () v
r7d₁-act (suc k) (suc w) (suc zero) y z p q r () ty tz px v
r7d₁-act (suc k) zero (suc zero) zero z p q r tx () tz px v
r7d₁-act (suc k) zero (suc zero) (suc zero) z p q r tx () tz px v
r7d₁-act (suc zero) zero (suc zero) (suc (suc ())) z p q r tx ty tz px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc (suc y))) z p q r tx () tz px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc zero)) zero p q r tx ty () px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc zero)) (suc zero) p q r tx ty () px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc zero)) (suc (suc zero)) p q r tx ty () px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc zero)) (suc (suc (suc (suc z)))) p q r tx ty () px v
r7d₁-act (suc (suc k)) zero (suc zero) (suc (suc zero)) (suc (suc (suc zero))) p q r tx ty tz px (a ∷ b ∷ c ∷ d ∷ v) =
  trans (cong (actIH (suc (suc k))) (X12-cons q (s * (a + b)) (s * (a + - b)) (s * (c + d)) (s * (c + - d) ∷ actIH k v)))
    (trans (cong₂ _∷_ (trans (e0 s a b c d) (cong (_* _) s-sq))
             (cong₂ _∷_ (trans (e1 s a b c d) (cong (_* _) s-sq))
               (cong₂ _∷_ (trans (e2 s a b c d) (cong (_* _) s-sq))
                 (cong₂ _∷_ (trans (e3 s a b c d) (cong (_* _) s-sq)) (actIH-invol k v)))))
      (sym (trans (cong (actV (X-gen (suc zero) (suc (suc zero)) q)) (K-cons p q r a b c d v))
             (X12-cons q (rowA a b c d) (rowB a b c d) (rowC a b c d) (rowD a b c d ∷ v)))))
r7d₁-act (suc k) zero (suc (suc x)) y z p q r () ty tz px v
r7d₁-act (suc zero) (suc zero) (suc (suc ())) y z p q r tx ty tz px v
r7d₁-act (suc (suc k)) (suc zero) (suc (suc zero)) y z p q r tx ty tz () v
r7d₁-act (suc (suc k)) (suc zero) (suc (suc (suc x))) y z p q r () ty tz px v
r7d₁-act (suc k) (suc (suc w)) (suc (suc x)) zero z p q r tx () tz px v
r7d₁-act (suc k) (suc (suc w)) (suc (suc x)) (suc zero) z p q r tx () tz px v
r7d₁-act (suc k) (suc (suc w)) (suc (suc x)) (suc (suc y)) zero p q r tx ty () px v
r7d₁-act (suc k) (suc (suc w)) (suc (suc x)) (suc (suc y)) (suc zero) p q r tx ty () px v
r7d₁-act (suc k) (suc (suc w)) (suc (suc x)) (suc (suc y)) (suc (suc z)) p q r tx ty tz px (a ∷ b ∷ v) =
  trans (cong (actIH (suc k)) (shift-actV k (X-gen x y (ℕP.≤-pred (ℕP.≤-pred q))) (s * (a + b)) (s * (a + - b)) (actIH k v)))
    (trans (cong₂ _∷_ (inv₁ a b) (cong₂ _∷_ (inv₂ a b) (r7d₁-act k w x y z (ℕP.≤-pred (ℕP.≤-pred p)) (ℕP.≤-pred (ℕP.≤-pred q)) (ℕP.≤-pred (ℕP.≤-pred r)) (pred₂ tx) (pred₂ ty) (pred₂ tz) px v)))
      (sym (trans (cong (actV (X-gen (suc (suc x)) (suc (suc y)) q)) (shift-actV k (K-gen w x y z (ℕP.≤-pred (ℕP.≤-pred p)) (ℕP.≤-pred (ℕP.≤-pred q)) (ℕP.≤-pred (ℕP.≤-pred r))) a b v))
             (shift-actV k (X-gen x y (ℕP.≤-pred (ℕP.≤-pred q))) a b (actV (K-gen w x y z (ℕP.≤-pred (ℕP.≤-pred p)) (ℕP.≤-pred (ℕP.≤-pred q)) (ℕP.≤-pred (ℕP.≤-pred r))) v)))))
