------------------------------------------------------------------------
-- The Agda standard library
--
-- The external central product of two groups G and H over a common
-- central subgroup A.
--
--                 inl                 inr
--       G ───────────────→ G ∘_A H ←─────────────── H
--
-- Elements are pairs |G| × |H|, as for the direct product, and they
-- multiply componentwise; what changes is the EQUALITY.  Two pairs are
-- identified when they differ by a common element of A, pushed into G
-- on the left and into H on the right with opposite signs:
--
--     (g₁ , h₁) ≈ (g₂ , h₂)   iff   ∃ x ∈ A.
--       g₂ ≈ g₁ ∙ ιˡ x   and   h₂ ≈ h₁ ∙ ιʳ (x ⁻¹).
--
-- That is, G ∘_A H is the quotient (G × H) / {(ιˡ x , ιʳ (x ⁻¹))}, and
-- the antidiagonal being quotiented out is a subgroup precisely because
-- the two images are central.  Centrality is used exactly once, for
-- congruence of the multiplication: the A-part of the left factor has
-- to move past the whole of the right factor.
--
-- The point of the construction is `glue` below — the two copies of A
-- become equal,
--
--     inl (ιˡ x) ≈ inr (ιʳ x),
--
-- so unlike a direct product, G ∘_A H does not contain two independent
-- copies of A.  Taking ιˡ and ιʳ constant at ε (`trivialPair`) collapses
-- the equality to the pointwise one and recovers the direct product.
--
-- This is the EXTERNAL construction: it builds a group from G, H and the
-- identification data.  The internal central product — a subgroup of a
-- given group generated by two commuting subgroups — is the image of
-- inl and inr.
--
-- (Staged in ForStdlib for upstreaming into
-- Algebra.Construct.CentralProduct.)
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module ForStdlib.Algebra.Construct.CentralProduct where

open import Algebra.Bundles using (AbelianGroup ; Group)
open import Algebra.Core using (Op₁ ; Op₂)
open import Algebra.Morphism.Structures
  using (module GroupMorphisms ; module MonoidMorphisms)
open import Algebra.Structures using (IsGroup)
open import Data.Product.Base using (_×_ ; _,_ ; ∃-syntax)
open import Level using (Level ; _⊔_)
open import Relation.Binary.Core using (Rel)
open import Relation.Binary.Structures using (IsEquivalence)
import Algebra.Properties.Group as GroupProperties
import Relation.Binary.Reasoning.Setoid as ≈-Reasoning

open import ForStdlib.Algebra.Morphism.Consequences
  using (isMonoidHomomorphism⇒isGroupHomomorphism)

private
  variable
    a b c ℓ₁ ℓ₂ ℓ₃ : Level

------------------------------------------------------------------------
-- Central identifications
--
-- The data amalgamating G and H: a group A together with a copy of it
-- inside the centre of each factor.  Injectivity of ιˡ and ιʳ is not
-- needed to build the product — it is what makes inl and inr injective,
-- i.e. what makes G and H embed.

record CentralPair (A : AbelianGroup a ℓ₁) (G : Group b ℓ₂) (H : Group c ℓ₃) :
                   Set (a ⊔ b ⊔ c ⊔ ℓ₁ ⊔ ℓ₂ ⊔ ℓ₃) where
  private
    module A = AbelianGroup A
    module G = Group G
    module H = Group H
    module Mˡ = GroupMorphisms A.rawGroup G.rawGroup
    module Mʳ = GroupMorphisms A.rawGroup H.rawGroup

  field
    ιˡ         : A.Carrier → G.Carrier
    ιʳ         : A.Carrier → H.Carrier
    ιˡ-isHomo  : Mˡ.IsGroupHomomorphism ιˡ
    ιʳ-isHomo  : Mʳ.IsGroupHomomorphism ιʳ
    ιˡ-central : ∀ x g → (ιˡ x G.∙ g) G.≈ (g G.∙ ιˡ x)
    ιʳ-central : ∀ x h → (ιʳ x H.∙ h) H.≈ (h H.∙ ιʳ x)

  open Mˡ.IsGroupHomomorphism ιˡ-isHomo public using () renaming
    (⟦⟧-cong to ιˡ-cong ; homo to ιˡ-∙ ; ε-homo to ιˡ-ε ; ⁻¹-homo to ιˡ-⁻¹)
  open Mʳ.IsGroupHomomorphism ιʳ-isHomo public using () renaming
    (⟦⟧-cong to ιʳ-cong ; homo to ιʳ-∙ ; ε-homo to ιʳ-ε ; ⁻¹-homo to ιʳ-⁻¹)

------------------------------------------------------------------------
-- The central product G ∘_A H

module _ (A : AbelianGroup a ℓ₁) (G : Group b ℓ₂) (H : Group c ℓ₃)
         (χ : CentralPair A G H) where

  private
    module A = AbelianGroup A
    module G = Group G
    module H = Group H
    module AP = GroupProperties A.group
    module GP = GroupProperties G
    module HP = GroupProperties H
  open CentralPair χ

  infix  4 _≈′_
  infixl 7 _∙′_
  infix  8 _⁻¹′

  Carrier′ : Set (b ⊔ c)
  Carrier′ = G.Carrier × H.Carrier

  -- Equal up to a common element of A, with opposite signs.
  _≈′_ : Rel Carrier′ (a ⊔ ℓ₂ ⊔ ℓ₃)
  (g₁ , h₁) ≈′ (g₂ , h₂) =
    ∃[ x ] (g₂ G.≈ (g₁ G.∙ ιˡ x)) × (h₂ H.≈ (h₁ H.∙ ιʳ (x A.⁻¹)))

  _∙′_ : Op₂ Carrier′
  (g₁ , h₁) ∙′ (g₂ , h₂) = (g₁ G.∙ g₂) , (h₁ H.∙ h₂)

  ε′ : Carrier′
  ε′ = G.ε , H.ε

  _⁻¹′ : Op₁ Carrier′
  (g₁ , h₁) ⁻¹′ = (g₁ G.⁻¹) , (h₁ H.⁻¹)

  ------------------------------------------------------------------------
  -- Moving a unit of A in and out

  private
    -- ιˡ absorbs the unit, so a pointwise equality is an equality here.
    ιˡ-unit : ∀ g → (g G.∙ ιˡ A.ε) G.≈ g
    ιˡ-unit g = G.trans (G.∙-congˡ ιˡ-ε) (G.identityʳ g)

    ιʳ-unit : ∀ h → (h H.∙ ιʳ (A.ε A.⁻¹)) H.≈ h
    ιʳ-unit h = H.trans (H.∙-congˡ (H.trans (ιʳ-cong AP.ε⁻¹≈ε) ιʳ-ε))
                        (H.identityʳ h)

    from≈ : ∀ {g₁ g₂ h₁ h₂} →
            g₁ G.≈ g₂ → h₁ H.≈ h₂ → (g₁ , h₁) ≈′ (g₂ , h₂)
    from≈ {g₁} {g₂} {h₁} {h₂} eg eh =
      A.ε , G.trans (G.sym eg) (G.sym (ιˡ-unit g₁))
          , H.trans (H.sym eh) (H.sym (ιʳ-unit h₁))

  ------------------------------------------------------------------------
  -- The equality is an equivalence

  private
    refl′ : ∀ {u} → u ≈′ u
    refl′ {g₁ , h₁} = from≈ G.refl H.refl

    sym′ : ∀ {u v} → u ≈′ v → v ≈′ u
    sym′ {g₁ , h₁} {g₂ , h₂} (x , eg , eh) = x A.⁻¹ , left , right
      where
      left : g₁ G.≈ (g₂ G.∙ ιˡ (x A.⁻¹))
      left = begin
        g₁                            ≈⟨ G.sym (G.identityʳ g₁) ⟩
        g₁ G.∙ G.ε                    ≈⟨ G.∙-congˡ (G.sym (G.inverseʳ (ιˡ x))) ⟩
        g₁ G.∙ (ιˡ x G.∙ (ιˡ x) G.⁻¹) ≈⟨ G.sym (G.assoc g₁ (ιˡ x) _) ⟩
        (g₁ G.∙ ιˡ x) G.∙ (ιˡ x) G.⁻¹ ≈⟨ G.∙-congʳ (G.sym eg) ⟩
        g₂ G.∙ (ιˡ x) G.⁻¹            ≈⟨ G.∙-congˡ (G.sym (ιˡ-⁻¹ x)) ⟩
        g₂ G.∙ ιˡ (x A.⁻¹)            ∎
        where open ≈-Reasoning G.setoid
      right : h₁ H.≈ (h₂ H.∙ ιʳ ((x A.⁻¹) A.⁻¹))
      right = begin
        h₁                                    ≈⟨ H.sym (H.identityʳ h₁) ⟩
        h₁ H.∙ H.ε
          ≈⟨ H.∙-congˡ (H.sym (H.inverseʳ (ιʳ (x A.⁻¹)))) ⟩
        h₁ H.∙ (ιʳ (x A.⁻¹) H.∙ (ιʳ (x A.⁻¹)) H.⁻¹)
          ≈⟨ H.sym (H.assoc h₁ (ιʳ (x A.⁻¹)) _) ⟩
        (h₁ H.∙ ιʳ (x A.⁻¹)) H.∙ (ιʳ (x A.⁻¹)) H.⁻¹
          ≈⟨ H.∙-congʳ (H.sym eh) ⟩
        h₂ H.∙ (ιʳ (x A.⁻¹)) H.⁻¹
          ≈⟨ H.∙-congˡ (H.sym (ιʳ-⁻¹ (x A.⁻¹))) ⟩
        h₂ H.∙ ιʳ ((x A.⁻¹) A.⁻¹)             ∎
        where open ≈-Reasoning H.setoid

    trans′ : ∀ {u v w} → u ≈′ v → v ≈′ w → u ≈′ w
    trans′ {g₁ , h₁} {g₂ , h₂} {g₃ , h₃} (x , eg , eh) (y , eg′ , eh′) =
      (x A.∙ y) , left , right
      where
      left : g₃ G.≈ (g₁ G.∙ ιˡ (x A.∙ y))
      left = begin
        g₃                        ≈⟨ eg′ ⟩
        g₂ G.∙ ιˡ y               ≈⟨ G.∙-congʳ eg ⟩
        (g₁ G.∙ ιˡ x) G.∙ ιˡ y    ≈⟨ G.assoc g₁ (ιˡ x) (ιˡ y) ⟩
        g₁ G.∙ (ιˡ x G.∙ ιˡ y)    ≈⟨ G.∙-congˡ (G.sym (ιˡ-∙ x y)) ⟩
        g₁ G.∙ ιˡ (x A.∙ y)       ∎
        where open ≈-Reasoning G.setoid
      right : h₃ H.≈ (h₁ H.∙ ιʳ ((x A.∙ y) A.⁻¹))
      right = begin
        h₃                                        ≈⟨ eh′ ⟩
        h₂ H.∙ ιʳ (y A.⁻¹)                        ≈⟨ H.∙-congʳ eh ⟩
        (h₁ H.∙ ιʳ (x A.⁻¹)) H.∙ ιʳ (y A.⁻¹)
          ≈⟨ H.assoc h₁ (ιʳ (x A.⁻¹)) (ιʳ (y A.⁻¹)) ⟩
        h₁ H.∙ (ιʳ (x A.⁻¹) H.∙ ιʳ (y A.⁻¹))
          ≈⟨ H.∙-congˡ (H.sym (ιʳ-∙ (x A.⁻¹) (y A.⁻¹))) ⟩
        h₁ H.∙ ιʳ (x A.⁻¹ A.∙ y A.⁻¹)
          ≈⟨ H.∙-congˡ (ιʳ-cong (A.sym (A.trans (AP.⁻¹-anti-homo-∙ x y)
                                                (A.comm (y A.⁻¹) (x A.⁻¹))))) ⟩
        h₁ H.∙ ιʳ ((x A.∙ y) A.⁻¹)                ∎
        where open ≈-Reasoning H.setoid

    isEquivalence′ : IsEquivalence _≈′_
    isEquivalence′ = record { refl = refl′ ; sym = sym′ ; trans = trans′ }

  ------------------------------------------------------------------------
  -- The group laws
  --
  -- Multiplication is that of the direct product, so associativity, the
  -- units and the inverses hold pointwise and lift with the witness ε.
  -- Only congruence sees the quotient, and that is where centrality of
  -- the two images is used.

  private
    ∙-cong′ : ∀ {u u′ v v′} → u ≈′ u′ → v ≈′ v′ → (u ∙′ v) ≈′ (u′ ∙′ v′)
    ∙-cong′ {g₁ , h₁} {g₂ , h₂} {g₃ , h₃} {g₄ , h₄}
            (x , eg , eh) (y , eg′ , eh′) = (x A.∙ y) , left , right
      where
      left : (g₂ G.∙ g₄) G.≈ ((g₁ G.∙ g₃) G.∙ ιˡ (x A.∙ y))
      left = begin
        g₂ G.∙ g₄                            ≈⟨ G.∙-cong eg eg′ ⟩
        (g₁ G.∙ ιˡ x) G.∙ (g₃ G.∙ ιˡ y)      ≈⟨ G.assoc g₁ (ιˡ x) _ ⟩
        g₁ G.∙ (ιˡ x G.∙ (g₃ G.∙ ιˡ y))
          ≈⟨ G.∙-congˡ (G.sym (G.assoc (ιˡ x) g₃ (ιˡ y))) ⟩
        g₁ G.∙ ((ιˡ x G.∙ g₃) G.∙ ιˡ y)
          ≈⟨ G.∙-congˡ (G.∙-congʳ (ιˡ-central x g₃)) ⟩
        g₁ G.∙ ((g₃ G.∙ ιˡ x) G.∙ ιˡ y)
          ≈⟨ G.∙-congˡ (G.assoc g₃ (ιˡ x) (ιˡ y)) ⟩
        g₁ G.∙ (g₃ G.∙ (ιˡ x G.∙ ιˡ y))
          ≈⟨ G.sym (G.assoc g₁ g₃ _) ⟩
        (g₁ G.∙ g₃) G.∙ (ιˡ x G.∙ ιˡ y)
          ≈⟨ G.∙-congˡ (G.sym (ιˡ-∙ x y)) ⟩
        (g₁ G.∙ g₃) G.∙ ιˡ (x A.∙ y)         ∎
        where open ≈-Reasoning G.setoid
      right : (h₂ H.∙ h₄) H.≈ ((h₁ H.∙ h₃) H.∙ ιʳ ((x A.∙ y) A.⁻¹))
      right = begin
        h₂ H.∙ h₄
          ≈⟨ H.∙-cong eh eh′ ⟩
        (h₁ H.∙ ιʳ (x A.⁻¹)) H.∙ (h₃ H.∙ ιʳ (y A.⁻¹))
          ≈⟨ H.assoc h₁ (ιʳ (x A.⁻¹)) _ ⟩
        h₁ H.∙ (ιʳ (x A.⁻¹) H.∙ (h₃ H.∙ ιʳ (y A.⁻¹)))
          ≈⟨ H.∙-congˡ (H.sym (H.assoc (ιʳ (x A.⁻¹)) h₃ (ιʳ (y A.⁻¹)))) ⟩
        h₁ H.∙ ((ιʳ (x A.⁻¹) H.∙ h₃) H.∙ ιʳ (y A.⁻¹))
          ≈⟨ H.∙-congˡ (H.∙-congʳ (ιʳ-central (x A.⁻¹) h₃)) ⟩
        h₁ H.∙ ((h₃ H.∙ ιʳ (x A.⁻¹)) H.∙ ιʳ (y A.⁻¹))
          ≈⟨ H.∙-congˡ (H.assoc h₃ (ιʳ (x A.⁻¹)) (ιʳ (y A.⁻¹))) ⟩
        h₁ H.∙ (h₃ H.∙ (ιʳ (x A.⁻¹) H.∙ ιʳ (y A.⁻¹)))
          ≈⟨ H.sym (H.assoc h₁ h₃ _) ⟩
        (h₁ H.∙ h₃) H.∙ (ιʳ (x A.⁻¹) H.∙ ιʳ (y A.⁻¹))
          ≈⟨ H.∙-congˡ (H.sym (ιʳ-∙ (x A.⁻¹) (y A.⁻¹))) ⟩
        (h₁ H.∙ h₃) H.∙ ιʳ (x A.⁻¹ A.∙ y A.⁻¹)
          ≈⟨ H.∙-congˡ (ιʳ-cong (A.sym (A.trans (AP.⁻¹-anti-homo-∙ x y)
                                                (A.comm (y A.⁻¹) (x A.⁻¹))))) ⟩
        (h₁ H.∙ h₃) H.∙ ιʳ ((x A.∙ y) A.⁻¹)  ∎
        where open ≈-Reasoning H.setoid

    assoc′ : ∀ u v w → ((u ∙′ v) ∙′ w) ≈′ (u ∙′ (v ∙′ w))
    assoc′ (g₁ , h₁) (g₂ , h₂) (g₃ , h₃) =
      from≈ (G.assoc g₁ g₂ g₃) (H.assoc h₁ h₂ h₃)

    identityˡ′ : ∀ u → (ε′ ∙′ u) ≈′ u
    identityˡ′ (g₁ , h₁) = from≈ (G.identityˡ g₁) (H.identityˡ h₁)

    identityʳ′ : ∀ u → (u ∙′ ε′) ≈′ u
    identityʳ′ (g₁ , h₁) = from≈ (G.identityʳ g₁) (H.identityʳ h₁)

    inverseˡ′ : ∀ u → ((u ⁻¹′) ∙′ u) ≈′ ε′
    inverseˡ′ (g₁ , h₁) = from≈ (G.inverseˡ g₁) (H.inverseˡ h₁)

    inverseʳ′ : ∀ u → (u ∙′ (u ⁻¹′)) ≈′ ε′
    inverseʳ′ (g₁ , h₁) = from≈ (G.inverseʳ g₁) (H.inverseʳ h₁)

    -- Inverting turns the witness x into x ⁻¹; centrality is what lets
    -- the A-part come back out on the right of the inverted product.
    ⁻¹-cong′ : ∀ {u u′} → u ≈′ u′ → (u ⁻¹′) ≈′ (u′ ⁻¹′)
    ⁻¹-cong′ {g₁ , h₁} {g₂ , h₂} (x , eg , eh) = x A.⁻¹ , left , right
      where
      left : (g₂ G.⁻¹) G.≈ ((g₁ G.⁻¹) G.∙ ιˡ (x A.⁻¹))
      left = begin
        g₂ G.⁻¹                       ≈⟨ G.⁻¹-cong eg ⟩
        (g₁ G.∙ ιˡ x) G.⁻¹            ≈⟨ GP.⁻¹-anti-homo-∙ g₁ (ιˡ x) ⟩
        (ιˡ x) G.⁻¹ G.∙ (g₁ G.⁻¹)     ≈⟨ G.∙-congʳ (G.sym (ιˡ-⁻¹ x)) ⟩
        ιˡ (x A.⁻¹) G.∙ (g₁ G.⁻¹)     ≈⟨ ιˡ-central (x A.⁻¹) (g₁ G.⁻¹) ⟩
        (g₁ G.⁻¹) G.∙ ιˡ (x A.⁻¹)     ∎
        where open ≈-Reasoning G.setoid
      right : (h₂ H.⁻¹) H.≈ ((h₁ H.⁻¹) H.∙ ιʳ ((x A.⁻¹) A.⁻¹))
      right = begin
        h₂ H.⁻¹                                   ≈⟨ H.⁻¹-cong eh ⟩
        (h₁ H.∙ ιʳ (x A.⁻¹)) H.⁻¹
          ≈⟨ HP.⁻¹-anti-homo-∙ h₁ (ιʳ (x A.⁻¹)) ⟩
        (ιʳ (x A.⁻¹)) H.⁻¹ H.∙ (h₁ H.⁻¹)
          ≈⟨ H.∙-congʳ (H.sym (ιʳ-⁻¹ (x A.⁻¹))) ⟩
        ιʳ ((x A.⁻¹) A.⁻¹) H.∙ (h₁ H.⁻¹)
          ≈⟨ ιʳ-central ((x A.⁻¹) A.⁻¹) (h₁ H.⁻¹) ⟩
        (h₁ H.⁻¹) H.∙ ιʳ ((x A.⁻¹) A.⁻¹)          ∎
        where open ≈-Reasoning H.setoid

  isGroup′ : IsGroup _≈′_ _∙′_ ε′ _⁻¹′
  isGroup′ = record
    { isMonoid = record
      { isSemigroup = record
        { isMagma = record
          { isEquivalence = isEquivalence′
          ; ∙-cong        = ∙-cong′
          }
        ; assoc = assoc′
        }
      ; identity = identityˡ′ , identityʳ′
      }
    ; inverse = inverseˡ′ , inverseʳ′
    ; ⁻¹-cong = ⁻¹-cong′
    }

  group : Group (b ⊔ c) (a ⊔ ℓ₂ ⊔ ℓ₃)
  group = record { isGroup = isGroup′ }

  ------------------------------------------------------------------------
  -- The two factors, and the identification they satisfy

  inl : G.Carrier → Carrier′
  inl g = g , H.ε

  inr : H.Carrier → Carrier′
  inr h = G.ε , h

  private
    module MG = MonoidMorphisms G.rawMonoid (Group.rawMonoid group)
    module MH = MonoidMorphisms H.rawMonoid (Group.rawMonoid group)

    inl-mon : MG.IsMonoidHomomorphism inl
    inl-mon = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = λ eq → from≈ eq H.refl }
        ; homo              = λ g₁ g₂ →
                              from≈ G.refl (H.sym (H.identityˡ H.ε))
        }
      ; ε-homo = refl′
      }

    inr-mon : MH.IsMonoidHomomorphism inr
    inr-mon = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = from≈ G.refl }
        ; homo              = λ h₁ h₂ →
                              from≈ (G.sym (G.identityˡ G.ε)) H.refl
        }
      ; ε-homo = refl′
      }

  inl-isHomo = isMonoidHomomorphism⇒isGroupHomomorphism G group inl-mon
  inr-isHomo = isMonoidHomomorphism⇒isGroupHomomorphism H group inr-mon

  -- The images of G and of H commute with one another.
  commuting : ∀ g h → (inl g ∙′ inr h) ≈′ (inr h ∙′ inl g)
  commuting g h = from≈ (G.trans (G.identityʳ g) (G.sym (G.identityˡ g)))
                        (H.trans (H.identityˡ h) (H.sym (H.identityʳ h)))

  -- …and the two copies of A have become one.  This is what makes the
  -- central product a quotient of, and not equal to, the direct product.
  glue : ∀ x → inl (ιˡ x) ≈′ inr (ιʳ x)
  glue x = x A.⁻¹ , left , right
    where
    left : G.ε G.≈ (ιˡ x G.∙ ιˡ (x A.⁻¹))
    left = begin
      G.ε                       ≈⟨ G.sym (G.inverseʳ (ιˡ x)) ⟩
      ιˡ x G.∙ (ιˡ x) G.⁻¹      ≈⟨ G.∙-congˡ (G.sym (ιˡ-⁻¹ x)) ⟩
      ιˡ x G.∙ ιˡ (x A.⁻¹)      ∎
      where open ≈-Reasoning G.setoid
    right : ιʳ x H.≈ (H.ε H.∙ ιʳ ((x A.⁻¹) A.⁻¹))
    right = begin
      ιʳ x                             ≈⟨ ιʳ-cong (A.sym (AP.⁻¹-involutive x)) ⟩
      ιʳ ((x A.⁻¹) A.⁻¹)               ≈⟨ H.sym (H.identityˡ _) ⟩
      H.ε H.∙ ιʳ ((x A.⁻¹) A.⁻¹)       ∎
      where open ≈-Reasoning H.setoid

------------------------------------------------------------------------
-- The trivial identification
--
-- ιˡ, ιʳ constant at ε is central and homomorphic, and the equality it
-- induces is the pointwise one: the central product over it is the
-- direct product of G and H.

trivialPair : (A : AbelianGroup a ℓ₁) (G : Group b ℓ₂) (H : Group c ℓ₃) →
              CentralPair A G H
trivialPair A G H = record
  { ιˡ         = λ _ → G.ε
  ; ιʳ         = λ _ → H.ε
  ; ιˡ-isHomo  = record
    { isMonoidHomomorphism = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = λ _ → G.refl }
        ; homo              = λ _ _ → G.sym (G.identityˡ G.ε)
        }
      ; ε-homo = G.refl
      }
    ; ⁻¹-homo = λ _ → G.sym GP.ε⁻¹≈ε
    }
  ; ιʳ-isHomo  = record
    { isMonoidHomomorphism = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = λ _ → H.refl }
        ; homo              = λ _ _ → H.sym (H.identityˡ H.ε)
        }
      ; ε-homo = H.refl
      }
    ; ⁻¹-homo = λ _ → H.sym HP.ε⁻¹≈ε
    }
  ; ιˡ-central = λ _ g → G.trans (G.identityˡ g) (G.sym (G.identityʳ g))
  ; ιʳ-central = λ _ h → H.trans (H.identityˡ h) (H.sym (H.identityʳ h))
  }
  where
  module G = Group G
  module H = Group H
  module GP = GroupProperties G
  module HP = GroupProperties H
