------------------------------------------------------------------------
-- Presentations of groups
--
-- The relations of Clément's Subcase 1.14.2, on four indices
-- 0 < 1 < 2 < 3 in any set of relations Γ that derives the local ones.
--
-- With PA = H[0,1] H[2,3], PB = H[0,2] H[1,3] and PC = H[0,3] H[1,2],
-- the squares of 1.14.2 close by
--
--   r27 : H[2,3] PB X[1,2] PB H[2,3] • H[0,1] • X[1,2] = H[0,1]
--   r28 : H[2,3] PC X[1,3] PC H[2,3] • H[0,1] • X[1,2] = H[0,1]
--
-- (his (27) and (28) in the form the squares use), from (f1)
-- PA PB = PB PA and (G) PB PC = H[0,1] H[2,3] X[1,3] Z[3] H[2,3] H[0,1]
-- (Real-Clifford+CH-TwoLevel.Pairings).  Generated by
-- scripts/diagrams/gen1142.py.
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

open import Word.Base using (WRel)
import Presentation.Base as PB
open import Examples.Groups.Real-Clifford+CH-TwoLevel.Syntactics using (Gen)
open import Examples.Groups.Real-Clifford+CH-TwoLevel.LocalRelations using (_===ˡ_)

module Examples.Groups.Real-Clifford+CH-TwoLevel-Clement.Thesis.Rel1142 where

open import Data.Fin.Base using (Fin ; zero ; suc ; _<_)
open import Data.List.Base using (List ; [] ; _∷_)
open import Data.Nat.Base using (z≤n ; s≤s)
open import Relation.Binary.PropositionalEquality using (refl)

open import Examples.Groups.Real-Clifford+CH-TwoLevel.Syntactics using (H-gen ; X-gen ; Z-gen)
import Presentation.Tactics.Words as TW

------------------------------------------------------------------------
-- Letters

f0 f1 f2 f3 : Fin 4
f0 = zero
f1 = (suc zero)
f2 = (suc (suc zero))
f3 = (suc (suc (suc zero)))

lt01 : f0 < f1
lt01 = s≤s z≤n
lt02 : f0 < f2
lt02 = s≤s z≤n
lt03 : f0 < f3
lt03 = s≤s z≤n
lt12 : f1 < f2
lt12 = s≤s (s≤s z≤n)
lt13 : f1 < f3
lt13 = s≤s (s≤s z≤n)
lt23 : f2 < f3
lt23 = s≤s (s≤s (s≤s z≤n))

h01 : Gen 4
h01 = H-gen f0 f1 lt01
h02 : Gen 4
h02 = H-gen f0 f2 lt02
h03 : Gen 4
h03 = H-gen f0 f3 lt03
h12 : Gen 4
h12 = H-gen f1 f2 lt12
h13 : Gen 4
h13 = H-gen f1 f3 lt13
h23 : Gen 4
h23 = H-gen f2 f3 lt23
x12 : Gen 4
x12 = X-gen f1 f2 lt12
x13 : Gen 4
x13 = X-gen f1 f3 lt13
x23 : Gen 4
x23 = X-gen f2 f3 lt23
z3 : Gen 4
z3 = Z-gen f3

------------------------------------------------------------------------
-- The relations as letter lists (operator order)

Lf1 : List (Gen 4)
Lf1 = (h01 ∷ h23 ∷ h02 ∷ h13 ∷ [])
Rf1 : List (Gen 4)
Rf1 = (h02 ∷ h13 ∷ h01 ∷ h23 ∷ [])
LG : List (Gen 4)
LG = (h02 ∷ h13 ∷ h03 ∷ h12 ∷ [])
RG : List (Gen 4)
RG = (h01 ∷ h23 ∷ x13 ∷ z3 ∷ h23 ∷ h01 ∷ [])
L27 : List (Gen 4)
L27 = (h23 ∷ h02 ∷ h13 ∷ x12 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
L28 : List (Gen 4)
L28 = (h23 ∷ h03 ∷ h12 ∷ x13 ∷ h03 ∷ h12 ∷ h23 ∷ h01 ∷ x12 ∷ [])
R2728 : List (Gen 4)
R2728 = (h01 ∷ [])

------------------------------------------------------------------------
-- The derivations

module From (Γ : WRel (Gen 4)) (loc : ∀ {u v} → u ===ˡ v → PB._≈_ Γ u v)
  (f1eh : PB._≈_ Γ (TW.Associative.word-of-list Lf1) (TW.Associative.word-of-list Rf1))
  (Geh : PB._≈_ Γ (TW.Associative.word-of-list LG) (TW.Associative.word-of-list RG)) where

  open import Examples.Groups.Real-Clifford+CH-TwoLevel.Engine Γ loc
  open PB Γ using (_≈_)

  private
    f1e : Eqn
    f1e = eqn Lf1 Rf1 f1eh
    Ge : Eqn
    Ge = eqn LG RG Geh

    δxpp : Eqn
    δxpp = derive (x13 ∷ h02 ∷ h13 ∷ h01 ∷ h23 ∷ []) (h02 ∷ h13 ∷ h01 ∷ h23 ∷ x23 ∷ [])
      ( perm (x13 ∷ h02 ∷ h13 ∷ h01 ∷ h23 ∷ [])
      ∷ rw 0 (sym⁼ (ʟa3 f1 f3 lt13))
      ∷ perm (h13 ∷ h13 ∷ x13 ∷ h02 ∷ h13 ∷ h01 ∷ h23 ∷ [])
      ∷ rw 1 (sym⁼ (ʟd2 f1 f3 lt13))
      ∷ perm (h13 ∷ z3 ∷ h02 ∷ h13 ∷ h13 ∷ h01 ∷ h23 ∷ [])
      ∷ rw 3 (ʟa3 f1 f3 lt13)
      ∷ perm (h02 ∷ h13 ∷ h01 ∷ z3 ∷ h23 ∷ [])
      ∷ rw 3 (ʟd2 f2 f3 lt23)
      ∷ perm (h02 ∷ h13 ∷ h01 ∷ h23 ∷ x23 ∷ [])
      ∷ []
      ) refl

    δpcG : Eqn
    δpcG = derive (h03 ∷ h12 ∷ []) (h02 ∷ h13 ∷ h01 ∷ h23 ∷ x13 ∷ z3 ∷ h23 ∷ h01 ∷ [])
      ( perm (h03 ∷ h12 ∷ [])
      ∷ rw 0 (sym⁼ (ʟa3 f0 f2 lt02))
      ∷ perm (h02 ∷ h02 ∷ h03 ∷ h12 ∷ [])
      ∷ rw 0 (sym⁼ (ʟa3 f1 f3 lt13))
      ∷ perm (h02 ∷ h13 ∷ h02 ∷ h13 ∷ h03 ∷ h12 ∷ [])
      ∷ rw 2 Ge
      ∷ perm (h02 ∷ h13 ∷ h01 ∷ h23 ∷ x13 ∷ z3 ∷ h23 ∷ h01 ∷ [])
      ∷ []
      ) refl

    δxx : Eqn
    δxx = derive (x23 ∷ x13 ∷ []) (x13 ∷ x12 ∷ [])
      ( perm (x23 ∷ x13 ∷ [])
      ∷ rw 1 (sym⁼ (ʟa2 f1 f2 lt12))
      ∷ perm (x23 ∷ x12 ∷ x12 ∷ x13 ∷ [])
      ∷ rw 0 (sym⁼ (ʟc3 f1 f2 f3 lt12 lt23))
      ∷ perm (x13 ∷ x23 ∷ x12 ∷ x13 ∷ [])
      ∷ rw 1 (ʟc2 f1 f2 f3 lt12 lt23)
      ∷ perm (x13 ∷ x12 ∷ x13 ∷ x13 ∷ [])
      ∷ rw 2 (ʟa2 f1 f3 lt13)
      ∷ perm (x13 ∷ x12 ∷ [])
      ∷ []
      ) refl

    δcore : Eqn
    δcore = derive (x13 ∷ h03 ∷ h12 ∷ h01 ∷ h23 ∷ []) (h03 ∷ h12 ∷ h01 ∷ h23 ∷ x12 ∷ [])
      ( rw 1 δpcG
      ∷ perm (x13 ∷ h02 ∷ h13 ∷ h01 ∷ h23 ∷ x13 ∷ z3 ∷ h23 ∷ h23 ∷ h01 ∷ h01 ∷ [])
      ∷ rw 7 (ʟa3 f2 f3 lt23)
      ∷ rw 7 (ʟa3 f0 f1 lt01)
      ∷ rw 0 δxpp
      ∷ rw 4 δxx
      ∷ perm (h02 ∷ h13 ∷ h01 ∷ h23 ∷ x13 ∷ z3 ∷ x12 ∷ [])
      ∷ rw 6 (sym⁼ (ʟa3 f2 f3 lt23))
      ∷ rw 7 (sym⁼ (ʟa3 f0 f1 lt01))
      ∷ rw 0 (sym⁼ δpcG)
      ∷ perm (h03 ∷ h12 ∷ h01 ∷ h23 ∷ x12 ∷ [])
      ∷ perm (h03 ∷ h12 ∷ h01 ∷ h23 ∷ x12 ∷ [])
      ∷ []
      ) refl

    δr27 : Eqn
    δr27 = derive (h23 ∷ h02 ∷ h13 ∷ x12 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ []) (h01 ∷ [])
      ( perm (h23 ∷ h02 ∷ h13 ∷ x12 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 1 (sym⁼ (ʟa2 f1 f2 lt12))
      ∷ perm (h23 ∷ x12 ∷ x12 ∷ h13 ∷ h02 ∷ x12 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 4 (ʟc5 f0 f1 f2 lt01 lt12)
      ∷ perm (h23 ∷ x12 ∷ x12 ∷ h13 ∷ x12 ∷ h01 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 0 (ʟc4 f1 f2 f3 lt12 lt23)
      ∷ perm (x12 ∷ h13 ∷ x12 ∷ h13 ∷ x12 ∷ h01 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 2 (sym⁼ (ʟc4 f1 f2 f3 lt12 lt23))
      ∷ perm (x12 ∷ h13 ∷ h23 ∷ x12 ∷ x12 ∷ h01 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 3 (ʟa2 f1 f2 lt12)
      ∷ perm (x12 ∷ h13 ∷ h01 ∷ h23 ∷ h02 ∷ h13 ∷ h23 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 2 f1e
      ∷ perm (x12 ∷ h13 ∷ h13 ∷ h02 ∷ h23 ∷ h23 ∷ h01 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 4 (ʟa3 f2 f3 lt23)
      ∷ perm (x12 ∷ h13 ∷ h13 ∷ h02 ∷ h01 ∷ h01 ∷ x12 ∷ [])
      ∷ rw 4 (ʟa3 f0 f1 lt01)
      ∷ perm (x12 ∷ h13 ∷ h13 ∷ h02 ∷ x12 ∷ [])
      ∷ rw 3 (ʟc5 f0 f1 f2 lt01 lt12)
      ∷ perm (x12 ∷ h13 ∷ h13 ∷ x12 ∷ h01 ∷ [])
      ∷ rw 1 (ʟa3 f1 f3 lt13)
      ∷ perm (x12 ∷ x12 ∷ h01 ∷ [])
      ∷ rw 0 (ʟa2 f1 f2 lt12)
      ∷ perm (h01 ∷ [])
      ∷ []
      ) refl

    δr28 : Eqn
    δr28 = derive (h23 ∷ h03 ∷ h12 ∷ x13 ∷ h03 ∷ h12 ∷ h23 ∷ h01 ∷ x12 ∷ []) (h01 ∷ [])
      ( perm (h23 ∷ h03 ∷ h12 ∷ x13 ∷ h03 ∷ h12 ∷ h01 ∷ h23 ∷ x12 ∷ [])
      ∷ rw 4 (sym⁼ δcore)
      ∷ rw 3 (ʟa2 f1 f3 lt13)
      ∷ perm (h23 ∷ h03 ∷ h03 ∷ h12 ∷ h12 ∷ h01 ∷ h23 ∷ [])
      ∷ rw 1 (ʟa3 f0 f3 lt03)
      ∷ rw 1 (ʟa3 f1 f2 lt12)
      ∷ perm (h23 ∷ h23 ∷ h01 ∷ [])
      ∷ rw 0 (ʟa3 f2 f3 lt23)
      ∷ perm (h01 ∷ [])
      ∷ perm (h01 ∷ [])
      ∷ []
      ) refl

  r27 : ⟪ L27 ⟫ ≈ ⟪ R2728 ⟫
  r27 = prf δr27

  r28 : ⟪ L28 ⟫ ≈ ⟪ R2728 ⟫
  r28 = prf δr28
