------------------------------------------------------------------------
-- Presentations of groups
--
-- The local vectors along the routes of Clément's Subcase 1.14.2.
--
-- On the four entries a < b < c < d of one class, at r = X[b,c]·s,
-- with entries A, A + 2p, A + 2q, A + 2d: H[a,b] and H[c,d], then
-- PB = H[a,c] H[b,d], X[b,c] and PB again (vr, v0, …, v6), or PC =
-- H[a,d] H[b,c], X[b,d] and PC again (w2, …, w6).  Each H acts at the
-- same scale: the sum and the difference of its two entries are √2
-- times the new entries.  Generated by scripts/diagrams/gen1142.py.
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

open import Examples.Groups.Real-Clifford+CH-TwoLevel.Ring using (Z)

module Examples.Groups.Real-Clifford+CH-TwoLevel-Clement.Thesis.Steps1142 (A p q d : Z) where

open import Data.Vec.Base using (Vec ; [] ; _∷_)
open import Relation.Binary.PropositionalEquality using (_≡_ ; refl)

open import Examples.Groups.Real-Clifford+CH-TwoLevel.Ring using (module ZR ; module ZG ; √2ᶻ)
open import Examples.Groups.Real-Clifford+CH-TwoLevel.Norm using (2ᶻ)

open ZG using (_:+_ ; _:*_ ; :-_ ; _:-_ ; _:=_ ; con)

------------------------------------------------------------------------
-- The vectors

vr : Vec Z 4
vr = A ∷ (A ZR.+ (2ᶻ ZR.* p)) ∷ (A ZR.+ (2ᶻ ZR.* q)) ∷ (A ZR.+ (2ᶻ ZR.* d)) ∷ []
v0 : Vec Z 4
v0 = (√2ᶻ ZR.* (A ZR.+ p)) ∷ (ZR.- (√2ᶻ ZR.* p)) ∷ (A ZR.+ (2ᶻ ZR.* q)) ∷ (A ZR.+ (2ᶻ ZR.* d)) ∷ []
v1 : Vec Z 4
v1 = (√2ᶻ ZR.* (A ZR.+ p)) ∷ (ZR.- (√2ᶻ ZR.* p)) ∷ (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ∷ (√2ᶻ ZR.* (q ZR.- d)) ∷ []
v2 : Vec Z 4
v2 = (√2ᶻ ZR.* (A ZR.+ p)) ∷ ((q ZR.- d) ZR.- p) ∷ (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ∷ ((ZR.- p) ZR.- (q ZR.- d)) ∷ []
v3 : Vec Z 4
v3 = ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d)) ∷ ((q ZR.- d) ZR.- p) ∷ ((A ZR.+ p) ZR.- ((A ZR.+ q) ZR.+ d)) ∷ ((ZR.- p) ZR.- (q ZR.- d)) ∷ []
v4 : Vec Z 4
v4 = ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d)) ∷ ((A ZR.+ p) ZR.- ((A ZR.+ q) ZR.+ d)) ∷ ((q ZR.- d) ZR.- p) ∷ ((ZR.- p) ZR.- (q ZR.- d)) ∷ []
v5 : Vec Z 4
v5 = ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d)) ∷ (ZR.- (√2ᶻ ZR.* q)) ∷ ((q ZR.- d) ZR.- p) ∷ (√2ᶻ ZR.* (p ZR.- d)) ∷ []
v6 : Vec Z 4
v6 = (√2ᶻ ZR.* (A ZR.+ q)) ∷ (ZR.- (√2ᶻ ZR.* q)) ∷ (√2ᶻ ZR.* ((A ZR.+ p) ZR.+ d)) ∷ (√2ᶻ ZR.* (p ZR.- d)) ∷ []
w2 : Vec Z 4
w2 = (√2ᶻ ZR.* (A ZR.+ p)) ∷ (((A ZR.+ q) ZR.+ d) ZR.- p) ∷ ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d)) ∷ (√2ᶻ ZR.* (q ZR.- d)) ∷ []
w3 : Vec Z 4
w3 = ((A ZR.+ p) ZR.+ (q ZR.- d)) ∷ (((A ZR.+ q) ZR.+ d) ZR.- p) ∷ ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d)) ∷ ((A ZR.+ p) ZR.- (q ZR.- d)) ∷ []
w4 : Vec Z 4
w4 = ((A ZR.+ p) ZR.+ (q ZR.- d)) ∷ ((A ZR.+ p) ZR.- (q ZR.- d)) ∷ ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d)) ∷ (((A ZR.+ q) ZR.+ d) ZR.- p) ∷ []
w5 : Vec Z 4
w5 = ((A ZR.+ p) ZR.+ (q ZR.- d)) ∷ (ZR.- (√2ᶻ ZR.* q)) ∷ (√2ᶻ ZR.* ((A ZR.+ p) ZR.+ d)) ∷ (((A ZR.+ q) ZR.+ d) ZR.- p) ∷ []
w6 : Vec Z 4
w6 = (√2ᶻ ZR.* (A ZR.+ q)) ∷ (ZR.- (√2ᶻ ZR.* q)) ∷ (√2ᶻ ZR.* ((A ZR.+ p) ZR.+ d)) ∷ (√2ᶻ ZR.* (p ZR.- d)) ∷ []

------------------------------------------------------------------------
-- The steps

h01-sum : A ZR.+ (A ZR.+ (2ᶻ ZR.* p)) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (A ZR.+ p))
h01-sum = ZG.solve 4 (λ A p q d → A :+ (A :+ ((con 2ᶻ) :* p)) := (con √2ᶻ) :* ((con √2ᶻ) :* (A :+ p))) refl A p q d
h01-dif : A ZR.- (A ZR.+ (2ᶻ ZR.* p)) ≡ √2ᶻ ZR.* (ZR.- (√2ᶻ ZR.* p))
h01-dif = ZG.solve 4 (λ A p q d → A :- (A :+ ((con 2ᶻ) :* p)) := (con √2ᶻ) :* (:- ((con √2ᶻ) :* p))) refl A p q d

h23-sum : (A ZR.+ (2ᶻ ZR.* q)) ZR.+ (A ZR.+ (2ᶻ ZR.* d)) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d))
h23-sum = ZG.solve 4 (λ A p q d → (A :+ ((con 2ᶻ) :* q)) :+ (A :+ ((con 2ᶻ) :* d)) := (con √2ᶻ) :* ((con √2ᶻ) :* ((A :+ q) :+ d))) refl A p q d
h23-dif : (A ZR.+ (2ᶻ ZR.* q)) ZR.- (A ZR.+ (2ᶻ ZR.* d)) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (q ZR.- d))
h23-dif = ZG.solve 4 (λ A p q d → (A :+ ((con 2ᶻ) :* q)) :- (A :+ ((con 2ᶻ) :* d)) := (con √2ᶻ) :* ((con √2ᶻ) :* (q :- d))) refl A p q d

e13-sum : (ZR.- (√2ᶻ ZR.* p)) ZR.+ (√2ᶻ ZR.* (q ZR.- d)) ≡ √2ᶻ ZR.* ((q ZR.- d) ZR.- p)
e13-sum = ZG.solve 4 (λ A p q d → (:- ((con √2ᶻ) :* p)) :+ ((con √2ᶻ) :* (q :- d)) := (con √2ᶻ) :* ((q :- d) :- p)) refl A p q d
e13-dif : (ZR.- (√2ᶻ ZR.* p)) ZR.- (√2ᶻ ZR.* (q ZR.- d)) ≡ √2ᶻ ZR.* ((ZR.- p) ZR.- (q ZR.- d))
e13-dif = ZG.solve 4 (λ A p q d → (:- ((con √2ᶻ) :* p)) :- ((con √2ᶻ) :* (q :- d)) := (con √2ᶻ) :* ((:- p) :- (q :- d))) refl A p q d

e02-sum : (√2ᶻ ZR.* (A ZR.+ p)) ZR.+ (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d))
e02-sum = ZG.solve 4 (λ A p q d → ((con √2ᶻ) :* (A :+ p)) :+ ((con √2ᶻ) :* ((A :+ q) :+ d)) := (con √2ᶻ) :* ((A :+ p) :+ ((A :+ q) :+ d))) refl A p q d
e02-dif : (√2ᶻ ZR.* (A ZR.+ p)) ZR.- (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* ((A ZR.+ p) ZR.- ((A ZR.+ q) ZR.+ d))
e02-dif = ZG.solve 4 (λ A p q d → ((con √2ᶻ) :* (A :+ p)) :- ((con √2ᶻ) :* ((A :+ q) :+ d)) := (con √2ᶻ) :* ((A :+ p) :- ((A :+ q) :+ d))) refl A p q d

e13′-sum : ((A ZR.+ p) ZR.- ((A ZR.+ q) ZR.+ d)) ZR.+ ((ZR.- p) ZR.- (q ZR.- d)) ≡ √2ᶻ ZR.* (ZR.- (√2ᶻ ZR.* q))
e13′-sum = ZG.solve 4 (λ A p q d → ((A :+ p) :- ((A :+ q) :+ d)) :+ ((:- p) :- (q :- d)) := (con √2ᶻ) :* (:- ((con √2ᶻ) :* q))) refl A p q d
e13′-dif : ((A ZR.+ p) ZR.- ((A ZR.+ q) ZR.+ d)) ZR.- ((ZR.- p) ZR.- (q ZR.- d)) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (p ZR.- d))
e13′-dif = ZG.solve 4 (λ A p q d → ((A :+ p) :- ((A :+ q) :+ d)) :- ((:- p) :- (q :- d)) := (con √2ᶻ) :* ((con √2ᶻ) :* (p :- d))) refl A p q d

e02′-sum : ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d)) ZR.+ ((q ZR.- d) ZR.- p) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (A ZR.+ q))
e02′-sum = ZG.solve 4 (λ A p q d → ((A :+ p) :+ ((A :+ q) :+ d)) :+ ((q :- d) :- p) := (con √2ᶻ) :* ((con √2ᶻ) :* (A :+ q))) refl A p q d
e02′-dif : ((A ZR.+ p) ZR.+ ((A ZR.+ q) ZR.+ d)) ZR.- ((q ZR.- d) ZR.- p) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* ((A ZR.+ p) ZR.+ d))
e02′-dif = ZG.solve 4 (λ A p q d → ((A :+ p) :+ ((A :+ q) :+ d)) :- ((q :- d) :- p) := (con √2ᶻ) :* ((con √2ᶻ) :* ((A :+ p) :+ d))) refl A p q d

o12-sum : (ZR.- (√2ᶻ ZR.* p)) ZR.+ (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* (((A ZR.+ q) ZR.+ d) ZR.- p)
o12-sum = ZG.solve 4 (λ A p q d → (:- ((con √2ᶻ) :* p)) :+ ((con √2ᶻ) :* ((A :+ q) :+ d)) := (con √2ᶻ) :* (((A :+ q) :+ d) :- p)) refl A p q d
o12-dif : (ZR.- (√2ᶻ ZR.* p)) ZR.- (√2ᶻ ZR.* ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d))
o12-dif = ZG.solve 4 (λ A p q d → (:- ((con √2ᶻ) :* p)) :- ((con √2ᶻ) :* ((A :+ q) :+ d)) := (con √2ᶻ) :* ((:- p) :- ((A :+ q) :+ d))) refl A p q d

o03-sum : (√2ᶻ ZR.* (A ZR.+ p)) ZR.+ (√2ᶻ ZR.* (q ZR.- d)) ≡ √2ᶻ ZR.* ((A ZR.+ p) ZR.+ (q ZR.- d))
o03-sum = ZG.solve 4 (λ A p q d → ((con √2ᶻ) :* (A :+ p)) :+ ((con √2ᶻ) :* (q :- d)) := (con √2ᶻ) :* ((A :+ p) :+ (q :- d))) refl A p q d
o03-dif : (√2ᶻ ZR.* (A ZR.+ p)) ZR.- (√2ᶻ ZR.* (q ZR.- d)) ≡ √2ᶻ ZR.* ((A ZR.+ p) ZR.- (q ZR.- d))
o03-dif = ZG.solve 4 (λ A p q d → ((con √2ᶻ) :* (A :+ p)) :- ((con √2ᶻ) :* (q :- d)) := (con √2ᶻ) :* ((A :+ p) :- (q :- d))) refl A p q d

o12′-sum : ((A ZR.+ p) ZR.- (q ZR.- d)) ZR.+ ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* (ZR.- (√2ᶻ ZR.* q))
o12′-sum = ZG.solve 4 (λ A p q d → ((A :+ p) :- (q :- d)) :+ ((:- p) :- ((A :+ q) :+ d)) := (con √2ᶻ) :* (:- ((con √2ᶻ) :* q))) refl A p q d
o12′-dif : ((A ZR.+ p) ZR.- (q ZR.- d)) ZR.- ((ZR.- p) ZR.- ((A ZR.+ q) ZR.+ d)) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* ((A ZR.+ p) ZR.+ d))
o12′-dif = ZG.solve 4 (λ A p q d → ((A :+ p) :- (q :- d)) :- ((:- p) :- ((A :+ q) :+ d)) := (con √2ᶻ) :* ((con √2ᶻ) :* ((A :+ p) :+ d))) refl A p q d

o03′-sum : ((A ZR.+ p) ZR.+ (q ZR.- d)) ZR.+ (((A ZR.+ q) ZR.+ d) ZR.- p) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (A ZR.+ q))
o03′-sum = ZG.solve 4 (λ A p q d → ((A :+ p) :+ (q :- d)) :+ (((A :+ q) :+ d) :- p) := (con √2ᶻ) :* ((con √2ᶻ) :* (A :+ q))) refl A p q d
o03′-dif : ((A ZR.+ p) ZR.+ (q ZR.- d)) ZR.- (((A ZR.+ q) ZR.+ d) ZR.- p) ≡ √2ᶻ ZR.* (√2ᶻ ZR.* (p ZR.- d))
o03′-dif = ZG.solve 4 (λ A p q d → ((A :+ p) :+ (q :- d)) :- (((A :+ q) :+ d) :- p) := (con √2ᶻ) :* ((con √2ᶻ) :* (p :- d))) refl A p q d
