------------------------------------------------------------------------
-- Presentations of groups
--
-- The monoid of 2 × 2 matrices over ℤ/17ℤ
--
-- This is the coefficient side of the faithful model of the qubit
-- Clifford group at one wire.  A Clifford matrix has entries in
-- ℤ[1/√2, i], and the model reduces that ring modulo a prime above 17;
-- all the constants Selinger's one-wire gates need are then residues:
--
--     i    = 4        4² = 16 = −1
--     √2   = 11       11² = 121 = 2
--     1/√2 = 14       11 · 14 = 154 = 9 · 17 + 1
--     ω    = 2        2⁴ = 16 = −1, so 2 has order exactly 8
--
-- 17 is the smallest modulus that can serve: ω has to have order 8, so
-- the modulus must be a prime m with 8 ∣ m − 1, and 17 is the first.
-- That ω keeps its order is the whole point — it is the one thing the
-- P4-action model of the Clifford group cannot see (Qubit.ExactExtension.
-- action-blind), and the reason ω-faithful needs a model at all.
--
-- Only the monoid structure is developed: the presented congruence is
-- generated by the monoid laws and the axioms, so interpreting a circuit
-- needs associativity and a two-sided unit and nothing else.  Both come
-- from ℤ/17ℤ's commutative ring, entrywise; `key` is the one entry-level
-- identity behind associativity, and it is the ring solver's, at modulus
-- 17 = ₂₊ 15.
--
-- The product is written _⊙_ rather than the usual _⊛_ because the ring
-- solver's expression syntax already claims that name.
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Examples.Groups.Clifford.Qubit.Model.Mat2 where

-- fromNat has to be in scope for a numeral to be read at ℤ 17 rather
-- than at ℕ; the Number instances themselves come with Fin.Mod below.
open import Agda.Builtin.FromNat using (Number ; fromNat)
open import Data.Product using (_,_)
-- With fromNat in scope every numeral is overloaded, ℕ's included, and
-- the ℕ instance's constraint is ⊤ — so tt has to be findable.
open import Data.Unit using (⊤ ; tt)
open import Relation.Binary.PropositionalEquality as Eq using (_≡_)

-- Opened wholesale, as Qubit.VSp opens it: the ring solver's operators
-- ⊕ / ⊗ and the Number instances that make 14 a residue both come with
-- it, and neither can be named in a using list.
open import ForStdlib.Data.Fin.Mod

------------------------------------------------------------------------
-- The coefficients

-- ℤ/17ℤ, the ring the Clifford entries are read in.
𝔽 : Set
𝔽 = ℤ 17

------------------------------------------------------------------------
-- The matrices
--
-- Written out entrywise rather than as a Vec of Vecs: at 2 × 2 the
-- products are small enough to state, and being a record the type has
-- eta, so two matrices are equal as soon as their entries are.

infixl 7 _⊙_

record M2 : Set where
  constructor ⟪_,_,_,_⟫
  field
    m₁₁ m₁₂ m₂₁ m₂₂ : 𝔽

open M2 public

-- Matrix product and identity.
_⊙_ : M2 → M2 → M2
⟪ a , b , c , d ⟫ ⊙ ⟪ e , f , g , h ⟫ =
  ⟪ a * e + b * g , a * f + b * h , c * e + d * g , c * f + d * h ⟫

Id : M2
Id = ⟪ 1 , 0 , 0 , 1 ⟫

private

  ⟪⟫-cong : {a b c d a' b' c' d' : 𝔽} →
            a ≡ a' → b ≡ b' → c ≡ c' → d ≡ d' →
            ⟪ a , b , c , d ⟫ ≡ ⟪ a' , b' , c' , d' ⟫
  ⟪⟫-cong Eq.refl Eq.refl Eq.refl Eq.refl = Eq.refl

------------------------------------------------------------------------
-- The monoid laws
--
-- Associativity is `key` at each of the four entries: the entry (i , j)
-- of (M N) P and of M (N P) are its two sides, read off row i of M and
-- column j of P.

private

  key : (a b e f g h p r : 𝔽) →
        (a * e + b * g) * p + (a * f + b * h) * r ≡
        a * (e * p + f * r) + b * (g * p + h * r)
  key = solve 15 8
          (λ a b e f g h p r →
             (((a ⊗ e) ⊕ (b ⊗ g)) ⊗ p) ⊕ (((a ⊗ f) ⊕ (b ⊗ h)) ⊗ r) ,
             (a ⊗ ((e ⊗ p) ⊕ (f ⊗ r))) ⊕ (b ⊗ ((g ⊗ p) ⊕ (h ⊗ r))))
          (λ {_} {_} {_} {_} {_} {_} {_} {_} → Eq.refl)

  unit-l : (x y : 𝔽) → 1 * x + 0 * y ≡ x
  unit-l x y =
    Eq.trans (Eq.cong₂ _+_ (*-identityˡ x) (*-zeroˡ y)) (+-identityʳ x)

  unit-r : (x y : 𝔽) → 0 * x + 1 * y ≡ y
  unit-r x y =
    Eq.trans (Eq.cong₂ _+_ (*-zeroˡ x) (*-identityˡ y)) (+-identityˡ y)

  unit-l' : (x y : 𝔽) → x * 1 + y * 0 ≡ x
  unit-l' x y =
    Eq.trans (Eq.cong₂ _+_ (*-identityʳ x) (*-zeroʳ y)) (+-identityʳ x)

  unit-r' : (x y : 𝔽) → x * 0 + y * 1 ≡ y
  unit-r' x y =
    Eq.trans (Eq.cong₂ _+_ (*-zeroʳ x) (*-identityʳ y)) (+-identityˡ y)

⊙-assoc : (M N P : M2) → (M ⊙ N) ⊙ P ≡ M ⊙ (N ⊙ P)
⊙-assoc ⟪ a , b , c , d ⟫ ⟪ e , f , g , h ⟫ ⟪ p , q , r , s ⟫ =
  ⟪⟫-cong (key a b e f g h p r) (key a b e f g h q s)
          (key c d e f g h p r) (key c d e f g h q s)

⊙-identityˡ : (M : M2) → Id ⊙ M ≡ M
⊙-identityˡ ⟪ a , b , c , d ⟫ =
  ⟪⟫-cong (unit-l a c) (unit-l b d) (unit-r a c) (unit-r b d)

⊙-identityʳ : (M : M2) → M ⊙ Id ≡ M
⊙-identityʳ ⟪ a , b , c , d ⟫ =
  ⟪⟫-cong (unit-l' a b) (unit-r' a b) (unit-l' c d) (unit-r' c d)
